## Text Extraction, Cleaning, and Rephrasing from multiple books

In [1]:
import pandas as pd
import traceback
import json
from PyPDF2 import PdfReader
import os

from bson import ObjectId
from motor.motor_asyncio import AsyncIOMotorClient
from langchain_openai import ChatOpenAI
from langchain import PromptTemplate, LLMChain

from case_study_prompts import (
EXTRACTION_SYSTEM,
EXTRACTION_USER,
EXTRACTION_OUTPUT_FORMAT,
EMPTY_EXTRACTION_OUTPUT_FORMAT,
CLEAN_REPHRASE_USER,
CLEAN_REPHRASE_SYSTEM,
REPHRASE_OUTPUT_FORMAT,
REPHRASE_OUTPUT_EXAMPLE,
BIOLOGY_SOLUTION_SYSTEM_PROMPT,
CHEMISTRY_SOLUTION_SYSTEM_PROMPT,
MATHEMATICS_SOLUTION_SYSTEM_PROMPT,
PHYSICS_SOLUTION_SYSTEM_PROMPT,
DISTRACTOR_SYSTEM_PROMPT
)

from config import (
    OPENAI_API_KEY,
    MONGO_URL,
    DB_NAME
)

In [2]:
# os.environ["LANGCHAIN_TRACING_V2"] = "true"
# os.environ["LANGCHAIN_API_KEY"] = "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"
# os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
# os.environ["LANGCHAIN_PROJECT"] = "Questions Extractor"

# Pipeline

In [2]:
import json
def parse_Response(response):
    if isinstance(response, str):
        # print(response)
        start_index = response.find("{")
        end_index = response.rfind("}")
        if start_index != -1 and end_index != -1:
            valid_json_content = response[start_index : end_index + 1]
            try:
                JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
                # append_list_to_file(JSON_response)
                return JSON_response
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON response: {e.__class__.__name__} - {e}\n\n Still trying to work on particular exceptions ...")
                if str(e).startswith("Extra data"):
                    json_parts = valid_json_content.split('}\n{')
                    if json_parts:
                        first_json = json_parts[0] + '}'
                        return parse_Response(first_json)  
                elif str(e).startswith("Invalid \escape"):
                    print("Before removing \\ issue: ", valid_json_content)
                    str1 = valid_json_content.replace("\\\\\\\\\\", "fvback")
                    str1 = str1.replace("\\\\\\\\", "frback")
                    str1 = str1.replace("\\\\\\", "trlback")
                    str1 = str1.replace("\\\\", "dblback")
                    str1 = str1.replace("\\", "\\\\")
                    str1 = str1.replace("fvback","\\\\\\\\\\")
                    str1 = str1.replace("frback", "\\\\\\\\")
                    str1 = str1.replace("trlback","\\\\\\")
                    strfinal = str1.replace("dblback","\\\\")
                    print("After removing \\ issue: ", strfinal)
                    JSON_response = json.loads(strfinal.replace("\n", ""))
                    return JSON_response
                else:
                    print("Actual Content: ", valid_json_content)
        else:
            print("No valid JSON content found in the response.")
        # time.sleep(50)
    elif isinstance(response, dict):
        return response
    else:
        print("No response message found", type(response))

<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_25956\3339088456.py:10: SyntaxWarning: invalid escape sequence '\('
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_25956\3339088456.py:10: SyntaxWarning: invalid escape sequence '\)'
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_25956\3339088456.py:20: SyntaxWarning: invalid escape sequence '\e'
  elif str(e).startswith("Invalid \escape"):

In [3]:
# All question collection

def collect_questions_from_chapter_with_Langchain(subject, chapter_text, chapter_name, grade):
    try:
        # initialize the ChapOpenAI object
        llm = ChatOpenAI(
            model_name="gpt-4o",
            api_key= OPENAI_API_KEY,
            temperature=0.2,
        )
        # match subject:
        #     case "mathematics":
        #         examples=MATHEMATICS_EXTRACTION_OUTPUT_EXAMPLE
        #     case "biology":
        #         examples=BIOLOGY_EXTRACTION_OUTPUT_EXAMPLE
        #     case "physics":
        #         examples =PHYSICS_EXTRACTION_OUTPUT_EXAMPLE
        #     case "chemistry":
        #         examples=CHEMISTRY_EXTRACTION_OUTPUT_EXAMPLE

        #formatting prompts
        system = EXTRACTION_SYSTEM.format("",grade = grade, subject = subject,EMPTY_EXTRACTION_OUTPUT_FORMAT = EMPTY_EXTRACTION_OUTPUT_FORMAT, out_format = EXTRACTION_OUTPUT_FORMAT)
        user = EXTRACTION_USER.format(chapter_name = chapter_name, chapter_text = chapter_text)

        #generating response from api call
        response = llm.invoke(
            [
                ("system", system),
                ("human", user)
            ],
        )
        return response
    except Exception as e:
        print("Error with in extraction: ", type(e).__name__, "–", e, "\n", traceback.format_exc())
        return None

In [4]:
def clean_rephrase_question(question_text, topic_list):
    try:
        # initialize the ChapOpenAI object
        llm = ChatOpenAI(
            model_name="gpt-4o",
            api_key= OPENAI_API_KEY,
            temperature=0.2,
            # verbose = True
        )

        #formatting prompts
        system = CLEAN_REPHRASE_SYSTEM.format("",out_example = REPHRASE_OUTPUT_EXAMPLE, out_format = REPHRASE_OUTPUT_FORMAT)
        user = CLEAN_REPHRASE_USER.format(question_text = question_text, topic_list = topic_list)

        #generating response from api call
        response = llm.invoke(
            [
                ("system", system),
                ("human", user)
            ]
        )
        return response
    except Exception as e:
        print("Error cleaning text: ", type(e).__name__, "–", e, "\n", traceback.format_exc())
        return question_text  # Return original text in case of an error

In [5]:
import os
import traceback
from pathlib import Path
import zipfile
import tempfile
import shutil

def read_data_from_latex(publication: str, chapter_name: str) -> str:
    """
    Read LaTeX content from a specified publication and chapter zip file.
    
    Args:
        publication (str): Name of the publication (e.g., 'mtg')
        chapter_name (str): Name of the chapter (e.g., 'Life Processes')
    
    Returns:
        str: Content of the LaTeX file if successful, empty string if failed
    """
    try:
        # Construct the zip file path
        zip_path = os.path.join(r"textbooks", publication, f"{chapter_name}.zip")
        
        # Verify zip file exists
        if not os.path.exists(zip_path):
            raise FileNotFoundError(f"Zip file not found: {zip_path}")
        
        # Create a temporary directory to extract files
        with tempfile.TemporaryDirectory() as temp_dir:
            # Extract the zip file
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)
            
            # Find directories starting with 2025
            content_dirs = [d for d in os.listdir(temp_dir) 
                          if os.path.isdir(os.path.join(temp_dir, d)) and 
                          d.startswith('2025')]
            
            if not content_dirs:
                raise FileNotFoundError(f"No content directories found in zip file")
                
            # Get the latest directory
            latest_dir = sorted(content_dirs)[-1]
            dir_path = os.path.join(temp_dir, latest_dir)
            
            # Find the .tex file in the directory
            tex_files = [f for f in os.listdir(dir_path) if f.endswith('.tex')]
                    
            if not tex_files:
                raise FileNotFoundError(f"No .tex file found in {dir_path}")
                
            # Full path to the tex file
            latex_path = os.path.join(dir_path, tex_files[0])
            
            # Read the content
            with open(latex_path, 'r', encoding='utf-8') as file:
                content = file.read()
                
            print(f"Successfully processed LaTeX file from zip: {latex_path}")
            return content

    except Exception as e:
        print(
            "Failed to process the LaTeX file. Exception Occurred:",
            type(e).__name__,
            "–",
            e,
            "\n",
            traceback.format_exc()
        )
        return ""

In [25]:
def extract_questions(subject: str, chapter_texts: list, chapter_name: str, grade: str) -> dict:
    try:
        if not isinstance(chapter_texts, list) or not chapter_texts:
            return {}
            
        formatted_output = {}
        chunk_size = 500
        case_study_counter = 1
        
        for i in range(0, len(chapter_texts), chunk_size):
            chunk = chapter_texts[i:i + chunk_size]
            if not chunk:
                continue
                
            print(f"\nProcessing chunk {i//chunk_size + 1}/{-(-len(chapter_texts)//chunk_size)}")
            
            response = collect_questions_from_chapter_with_Langchain(
                subject=subject,
                chapter_text='\n'.join(chunk),
                chapter_name=chapter_name,
                grade=grade
            )
            
            if response and response.content:
                print("\nRaw response content:", response.content[:200])  # Print first 200 chars
                parsed = parse_Response(response.content)
                print("\nParsed response:", parsed)  # Print parsed response
                
                if parsed:
                    # Check if parsed response has case studies directly
                    if isinstance(parsed.get("case_studies"), dict):
                        case_studies = parsed["case_studies"]
                    else:
                        case_studies = parsed  # Assume the whole response is case studies
                        
                    for content in case_studies.values():
                        if isinstance(content, dict):
                            if "description" not in content or "questions" not in content:
                                print(f"\nMissing required fields. Content structure: {content.keys()}")
                                continue
                                
                            new_key = f"case_study_{case_study_counter}"
                            formatted_output[new_key] = {
                                "description": content["description"],
                                "questions": content["questions"]
                            }
                            print(f"\nExtracted questions from {new_key}")
                            print(f"Number of questions: {len(content['questions'])}")
                            case_study_counter += 1
            
            print(f"\nCompleted processing chunk {i//chunk_size + 1}")
                
        total_questions = sum(len(case_study["questions"]) for case_study in formatted_output.values())
        print(f"\nTotal questions extracted: {total_questions}")
        return formatted_output

    except Exception as e:
        print(f"Error: {str(e)}")
        return {}

In [26]:
def rephrase_questions(conf_data: dict, extracted_questions: dict, topics: list) -> dict:
   print("Starting the cleanup and rephrasing process...")
   try:
       if not conf_data or "chapter_name" not in conf_data:
           raise ValueError("Missing chapter_name in configuration")
           
       if not topics:
           raise ValueError("No topics found in the data")
           
       if not extracted_questions:
           raise ValueError(f"No questions found")
       
       formatted_output = {}
       
       # Process one case study at a time
       for case_study_key, content in extracted_questions.items():
           try:
               print(f"\nProcessing {case_study_key}")
               
               # Clean and rephrase the case study
               cleaned_response = clean_rephrase_question(content, topics)
               
               if cleaned_response and cleaned_response.content:
                   parsed = parse_Response(cleaned_response.content)
                   if parsed and isinstance(parsed, dict):
                       # Keep the same case_study_key from input
                       for key, case_study in parsed.items():
                           if isinstance(case_study, dict) and all(k in case_study for k in ["description", "questions", "topic", "topic_id"]):
                               formatted_output[case_study_key] = case_study
                               print(f"Successfully processed {case_study_key}")
                               print(f"Mapped topic: {case_study['topic']}")
                   else:
                       print(f"Warning: Invalid format in cleaned response for {case_study_key}")
               
               print("-" * 50)
               
           except Exception as e:
               print(f"Error processing {case_study_key}: {str(e)}")
               continue
       
       total_questions = sum(len(case_study["questions"]) for case_study in formatted_output.values())
       print(f"Total questions processed: {total_questions}")
       return formatted_output

   except Exception as e:
       print(f"Error: {str(e)}")
       return {}

In [20]:
# get chapter and book data from defaultConf
with open("defaultConf.json", "r") as f:
    conf_data = json.load(f)

chapter = conf_data["chapter_name"]
subject = conf_data["subject"]


print("Chapter to work on: ", chapter)
print(subject)
print(conf_data['publication'])

Chapter to work on:  Chemical Reactions and Equations
chemistry
mtg

In [21]:
from typing import Tuple, Dict, Optional
import traceback
import logging

def extract_rephrase_questions(conf_data: dict, topics: list) -> Tuple[Optional[Dict], Optional[Dict]]:
    try:
        # Validate configuration data
        required_fields = ["subject", "grade", "chapter_name"]
        missing_fields = [field for field in required_fields if field not in conf_data]
        if missing_fields:
            raise ValueError(f"Missing required configuration fields: {', '.join(missing_fields)}")
            
        if not topics:
            raise ValueError("No topics provided for question rephrasing")
            
        print("Starting question extraction and rephrasing pipeline...")
        
        # Step 1: Scrape text from PDF/LaTeX
        print("\nStep 1: Scraping textbook content...")
        pdf_text = read_data_from_latex(publication=conf_data['publication'] , chapter_name=conf_data['chapter_name'])
        if not pdf_text:
            raise ValueError("No text content extracted from textbook")
        print(f"Successfully extracted {len(pdf_text)} text segments")
            
        # Step 2: Extract questions from text
        print("\nStep 2: Extracting questions from text...")
        extracted_questions = extract_questions(
            subject=conf_data["subject"],
            grade=conf_data["grade"],
            chapter_name=conf_data["chapter_name"],
            chapter_texts=pdf_text.split("\n")
        )
        
        if not extracted_questions:
            raise ValueError("No questions were extracted from the text")
        print(f"Successfully extracted questions")
            
        # Step 3: Clean and rephrase questions
        print("\nStep 3: Cleaning and rephrasing questions...")
        final_rephrased_questions = rephrase_questions(
            conf_data=conf_data,
            extracted_questions=extracted_questions,
            topics=topics
        )
        if not final_rephrased_questions:
            raise ValueError("No questions were successfully rephrased")
        print("Successfully rephrased questions")
            
        # Return results
        print("\nPipeline completed successfully!")
        return extracted_questions, final_rephrased_questions
        
    except ValueError as val_err:
        print(f"Validation error: {str(val_err)}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return None, None
        
    except Exception as e:
        print(f"Unexpected error in question processing pipeline: {str(e)}")
        print(f"Exception type: {type(e).__name__}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return None, None
        
    finally:
        print("\nQuestion processing pipeline finished")

In [27]:
import pandas as pd

def process_filename(filename):
    """
    Process filename by stripping whitespace and converting to lowercase
    """
    return filename.strip().lower()

# Match subject to determine sheet name
match subject:
    case "mathematics":
        sheet_name = "G10 Maths"
    case "biology":
        sheet_name = "G10 Science"
    case "physics":
        sheet_name = "G10 Science"
    case "chemistry":
        sheet_name = "G10 Science"

# Read Excel file and process the filename
file_name = process_filename("LEAP Course Creation - Topic LU Prerequisite Misconceptions.xlsx")
misconceptions_df = pd.read_excel(file_name, sheet_name=sheet_name)

# Clean column names
misconceptions_df.columns = misconceptions_df.columns.str.strip()
misconceptions_df.fillna("", inplace=True)

# Process chapter name from conf_data for comparison
chapter_name = conf_data["chapter_name"].strip().lower()

# Get unique topics for the specified chapter
tempTopics = list(misconceptions_df[
    misconceptions_df["Chapter (NCERT/AcadAlly's name)"].str.strip().str.lower() == chapter_name
]["Topic"].unique())

# Create topics dictionary with processed IDs
topics = {}
for i in range(len(tempTopics)):
    topic_id = f"{conf_data['grade']}_{conf_data['subject']}_{chapter_name}_{i+1}"
    topics[topic_id] = tempTopics[i].strip()

print("Topics with ID: ", topics, "\n\n", topics.values())

# Process misconceptions and LUs
total_misconceptions = {}
total_LUs = {}

for i, row in misconceptions_df.iterrows():
    topic = str(row["Topic"]).strip()
    
    if topic in topics.values():
        # Process LUs
        if topic in total_LUs:
            total_LUs[topic].append(row["LU text"])
        else:
            total_LUs[topic] = [row["LU text"]]

        # Process misconceptions
        temp_misconceptions = [
            row[f"Misconceptions {i}"] 
            for i in range(1, 11) 
            if row[f"Misconceptions {i}"] != ""
        ]

        if topic in total_misconceptions:
            total_misconceptions[topic].extend(temp_misconceptions)
        else:
            total_misconceptions[topic] = temp_misconceptions

print(total_LUs, total_misconceptions, sep="\n\n-------------------------------------------------------------------\n\n")

Topics with ID:  {'10_chemistry_chemical reactions and equations_1': 'Writing Chemical Reactions and Equations', '10_chemistry_chemical reactions and equations_2': 'Balancing Chemical Equations', '10_chemistry_chemical reactions and equations_3': 'Combination and Decomposition Reactions', '10_chemistry_chemical reactions and equations_4': 'Displacement and Double Displacement Reactions', '10_chemistry_chemical reactions and equations_5': 'Redox Reactions and Their Effects'}

 dict_values(['Writing Chemical Reactions and Equations', 'Balancing Chemical Equations', 'Combination and Decomposition Reactions', 'Displacement and Double Displacement Reactions', 'Redox Reactions and Their Effects'])
{'Writing Chemical Reactions and Equations': ['Definition and Indicators of Chemical Reactions', 'Writing Chemical Equations'], 'Balancing Chemical Equations': ['Steps to balance a Chemical equation', 'Balancing the chemical equations '], 'Combination and Decomposition Reactions': ['Combination Reactions ', 'Exothermic and Endothermic Reactions (Examples and Differences)', 'Decomposition Reactions '], 'Displacement and Double Displacement Reactions': ['Displacement Reactions ', 'Double Displacement Reactions (including precipitation reactions)'], 'Redox Reactions and Their Effects': ['Redox Reactions ', 'Effects of Oxidation Reactions']}

-------------------------------------------------------------------

{'Writing Chemical Reactions and Equations': ['A chemical reaction always requires visible changes, like gas or heat.', 'A change in color always means a chemical reaction has occurred.', 'A chemical reaction cannot occur without a change in temperature.', 'The release of gas is mandatory for a reaction to be chemical.', 'Subscripts in chemical formulas (e.g., H2\u200b) can be altered to balance an equation.', 'Physical states (like (s),(g)) are optional and do not affect chemical equations.', 'Word equations and symbolic equations can be written in any order.', 'The placement of reactants and products on either side of the equation does not matter.', 'Reactants and products can have different numbers of atoms in a chemical equation.'], 'Balancing Chemical Equations': ['The mass of reactants and products does not need to be equal when balancing.', 'You can add or remove elements to balance a chemical equation.', 'Coefficients can be fractions, and there is no need to convert them to whole numbers.', 'The order of balancing elements does not impact the accuracy of the equation.', 'A skeletal equation (unbalanced) is sufficient for representing chemical reactions.', 'A balanced equation does not necessarily follow the law of conservation of mass.', 'Balancing equations does not require checking all elements.', 'The placement of coefficients is arbitrary as long as numbers match.', 'Balancing an equation changes the nature of the reaction itself.'], 'Combination and Decomposition Reactions': ['Combination reactions can only occur with elements, not compounds.', 'All combination reactions are exothermic.', 'A single reactant can form two or more products in a combination reaction.', 'The reactants in combination reactions must always be in solid form.', 'The reaction must release heat or light to qualify as a combination reaction.', 'Exothermic reactions must produce flames or visible heat.', 'Endothermic reactions cannot occur naturally.', 'Endothermic reactions absorb heat permanently without energy release.', 'All decomposition reactions are endothermic.', 'Exothermic reactions are always fast, while endothermic reactions are slow.', 'Decomposition reactions can only occur when heat is applied.', 'Only a single product can be formed in a decomposition reaction.', 'Decomposition cannot be caused by light or electricity, only by heat.', 'Decomposition reactions occur instantaneously, with no delay.'], 'Displacement and Double Displacement Reactions': ['Displacement reactions always involve metals as the more reactive element.', 'The displaced element must always form a visible solid.', 'Displacement reactions cannot occur in aqueous solutions.', "Reactivity depends on the element's physical state, not its chemical nature.", 'Only highly reactive metals can cause displacement reactions.', 'Double displacement reactions cannot occur without precipitation.', 'Precipitation reactions require equal amounts of reactants.', 'Precipitation occurs only when solids are involved.', 'All products in a double displacement reaction are always soluble.'], 'Redox Reactions and Their Effects': ['Oxidation and reduction cannot happen simultaneously.', 'Reduction only means losing oxygen, and oxidation only means gaining oxygen.', 'Redox reactions only occur with metals and not with compounds.', 'Redox reactions always require oxygen as a reactant.', 'An oxidizing agent is not reduced during the reaction.', 'Corrosion occurs instantly and produces visible effects immediately.', 'Only metals undergo corrosion; non-metals are unaffected.', 'Rancidity occurs only when food smells bad.', 'Corrosion stops permanently after painting or coating.', 'Oxidation reactions are always harmful and never beneficial.']}

In [28]:
total_LUs

{'Writing Chemical Reactions and Equations': ['Definition and Indicators of Chemical Reactions',
  'Writing Chemical Equations'],
 'Balancing Chemical Equations': ['Steps to balance a Chemical equation',
  'Balancing the chemical equations '],
 'Combination and Decomposition Reactions': ['Combination Reactions ',
  'Exothermic and Endothermic Reactions (Examples and Differences)',
  'Decomposition Reactions '],
 'Displacement and Double Displacement Reactions': ['Displacement Reactions ',
  'Double Displacement Reactions (including precipitation reactions)'],
 'Redox Reactions and Their Effects': ['Redox Reactions ',
  'Effects of Oxidation Reactions']}

In [29]:
# function call for execution
extracted_raw_questions_json ,clean_rephrased_questions_json = extract_rephrase_questions(conf_data, topics)
# clean_rephrased_questions_json

Starting question extraction and rephrasing pipeline...

Step 1: Scraping textbook content...
Successfully processed LaTeX file from zip: C:\Users\ANIKET~1\AppData\Local\Temp\tmplg7txxnc\2025_01_24_65cd09b9c0c686f18039g\2025_01_24_65cd09b9c0c686f18039g.tex
Successfully extracted 34483 text segments

Step 2: Extracting questions from text...

Processing chunk 1/2

Raw response content: {
    "case_study_1": {
        "description": "Chemical equation is a method of representing a chemical reaction with the help of symbols and formulae of the substances involved in it. In a chemical


In [30]:
print("Chapter name: ",chapter, ",  Raw questions: ",  len(extracted_raw_questions_json))
print("Chapter name: ",chapter, ",  Cleaned questions: ",  len(clean_rephrased_questions_json))

Chapter name:  Chemical Reactions and Equations ,  Raw questions:  11
Chapter name:  Chemical Reactions and Equations ,  Cleaned questions:  10

In [33]:
def convert_case_studies_to_df(case_studies_data: dict) -> pd.DataFrame:
   try:
       rows = []
       
       for case_study_key, content in case_studies_data.items():
           # Get case study level data
           description = content.get("description", "")
           topic = content.get("topic", "")
           topic_id = content.get("topic_id", "")
           
           # Process each question in the case study
           for question in content.get("questions", []):
               row = {
                   "case_study": case_study_key,
                   "description": description,
                   "topic": topic, 
                   "topic_id": topic_id,
                   "question": question.get("question", ""),
                   "hint": question.get("hint", ""),
                   "solution": question.get("solution", ""),
                   "correct_option": question.get("correct_option", ""),
                   "option1": question.get("option1", ""),
                   "dr1": question.get("dr1", ""),
                   "option2": question.get("option2", ""),
                   "dr2": question.get("dr2", ""),
                   "option3": question.get("option3", ""),
                   "dr3": question.get("dr3", "")
               }
               rows.append(row)
       
       # Create DataFrame
       df = pd.DataFrame(rows)
       
       # Reorder columns 
       column_order = [
           "case_study", "description", "topic", "topic_id", 
           "question", "hint", "solution", "correct_option",
           "option1", "dr1", "option2", "dr2", "option3", "dr3"
       ]
       df = df[column_order]
       
       print(f"Created DataFrame with {len(df)} questions from {len(case_studies_data)} case studies")
       return df
       
   except Exception as e:
       print(f"Error converting to DataFrame: {str(e)}")
       return pd.DataFrame()

In [34]:
clean_rephrased_questions_json['case_study_1']

{'description': '\\begin{aligned} & \\text{Chemical equation is a method of representing a chemical reaction with the help of symbols and formulae of the substances involved in it.} \\\\ & \\text{In a chemical equation, the substances which combine or react are called reactants and new substances produced are called products.} \\\\ & \\text{A chemical equation is a short hand method of representing a chemical reaction.} \\\\ & \\text{A balanced chemical equation has equal number of atoms of different elements in the reactants and products side.} \\\\ & \\text{An unbalanced chemical equation has unequal number of atoms of one or more elements in reactants and products.} \\\\ & \\text{Formulae of elements and compounds are not changed to balance an equation.} \\\\ \\end{aligned}',
 'questions': [{'question': '\\begin{aligned} & \\text{Consider the following reaction:} \\\\ & \\quad p \\mathrm{Mg}_{3} \\mathrm{~N}_{2}+q \\mathrm{H}_{2} \\mathrm{O} \\rightarrow r \\mathrm{Mg}(\\mathrm{OH})_{2}+s \\mathrm{NH}_{3} \\\\ & \\text{When the equation is balanced, what are the coefficients } p, q, r, s \\text{ respectively?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'},
  {'question': '\\begin{aligned} & \\text{Which of the following information is not conveyed by a balanced chemical equation?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'},
  {'question': '\\begin{aligned} & \\text{The balancing of chemical equations is in accordance with which law?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'},
  {'question': '\\begin{aligned} & \\text{Which of the following chemical equations is an unbalanced one?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'},
  {'question': '\\begin{aligned} & \\text{Which of the following statements is/are correct?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
 'topic': 'Balancing Chemical Equations',
 'topic_id': '10_chemistry_chemical reactions and equations_2'}

# Solution and Distractors(Based on misconceptions)

In [35]:
llm = ChatOpenAI(model="gpt-4o", temperature=0.2, api_key = OPENAI_API_KEY ,  request_timeout=30.0)

In [36]:
questions_df = convert_case_studies_to_df(clean_rephrased_questions_json)
questions_df

Created DataFrame with 50 questions from 10 case studies

,case_study,description,topic,topic_id,question,hint,solution,correct_option,option1,dr1,option2,dr2,option3,dr3
0,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Consider the following...,,,,,,,,,
1,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,,,,,,,,,
2,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{The balancing of chemi...,,,,,,,,,
3,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,,,,,,,,,
4,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,,,,,,,,,
5,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Which of the following...,,,,,,,,,
6,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{In the reaction } 2 \m...,,,,,,,,,
7,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Amino acid is formed b...,,,,,,,,,
8,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Silver chloride on exp...,,,,,,,,,
9,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{What type of chemical ...,,,,,,,,,
10,case_study_3,\begin{aligned} & \text{Redox reactions are th...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{Which of the following...,,,,,,,,,
11,case_study_3,\begin{aligned} & \text{Redox reactions are th...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{In which of the follow...,,,,,,,,,
12,case_study_3,\begin{aligned} & \text{Redox reactions are th...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{Identify the reaction ...,,,,,,,,,
13,case_study_3,\begin{aligned} & \text{Redox reactions are th...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{For the reaction } \ma...,,,,,,,,,
14,case_study_3,\begin{aligned} & \text{Redox reactions are th...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{In the reaction } \mat...,,,,,,,,,
15,case_study_4,\begin{aligned} & \text{In a balanced chemical...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,"\begin{aligned} & \text{In a reaction, 40 g of...",,,,,,,,,
16,case_study_4,\begin{aligned} & \text{In a balanced chemical...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{When solid mercury (II...,,,,,,,,,
17,case_study_4,\begin{aligned} & \text{In a balanced chemical...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,,,,,,,,,
18,case_study_4,\begin{aligned} & \text{In a balanced chemical...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{In the given chemical ...,,,,,,,,,
19,case_study_4,\begin{aligned} & \text{In a balanced chemical...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Sulphur dioxide reacts...,,,,,,,,,
20,case_study_5,\begin{aligned} & \text{In a chemical reaction...,Writing Chemical Reactions and Equations,10_chemistry_chemical reactions and equations_1,\begin{aligned} & \text{Which type of reaction...,,,,,,,,,
21,case_study_5,\begin{aligned} & \text{In a chemical reaction...,Writing Chemical Reactions and Equations,10_chemistry_chemical reactions and equations_1,\begin{aligned} & \text{What is the color of t...,,,,,,,,,
22,case_study_5,\begin{aligned} & \text{In a chemical reaction...,Writing Chemical Reactions and Equations,10_chemistry_chemical reactions and equations_1,\begin{aligned} & \text{What is the physical s...,,,,,,,,,
23,case_study_5,\begin{aligned} & \text{In a chemical reaction...,Writing Chemical Reactions and Equations,10_chemistry_chemical reactions and equations_1,\begin{aligned} & \text{Which of the following...,,,,,,,,,
24,case_study_5,\begin{aligned} & \text{In a chemical reaction...,Writing Chemical Reactions and Equations,10_chemistry_chemical reactions and equations_1,\begin{aligned} & \text{In which of the follow...,,,,,,,,,
25,case_study_6,\begin{aligned} & \text{A reaction in which tw...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{What is the chemical n...,,,,,,,,,
26,case_study_6,\begin{aligned} & \text{A reaction in which tw...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{When carbon dioxide is...,,,,,,,,,
27,case_study_6,\begin{aligned} & \text{A reaction in which tw...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Identify the incorrect...,,,,,,,,,
28,case_study_6,\begin{aligned} & \text{A reaction in which tw...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Quick lime combines vi...,,,,,,,,,
29,case_study_6,\begin{aligned} & \text{A reaction in which tw...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,"\begin{aligned} & \text{Among the following, w...",,,,,,,,,
30,case_study_7,\begin{aligned} & \text{Reactions in which one...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{Which metal does coppe...,,,,,,,,,
31,case_study_7,\begin{aligned} & \text{Reactions in which one...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{What is the characteri...,,,,,,,,,
32,case_study_7,\begin{aligned} & \text{Reactions in which one...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{When dry hydrogen is p...,,,,,,,,,
33,case_study_7,\begin{aligned} & \text{Reactions in which one...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{Which of the following...,,,,,,,,,
34,case_study_7,\begin{aligned} & \text{Reactions in which one...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{What observation is ma...,,,,,,,,,
35,case_study_8,\begin{aligned} & \text{Those reactions in whi...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{Which type of reaction...,,,,,,,,,
36,case_study_8,\begin{aligned} & \text{Those reactions in whi...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{Identify the reaction ...,,,,,,,,,
37,case_study_8,\begin{aligned} & \text{Those reactions in whi...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{Barium chloride reacts...,,,,,,,,,
38,case_study_8,\begin{aligned} & \text{Those reactions in whi...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{In the reaction} \\ & ...,,,,,,,,,
39,case_study_8,\begin{aligned} & \text{Those reactions in whi...,Displacement and Double Displacement Reactions,10_chemistry_chemical reactions and equations_4,\begin{aligned} & \text{In the reaction} \\ & ...,,,,,,,,,
40,case_study_9,\begin{aligned} & \text{The earlier concept of...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{Which of the following...,,,,,,,,,
41,case_study_9,\begin{aligned} & \text{The earlier concept of...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,"\begin{aligned} & \text{In the reaction, } \ma...",,,,,,,,,
42,case_study_9,\begin{aligned} & \text{The earlier concept of...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{Which of the following...,,,,,,,,,
43,case_study_9,\begin{aligned} & \text{The earlier concept of...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{In the reaction } \mat...,,,,,,,,,
44,case_study_9,\begin{aligned} & \text{The earlier concept of...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{Identify the correct o...,,,,,,,,,
45,case_study_10,\begin{aligned} & \text{Oxidation has damaging...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{Which of the following...,,,,,,,,,
46,case_study_10,\begin{aligned} & \text{Oxidation has damaging...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{The combination of pho...,,,,,,,,,
47,case_study_10,\begin{aligned} & \text{Oxidation has damaging...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{Read the Assertion (A)...,,,,,,,,,
48,case_study_10,\begin{aligned} & \text{Oxidation has damaging...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{Which of the following...,,,,,,,,,
49,case_study_10,\begin{aligned} & \text{Oxidation has damaging...,Redox Reactions and Their Effects,10_chemistry_chemical reactions and equations_5,\begin{aligned} & \text{What measures can be a...,,,,,,,,,

In [37]:
import json
def parse_Response(response):
    if isinstance(response, str):
        # print(response)
        start_index = response.find("{")
        end_index = response.rfind("}")
        if start_index != -1 and end_index != -1:
            valid_json_content = response[start_index : end_index + 1]
            try:
                JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
                # append_list_to_file(JSON_response)
                return JSON_response
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON response: {e.__class__.__name__} - {e}\n\n Still trying to work on particular exceptions ...")
                if str(e).startswith("Extra data"):
                    json_parts = valid_json_content.split('}\n{')
                    if json_parts:
                        first_json = json_parts[0] + '}'
                        return parse_Response(first_json)  
                elif str(e).startswith("Invalid \escape"):
                    print("Before removing \\ issue: ", valid_json_content)
                    str1 = valid_json_content.replace("\\\\\\\\\\", "fvback")
                    str1 = str1.replace("\\\\\\\\", "frback")
                    str1 = str1.replace("\\\\\\", "trlback")
                    str1 = str1.replace("\\\\", "dblback")
                    str1 = str1.replace("\\", "\\\\")
                    str1 = str1.replace("fvback","\\\\\\\\\\")
                    str1 = str1.replace("frback", "\\\\\\\\")
                    str1 = str1.replace("trlback","\\\\\\")
                    strfinal = str1.replace("dblback","\\\\")
                    print("After removing \\ issue: ", strfinal)
                    JSON_response = json.loads(strfinal.replace("\n", ""))
                    return JSON_response
                else:
                    print("Actual Content: ", valid_json_content)
        else:
            print("No valid JSON content found in the response.")
        # time.sleep(50)
    elif isinstance(response, dict):
        return response
    else:
        print("No response message found", type(response))

<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_25956\3339088456.py:10: SyntaxWarning: invalid escape sequence '\('
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_25956\3339088456.py:10: SyntaxWarning: invalid escape sequence '\)'
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_25956\3339088456.py:20: SyntaxWarning: invalid escape sequence '\e'
  elif str(e).startswith("Invalid \escape"):

In [43]:
data = clean_rephrased_questions_json

In [44]:
clean_rephrased_questions_json = dict(list(clean_rephrased_questions_json.items())[:2])

In [45]:
## Generating solutions
prompt_template = PromptTemplate(
    input_variables=["system_prompt", "question", "topic", "topic_id", "lulist"],
    template="{system_prompt}\n\n\nGenerate a hint, and solution for the given question. Also rephrase the given question according to the specified steps.\nHere are the required context:\nQuestion: {question}\nLearning unit data which defines scope from which solution should be generated: {lulist}\nTopic: {topic}\nTopic ID: {topic_id}\n\nReturn the output in the specified JSON format."
)

chain = LLMChain(llm=llm, prompt=prompt_template)
# chain = prompt_template | llm
# Function to process each question and generate hint, solution, and final answer
def generate_explanation(subject, question, topic, topic_id):
    try:
        match subject:
            case "mathematics":
                system = MATHEMATICS_SOLUTION_SYSTEM_PROMPT
            case "biology":
                system = BIOLOGY_SOLUTION_SYSTEM_PROMPT
            case "physics":
                system = PHYSICS_SOLUTION_SYSTEM_PROMPT
            case "chemistry":
                system = CHEMISTRY_SOLUTION_SYSTEM_PROMPT

        response = chain.run(
            system_prompt=system,
            lulist=total_LUs,
            question=question,
            topic=topic,
            topic_id=topic_id
        )
        return response
    except Exception as e:
        print(f"Error processing question: {question}\nError: {str(e)}")
        return None
# parser = PydanticOutputParser(pydantic_object=sol_data)
# global explanations

def loopForSolution(subject, data):
   try:
       for case_study_key, content in data.items():
           print(f"\nProcessing solutions for {case_study_key}")
           retries = 0
           
           # Process each question in case study
           for i, question in enumerate(content["questions"]):
               while retries < 3:  # Try up to 3 times for each question
                   try:
                       print(f"Processing question {i + 1} out of {len(content['questions'])}")
                       explanation = generate_explanation(
                           subject=subject,
                           question=question["question"],
                           topic=content["topic"],
                           topic_id=content["topic_id"]
                       )
                       
                       parsed_explanation = parse_Response(explanation)
                       if parsed_explanation:
                           # Update question with solution data
                           question.update({
                               "hint": parsed_explanation.get("hint", ""),
                               "solution": parsed_explanation.get("solution", "")
                           })
                           retries = 0
                           break
                       
                       else:
                           print(f"Failed to parse solution for question {i + 1}, attempt {retries + 1}/3")
                           retries += 1
                           
                   except Exception as e:
                       print(f"Error processing question {i + 1}: {str(e)}")
                       retries += 1
               
               if retries == 3:
                   print(f"Failed to process question {i + 1} after 3 attempts, moving to next question")
                   retries = 0  # Reset for next question
           
       return data

   except Exception as e:
       print(f"Error in loopForSolution: {str(e)}")
       return data
   
loopForSolution(subject, clean_rephrased_questions_json)

C:\Users\aniket singh\AppData\Local\Temp\ipykernel_25956\4087258864.py:7: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  chain = LLMChain(llm=llm, prompt=prompt_template)
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_25956\4087258864.py:22: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  response = chain.run(

Processing solutions for case_study_1
Processing question 1 out of 5
Processing question 2 out of 5
Processing question 3 out of 5
Processing question 4 out of 5
Processing question 5 out of 5

Processing solutions for case_study_2
Processing question 1 out of 5
Processing question 2 out of 5
Processing question 3 out of 5
Processing question 4 out of 5
Processing question 5 out of 5

{'case_study_1': {'description': '\\begin{aligned} & \\text{Chemical equation is a method of representing a chemical reaction with the help of symbols and formulae of the substances involved in it.} \\\\ & \\text{In a chemical equation, the substances which combine or react are called reactants and new substances produced are called products.} \\\\ & \\text{A chemical equation is a short hand method of representing a chemical reaction.} \\\\ & \\text{A balanced chemical equation has equal number of atoms of different elements in the reactants and products side.} \\\\ & \\text{An unbalanced chemical equation has unequal number of atoms of one or more elements in reactants and products.} \\\\ & \\text{Formulae of elements and compounds are not changed to balance an equation.} \\\\ \\end{aligned}',
  'questions': [{'question': '\\begin{aligned} & \\text{Consider the following reaction:} \\\\ & \\quad p \\mathrm{Mg}_{3} \\mathrm{~N}_{2}+q \\mathrm{H}_{2} \\mathrm{O} \\rightarrow r \\mathrm{Mg}(\\mathrm{OH})_{2}+s \\mathrm{NH}_{3} \\\\ & \\text{When the equation is balanced, what are the coefficients } p, q, r, s \\text{ respectively?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{To balance the chemical equation, ensure that the number of each type of atom is the same on both sides of the equation. Start by balancing the atoms that appear in the least number of compounds.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{The given chemical reaction is:} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow \\mathrm{Mg} (\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{To balance the equation, we need to ensure that the number of each type of atom is the same on both sides.} \\\\ &\\text{Start by balancing the magnesium (Mg) atoms. There are 3 Mg atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 3 } \\mathrm{Mg}(\\mathrm{OH})_{2}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{Next, balance the nitrogen (N) atoms. There are 2 N atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 2 } \\mathrm{NH}_{3}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Finally, balance the hydrogen (H) and oxygen (O) atoms. There are 6 OH groups in } 3 \\mathrm{Mg}(\\mathrm{OH})_{2}, \\text{ which means 6 O and 12 H atoms are needed.} \\\\ &\\text{Since 2 } \\mathrm{NH}_{3} \\text{ provides 6 H atoms, we need 6 more H atoms from } \\mathrm{H}_{2} \\mathrm{O}. \\text{ Thus, 6 } \\mathrm{H}_{2} \\mathrm{O} \\text{ are needed.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{The balanced equation is:} \\\\ &\\quad 1 \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Thus, the coefficients are } p = 1, \\ q = 6, \\ r = 3, \\ s = 2. \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Which of the following information is not conveyed by a balanced chemical equation?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} & \\text{Consider what a balanced chemical equation typically conveys, such as the conservation of mass, the ratio of molecules, and the identities of reactants and products.} \\end{aligned}',
    'solution': '\\begin{aligned} & \\text{A balanced chemical equation provides information about the identities and relative amounts of reactants and products involved in a chemical reaction. It also indicates the conservation of mass, as the number of atoms of each element is the same on both sides of the equation. However, it does not convey information about the rate of the reaction or the conditions under which the reaction occurs, such as temperature or pressure.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{The balancing of chemical equations is in accordance with which law?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Think about the fundamental law that states mass is neither created nor destroyed in a chemical reaction.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{The balancing of chemical equations is in accordance with the Law of Conservation of Mass. This law states that mass is neither created nor destroyed in a chemical reaction.}\\ &\\text{Therefore, the mass of the reactants must equal the mass of the products, which is achieved by balancing the chemical equation.}\\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Which of the following chemical equations is an unbalanced one?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{To determine if a chemical equation is unbalanced, compare the number of atoms of each element on both sides of the equation. If they are not equal, the equation is unbalanced.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{A chemical equation is considered unbalanced if the number of atoms of each element is not the same on both sides of the equation.}\\quad \\text{For example, in the equation } \\text{H}_2 + \\text{O}_2 \\rightarrow \\text{H}_2\\text{O}, \\quad \\text{there are two hydrogen atoms on the left and two on the right, but there are two oxygen atoms on the left and only one on the right.}\\quad \\text{Thus, this equation is unbalanced.}\\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Which of the following statements is/are correct?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Consider the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{Ensure that the number of atoms for each element is the same on both sides of the equation.} \\\\ &\\text{This will help you identify the correct statement(s) regarding balanced chemical equations.} \\\\ \\end{aligned}',
    'solution': '\\begin{aligned} &\\text{A balanced chemical equation has equal numbers of each type of atom on both sides of the equation.} \\\\ &\\text{This is in accordance with the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{For example, in the equation } \\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O}, \\\\ &\\text{there are 4 hydrogen atoms and 2 oxygen atoms on both sides, indicating it is balanced.} \\\\ \\end{aligned}'}],
  'topic': 'Balancing Chemical Equations',
  'topic_id': '10_chemistry_chemical reactions and equations_2'},
 'case_study_2': {'description': '\\begin{aligned} & \\text{In decomposition reactions, a single reactant breaks down to form two or more products.} \\\\ & \\text{Decomposition reaction is opposite to combination reaction.} \\\\ & \\text{Thermal decomposition reactions use the energy in form of heat for decomposition of reactants.} \\\\ & \\text{Electrolytic decomposition reactions involve the use of electrical energy for the decomposition of reactant molecules.} \\\\ & \\text{Photolysis or photochemical decomposition involves the use of light energy for the purpose of decomposition.} \\\\ \\end{aligned}',
  'questions': [{'question': '\\begin{aligned} & \\text{Which of the following reactions is a decomposition reaction? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{A decomposition reaction involves a single compound breaking down into two or more simpler substances. Look for a reaction where one reactant forms multiple products.} \\end{aligned}',
    'solution': '\\begin{aligned} &\\text{In a decomposition reaction, a single compound breaks down into two or more simpler substances.} \\\\ &\\text{For example, the decomposition of calcium carbonate (CaCO}_3\\text{) is a typical decomposition reaction:} \\\\ &\\text{CaCO}_3 \\rightarrow \\text{CaO} + \\text{CO}_2 \\\\ &\\text{Here, calcium carbonate decomposes into calcium oxide and carbon dioxide.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{In the reaction } 2 \\mathrm{~Pb}\\left(\\mathrm{NO}_{3}\\right)_{2} \\rightarrow 2 \\mathrm{PbO}+n \\mathrm{~A}+\\mathrm{O}_{2}, \\\\ & \\text{what is } n \\mathrm{~A} \\text{ in the given reaction? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Identify the type of reaction and use stoichiometry to find the missing compound.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{The given reaction is a decomposition reaction where } 2 \\mathrm{~Pb}\\left(\\mathrm{NO}_{3}\\right)_{2} \\text{ decomposes into } 2 \\mathrm{PbO}, \\mathrm{O}_{2}, \\text{ and another compound.} \\\\ &\\text{The compound } \\mathrm{A} \\text{ is } \\mathrm{NO}_{2}, \\text{ which is a common product of the decomposition of metal nitrates.} \\\\ &\\text{Balancing the equation, we have:} \\\\ &2 \\mathrm{~Pb}\\left(\\mathrm{NO}_{3}\\right)_{2} \\rightarrow 2 \\mathrm{PbO} + 4 \\mathrm{NO}_{2} + \\mathrm{O}_{2} \\\\ &\\text{Thus, } n \\mathrm{~A} \\text{ is } 4 \\mathrm{NO}_{2}. \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Amino acid is formed by the decomposition of which component of our diet? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Consider which macromolecules in our diet break down to form amino acids.}\\\\ &\\text{Think about the role of proteins in the body and their basic building blocks.}\\\\ \\end{aligned}',
    'solution': '\\begin{aligned} &\\text{Amino acids are formed by the decomposition of proteins in our diet.}\\\\ &\\text{Proteins are large, complex molecules that are broken down into amino acids through}\\\\ &\\text{decomposition reactions in the digestive system. This process involves breaking the}\\\\ &\\text{peptide bonds that link amino acids together in proteins.}\\\\ \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Silver chloride on exposure to sunlight for a long duration turns grey due to which of the following? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Consider the type of reaction occurring when silver chloride is exposed to sunlight and the change in color.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{When silver chloride (AgCl) is exposed to sunlight, it undergoes a decomposition reaction.}\\\\ &\\text{This reaction is photochemical, meaning it is driven by light.}\\\\ &\\text{The chemical equation for this reaction is:}\\\\ &\\quad 2\\text{AgCl} \\rightarrow 2\\text{Ag} + \\text{Cl}_2\\\\ &\\text{In this reaction, silver chloride decomposes into silver (Ag) and chlorine gas (Cl}_2\\text{).}\\\\ &\\text{The grey color is due to the formation of metallic silver.}\\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{What type of chemical reaction takes place when electricity is passed through water? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Consider the process of breaking down a compound into simpler substances when electricity is applied.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{When electricity is passed through water, it undergoes a decomposition reaction.}\\quad \\text{In this type of reaction, a single compound breaks down into two or more simpler substances.}\\quad \\text{The chemical equation for the decomposition of water is:}\\\\ &\\quad 2\\text{H}_2\\text{O} \\rightarrow 2\\text{H}_2 + \\text{O}_2\\\\ &\\text{This reaction is an example of electrolysis, where water is decomposed into hydrogen and oxygen gases.}\\end{aligned}'}],
  'topic': 'Combination and Decomposition Reactions',
  'topic_id': '10_chemistry_chemical reactions and equations_3'}}

### Generating Distractors

In [46]:
data= convert_case_studies_to_df(clean_rephrased_questions_json)
data

Created DataFrame with 10 questions from 2 case studies

,case_study,description,topic,topic_id,question,hint,solution,correct_option,option1,dr1,option2,dr2,option3,dr3
0,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Consider the following...,\begin{aligned} &\text{To balance the chemical...,\begin{aligned} &\text{The given chemical reac...,,,,,,,
1,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,\begin{aligned} & \text{Consider what a balanc...,\begin{aligned} & \text{A balanced chemical eq...,,,,,,,
2,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{The balancing of chemi...,\begin{aligned} &\text{Think about the fundame...,\begin{aligned} &\text{The balancing of chemic...,,,,,,,
3,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,\begin{aligned} &\text{To determine if a chemi...,\begin{aligned} &\text{A chemical equation is ...,,,,,,,
4,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,\begin{aligned} &\text{Consider the law of con...,\begin{aligned} &\text{A balanced chemical equ...,,,,,,,
5,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Which of the following...,\begin{aligned} &\text{A decomposition reactio...,\begin{aligned} &\text{In a decomposition reac...,,,,,,,
6,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{In the reaction } 2 \m...,\begin{aligned} &\text{Identify the type of re...,\begin{aligned} &\text{The given reaction is a...,,,,,,,
7,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Amino acid is formed b...,\begin{aligned} &\text{Consider which macromol...,\begin{aligned} &\text{Amino acids are formed ...,,,,,,,
8,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Silver chloride on exp...,\begin{aligned} &\text{Consider the type of re...,\begin{aligned} &\text{When silver chloride (A...,,,,,,,
9,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{What type of chemical ...,\begin{aligned} &\text{Consider the process of...,\begin{aligned} &\text{When electricity is pas...,,,,,,,

In [47]:
clean_rephrased_questions_json['case_study_1']

{'description': '\\begin{aligned} & \\text{Chemical equation is a method of representing a chemical reaction with the help of symbols and formulae of the substances involved in it.} \\\\ & \\text{In a chemical equation, the substances which combine or react are called reactants and new substances produced are called products.} \\\\ & \\text{A chemical equation is a short hand method of representing a chemical reaction.} \\\\ & \\text{A balanced chemical equation has equal number of atoms of different elements in the reactants and products side.} \\\\ & \\text{An unbalanced chemical equation has unequal number of atoms of one or more elements in reactants and products.} \\\\ & \\text{Formulae of elements and compounds are not changed to balance an equation.} \\\\ \\end{aligned}',
 'questions': [{'question': '\\begin{aligned} & \\text{Consider the following reaction:} \\\\ & \\quad p \\mathrm{Mg}_{3} \\mathrm{~N}_{2}+q \\mathrm{H}_{2} \\mathrm{O} \\rightarrow r \\mathrm{Mg}(\\mathrm{OH})_{2}+s \\mathrm{NH}_{3} \\\\ & \\text{When the equation is balanced, what are the coefficients } p, q, r, s \\text{ respectively?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
   'hint': '\\begin{aligned} &\\text{To balance the chemical equation, ensure that the number of each type of atom is the same on both sides of the equation. Start by balancing the atoms that appear in the least number of compounds.}\\end{aligned}',
   'solution': '\\begin{aligned} &\\text{The given chemical reaction is:} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow \\mathrm{Mg} (\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{To balance the equation, we need to ensure that the number of each type of atom is the same on both sides.} \\\\ &\\text{Start by balancing the magnesium (Mg) atoms. There are 3 Mg atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 3 } \\mathrm{Mg}(\\mathrm{OH})_{2}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{Next, balance the nitrogen (N) atoms. There are 2 N atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 2 } \\mathrm{NH}_{3}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Finally, balance the hydrogen (H) and oxygen (O) atoms. There are 6 OH groups in } 3 \\mathrm{Mg}(\\mathrm{OH})_{2}, \\text{ which means 6 O and 12 H atoms are needed.} \\\\ &\\text{Since 2 } \\mathrm{NH}_{3} \\text{ provides 6 H atoms, we need 6 more H atoms from } \\mathrm{H}_{2} \\mathrm{O}. \\text{ Thus, 6 } \\mathrm{H}_{2} \\mathrm{O} \\text{ are needed.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{The balanced equation is:} \\\\ &\\quad 1 \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Thus, the coefficients are } p = 1, \\ q = 6, \\ r = 3, \\ s = 2. \\end{aligned}'},
  {'question': '\\begin{aligned} & \\text{Which of the following information is not conveyed by a balanced chemical equation?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
   'hint': '\\begin{aligned} & \\text{Consider what a balanced chemical equation typically conveys, such as the conservation of mass, the ratio of molecules, and the identities of reactants and products.} \\end{aligned}',
   'solution': '\\begin{aligned} & \\text{A balanced chemical equation provides information about the identities and relative amounts of reactants and products involved in a chemical reaction. It also indicates the conservation of mass, as the number of atoms of each element is the same on both sides of the equation. However, it does not convey information about the rate of the reaction or the conditions under which the reaction occurs, such as temperature or pressure.} \\end{aligned}'},
  {'question': '\\begin{aligned} & \\text{The balancing of chemical equations is in accordance with which law?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
   'hint': '\\begin{aligned} &\\text{Think about the fundamental law that states mass is neither created nor destroyed in a chemical reaction.}\\end{aligned}',
   'solution': '\\begin{aligned} &\\text{The balancing of chemical equations is in accordance with the Law of Conservation of Mass. This law states that mass is neither created nor destroyed in a chemical reaction.}\\ &\\text{Therefore, the mass of the reactants must equal the mass of the products, which is achieved by balancing the chemical equation.}\\end{aligned}'},
  {'question': '\\begin{aligned} & \\text{Which of the following chemical equations is an unbalanced one?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
   'hint': '\\begin{aligned} &\\text{To determine if a chemical equation is unbalanced, compare the number of atoms of each element on both sides of the equation. If they are not equal, the equation is unbalanced.}\\end{aligned}',
   'solution': '\\begin{aligned} &\\text{A chemical equation is considered unbalanced if the number of atoms of each element is not the same on both sides of the equation.}\\quad \\text{For example, in the equation } \\text{H}_2 + \\text{O}_2 \\rightarrow \\text{H}_2\\text{O}, \\quad \\text{there are two hydrogen atoms on the left and two on the right, but there are two oxygen atoms on the left and only one on the right.}\\quad \\text{Thus, this equation is unbalanced.}\\end{aligned}'},
  {'question': '\\begin{aligned} & \\text{Which of the following statements is/are correct?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
   'hint': '\\begin{aligned} &\\text{Consider the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{Ensure that the number of atoms for each element is the same on both sides of the equation.} \\\\ &\\text{This will help you identify the correct statement(s) regarding balanced chemical equations.} \\\\ \\end{aligned}',
   'solution': '\\begin{aligned} &\\text{A balanced chemical equation has equal numbers of each type of atom on both sides of the equation.} \\\\ &\\text{This is in accordance with the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{For example, in the equation } \\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O}, \\\\ &\\text{there are 4 hydrogen atoms and 2 oxygen atoms on both sides, indicating it is balanced.} \\\\ \\end{aligned}'}],
 'topic': 'Balancing Chemical Equations',
 'topic_id': '10_chemistry_chemical reactions and equations_2'}

In [48]:
# Define the prompt template for generating misconceptions
prompt_template = PromptTemplate(
    input_variables=["system_prompt","topic", "topic_id", "question", "hint", "solution"],
    template="{system_prompt}\n\nGenerate one correct option and appropriate incorrect options in latex using given solution, hint, and misconceptions for the given question.\n\nTopic ID: {topic_id}\nTopic: {topic}\nQuestion: {question}\nHint: {hint}\nSolution: {solution}\n\nReturn the output in the specified JSON format."
)

# Extract relevant information from the 'explanation' column

def extract_explanation_details(explanation):
    try:
        explanation_data = json.loads(explanation)
        hint = explanation_data.get('hint', 'No hint available')
        solution = explanation_data.get('solution', 'No solution available')
        return hint, solution
    except json.JSONDecodeError:
        return 'No hint available', 'No solution available'

# Function to generate misconceptions-based incorrect options

def generate_incorrect_options(row):

    chain = LLMChain(llm=llm, prompt=prompt_template)
    try:
        response = chain.run(
            system_prompt=DISTRACTOR_SYSTEM_PROMPT,
            topic=row['topic'],
            topic_id=row['topic_id'],
            question=row['question'],
            hint=row['hint'],
            solution=row['solution']
        )
        # if response.strip().startswith("```json"):
        #     response = response.strip().strip("```json").strip("```").strip()
        return response
    except Exception as e:
        print(f"Unexpected error: {str(e)}")
        return None

def loopForDistractor(case_studies_data: dict) -> dict:
   try:
       for case_study_key, content in case_studies_data.items():
           print(f"\nProcessing distractors for {case_study_key}")
           
           for i, question in enumerate(content.get("questions", [])):
               retries = 0
               while retries < 3:  
                   try:
                       print(f"Processing question {i + 1} out of {len(content['questions'])}")
                       
                       misconception_options = generate_incorrect_options({
                           'question': question.get("question", ""),
                           'solution': question.get("solution", ""),
                           'hint': question.get("hint", ""),
                           'topic': content.get("topic", ""),
                           'topic_id': content.get("topic_id", "")
                       })
                       
                       parsed_options = parse_Response(misconception_options)
                       if parsed_options:
                           question.update({
                               "correct_option": parsed_options.get("correct_option", ""),
                               "option1": parsed_options.get("option1", {}).get("option", ""),
                               "dr1": parsed_options.get("option1", {}).get("rationale", ""),
                               "option2": parsed_options.get("option2", {}).get("option", ""),
                               "dr2": parsed_options.get("option2", {}).get("rationale", ""),
                               "option3": parsed_options.get("option3", {}).get("option", ""),
                               "dr3": parsed_options.get("option3", {}).get("rationale", "")
                           })
                           retries = 0  
                           break
                       else:
                           print(f"Failed to parse options for question {i + 1}, attempt {retries + 1}/3")
                           retries += 1
                           
                   except Exception as e:
                       print(f"Error processing question {i + 1}: {str(e)}")
                       retries += 1
               
               if retries == 3:
                   print(f"Failed to process question {i + 1} after 3 attempts, moving to next question")
                   question.update({
                       "correct_option": "",
                       "option1": "", "dr1": "",
                       "option2": "", "dr2": "",
                       "option3": "", "dr3": ""
                   })
           
       return case_studies_data

   except Exception as e:
       print(f"Error in loopForDistractor: {str(e)}")
       return case_studies_data
loopForDistractor(clean_rephrased_questions_json)
# data['misconception_options'] = misconception_options

Processing distractors for case_study_1
Processing question 1 out of 5
Processing question 2 out of 5
Processing question 3 out of 5
Processing question 4 out of 5
Processing question 5 out of 5

Processing distractors for case_study_2
Processing question 1 out of 5
Processing question 2 out of 5
Processing question 3 out of 5
Processing question 4 out of 5
Processing question 5 out of 5

{'case_study_1': {'description': '\\begin{aligned} & \\text{Chemical equation is a method of representing a chemical reaction with the help of symbols and formulae of the substances involved in it.} \\\\ & \\text{In a chemical equation, the substances which combine or react are called reactants and new substances produced are called products.} \\\\ & \\text{A chemical equation is a short hand method of representing a chemical reaction.} \\\\ & \\text{A balanced chemical equation has equal number of atoms of different elements in the reactants and products side.} \\\\ & \\text{An unbalanced chemical equation has unequal number of atoms of one or more elements in reactants and products.} \\\\ & \\text{Formulae of elements and compounds are not changed to balance an equation.} \\\\ \\end{aligned}',
  'questions': [{'question': '\\begin{aligned} & \\text{Consider the following reaction:} \\\\ & \\quad p \\mathrm{Mg}_{3} \\mathrm{~N}_{2}+q \\mathrm{H}_{2} \\mathrm{O} \\rightarrow r \\mathrm{Mg}(\\mathrm{OH})_{2}+s \\mathrm{NH}_{3} \\\\ & \\text{When the equation is balanced, what are the coefficients } p, q, r, s \\text{ respectively?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{To balance the chemical equation, ensure that the number of each type of atom is the same on both sides of the equation. Start by balancing the atoms that appear in the least number of compounds.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{The given chemical reaction is:} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow \\mathrm{Mg} (\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{To balance the equation, we need to ensure that the number of each type of atom is the same on both sides.} \\\\ &\\text{Start by balancing the magnesium (Mg) atoms. There are 3 Mg atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 3 } \\mathrm{Mg}(\\mathrm{OH})_{2}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{Next, balance the nitrogen (N) atoms. There are 2 N atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 2 } \\mathrm{NH}_{3}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Finally, balance the hydrogen (H) and oxygen (O) atoms. There are 6 OH groups in } 3 \\mathrm{Mg}(\\mathrm{OH})_{2}, \\text{ which means 6 O and 12 H atoms are needed.} \\\\ &\\text{Since 2 } \\mathrm{NH}_{3} \\text{ provides 6 H atoms, we need 6 more H atoms from } \\mathrm{H}_{2} \\mathrm{O}. \\text{ Thus, 6 } \\mathrm{H}_{2} \\mathrm{O} \\text{ are needed.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{The balanced equation is:} \\\\ &\\quad 1 \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Thus, the coefficients are } p = 1, \\ q = 6, \\ r = 3, \\ s = 2. \\end{aligned}',
    'correct_option': '\\begin{aligned} &\\quad \\text{1, 6, 3, 2} \\end{aligned}',
    'option1': '\\begin{aligned} &\\quad \\text{1, 3, 3, 2} \\end{aligned}',
    'dr1': '\\begin{aligned} &\\quad \\text{Confused the number of water molecules needed to balance hydrogen atoms.} \\end{aligned}',
    'option2': '\\begin{aligned} &\\quad \\text{1, 6, 2, 2} \\end{aligned}',
    'dr2': '\\begin{aligned} &\\quad \\text{Forgot to balance the magnesium atoms correctly.} \\end{aligned}',
    'option3': '\\begin{aligned} &\\quad \\text{1, 6, 3, 1} \\end{aligned}',
    'dr3': '\\begin{aligned} &\\quad \\text{Ignored the correct number of ammonia molecules needed to balance nitrogen atoms.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Which of the following information is not conveyed by a balanced chemical equation?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} & \\text{Consider what a balanced chemical equation typically conveys, such as the conservation of mass, the ratio of molecules, and the identities of reactants and products.} \\end{aligned}',
    'solution': '\\begin{aligned} & \\text{A balanced chemical equation provides information about the identities and relative amounts of reactants and products involved in a chemical reaction. It also indicates the conservation of mass, as the number of atoms of each element is the same on both sides of the equation. However, it does not convey information about the rate of the reaction or the conditions under which the reaction occurs, such as temperature or pressure.} \\end{aligned}',
    'correct_option': '\\begin{aligned} & \\text{Reaction rate or conditions} \\end{aligned}',
    'option1': '\\begin{aligned} & \\text{Conservation of mass} \\end{aligned}',
    'dr1': '\\begin{aligned} & \\text{Confused the concept of mass conservation with reaction conditions, which are not shown in a balanced equation.} \\end{aligned}',
    'option2': '\\begin{aligned} & \\text{Identities of reactants and products} \\end{aligned}',
    'dr2': '\\begin{aligned} & \\text{Forgot that a balanced equation clearly shows the identities of reactants and products.} \\end{aligned}',
    'option3': '\\begin{aligned} & \\text{Molecular ratios} \\end{aligned}',
    'dr3': '\\begin{aligned} & \\text{Ignored that balanced equations provide the stoichiometric ratios of molecules involved.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{The balancing of chemical equations is in accordance with which law?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Think about the fundamental law that states mass is neither created nor destroyed in a chemical reaction.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{The balancing of chemical equations is in accordance with the Law of Conservation of Mass. This law states that mass is neither created nor destroyed in a chemical reaction.}\\ &\\text{Therefore, the mass of the reactants must equal the mass of the products, which is achieved by balancing the chemical equation.}\\end{aligned}',
    'correct_option': '\\begin{aligned} &\\text{Law of Conservation of Mass} \\end{aligned}',
    'option1': '\\begin{aligned} &\\text{Law of Definite Proportions} \\end{aligned}',
    'dr1': '\\begin{aligned} &\\text{Confused the concept with the law that states a chemical compound always contains the same proportion of elements by mass.} \\end{aligned}',
    'option2': '\\begin{aligned} &\\text{Law of Multiple Proportions} \\end{aligned}',
    'dr2': '\\begin{aligned} &\\text{Misunderstood the law that involves the ratios of masses of elements in different compounds.} \\end{aligned}',
    'option3': '\\begin{aligned} &\\text{Law of Conservation of Energy} \\end{aligned}',
    'dr3': '\\begin{aligned} &\\text{Ignored the distinction between mass and energy conservation, which are separate concepts.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Which of the following chemical equations is an unbalanced one?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{To determine if a chemical equation is unbalanced, compare the number of atoms of each element on both sides of the equation. If they are not equal, the equation is unbalanced.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{A chemical equation is considered unbalanced if the number of atoms of each element is not the same on both sides of the equation.}\\quad \\text{For example, in the equation } \\text{H}_2 + \\text{O}_2 \\rightarrow \\text{H}_2\\text{O}, \\quad \\text{there are two hydrogen atoms on the left and two on the right, but there are two oxygen atoms on the left and only one on the right.}\\quad \\text{Thus, this equation is unbalanced.}\\end{aligned}',
    'correct_option': '\\begin{aligned} &\\text{H}_2 + \\text{O}_2 \\rightarrow \\text{H}_2\\text{O} \\end{aligned}',
    'option1': '\\begin{aligned} &\\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O} \\end{aligned}',
    'dr1': '\\begin{aligned} &\\text{Confused the balanced equation with the unbalanced one, as this equation has equal numbers of each type of atom on both sides.} \\end{aligned}',
    'option2': '\\begin{aligned} &\\text{C}_2\\text{H}_4 + 3\\text{O}_2 \\rightarrow 2\\text{CO}_2 + 2\\text{H}_2\\text{O} \\end{aligned}',
    'dr2': '\\begin{aligned} &\\text{Forgot that this equation is balanced, with equal numbers of each type of atom on both sides.} \\end{aligned}',
    'option3': '\\begin{aligned} &\\text{N}_2 + 3\\text{H}_2 \\rightarrow 2\\text{NH}_3 \\end{aligned}',
    'dr3': '\\begin{aligned} &\\text{Ignored the fact that this equation is balanced, with equal numbers of nitrogen and hydrogen atoms on both sides.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Which of the following statements is/are correct?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Consider the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{Ensure that the number of atoms for each element is the same on both sides of the equation.} \\\\ &\\text{This will help you identify the correct statement(s) regarding balanced chemical equations.} \\\\ \\end{aligned}',
    'solution': '\\begin{aligned} &\\text{A balanced chemical equation has equal numbers of each type of atom on both sides of the equation.} \\\\ &\\text{This is in accordance with the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{For example, in the equation } \\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O}, \\\\ &\\text{there are 4 hydrogen atoms and 2 oxygen atoms on both sides, indicating it is balanced.} \\\\ \\end{aligned}',
    'correct_option': '\\begin{aligned} &\\text{A balanced chemical equation has equal numbers of each type of atom on both sides of the equation.} \\end{aligned}',
    'option1': '\\begin{aligned} &\\text{A balanced chemical equation has more atoms on the reactant side than the product side.} \\end{aligned}',
    'dr1': '\\begin{aligned} &\\text{Confused the concept of balancing with an imbalance, which violates the law of conservation of mass.} \\end{aligned}',
    'option2': '\\begin{aligned} &\\text{A balanced chemical equation has fewer atoms on the reactant side than the product side.} \\end{aligned}',
    'dr2': '\\begin{aligned} &\\text{Forgot that the number of atoms must be equal on both sides, not fewer on one side.} \\end{aligned}',
    'option3': '\\begin{aligned} &\\text{A balanced chemical equation can have different types of atoms on each side.} \\end{aligned}',
    'dr3': '\\begin{aligned} &\\text{Ignored the requirement for the same types of atoms on both sides, misunderstanding the balancing process.} \\end{aligned}'}],
  'topic': 'Balancing Chemical Equations',
  'topic_id': '10_chemistry_chemical reactions and equations_2'},
 'case_study_2': {'description': '\\begin{aligned} & \\text{In decomposition reactions, a single reactant breaks down to form two or more products.} \\\\ & \\text{Decomposition reaction is opposite to combination reaction.} \\\\ & \\text{Thermal decomposition reactions use the energy in form of heat for decomposition of reactants.} \\\\ & \\text{Electrolytic decomposition reactions involve the use of electrical energy for the decomposition of reactant molecules.} \\\\ & \\text{Photolysis or photochemical decomposition involves the use of light energy for the purpose of decomposition.} \\\\ \\end{aligned}',
  'questions': [{'question': '\\begin{aligned} & \\text{Which of the following reactions is a decomposition reaction? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{A decomposition reaction involves a single compound breaking down into two or more simpler substances. Look for a reaction where one reactant forms multiple products.} \\end{aligned}',
    'solution': '\\begin{aligned} &\\text{In a decomposition reaction, a single compound breaks down into two or more simpler substances.} \\\\ &\\text{For example, the decomposition of calcium carbonate (CaCO}_3\\text{) is a typical decomposition reaction:} \\\\ &\\text{CaCO}_3 \\rightarrow \\text{CaO} + \\text{CO}_2 \\\\ &\\text{Here, calcium carbonate decomposes into calcium oxide and carbon dioxide.} \\end{aligned}',
    'correct_option': '\\begin{aligned} &\\text{CaCO}_3 \\rightarrow \\text{CaO} + \\text{CO}_2 \\end{aligned}',
    'option1': '\\begin{aligned} &\\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O} \\end{aligned}',
    'dr1': '\\begin{aligned} &\\text{Confused the combination reaction with a decomposition reaction, as this involves two reactants forming one product.} \\end{aligned}',
    'option2': '\\begin{aligned} &\\text{N}_2 + \\text{3H}_2 \\rightarrow \\text{2NH}_3 \\end{aligned}',
    'dr2': '\\begin{aligned} &\\text{Forgot that this is a synthesis reaction, where multiple reactants combine to form a single product.} \\end{aligned}',
    'option3': '\\begin{aligned} &\\text{C}_6\\text{H}_{12}\\text{O}_6 \\rightarrow \\text{2C}_2\\text{H}_5\\text{OH} + \\text{2CO}_2 \\end{aligned}',
    'dr3': '\\begin{aligned} &\\text{Ignored that this is a fermentation process, not a simple decomposition reaction.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{In the reaction } 2 \\mathrm{~Pb}\\left(\\mathrm{NO}_{3}\\right)_{2} \\rightarrow 2 \\mathrm{PbO}+n \\mathrm{~A}+\\mathrm{O}_{2}, \\\\ & \\text{what is } n \\mathrm{~A} \\text{ in the given reaction? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Identify the type of reaction and use stoichiometry to find the missing compound.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{The given reaction is a decomposition reaction where } 2 \\mathrm{~Pb}\\left(\\mathrm{NO}_{3}\\right)_{2} \\text{ decomposes into } 2 \\mathrm{PbO}, \\mathrm{O}_{2}, \\text{ and another compound.} \\\\ &\\text{The compound } \\mathrm{A} \\text{ is } \\mathrm{NO}_{2}, \\text{ which is a common product of the decomposition of metal nitrates.} \\\\ &\\text{Balancing the equation, we have:} \\\\ &2 \\mathrm{~Pb}\\left(\\mathrm{NO}_{3}\\right)_{2} \\rightarrow 2 \\mathrm{PbO} + 4 \\mathrm{NO}_{2} + \\mathrm{O}_{2} \\\\ &\\text{Thus, } n \\mathrm{~A} \\text{ is } 4 \\mathrm{NO}_{2}. \\end{aligned}',
    'correct_option': '\\begin{aligned} &4 \\mathrm{NO}_{2} \\end{aligned}',
    'option1': '\\begin{aligned} &2 \\mathrm{NO}_{2} \\end{aligned}',
    'dr1': '\\begin{aligned} &\\text{Confused the stoichiometric coefficients, using the coefficient of } \\mathrm{PbO} \\text{ instead of } \\mathrm{NO}_{2}. \\end{aligned}',
    'option2': '\\begin{aligned} &3 \\mathrm{NO}_{2} \\end{aligned}',
    'dr2': '\\begin{aligned} &\\text{Forgot to balance the equation correctly, leading to an incorrect coefficient for } \\mathrm{NO}_{2}. \\end{aligned}',
    'option3': '\\begin{aligned} &5 \\mathrm{NO}_{2} \\end{aligned}',
    'dr3': '\\begin{aligned} &\\text{Ignored the correct stoichiometry, overestimating the amount of } \\mathrm{NO}_{2} \\text{ produced.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Amino acid is formed by the decomposition of which component of our diet? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Consider which macromolecules in our diet break down to form amino acids.}\\\\ &\\text{Think about the role of proteins in the body and their basic building blocks.}\\\\ \\end{aligned}',
    'solution': '\\begin{aligned} &\\text{Amino acids are formed by the decomposition of proteins in our diet.}\\\\ &\\text{Proteins are large, complex molecules that are broken down into amino acids through}\\\\ &\\text{decomposition reactions in the digestive system. This process involves breaking the}\\\\ &\\text{peptide bonds that link amino acids together in proteins.}\\\\ \\end{aligned}',
    'correct_option': '\\begin{aligned} &\\text{Proteins} \\end{aligned}',
    'option1': '\\begin{aligned} &\\text{Carbohydrates} \\end{aligned}',
    'dr1': '\\begin{aligned} &\\text{Confused carbohydrates with proteins, which are not broken down into amino acids.} \\end{aligned}',
    'option2': '\\begin{aligned} &\\text{Fats} \\end{aligned}',
    'dr2': '\\begin{aligned} &\\text{Forgot that fats decompose into fatty acids and glycerol, not amino acids.} \\end{aligned}',
    'option3': '\\begin{aligned} &\\text{Vitamins} \\end{aligned}',
    'dr3': '\\begin{aligned} &\\text{Ignored that vitamins are not macromolecules that decompose into amino acids.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{Silver chloride on exposure to sunlight for a long duration turns grey due to which of the following? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Consider the type of reaction occurring when silver chloride is exposed to sunlight and the change in color.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{When silver chloride (AgCl) is exposed to sunlight, it undergoes a decomposition reaction.}\\\\ &\\text{This reaction is photochemical, meaning it is driven by light.}\\\\ &\\text{The chemical equation for this reaction is:}\\\\ &\\quad 2\\text{AgCl} \\rightarrow 2\\text{Ag} + \\text{Cl}_2\\\\ &\\text{In this reaction, silver chloride decomposes into silver (Ag) and chlorine gas (Cl}_2\\text{).}\\\\ &\\text{The grey color is due to the formation of metallic silver.}\\end{aligned}',
    'correct_option': '\\begin{aligned} &\\text{Formation of metallic silver} \\end{aligned}',
    'option1': '\\begin{aligned} &\\text{Formation of silver oxide} \\end{aligned}',
    'dr1': '\\begin{aligned} &\\text{Confused the decomposition reaction with oxidation, leading to silver oxide instead of metallic silver.} \\end{aligned}',
    'option2': '\\begin{aligned} &\\text{Formation of silver nitrate} \\end{aligned}',
    'dr2': '\\begin{aligned} &\\text{Misunderstood the reaction process, thinking nitrate ions are involved instead of decomposition.} \\end{aligned}',
    'option3': '\\begin{aligned} &\\text{Formation of silver sulfide} \\end{aligned}',
    'dr3': '\\begin{aligned} &\\text{Ignored the absence of sulfur in the reaction, mistakenly assuming silver sulfide formation.} \\end{aligned}'},
   {'question': '\\begin{aligned} & \\text{What type of chemical reaction takes place when electricity is passed through water? (Multiple Choice)} \\\\ \\end{aligned}',
    'hint': '\\begin{aligned} &\\text{Consider the process of breaking down a compound into simpler substances when electricity is applied.}\\end{aligned}',
    'solution': '\\begin{aligned} &\\text{When electricity is passed through water, it undergoes a decomposition reaction.}\\quad \\text{In this type of reaction, a single compound breaks down into two or more simpler substances.}\\quad \\text{The chemical equation for the decomposition of water is:}\\\\ &\\quad 2\\text{H}_2\\text{O} \\rightarrow 2\\text{H}_2 + \\text{O}_2\\\\ &\\text{This reaction is an example of electrolysis, where water is decomposed into hydrogen and oxygen gases.}\\end{aligned}',
    'correct_option': '\\begin{aligned} &\\text{Decomposition reaction} \\end{aligned}',
    'option1': '\\begin{aligned} &\\text{Combination reaction} \\end{aligned}',
    'dr1': '\\begin{aligned} &\\text{Confused the process with a combination reaction, which involves forming a compound from simpler substances.} \\end{aligned}',
    'option2': '\\begin{aligned} &\\text{Displacement reaction} \\end{aligned}',

In [49]:
data = convert_case_studies_to_df(clean_rephrased_questions_json)
data

Created DataFrame with 10 questions from 2 case studies

,case_study,description,topic,topic_id,question,hint,solution,correct_option,option1,dr1,option2,dr2,option3,dr3
0,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Consider the following...,\begin{aligned} &\text{To balance the chemical...,\begin{aligned} &\text{The given chemical reac...,"\begin{aligned} &\quad \text{1, 6, 3, 2} \end{...","\begin{aligned} &\quad \text{1, 3, 3, 2} \end{...",\begin{aligned} &\quad \text{Confused the numb...,"\begin{aligned} &\quad \text{1, 6, 2, 2} \end{...",\begin{aligned} &\quad \text{Forgot to balance...,"\begin{aligned} &\quad \text{1, 6, 3, 1} \end{...",\begin{aligned} &\quad \text{Ignored the corre...
1,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,\begin{aligned} & \text{Consider what a balanc...,\begin{aligned} & \text{A balanced chemical eq...,\begin{aligned} & \text{Reaction rate or condi...,\begin{aligned} & \text{Conservation of mass} ...,\begin{aligned} & \text{Confused the concept o...,\begin{aligned} & \text{Identities of reactant...,\begin{aligned} & \text{Forgot that a balanced...,\begin{aligned} & \text{Molecular ratios} \end...,\begin{aligned} & \text{Ignored that balanced ...
2,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{The balancing of chemi...,\begin{aligned} &\text{Think about the fundame...,\begin{aligned} &\text{The balancing of chemic...,\begin{aligned} &\text{Law of Conservation of ...,\begin{aligned} &\text{Law of Definite Proport...,\begin{aligned} &\text{Confused the concept wi...,\begin{aligned} &\text{Law of Multiple Proport...,\begin{aligned} &\text{Misunderstood the law t...,\begin{aligned} &\text{Law of Conservation of ...,\begin{aligned} &\text{Ignored the distinction...
3,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,\begin{aligned} &\text{To determine if a chemi...,\begin{aligned} &\text{A chemical equation is ...,\begin{aligned} &\text{H}_2 + \text{O}_2 \righ...,\begin{aligned} &\text{2H}_2 + \text{O}_2 \rig...,\begin{aligned} &\text{Confused the balanced e...,\begin{aligned} &\text{C}_2\text{H}_4 + 3\text...,\begin{aligned} &\text{Forgot that this equati...,\begin{aligned} &\text{N}_2 + 3\text{H}_2 \rig...,\begin{aligned} &\text{Ignored the fact that t...
4,case_study_1,\begin{aligned} & \text{Chemical equation is a...,Balancing Chemical Equations,10_chemistry_chemical reactions and equations_2,\begin{aligned} & \text{Which of the following...,\begin{aligned} &\text{Consider the law of con...,\begin{aligned} &\text{A balanced chemical equ...,\begin{aligned} &\text{A balanced chemical equ...,\begin{aligned} &\text{A balanced chemical equ...,\begin{aligned} &\text{Confused the concept of...,\begin{aligned} &\text{A balanced chemical equ...,\begin{aligned} &\text{Forgot that the number ...,\begin{aligned} &\text{A balanced chemical equ...,\begin{aligned} &\text{Ignored the requirement...
5,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Which of the following...,\begin{aligned} &\text{A decomposition reactio...,\begin{aligned} &\text{In a decomposition reac...,\begin{aligned} &\text{CaCO}_3 \rightarrow \te...,\begin{aligned} &\text{2H}_2 + \text{O}_2 \rig...,\begin{aligned} &\text{Confused the combinatio...,\begin{aligned} &\text{N}_2 + \text{3H}_2 \rig...,\begin{aligned} &\text{Forgot that this is a s...,\begin{aligned} &\text{C}_6\text{H}_{12}\text{...,\begin{aligned} &\text{Ignored that this is a ...
6,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{In the reaction } 2 \m...,\begin{aligned} &\text{Identify the type of re...,\begin{aligned} &\text{The given reaction is a...,\begin{aligned} &4 \mathrm{NO}_{2} \end{aligned},\begin{aligned} &2 \mathrm{NO}_{2} \end{aligned},\begin{aligned} &\text{Confused the stoichiome...,\begin{aligned} &3 \mathrm{NO}_{2} \end{aligned},\begin{aligned} &\text{Forgot to balance the e...,\begin{aligned} &5 \mathrm{NO}_{2} \end{aligned},\begin{aligned} &\text{Ignored the correct sto...
7,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Amino acid is formed b...,\begin{aligned} &\text{Consider which macromol...,\begin{aligned} &\text{Amino acids are formed ...,\begin{aligned} &\text{Proteins} \end{aligned},\begin{aligned} &\text{Carbohydrates} \end{ali...,\begin{aligned} &\text{Confused carbohydrates ...,\begin{aligned} &\text{Fats} \end{aligned},\begin{aligned} &\text{Forgot that fats decomp...,\begin{aligned} &\text{Vitamins} \end{aligned},\begin{aligned} &\text{Ignored that vitamins a...
8,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{Silver chloride on exp...,\begin{aligned} &\text{Consider the type of re...,\begin{aligned} &\text{When silver chloride (A...,\begin{aligned} &\text{Formation of metallic s...,\begin{aligned} &\text{Formation of silver oxi...,\begin{aligned} &\text{Confused the decomposit...,\begin{aligned} &\text{Formation of silver nit...,\begin{aligned} &\text{Misunderstood the react...,\begin{aligned} &\text{Formation of silver sul...,\begin{aligned} &\text{Ignored the absence of ...
9,case_study_2,\begin{aligned} & \text{In decomposition react...,Combination and Decomposition Reactions,10_chemistry_chemical reactions and equations_3,\begin{aligned} & \text{What type of chemical ...,\begin{aligned} &\text{Consider the process of...,\begin{aligned} &\text{When electricity is pas...,\begin{aligned} &\text{Decomposition reaction}...,\begin{aligned} &\text{Combination reaction} \...,\begin{aligned} &\text{Confused the process wi...,\begin{aligned} &\text{Displacement reaction} ...,\begin{aligned} &\text{Misunderstood the react...,\begin{aligned} &\text{Redox reaction} \end{al...,\begin{aligned} &\text{Ignored that while elec...

### Output Formatting & Pushing into the DB

In [50]:
def process_case_studies(data, conf_data):
   try:
       # Common metadata for all case studies
       common_metadata = {
           "grade": conf_data['grade'],
           "board": "CBSE",
           "subject": subject,
           "chapter_name": conf_data['chapter_name'],
           "publication": conf_data['publication']
       }

       # Group by case study and process rows
       case_study_data = {}
       for idx, row in data.iterrows():
           case_key = row["case_study"]
           
           # Create question data
           question_data = {
               "topic_id": row["topic_id"],
               "topic_name": row["topic"],
               "question": [{"content": row["question"]}],
               "hint": [{"content": row["hint"]}],
               "solution": [{"content": row["solution"]}],
               "final_answer": [{"content": row["correct_option"]}],
               "option1": [{"content": row["option1"]}],
               "dr1": [{"content": row["dr1"]}],
               "option2": [{"content": row["option2"]}],
               "dr2": [{"content": row["dr2"]}],
               "option3": [{"content": row["option3"]}],
               "dr3": [{"content": row["dr3"]}]
           }
           
           # Add to case study group
           if case_key not in case_study_data:
               case_study_data[case_key] = {
                   **common_metadata,  # Add common metadata
                   "case_study": row["description"],
                   "questions": []
               }
           case_study_data[case_key]["questions"].append(question_data)

       final_output = list(case_study_data.values())
       return final_output

   except Exception as e:
       print(f"Error processing case studies: {str(e)}")
       return []

# Process the data
final_output = process_case_studies(data, conf_data)
final_output

[{'grade': '10',
  'board': 'CBSE',
  'subject': 'chemistry',
  'chapter_name': 'Chemical Reactions and Equations',
  'publication': 'mtg',
  'case_study': '\\begin{aligned} & \\text{Chemical equation is a method of representing a chemical reaction with the help of symbols and formulae of the substances involved in it.} \\\\ & \\text{In a chemical equation, the substances which combine or react are called reactants and new substances produced are called products.} \\\\ & \\text{A chemical equation is a short hand method of representing a chemical reaction.} \\\\ & \\text{A balanced chemical equation has equal number of atoms of different elements in the reactants and products side.} \\\\ & \\text{An unbalanced chemical equation has unequal number of atoms of one or more elements in reactants and products.} \\\\ & \\text{Formulae of elements and compounds are not changed to balance an equation.} \\\\ \\end{aligned}',
  'questions': [{'topic_id': '10_chemistry_chemical reactions and equations_2',
    'topic_name': 'Balancing Chemical Equations',
    'question': [{'content': '\\begin{aligned} & \\text{Consider the following reaction:} \\\\ & \\quad p \\mathrm{Mg}_{3} \\mathrm{~N}_{2}+q \\mathrm{H}_{2} \\mathrm{O} \\rightarrow r \\mathrm{Mg}(\\mathrm{OH})_{2}+s \\mathrm{NH}_{3} \\\\ & \\text{When the equation is balanced, what are the coefficients } p, q, r, s \\text{ respectively?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
    'hint': [{'content': '\\begin{aligned} &\\text{To balance the chemical equation, ensure that the number of each type of atom is the same on both sides of the equation. Start by balancing the atoms that appear in the least number of compounds.}\\end{aligned}'}],
    'solution': [{'content': '\\begin{aligned} &\\text{The given chemical reaction is:} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow \\mathrm{Mg} (\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{To balance the equation, we need to ensure that the number of each type of atom is the same on both sides.} \\\\ &\\text{Start by balancing the magnesium (Mg) atoms. There are 3 Mg atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 3 } \\mathrm{Mg}(\\mathrm{OH})_{2}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{Next, balance the nitrogen (N) atoms. There are 2 N atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 2 } \\mathrm{NH}_{3}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Finally, balance the hydrogen (H) and oxygen (O) atoms. There are 6 OH groups in } 3 \\mathrm{Mg}(\\mathrm{OH})_{2}, \\text{ which means 6 O and 12 H atoms are needed.} \\\\ &\\text{Since 2 } \\mathrm{NH}_{3} \\text{ provides 6 H atoms, we need 6 more H atoms from } \\mathrm{H}_{2} \\mathrm{O}. \\text{ Thus, 6 } \\mathrm{H}_{2} \\mathrm{O} \\text{ are needed.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{The balanced equation is:} \\\\ &\\quad 1 \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Thus, the coefficients are } p = 1, \\ q = 6, \\ r = 3, \\ s = 2. \\end{aligned}'}],
    'final_answer': [{'content': '\\begin{aligned} &\\quad \\text{1, 6, 3, 2} \\end{aligned}'}],
    'option1': [{'content': '\\begin{aligned} &\\quad \\text{1, 3, 3, 2} \\end{aligned}'}],
    'dr1': [{'content': '\\begin{aligned} &\\quad \\text{Confused the number of water molecules needed to balance hydrogen atoms.} \\end{aligned}'}],
    'option2': [{'content': '\\begin{aligned} &\\quad \\text{1, 6, 2, 2} \\end{aligned}'}],
    'dr2': [{'content': '\\begin{aligned} &\\quad \\text{Forgot to balance the magnesium atoms correctly.} \\end{aligned}'}],
    'option3': [{'content': '\\begin{aligned} &\\quad \\text{1, 6, 3, 1} \\end{aligned}'}],
    'dr3': [{'content': '\\begin{aligned} &\\quad \\text{Ignored the correct number of ammonia molecules needed to balance nitrogen atoms.} \\end{aligned}'}]},
   {'topic_id': '10_chemistry_chemical reactions and equations_2',
    'topic_name': 'Balancing Chemical Equations',
    'question': [{'content': '\\begin{aligned} & \\text{Which of the following information is not conveyed by a balanced chemical equation?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
    'hint': [{'content': '\\begin{aligned} & \\text{Consider what a balanced chemical equation typically conveys, such as the conservation of mass, the ratio of molecules, and the identities of reactants and products.} \\end{aligned}'}],
    'solution': [{'content': '\\begin{aligned} & \\text{A balanced chemical equation provides information about the identities and relative amounts of reactants and products involved in a chemical reaction. It also indicates the conservation of mass, as the number of atoms of each element is the same on both sides of the equation. However, it does not convey information about the rate of the reaction or the conditions under which the reaction occurs, such as temperature or pressure.} \\end{aligned}'}],
    'final_answer': [{'content': '\\begin{aligned} & \\text{Reaction rate or conditions} \\end{aligned}'}],
    'option1': [{'content': '\\begin{aligned} & \\text{Conservation of mass} \\end{aligned}'}],
    'dr1': [{'content': '\\begin{aligned} & \\text{Confused the concept of mass conservation with reaction conditions, which are not shown in a balanced equation.} \\end{aligned}'}],
    'option2': [{'content': '\\begin{aligned} & \\text{Identities of reactants and products} \\end{aligned}'}],
    'dr2': [{'content': '\\begin{aligned} & \\text{Forgot that a balanced equation clearly shows the identities of reactants and products.} \\end{aligned}'}],
    'option3': [{'content': '\\begin{aligned} & \\text{Molecular ratios} \\end{aligned}'}],
    'dr3': [{'content': '\\begin{aligned} & \\text{Ignored that balanced equations provide the stoichiometric ratios of molecules involved.} \\end{aligned}'}]},
   {'topic_id': '10_chemistry_chemical reactions and equations_2',
    'topic_name': 'Balancing Chemical Equations',
    'question': [{'content': '\\begin{aligned} & \\text{The balancing of chemical equations is in accordance with which law?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
    'hint': [{'content': '\\begin{aligned} &\\text{Think about the fundamental law that states mass is neither created nor destroyed in a chemical reaction.}\\end{aligned}'}],
    'solution': [{'content': '\\begin{aligned} &\\text{The balancing of chemical equations is in accordance with the Law of Conservation of Mass. This law states that mass is neither created nor destroyed in a chemical reaction.}\\ &\\text{Therefore, the mass of the reactants must equal the mass of the products, which is achieved by balancing the chemical equation.}\\end{aligned}'}],
    'final_answer': [{'content': '\\begin{aligned} &\\text{Law of Conservation of Mass} \\end{aligned}'}],
    'option1': [{'content': '\\begin{aligned} &\\text{Law of Definite Proportions} \\end{aligned}'}],
    'dr1': [{'content': '\\begin{aligned} &\\text{Confused the concept with the law that states a chemical compound always contains the same proportion of elements by mass.} \\end{aligned}'}],
    'option2': [{'content': '\\begin{aligned} &\\text{Law of Multiple Proportions} \\end{aligned}'}],
    'dr2': [{'content': '\\begin{aligned} &\\text{Misunderstood the law that involves the ratios of masses of elements in different compounds.} \\end{aligned}'}],
    'option3': [{'content': '\\begin{aligned} &\\text{Law of Conservation of Energy} \\end{aligned}'}],
    'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the distinction between mass and energy conservation, which are separate concepts.} \\end{aligned}'}]},
   {'topic_id': '10_chemistry_chemical reactions and equations_2',
    'topic_name': 'Balancing Chemical Equations',
    'question': [{'content': '\\begin{aligned} & \\text{Which of the following chemical equations is an unbalanced one?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
    'hint': [{'content': '\\begin{aligned} &\\text{To determine if a chemical equation is unbalanced, compare the number of atoms of each element on both sides of the equation. If they are not equal, the equation is unbalanced.}\\end{aligned}'}],
    'solution': [{'content': '\\begin{aligned} &\\text{A chemical equation is considered unbalanced if the number of atoms of each element is not the same on both sides of the equation.}\\quad \\text{For example, in the equation } \\text{H}_2 + \\text{O}_2 \\rightarrow \\text{H}_2\\text{O}, \\quad \\text{there are two hydrogen atoms on the left and two on the right, but there are two oxygen atoms on the left and only one on the right.}\\quad \\text{Thus, this equation is unbalanced.}\\end{aligned}'}],
    'final_answer': [{'content': '\\begin{aligned} &\\text{H}_2 + \\text{O}_2 \\rightarrow \\text{H}_2\\text{O} \\end{aligned}'}],
    'option1': [{'content': '\\begin{aligned} &\\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O} \\end{aligned}'}],
    'dr1': [{'content': '\\begin{aligned} &\\text{Confused the balanced equation with the unbalanced one, as this equation has equal numbers of each type of atom on both sides.} \\end{aligned}'}],
    'option2': [{'content': '\\begin{aligned} &\\text{C}_2\\text{H}_4 + 3\\text{O}_2 \\rightarrow 2\\text{CO}_2 + 2\\text{H}_2\\text{O} \\end{aligned}'}],
    'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that this equation is balanced, with equal numbers of each type of atom on both sides.} \\end{aligned}'}],
    'option3': [{'content': '\\begin{aligned} &\\text{N}_2 + 3\\text{H}_2 \\rightarrow 2\\text{NH}_3 \\end{aligned}'}],
    'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the fact that this equation is balanced, with equal numbers of nitrogen and hydrogen atoms on both sides.} \\end{aligned}'}]},
   {'topic_id': '10_chemistry_chemical reactions and equations_2',
    'topic_name': 'Balancing Chemical Equations',
    'question': [{'content': '\\begin{aligned} & \\text{Which of the following statements is/are correct?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
    'hint': [{'content': '\\begin{aligned} &\\text{Consider the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{Ensure that the number of atoms for each element is the same on both sides of the equation.} \\\\ &\\text{This will help you identify the correct statement(s) regarding balanced chemical equations.} \\\\ \\end{aligned}'}],
    'solution': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation has equal numbers of each type of atom on both sides of the equation.} \\\\ &\\text{This is in accordance with the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{For example, in the equation } \\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O}, \\\\ &\\text{there are 4 hydrogen atoms and 2 oxygen atoms on both sides, indicating it is balanced.} \\\\ \\end{aligned}'}],
    'final_answer': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation has equal numbers of each type of atom on both sides of the equation.} \\end{aligned}'}],
    'option1': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation has more atoms on the reactant side than the product side.} \\end{aligned}'}],
    'dr1': [{'content': '\\begin{aligned} &\\text{Confused the concept of balancing with an imbalance, which violates the law of conservation of mass.} \\end{aligned}'}],
    'option2': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation has fewer atoms on the reactant side than the product side.} \\end{aligned}'}],
    'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that the number of atoms must be equal on both sides, not fewer on one side.} \\end{aligned}'}],
    'option3': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation can have different types of atoms on each side.} \\end{aligned}'}],
    'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the requirement for the same types of atoms on both sides, misunderstanding the balancing process.} \\end{aligned}'}]}]},
 {'grade': '10',
  'board': 'CBSE',
  'subject': 'chemistry',
  'chapter_name': 'Chemical Reactions and Equations',
  'publication': 'mtg',
  'case_study': '\\begin{aligned} & \\text{In decomposition reactions, a single reactant breaks down to form two or more products.} \\\\ & \\text{Decomposition reaction is opposite to combination reaction.} \\\\ & \\text{Thermal decomposition reactions use the energy in form of heat for decomposition of reactants.} \\\\ & \\text{Electrolytic decomposition reactions involve the use of electrical energy for the decomposition of reactant molecules.} \\\\ & \\text{Photolysis or photochemical decomposition involves the use of light energy for the purpose of decomposition.} \\\\ \\end{aligned}',
  'questions': [{'topic_id': '10_chemistry_chemical reactions and equations_3',
    'topic_name': 'Combination and Decomposition Reactions',
    'question': [{'content': '\\begin{aligned} & \\text{Which of the following reactions is a decomposition reaction? (Multiple Choice)} \\\\ \\end{aligned}'}],
    'hint': [{'content': '\\begin{aligned} &\\text{A decomposition reaction involves a single compound breaking down into two or more simpler substances. Look for a reaction where one reactant forms multiple products.} \\end{aligned}'}],
    'solution': [{'content': '\\begin{aligned} &\\text{In a decomposition reaction, a single compound breaks down into two or more simpler substances.} \\\\ &\\text{For example, the decomposition of calcium carbonate (CaCO}_3\\text{) is a typical decomposition reaction:} \\\\ &\\text{CaCO}_3 \\rightarrow \\text{CaO} + \\text{CO}_2 \\\\ &\\text{Here, calcium carbonate decomposes into calcium oxide and carbon dioxide.} \\end{aligned}'}],
    'final_answer': [{'content': '\\begin{aligned} &\\text{CaCO}_3 \\rightarrow \\text{CaO} + \\text{CO}_2 \\end{aligned}'}],
    'option1': [{'content': '\\begin{aligned} &\\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O} \\end{aligned}'}],
    'dr1': [{'content': '\\begin{aligned} &\\text{Confused the combination reaction with a decomposition reaction, as this involves two reactants forming one product.} \\end{aligned}'}],
    'option2': [{'content': '\\begin{aligned} &\\text{N}_2 + \\text{3H}_2 \\rightarrow \\text{2NH}_3 \\end{aligned}'}],
    'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that this is a synthesis reaction, where multiple reactants combine to form a single product.} \\end{aligned}'}],
    'option3': [{'content': '\\begin{aligned} &\\text{C}_6\\text{H}_{12}\\text{O}_6 \\rightarrow \\text{2C}_2\\text{H}_5\\text{OH} + \\text{2CO}_2 \\end{aligned}'}],
    'dr3': [{'content': '\\begin{aligned} &\\text{Ignored that this is a fermentation process, not a simple decomposition reaction.} \\end{aligned}'}]},
   {'topic_id': '10_chemistry_chemical reactions and equations_3',
    'topic_name': 'Combination and Decomposition Reactions',
    'question': [{'content': '\\begin{aligned} & \\text{In the reaction } 2 \\mathrm{~Pb}\\left(\\mathrm{NO}_{3}\\right)_{2} \\rightarrow 2 \\mathrm{PbO}+n \\mathrm{~A}+\\mathrm{O}_{2}, \\\\ & \\text{what is } n \\mathrm{~A} \\text{ in the given reaction? (Multiple Choice)} \\\\ \\end{aligned}'}],
    'hint': [{'content': '\\begin{aligned} &\\text{Identify the type of reaction and use stoichiometry to find the missing compound.}\\end{aligned}'}],
    'solution': [{'content': '\\begin{aligned} &\\text{The given reaction is a decomposition reaction where } 2 \\mathrm{~Pb}\\left(\\mathrm{NO}_{3}\\right)_{2} \\text{ decomposes into } 2 \\mathrm{PbO}, \\mathrm{O}_{2}, \\text{ and another compound.} \\\\ &\\text{The compound } \\mathrm{A} \\text{ is } \\mathrm{NO}_{2}, \\text{ which is a common product of the decomposition of metal nitrates.} \\\\ &\\text{Balancing the equation, we have:} \\\\ &2 \\mathrm{~Pb}\\left(\\mathrm{NO}_{3}\\right)_{2} \\rightarrow 2 \\mathrm{PbO} + 4 \\mathrm{NO}_{2} + \\mathrm{O}_{2} \\\\ &\\text{Thus, } n \\mathrm{~A} \\text{ is } 4 \\mathrm{NO}_{2}. \\end{aligned}'}],
    'final_answer': [{'content': '\\begin{aligned} &4 \\mathrm{NO}_{2} \\end{aligned}'}],
    'option1': [{'content': '\\begin{aligned} &2 \\mathrm{NO}_{2} \\end{aligned}'}],
    'dr1': [{'content': '\\begin{aligned} &\\text{Confused the stoichiometric coefficients, using the coefficient of } \\mathrm{PbO} \\text{ instead of } \\mathrm{NO}_{2}. \\end{aligned}'}],
    'option2': [{'content': '\\begin{aligned} &3 \\mathrm{NO}_{2} \\end{aligned}'}],
    'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to balance the equation correctly, leading to an incorrect coefficient for } \\mathrm{NO}_{2}. \\end{aligned}'}],
    'option3': [{'content': '\\begin{aligned} &5 \\mathrm{NO}_{2} \\end{aligned}'}],
    'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the correct stoichiometry, overestimating the amount of } \\mathrm{NO}_{2} \\text{ produced.} \\end{aligned}'}]},
   {'topic_id': '10_chemistry_chemical reactions and equations_3',
    'topic_name': 'Combination and Decomposition Reactions',
    'question': [{'content': '\\begin{aligned} & \\text{Amino acid is formed by the decomposition of which component of our diet? (Multiple Choice)} \\\\ \\end{aligned}'}],
    'hint': [{'content': '\\begin{aligned} &\\text{Consider which macromolecules in our diet break down to form amino acids.}\\\\ &\\text{Think about the role of proteins in the body and their basic building blocks.}\\\\ \\end{aligned}'}],
    'solution': [{'content': '\\begin{aligned} &\\text{Amino acids are formed by the decomposition of proteins in our diet.}\\\\ &\\text{Proteins are large, complex molecules that are broken down into amino acids through}\\\\ &\\text{decomposition reactions in the digestive system. This process involves breaking the}\\\\ &\\text{peptide bonds that link amino acids together in proteins.}\\\\ \\end{aligned}'}],
    'final_answer': [{'content': '\\begin{aligned} &\\text{Proteins} \\end{aligned}'}],
    'option1': [{'content': '\\begin{aligned} &\\text{Carbohydrates} \\end{aligned}'}],
    'dr1': [{'content': '\\begin{aligned} &\\text{Confused carbohydrates with proteins, which are not broken down into amino acids.} \\end{aligned}'}],
    'option2': [{'content': '\\begin{aligned} &\\text{Fats} \\end{aligned}'}],
    'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that fats decompose into fatty acids and glycerol, not amino acids.} \\end{aligned}'}],
    'option3': [{'content': '\\begin{aligned} &\\text{Vitamins} \\end{aligned}'}],
    'dr3': [{'content': '\\begin{aligned} &\\text{Ignored that vitamins are not macromolecules that decompose into amino acids.} \\end{aligned}'}]},
   {'topic_id': '10_chemistry_chemical reactions and equations_3',
    'topic_name': 'Combination and Decomposition Reactions',
    'question': [{'content': '\\begin{aligned} & \\text{Silver chloride on exposure to sunlight for a long duration turns grey due to which of the following? (Multiple Choice)} \\\\ \\end{aligned}'}],
    'hint': [{'content': '\\begin{aligned} &\\text{Consider the type of reaction occurring when silver chloride is exposed to sunlight and the change in color.}\\end{aligned}'}],

In [51]:
final_output[0]

{'grade': '10',
 'board': 'CBSE',
 'subject': 'chemistry',
 'chapter_name': 'Chemical Reactions and Equations',
 'publication': 'mtg',
 'case_study': '\\begin{aligned} & \\text{Chemical equation is a method of representing a chemical reaction with the help of symbols and formulae of the substances involved in it.} \\\\ & \\text{In a chemical equation, the substances which combine or react are called reactants and new substances produced are called products.} \\\\ & \\text{A chemical equation is a short hand method of representing a chemical reaction.} \\\\ & \\text{A balanced chemical equation has equal number of atoms of different elements in the reactants and products side.} \\\\ & \\text{An unbalanced chemical equation has unequal number of atoms of one or more elements in reactants and products.} \\\\ & \\text{Formulae of elements and compounds are not changed to balance an equation.} \\\\ \\end{aligned}',
 'questions': [{'topic_id': '10_chemistry_chemical reactions and equations_2',
   'topic_name': 'Balancing Chemical Equations',
   'question': [{'content': '\\begin{aligned} & \\text{Consider the following reaction:} \\\\ & \\quad p \\mathrm{Mg}_{3} \\mathrm{~N}_{2}+q \\mathrm{H}_{2} \\mathrm{O} \\rightarrow r \\mathrm{Mg}(\\mathrm{OH})_{2}+s \\mathrm{NH}_{3} \\\\ & \\text{When the equation is balanced, what are the coefficients } p, q, r, s \\text{ respectively?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
   'hint': [{'content': '\\begin{aligned} &\\text{To balance the chemical equation, ensure that the number of each type of atom is the same on both sides of the equation. Start by balancing the atoms that appear in the least number of compounds.}\\end{aligned}'}],
   'solution': [{'content': '\\begin{aligned} &\\text{The given chemical reaction is:} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow \\mathrm{Mg} (\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{To balance the equation, we need to ensure that the number of each type of atom is the same on both sides.} \\\\ &\\text{Start by balancing the magnesium (Mg) atoms. There are 3 Mg atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 3 } \\mathrm{Mg}(\\mathrm{OH})_{2}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + \\mathrm{NH}_{3} \\\\ &\\text{Next, balance the nitrogen (N) atoms. There are 2 N atoms in } \\mathrm{Mg}_{3} \\mathrm{~N}_{2}, \\text{ so we need 2 } \\mathrm{NH}_{3}.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Finally, balance the hydrogen (H) and oxygen (O) atoms. There are 6 OH groups in } 3 \\mathrm{Mg}(\\mathrm{OH})_{2}, \\text{ which means 6 O and 12 H atoms are needed.} \\\\ &\\text{Since 2 } \\mathrm{NH}_{3} \\text{ provides 6 H atoms, we need 6 more H atoms from } \\mathrm{H}_{2} \\mathrm{O}. \\text{ Thus, 6 } \\mathrm{H}_{2} \\mathrm{O} \\text{ are needed.} \\\\ &\\quad \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{The balanced equation is:} \\\\ &\\quad 1 \\mathrm{Mg}_{3} \\mathrm{~N}_{2} + 6 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 3 \\mathrm{Mg}(\\mathrm{OH})_{2} + 2 \\mathrm{NH}_{3} \\\\ &\\text{Thus, the coefficients are } p = 1, \\ q = 6, \\ r = 3, \\ s = 2. \\end{aligned}'}],
   'final_answer': [{'content': '\\begin{aligned} &\\quad \\text{1, 6, 3, 2} \\end{aligned}'}],
   'option1': [{'content': '\\begin{aligned} &\\quad \\text{1, 3, 3, 2} \\end{aligned}'}],
   'dr1': [{'content': '\\begin{aligned} &\\quad \\text{Confused the number of water molecules needed to balance hydrogen atoms.} \\end{aligned}'}],
   'option2': [{'content': '\\begin{aligned} &\\quad \\text{1, 6, 2, 2} \\end{aligned}'}],
   'dr2': [{'content': '\\begin{aligned} &\\quad \\text{Forgot to balance the magnesium atoms correctly.} \\end{aligned}'}],
   'option3': [{'content': '\\begin{aligned} &\\quad \\text{1, 6, 3, 1} \\end{aligned}'}],
   'dr3': [{'content': '\\begin{aligned} &\\quad \\text{Ignored the correct number of ammonia molecules needed to balance nitrogen atoms.} \\end{aligned}'}]},
  {'topic_id': '10_chemistry_chemical reactions and equations_2',
   'topic_name': 'Balancing Chemical Equations',
   'question': [{'content': '\\begin{aligned} & \\text{Which of the following information is not conveyed by a balanced chemical equation?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
   'hint': [{'content': '\\begin{aligned} & \\text{Consider what a balanced chemical equation typically conveys, such as the conservation of mass, the ratio of molecules, and the identities of reactants and products.} \\end{aligned}'}],
   'solution': [{'content': '\\begin{aligned} & \\text{A balanced chemical equation provides information about the identities and relative amounts of reactants and products involved in a chemical reaction. It also indicates the conservation of mass, as the number of atoms of each element is the same on both sides of the equation. However, it does not convey information about the rate of the reaction or the conditions under which the reaction occurs, such as temperature or pressure.} \\end{aligned}'}],
   'final_answer': [{'content': '\\begin{aligned} & \\text{Reaction rate or conditions} \\end{aligned}'}],
   'option1': [{'content': '\\begin{aligned} & \\text{Conservation of mass} \\end{aligned}'}],
   'dr1': [{'content': '\\begin{aligned} & \\text{Confused the concept of mass conservation with reaction conditions, which are not shown in a balanced equation.} \\end{aligned}'}],
   'option2': [{'content': '\\begin{aligned} & \\text{Identities of reactants and products} \\end{aligned}'}],
   'dr2': [{'content': '\\begin{aligned} & \\text{Forgot that a balanced equation clearly shows the identities of reactants and products.} \\end{aligned}'}],
   'option3': [{'content': '\\begin{aligned} & \\text{Molecular ratios} \\end{aligned}'}],
   'dr3': [{'content': '\\begin{aligned} & \\text{Ignored that balanced equations provide the stoichiometric ratios of molecules involved.} \\end{aligned}'}]},
  {'topic_id': '10_chemistry_chemical reactions and equations_2',
   'topic_name': 'Balancing Chemical Equations',
   'question': [{'content': '\\begin{aligned} & \\text{The balancing of chemical equations is in accordance with which law?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
   'hint': [{'content': '\\begin{aligned} &\\text{Think about the fundamental law that states mass is neither created nor destroyed in a chemical reaction.}\\end{aligned}'}],
   'solution': [{'content': '\\begin{aligned} &\\text{The balancing of chemical equations is in accordance with the Law of Conservation of Mass. This law states that mass is neither created nor destroyed in a chemical reaction.}\\ &\\text{Therefore, the mass of the reactants must equal the mass of the products, which is achieved by balancing the chemical equation.}\\end{aligned}'}],
   'final_answer': [{'content': '\\begin{aligned} &\\text{Law of Conservation of Mass} \\end{aligned}'}],
   'option1': [{'content': '\\begin{aligned} &\\text{Law of Definite Proportions} \\end{aligned}'}],
   'dr1': [{'content': '\\begin{aligned} &\\text{Confused the concept with the law that states a chemical compound always contains the same proportion of elements by mass.} \\end{aligned}'}],
   'option2': [{'content': '\\begin{aligned} &\\text{Law of Multiple Proportions} \\end{aligned}'}],
   'dr2': [{'content': '\\begin{aligned} &\\text{Misunderstood the law that involves the ratios of masses of elements in different compounds.} \\end{aligned}'}],
   'option3': [{'content': '\\begin{aligned} &\\text{Law of Conservation of Energy} \\end{aligned}'}],
   'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the distinction between mass and energy conservation, which are separate concepts.} \\end{aligned}'}]},
  {'topic_id': '10_chemistry_chemical reactions and equations_2',
   'topic_name': 'Balancing Chemical Equations',
   'question': [{'content': '\\begin{aligned} & \\text{Which of the following chemical equations is an unbalanced one?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
   'hint': [{'content': '\\begin{aligned} &\\text{To determine if a chemical equation is unbalanced, compare the number of atoms of each element on both sides of the equation. If they are not equal, the equation is unbalanced.}\\end{aligned}'}],
   'solution': [{'content': '\\begin{aligned} &\\text{A chemical equation is considered unbalanced if the number of atoms of each element is not the same on both sides of the equation.}\\quad \\text{For example, in the equation } \\text{H}_2 + \\text{O}_2 \\rightarrow \\text{H}_2\\text{O}, \\quad \\text{there are two hydrogen atoms on the left and two on the right, but there are two oxygen atoms on the left and only one on the right.}\\quad \\text{Thus, this equation is unbalanced.}\\end{aligned}'}],
   'final_answer': [{'content': '\\begin{aligned} &\\text{H}_2 + \\text{O}_2 \\rightarrow \\text{H}_2\\text{O} \\end{aligned}'}],
   'option1': [{'content': '\\begin{aligned} &\\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O} \\end{aligned}'}],
   'dr1': [{'content': '\\begin{aligned} &\\text{Confused the balanced equation with the unbalanced one, as this equation has equal numbers of each type of atom on both sides.} \\end{aligned}'}],
   'option2': [{'content': '\\begin{aligned} &\\text{C}_2\\text{H}_4 + 3\\text{O}_2 \\rightarrow 2\\text{CO}_2 + 2\\text{H}_2\\text{O} \\end{aligned}'}],
   'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that this equation is balanced, with equal numbers of each type of atom on both sides.} \\end{aligned}'}],
   'option3': [{'content': '\\begin{aligned} &\\text{N}_2 + 3\\text{H}_2 \\rightarrow 2\\text{NH}_3 \\end{aligned}'}],
   'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the fact that this equation is balanced, with equal numbers of nitrogen and hydrogen atoms on both sides.} \\end{aligned}'}]},
  {'topic_id': '10_chemistry_chemical reactions and equations_2',
   'topic_name': 'Balancing Chemical Equations',
   'question': [{'content': '\\begin{aligned} & \\text{Which of the following statements is/are correct?} \\\\ & \\text{(Multiple Choice)} \\\\ \\end{aligned}'}],
   'hint': [{'content': '\\begin{aligned} &\\text{Consider the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{Ensure that the number of atoms for each element is the same on both sides of the equation.} \\\\ &\\text{This will help you identify the correct statement(s) regarding balanced chemical equations.} \\\\ \\end{aligned}'}],
   'solution': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation has equal numbers of each type of atom on both sides of the equation.} \\\\ &\\text{This is in accordance with the law of conservation of mass, which states that mass is neither created nor destroyed in a chemical reaction.} \\\\ &\\text{For example, in the equation } \\text{2H}_2 + \\text{O}_2 \\rightarrow \\text{2H}_2\\text{O}, \\\\ &\\text{there are 4 hydrogen atoms and 2 oxygen atoms on both sides, indicating it is balanced.} \\\\ \\end{aligned}'}],
   'final_answer': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation has equal numbers of each type of atom on both sides of the equation.} \\end{aligned}'}],
   'option1': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation has more atoms on the reactant side than the product side.} \\end{aligned}'}],
   'dr1': [{'content': '\\begin{aligned} &\\text{Confused the concept of balancing with an imbalance, which violates the law of conservation of mass.} \\end{aligned}'}],
   'option2': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation has fewer atoms on the reactant side than the product side.} \\end{aligned}'}],
   'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that the number of atoms must be equal on both sides, not fewer on one side.} \\end{aligned}'}],
   'option3': [{'content': '\\begin{aligned} &\\text{A balanced chemical equation can have different types of atoms on each side.} \\end{aligned}'}],
   'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the requirement for the same types of atoms on both sides, misunderstanding the balancing process.} \\end{aligned}'}]}]}

#### Latex Formatting to store in DB

In [52]:
from config import MONGO_URL , DB_NAME

In [56]:
dbCollection = "Latex_CaseStudy"
client = AsyncIOMotorClient(MONGO_URL)

In [57]:
async def pushToDB(dbContent, subject):
    try:
        db = client[DB_NAME]
        que_collection = db[dbCollection]

        dbContent["status"] = "not_reviewed"
        dbContent["comment"] = ""
        dbContent["testFlag"] = "true"
        dbContent["subject"] = subject
        await que_collection.insert_one(dbContent)
        print("Data Uploaded to the database successfully.")
    except Exception as e:
        print("Exception Occurred: ", type(e).__name__, "–", e, "\n", traceback.format_exc())

In [58]:
for doc in final_output:
    await pushToDB(doc, subject)
client.close()

Data Uploaded to the database successfully.
Data Uploaded to the database successfully.