## Text Extraction, Cleaning, and Rephrasing from multiple books

In [1]:
import pandas as pd
import traceback
import json
from PyPDF2 import PdfReader
import os

from bson import ObjectId
from motor.motor_asyncio import AsyncIOMotorClient
from langchain_openai import ChatOpenAI
from langchain import PromptTemplate, LLMChain

from latext_Prompts import (
EXTRACTION_SYSTEM,
EXTRACTION_USER,
EXTRACTION_OUTPUT_FORMAT,
MATHEMATICS_EXTRACTION_OUTPUT_EXAMPLE,
BIOLOGY_EXTRACTION_OUTPUT_EXAMPLE,
PHYSICS_EXTRACTION_OUTPUT_EXAMPLE,
CHEMISTRY_EXTRACTION_OUTPUT_EXAMPLE,
EMPTY_EXTRACTION_OUTPUT_FORMAT,
CLEAN_REPHRASE_USER,
CLEAN_REPHRASE_SYSTEM,
REPHRASE_OUTPUT_FORMAT,
REPHRASE_OUTPUT_EXAMPLE,
BIOLOGY_SOLUTION_SYSTEM_PROMPT,
CHEMISTRY_SOLUTION_SYSTEM_PROMPT,
MATHEMATICS_SOLUTION_SYSTEM_PROMPT,
PHYSICS_SOLUTION_SYSTEM_PROMPT,
DISTRACTOR_SYSTEM_PROMPT
)

from config import (
    OPENAI_API_KEY,
    MONGO_URL,
    DB_NAME
)

In [2]:
# os.environ["LANGCHAIN_TRACING_V2"] = "true"
# os.environ["LANGCHAIN_API_KEY"] = "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"
# os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
# os.environ["LANGCHAIN_PROJECT"] = "Questions Extractor"

# Pipeline

In [2]:
import json
def parse_Response(response):
    if isinstance(response, str):
        # print(response)
        start_index = response.find("{")
        end_index = response.rfind("}")
        if start_index != -1 and end_index != -1:
            valid_json_content = response[start_index : end_index + 1]
            try:
                JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
                # append_list_to_file(JSON_response)
                return JSON_response
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON response: {e.__class__.__name__} - {e}\n\n Still trying to work on particular exceptions ...")
                if str(e).startswith("Extra data"):
                    json_parts = valid_json_content.split('}\n{')
                    if json_parts:
                        first_json = json_parts[0] + '}'
                        return parse_Response(first_json)  
                elif str(e).startswith("Invalid \escape"):
                    print("Before removing \\ issue: ", valid_json_content)
                    str1 = valid_json_content.replace("\\\\\\\\\\", "fvback")
                    str1 = str1.replace("\\\\\\\\", "frback")
                    str1 = str1.replace("\\\\\\", "trlback")
                    str1 = str1.replace("\\\\", "dblback")
                    str1 = str1.replace("\\", "\\\\")
                    str1 = str1.replace("fvback","\\\\\\\\\\")
                    str1 = str1.replace("frback", "\\\\\\\\")
                    str1 = str1.replace("trlback","\\\\\\")
                    strfinal = str1.replace("dblback","\\\\")
                    print("After removing \\ issue: ", strfinal)
                    JSON_response = json.loads(strfinal.replace("\n", ""))
                    return JSON_response
                else:
                    print("Actual Content: ", valid_json_content)
        else:
            print("No valid JSON content found in the response.")
        # time.sleep(50)
    elif isinstance(response, dict):
        return response
    else:
        print("No response message found", type(response))

<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_3636\3339088456.py:10: SyntaxWarning: invalid escape sequence '\('
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_3636\3339088456.py:10: SyntaxWarning: invalid escape sequence '\)'
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_3636\3339088456.py:20: SyntaxWarning: invalid escape sequence '\e'
  elif str(e).startswith("Invalid \escape"):

In [3]:
# All question collection

def collect_questions_from_chapter_with_Langchain(subject, chapter_text, chapter_name, grade):
    try:
        # initialize the ChapOpenAI object
        llm = ChatOpenAI(
            model_name="gpt-4o",
            api_key= OPENAI_API_KEY,
            temperature=0.2,
        )
        match subject:
            case "mathematics":
                examples=MATHEMATICS_EXTRACTION_OUTPUT_EXAMPLE
            case "biology":
                examples=BIOLOGY_EXTRACTION_OUTPUT_EXAMPLE
            case "physics":
                examples =PHYSICS_EXTRACTION_OUTPUT_EXAMPLE
            case "chemistry":
                examples=CHEMISTRY_EXTRACTION_OUTPUT_EXAMPLE

        #formatting prompts
        system = EXTRACTION_SYSTEM.format("",grade = grade, subject = subject,EMPTY_EXTRACTION_OUTPUT_FORMAT = EMPTY_EXTRACTION_OUTPUT_FORMAT, out_format = EXTRACTION_OUTPUT_FORMAT, out_example = examples)
        user = EXTRACTION_USER.format(chapter_name = chapter_name, chapter_text = chapter_text)

        #generating response from api call
        response = llm.invoke(
            [
                ("system", system),
                ("human", user)
            ],
        )
        return response
    except Exception as e:
        print("Error with in extraction: ", type(e).__name__, "–", e, "\n", traceback.format_exc())
        return None

In [4]:
def clean_rephrase_question(question_text, topic_list):
    try:
        # initialize the ChapOpenAI object
        llm = ChatOpenAI(
            model_name="gpt-4o",
            api_key= OPENAI_API_KEY,
            temperature=0.2,
            # verbose = True
        )

        #formatting prompts
        system = CLEAN_REPHRASE_SYSTEM.format("",out_example = REPHRASE_OUTPUT_EXAMPLE, out_format = REPHRASE_OUTPUT_FORMAT)
        user = CLEAN_REPHRASE_USER.format(question_text = question_text, topic_list = topic_list)

        #generating response from api call
        response = llm.invoke(
            [
                ("system", system),
                ("human", user)
            ]
        )
        return response
    except Exception as e:
        print("Error cleaning text: ", type(e).__name__, "–", e, "\n", traceback.format_exc())
        return question_text  # Return original text in case of an error

In [5]:
import os
import traceback
from pathlib import Path
import zipfile
import tempfile
import shutil

def read_data_from_latex(publication: str, chapter_name: str,grade:str) -> str:
    """
    Read LaTeX content from a specified publication and chapter zip file.
    
    Args:
        publication (str): Name of the publication (e.g., 'mtg')
        chapter_name (str): Name of the chapter (e.g., 'Life Processes')
    
    Returns:
        str: Content of the LaTeX file if successful, empty string if failed
    """
    try:
        # Construct the zip file path
        zip_path = os.path.join(r"textbooks", publication, f"{chapter_name}_{grade}.zip")
        
        # Verify zip file exists
        if not os.path.exists(zip_path):
            raise FileNotFoundError(f"Zip file not found: {zip_path}")
        
        # Create a temporary directory to extract files
        with tempfile.TemporaryDirectory() as temp_dir:
            # Extract the zip file
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)
            
            # Find directories starting with 2025
            content_dirs = [d for d in os.listdir(temp_dir) 
                          if os.path.isdir(os.path.join(temp_dir, d)) and 
                          d.startswith('2025')]
            
            if not content_dirs:
                raise FileNotFoundError(f"No content directories found in zip file")
                
            # Get the latest directory
            latest_dir = sorted(content_dirs)[-1]
            dir_path = os.path.join(temp_dir, latest_dir)
            
            # Find the .tex file in the directory
            tex_files = [f for f in os.listdir(dir_path) if f.endswith('.tex')]
                    
            if not tex_files:
                raise FileNotFoundError(f"No .tex file found in {dir_path}")
                
            # Full path to the tex file
            latex_path = os.path.join(dir_path, tex_files[0])
            
            # Read the content
            with open(latex_path, 'r', encoding='utf-8') as file:
                content = file.read()
                
            print(f"Successfully processed LaTeX file from zip: {latex_path}")
            return content

    except Exception as e:
        print(
            "Failed to process the LaTeX file. Exception Occurred:",
            type(e).__name__,
            "–",
            e,
            "\n",
            traceback.format_exc()
        )
        return ""

In [6]:
def extract_questions(subject: str, chapter_texts: list, chapter_name: str, grade: str) -> list:
    try:
        # Validate inputs
        if not isinstance(chapter_texts, list):
            raise ValueError("chapter_texts must be a list of strings")
            
        if not chapter_texts:
            print(f"Warning: Empty chapter_texts for chapter {chapter_name}")
            return []
            
        all_questions = []
        
        # Process lines in chunks of 500
        chunk_size = 250
        for chunk_index in range(0, len(chapter_texts), chunk_size):
            try:
                # Get current chunk of lines
                chunk = chapter_texts[chunk_index:chunk_index + chunk_size]
                
                # Skip empty chunks
                if not chunk:
                    continue
                    
                print(f"Processing chunk {chunk_index//chunk_size + 1}/{-(-len(chapter_texts)//chunk_size)}")
                
                # Use the original collection function
                questions = collect_questions_from_chapter_with_Langchain(
                    subject=subject,
                    chapter_text="\n".join(chunk),
                    chapter_name=chapter_name,
                    grade=grade
                )
                
                # Parse and store valid questions
                if questions and questions.content:
                    parsed = parse_Response(questions.content)
                    if parsed and "questions" in parsed:
                        questions_list = parsed["questions"]
                        if questions_list:
                            all_questions.extend(questions_list)
                            print(f"Extracted {len(questions_list)} questions from chunk {chunk_index//chunk_size + 1}")
                
            except Exception as e:
                print(f"Error processing chunk {chunk_index//chunk_size + 1}: {str(e)}")
                continue
        
        print(f"Total questions extracted: {len(all_questions)}")
        return all_questions

    except Exception as e:
        print(f"Error in extract_questions: {str(e)}")
        return []

In [7]:
def rephrase_questions(conf_data: dict, all_questions: list, topics: list) -> dict:
    print("Starting the cleanup and rephrasing process...")
    try:
        # Validate inputs
        if not conf_data or "chapter_name" not in conf_data:
            raise ValueError("Missing chapter_name in configuration")
            
        if not topics:
            print("\n\nNo topics found in the data.")
            raise ValueError("No topics found in the data")
            
        chapter = conf_data["chapter_name"]
        clean_rephrased_questions = {}
        chapterwise_formatted_questions = []
        
        if not all_questions:
            raise ValueError(f"No questions found for chapter {chapter}")
            
        print(f"\nWorking on chapter {chapter}")
        print(f"Total questions to process: {len(all_questions)}")
        
        # Process questions in batches of 5
        batch_size = 5
        for batch_start in range(0, len(all_questions), batch_size):
            try:
                # Get current batch of questions
                question_batch = all_questions[batch_start:batch_start + batch_size]
                print(f"\nProcessing batch {batch_start//batch_size + 1}/{-(-len(all_questions)//batch_size)}")
                
                # Clean and rephrase the batch
                cleaned_rephrased_questions = clean_rephrase_question(question_batch, topics)
                print("Raw response:", cleaned_rephrased_questions)
                
                # Parse the cleaned response
                if cleaned_rephrased_questions and cleaned_rephrased_questions.content:
                    formatted_questions = parse_Response(cleaned_rephrased_questions.content)
                    if formatted_questions and "questions" in formatted_questions:
                        chapterwise_formatted_questions.extend(formatted_questions["questions"])
                        print(f"Successfully processed {len(formatted_questions['questions'])} questions in batch")
                    else:
                        print(f"Warning: No valid questions found in batch {batch_start//batch_size + 1}")
                
                print("-" * 100)
                
            except Exception as batch_error:
                print(f"Error processing batch {batch_start//batch_size + 1}: {str(batch_error)}")
                continue
        
        # Store processed questions if any were successful
        if chapterwise_formatted_questions:
            clean_rephrased_questions[chapter] = chapterwise_formatted_questions
            print(f"\nSuccessfully processed {len(chapterwise_formatted_questions)} questions for chapter {chapter}")
        else:
            print(f"\nWarning: No questions were successfully processed for chapter {chapter}")
        
        return clean_rephrased_questions
        
    except Exception as e:
        print(f"Failed to clean and rephrase questions. Exception Occurred: {type(e).__name__} – {str(e)}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return {}

In [8]:
from typing import Tuple, Dict, Optional
import traceback
import logging

def extract_rephrase_questions(conf_data: dict, topics: list) -> Tuple[Optional[Dict], Optional[Dict]]:
    try:
        # Validate configuration data
        required_fields = ["subject", "grade", "chapter_name"]
        missing_fields = [field for field in required_fields if field not in conf_data]
        if missing_fields:
            raise ValueError(f"Missing required configuration fields: {', '.join(missing_fields)}")
            
        if not topics:
            raise ValueError("No topics provided for question rephrasing")
            
        print("Starting question extraction and rephrasing pipeline...")
        
        # Step 1: Scrape text from PDF/LaTeX
        print("\nStep 1: Scraping textbook content...")
        pdf_text = read_data_from_latex(publication=conf_data['publication'] , chapter_name=conf_data['chapter_name'] , grade=conf_data['grade'])
        if not pdf_text:
            raise ValueError("No text content extracted from textbook")
        print(f"Successfully extracted {len(pdf_text)} text segments")
            
        # Step 2: Extract questions from text
        print("\nStep 2: Extracting questions from text...")
        extracted_questions = extract_questions(
            subject=conf_data["subject"],
            grade=conf_data["grade"],
            chapter_name=conf_data["chapter_name"],
            chapter_texts=pdf_text.split("\n")
        )
        if not extracted_questions:
            raise ValueError("No questions were extracted from the text")
        print(f"Successfully extracted questions")
            
        # Step 3: Clean and rephrase questions
        print("\nStep 3: Cleaning and rephrasing questions...")
        final_rephrased_questions = rephrase_questions(
            conf_data=conf_data,
            all_questions=extracted_questions,
            topics=topics
        )
        if not final_rephrased_questions:
            raise ValueError("No questions were successfully rephrased")
        print("Successfully rephrased questions")
            
        # Return results
        print("\nPipeline completed successfully!")
        return extracted_questions, final_rephrased_questions
        
    except ValueError as val_err:
        print(f"Validation error: {str(val_err)}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return None, None
        
    except Exception as e:
        print(f"Unexpected error in question processing pipeline: {str(e)}")
        print(f"Exception type: {type(e).__name__}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return None, None
        
    finally:
        print("\nQuestion processing pipeline finished")

In [9]:
# get chapter and book data from defaultConf
with open("defaultConf.json", "r") as f:
    conf_data = json.load(f)

chapter = conf_data["chapter_name"]
subject = conf_data["subject"]


print("Chapter to work on: ", chapter)
print(subject)
print(conf_data['publication'])
print(conf_data['grade'])

Chapter to work on:  Physical Quantities and Measurement
physics
goyal
6

In [10]:
import pandas as pd

def process_filename(filename):
    """
    Process filename by stripping whitespace and converting to lowercase
    """
    return filename.strip().lower()
grade = conf_data['grade']
# Match subject to determine sheet name
match subject:
    case "mathematics":
        sheet_name = f"G{grade} Maths"
    case "biology":
        sheet_name = f"G{grade} Bio"
    case "physics":
        sheet_name = f"G{grade} Phy"
    case "chemistry":
        sheet_name = f"G{grade} Chem"
print(sheet_name)
# Read Excel file and process the filename
file_name = process_filename("LEAP ICSE DEFAULTs.xlsx")
misconceptions_df = pd.read_excel(file_name, sheet_name=sheet_name)

# Clean column names
misconceptions_df.columns = misconceptions_df.columns.str.strip()
misconceptions_df.fillna("", inplace=True)

# Process chapter name from conf_data for comparison
chapter_name = conf_data["chapter_name"].strip().lower()

# Get unique topics for the specified chapter
tempTopics = list(misconceptions_df[
    misconceptions_df["Chapter Name"].str.strip().str.lower() == chapter_name
]["Topic"].unique())

# Create topics dictionary with processed IDs
topics = {}
for i in range(len(tempTopics)):
    topic_id = f"{conf_data['grade']}_{conf_data['subject']}_{chapter_name}_{i+1}"
    topics[topic_id] = tempTopics[i].strip()

print("Topics with ID: ", topics, "\n\n", topics.values())

# Process misconceptions and LUs
total_misconceptions = {}
total_LUs = {}

for i, row in misconceptions_df.iterrows():
    topic = str(row["Topic"]).strip()
    
    if topic in topics.values():
        # Process LUs
        if topic in total_LUs:
            total_LUs[topic].append(row["Sub-topic/LU"])
        else:
            total_LUs[topic] = [row["Sub-topic/LU"]]

        # # Process misconceptions
        # temp_misconceptions = [
        #     row[f"Misconceptions {i}"] 
        #     for i in range(1, 11) 
        #     if row[f"Misconceptions {i}"] != ""
        # ]

        # if topic in total_misconceptions:
        #     total_misconceptions[topic].extend(temp_misconceptions)
        # else:
        #     total_misconceptions[topic] = temp_misconceptions

print(total_LUs, sep="\n\n-------------------------------------------------------------------\n\n")

G6 Phy
Topics with ID:  {'6_physics_physical quantities and measurement_1': 'Measurement of Length', '6_physics_physical quantities and measurement_2': 'Measurement of Mass', '6_physics_physical quantities and measurement_3': 'Measurement of Time', '6_physics_physical quantities and measurement_4': 'Temperature and its Measurement', '6_physics_physical quantities and measurement_5': 'Types of Thermometers', '6_physics_physical quantities and measurement_6': 'Measurement of Area'}

 dict_values(['Measurement of Length', 'Measurement of Mass', 'Measurement of Time', 'Temperature and its Measurement', 'Types of Thermometers', 'Measurement of Area'])
{'Measurement of Length': ['Concept of length as distance between two points.', 'Measurement of length using a ruler and measuring tape', 'Units of length'], 'Measurement of Mass': ['Properties of material- Mass', 'Measurement of mass using beam balance and electronic balance', 'Units of mass'], 'Measurement of Time': ['Measurement of time using clock, watch and stop watch', 'Units of Time'], 'Temperature and its Measurement': ['Sense of touch as temperature sensor', 'Temperature, Its Measurement Scales, and Conversion Methods'], 'Types of Thermometers': ['Temperature Measurement of Human Body using clinical thermometer', 'Temperature Measurement of Human Body using digital clinical thermometer', 'Correct Way of using Laboratory thermometer'], 'Measurement of Area': ['Concept of area and its units', 'Measurement of area of objects of regular shapes']}

C:\Users\aniket singh\AppData\Local\Temp\ipykernel_3636\64891827.py:26: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  misconceptions_df.fillna("", inplace=True)

In [16]:
total_LUs

{'Measurement of Length': ['Concept of length as distance between two points.',
  'Measurement of length using a ruler and measuring tape',
  'Units of length'],
 'Measurement of Mass': ['Properties of material- Mass',
  'Measurement of mass using beam balance and electronic balance',
  'Units of mass'],
 'Measurement of Time': ['Measurement of time using clock, watch and stop watch',
  'Units of Time'],
 'Temperature and its Measurement': ['Sense of touch as temperature sensor',
  'Temperature, Its Measurement Scales, and Conversion Methods'],
 'Types of Thermometers': ['Temperature Measurement of Human Body using clinical thermometer',
  'Temperature Measurement of Human Body using digital clinical thermometer',
  'Correct Way of using Laboratory thermometer'],
 'Measurement of Area': ['Concept of area and its units',
  'Measurement of area of objects of regular shapes']}

In [12]:
extracted_raw_questions_json ,clean_rephrased_questions_json = extract_rephrase_questions(conf_data, topics)

Starting question extraction and rephrasing pipeline...

Step 1: Scraping textbook content...
Successfully processed LaTeX file from zip: C:\Users\ANIKET~1\AppData\Local\Temp\tmpo0yyhpwi\2025_01_28_f063d28aa35ccb17e8cag\2025_01_28_f063d28aa35ccb17e8cag.tex
Successfully extracted 76636 text segments

Step 2: Extracting questions from text...
Processing chunk 1/6
Processing chunk 2/6
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 571 (char 570)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "questions": [
        {
            "question": "\begin{aligned} \text{Imagine you are asked to find the diameter of thin copper wire by using a centimetre scale. If you directly use the centimetre scale you will notice that the diameter of wire is less than 1 mm. In order to find diameter accurately, wind the wire over a smooth pencil in the form of a tight coil, such that there are 30 turns in the coil as shown in Fig. 2.9. Place the pencil along with the coil along the edge of centimetre scale. If the length of coil is 1.5 cm, then the diameter of wire is} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{What is length? Name four early units of measurement of length.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Why do we need standard units for measurement?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{What are standard international units of measurement? State the unit of length in this system.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Define the term metre. Name one multiple and two submultiples of metre.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Fig 2.13 shows a pencil, whose length is measured by positioning eye at A, B and C. In which position of eye is the accurate measurement of length recorded? What is the magnitude of accurate length? What is the magnitude of length, when the eye is positioned at A or C?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Name two characteristics of a standard unit for a physical quantity.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{By using a thin cotton thread, how will you find length of a curved line?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Fig. 2.14 shows four identical wooden rods, placed side by side, such that their total thickness is 5 cm. Find the thickness of a single rod, correct to two decimal places.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{24 coins are placed one upon another and their total thickness is recorded by a half metre scale. The thickness is found to be 4.8 cm. Find the thickness of each coin in millimetres.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Name the unit for measuring the distance of a star from the earth. How many kilometre are present in the above unit?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Name two units for measuring the diameter of a bacterial cell or nucleus of atom. Express the value of above units in mm.} \end{aligned}"
        }
    ]
}
After removing \ issue:  {
    "questions": [
        {
            "question": "\\begin{aligned} \\text{Imagine you are asked to find the diameter of thin copper wire by using a centimetre scale. If you directly use the centimetre scale you will notice that the diameter of wire is less than 1 mm. In order to find diameter accurately, wind the wire over a smooth pencil in the form of a tight coil, such that there are 30 turns in the coil as shown in Fig. 2.9. Place the pencil along with the coil along the edge of centimetre scale. If the length of coil is 1.5 cm, then the diameter of wire is} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{What is length? Name four early units of measurement of length.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Why do we need standard units for measurement?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{What are standard international units of measurement? State the unit of length in this system.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Define the term metre. Name one multiple and two submultiples of metre.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Fig 2.13 shows a pencil, whose length is measured by positioning eye at A, B and C. In which position of eye is the accurate measurement of length recorded? What is the magnitude of accurate length? What is the magnitude of length, when the eye is positioned at A or C?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Name two characteristics of a standard unit for a physical quantity.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{By using a thin cotton thread, how will you find length of a curved line?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Fig. 2.14 shows four identical wooden rods, placed side by side, such that their total thickness is 5 cm. Find the thickness of a single rod, correct to two decimal places.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{24 coins are placed one upon another and their total thickness is recorded by a half metre scale. The thickness is found to be 4.8 cm. Find the thickness of each coin in millimetres.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Name the unit for measuring the distance of a star from the earth. How many kilometre are present in the above unit?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Name two units for measuring the diameter of a bacterial cell or nucleus of atom. Express the value of above units in mm.} \\end{aligned}"
        }
    ]
}
Extracted 12 questions from chunk 2
Processing chunk 3/6
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 120 (char 119)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "questions": [
        {
            "question": "\begin{aligned} \text{Convert following 24 h time to 12 h time :} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Convert following 12 h time to 24 h time :} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{What do you understand by the term 'mass'? State its SI unit.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Name two multiples and two submultiples of SI unit of mass.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{What kind of balance is used for finding the mass of (a) gold ornament (b) vegetables?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{What do you understand by the term 'time'? State its SI unit.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(a) How many centuries make one millennium?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(b) How many decades make one millennium?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(c) How many years make one millennium?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(a) What do you understand by the term 'mean solar day'?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(b) How many hours are there in one mean solar day?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(c) How many minutes are there in one mean solar day?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(d) How many seconds are there in one mean solar day?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Define the following terms: (a) Simple pendulum} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(b) Oscillation} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(c) Length of pendulum} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(d) Time period} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(a) The time period of a second's pendulum is 2 s . What is the length of pendulum?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(b) When a boy finishes a race, the pendulum makes 30 oscillations, in case of second's pendulum. What is the time taken by the boy in seconds to finish the race?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(a) What is 24 hour clock?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(b) Name two organisations which use 24 hour clock.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(c) The time on 24 hour clock is: Express the time on 12 hour clock. (i) 08: 37} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(ii) 23: 48} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(a) What is 12 hour clock?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(b) What are the indications of a.m. and p.m. on 12 hour clock?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{(c) The time on 12 hour clock is : (i) 3:30 p.m. (ii) 9:40 a.m. Convert the time on 24 h clock.} \end{aligned}"
        }
    ]
}
After removing \ issue:  {
    "questions": [
        {
            "question": "\\begin{aligned} \\text{Convert following 24 h time to 12 h time :} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Convert following 12 h time to 24 h time :} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{What do you understand by the term 'mass'? State its SI unit.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Name two multiples and two submultiples of SI unit of mass.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{What kind of balance is used for finding the mass of (a) gold ornament (b) vegetables?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{What do you understand by the term 'time'? State its SI unit.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(a) How many centuries make one millennium?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(b) How many decades make one millennium?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(c) How many years make one millennium?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(a) What do you understand by the term 'mean solar day'?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(b) How many hours are there in one mean solar day?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(c) How many minutes are there in one mean solar day?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(d) How many seconds are there in one mean solar day?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Define the following terms: (a) Simple pendulum} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(b) Oscillation} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(c) Length of pendulum} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(d) Time period} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(a) The time period of a second's pendulum is 2 s . What is the length of pendulum?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(b) When a boy finishes a race, the pendulum makes 30 oscillations, in case of second's pendulum. What is the time taken by the boy in seconds to finish the race?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(a) What is 24 hour clock?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(b) Name two organisations which use 24 hour clock.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(c) The time on 24 hour clock is: Express the time on 12 hour clock. (i) 08: 37} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(ii) 23: 48} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(a) What is 12 hour clock?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(b) What are the indications of a.m. and p.m. on 12 hour clock?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{(c) The time on 12 hour clock is : (i) 3:30 p.m. (ii) 9:40 a.m. Convert the time on 24 h clock.} \\end{aligned}"
        }
    ]
}
Extracted 26 questions from chunk 3
Processing chunk 4/6
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 129 (char 128)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "questions": [
        {
            "question": "\begin{aligned} & \text{Convert following celsius temperatures to kelvin.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} & \text{Convert following kelvin temperatures to celsius.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} & \text{You have to decide quickly which piece of cloth is more rough than the other. For this, you do not need any special tools. You will just move your fingers on each piece and feel. Here, we use sensation of touch.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} & \text{Suppose you have to drink sweetened milk. You will add two or more spoons of sugar to it according to your taste. You just estimate the amount of sugar to be added by your sensation of taste. You need not actually weigh out certain fixed amount of sugar.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} & \text{When do we make estimations?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} & \text{How do we make estimations?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} & \text{Find the average pulse rate of the class and the range of pulse rate of the students.} \end{aligned}"
        }
    ]
}
After removing \ issue:  {
    "questions": [
        {
            "question": "\\begin{aligned} & \\text{Convert following celsius temperatures to kelvin.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} & \\text{Convert following kelvin temperatures to celsius.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} & \\text{You have to decide quickly which piece of cloth is more rough than the other. For this, you do not need any special tools. You will just move your fingers on each piece and feel. Here, we use sensation of touch.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} & \\text{Suppose you have to drink sweetened milk. You will add two or more spoons of sugar to it according to your taste. You just estimate the amount of sugar to be added by your sensation of taste. You need not actually weigh out certain fixed amount of sugar.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} & \\text{When do we make estimations?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} & \\text{How do we make estimations?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} & \\text{Find the average pulse rate of the class and the range of pulse rate of the students.} \\end{aligned}"
        }
    ]
}
Extracted 7 questions from chunk 4
Processing chunk 5/6
Extracted 51 questions from chunk 5
Processing chunk 6/6
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 143 (char 142)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "questions": [
        {
            "question": "\begin{aligned} &\text{The tool used to take body measurements for stitching clothes is} \quad \text{[metre scale/measuring tape]} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{The SI unit of mass is} \quad \text{-. [kilogram/gram]} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{Twelve inches equal one} \quad \text{.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{The symbol for 100 metres is} \quad \text{[100M/100m]} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{Sundials are} \quad \text{clocks which work only when there is the Sun in the sky. [ancient/modern]} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{Appropriate unit to measure the length of a football ground is :} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{Sl unit of time is} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{The mercury in the capillary tube of clinical thermometer does not flow back because:} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{Which of these are basic quantities of measurement?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{Which of these is the measure of distance between two points?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{The distances of stars from the earth are measured in kilometres.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{A pendulum of length 100 cm which is swinging freely has a time period of one second.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{A clinical thermometer should be sterilised in boiling water.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{Assertion (A) : Time is defined as an interval between two events.} \\ &\text{Reason (R): The interval between two successive noons is called a solar day.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{Assertion (A): Clinical thermometer is marked from $35^{\circ} \mathrm{C}$ to $42^{\circ} \mathrm{C}$.} \\ &\text{Reason (R) : Temperature of the human body does not fall below $35^{\circ} \mathrm{C}$, nor does it rise above $42^{\circ} \mathrm{C}$.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} &\text{Assertion (A): The symbols for the units of quantities are written in capital letter.} \\ &\text{Reason (R) : Symbol for kilogram is kg .} \end{aligned}"
        },
        {

In [13]:
print("Chapter name: ",chapter, ",  Raw questions: ",  len(extracted_raw_questions_json))
print("Chapter name: ",chapter, ",  Cleaned questions: ",  len(clean_rephrased_questions_json[chapter]))

Chapter name:  Physical Quantities and Measurement ,  Raw questions:  124
Chapter name:  Physical Quantities and Measurement ,  Cleaned questions:  121

In [14]:
extracted_raw_questions_json

[{'question': '\\begin{aligned} \\text{Imagine you are asked to find the diameter of thin copper wire by using a centimetre scale. If you directly use the centimetre scale you will notice that the diameter of wire is less than 1 mm. In order to find diameter accurately, wind the wire over a smooth pencil in the form of a tight coil, such that there are 30 turns in the coil as shown in Fig. 2.9. Place the pencil along with the coil along the edge of centimetre scale. If the length of coil is 1.5 cm, then the diameter of wire is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{What is length? Name four early units of measurement of length.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Why do we need standard units for measurement?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{What are standard international units of measurement? State the unit of length in this system.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Define the term metre. Name one multiple and two submultiples of metre.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Fig 2.13 shows a pencil, whose length is measured by positioning eye at A, B and C. In which position of eye is the accurate measurement of length recorded? What is the magnitude of accurate length? What is the magnitude of length, when the eye is positioned at A or C?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Name two characteristics of a standard unit for a physical quantity.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{By using a thin cotton thread, how will you find length of a curved line?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Fig. 2.14 shows four identical wooden rods, placed side by side, such that their total thickness is 5 cm. Find the thickness of a single rod, correct to two decimal places.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{24 coins are placed one upon another and their total thickness is recorded by a half metre scale. The thickness is found to be 4.8 cm. Find the thickness of each coin in millimetres.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Name the unit for measuring the distance of a star from the earth. How many kilometre are present in the above unit?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Name two units for measuring the diameter of a bacterial cell or nucleus of atom. Express the value of above units in mm.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Convert following 24 h time to 12 h time :} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Convert following 12 h time to 24 h time :} \\end{aligned}'},
 {'question': "\\begin{aligned} \\text{What do you understand by the term 'mass'? State its SI unit.} \\end{aligned}"},
 {'question': '\\begin{aligned} \\text{Name two multiples and two submultiples of SI unit of mass.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{What kind of balance is used for finding the mass of (a) gold ornament (b) vegetables?} \\end{aligned}'},
 {'question': "\\begin{aligned} \\text{What do you understand by the term 'time'? State its SI unit.} \\end{aligned}"},
 {'question': '\\begin{aligned} \\text{(a) How many centuries make one millennium?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(b) How many decades make one millennium?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(c) How many years make one millennium?} \\end{aligned}'},
 {'question': "\\begin{aligned} \\text{(a) What do you understand by the term 'mean solar day'?} \\end{aligned}"},
 {'question': '\\begin{aligned} \\text{(b) How many hours are there in one mean solar day?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(c) How many minutes are there in one mean solar day?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(d) How many seconds are there in one mean solar day?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Define the following terms: (a) Simple pendulum} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(b) Oscillation} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(c) Length of pendulum} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(d) Time period} \\end{aligned}'},
 {'question': "\\begin{aligned} \\text{(a) The time period of a second's pendulum is 2 s . What is the length of pendulum?} \\end{aligned}"},
 {'question': "\\begin{aligned} \\text{(b) When a boy finishes a race, the pendulum makes 30 oscillations, in case of second's pendulum. What is the time taken by the boy in seconds to finish the race?} \\end{aligned}"},
 {'question': '\\begin{aligned} \\text{(a) What is 24 hour clock?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(b) Name two organisations which use 24 hour clock.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(c) The time on 24 hour clock is: Express the time on 12 hour clock. (i) 08: 37} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(ii) 23: 48} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(a) What is 12 hour clock?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(b) What are the indications of a.m. and p.m. on 12 hour clock?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{(c) The time on 12 hour clock is : (i) 3:30 p.m. (ii) 9:40 a.m. Convert the time on 24 h clock.} \\end{aligned}'},
 {'question': '\\begin{aligned} & \\text{Convert following celsius temperatures to kelvin.} \\end{aligned}'},
 {'question': '\\begin{aligned} & \\text{Convert following kelvin temperatures to celsius.} \\end{aligned}'},
 {'question': '\\begin{aligned} & \\text{You have to decide quickly which piece of cloth is more rough than the other. For this, you do not need any special tools. You will just move your fingers on each piece and feel. Here, we use sensation of touch.} \\end{aligned}'},
 {'question': '\\begin{aligned} & \\text{Suppose you have to drink sweetened milk. You will add two or more spoons of sugar to it according to your taste. You just estimate the amount of sugar to be added by your sensation of taste. You need not actually weigh out certain fixed amount of sugar.} \\end{aligned}'},
 {'question': '\\begin{aligned} & \\text{When do we make estimations?} \\end{aligned}'},
 {'question': '\\begin{aligned} & \\text{How do we make estimations?} \\end{aligned}'},
 {'question': '\\begin{aligned} & \\text{Find the average pulse rate of the class and the range of pulse rate of the students.} \\end{aligned}'},
 {'question': 'What is the area of cardboard in $|\\mathrm{a}| \\mathrm{cm}^{2}\\left(\\mathrm{~b} \\mid \\mathrm{mm}^{2}\\right.$ and (c) $\\mathrm{m}^{2}$ ?'},
 {'question': 'The length of a hall is 15 m and breadth 4 m . Find the area of the hall in (a) $\\mathrm{m}^{2}(\\mathrm{~b})$ hectares.'},
 {'question': 'A flat circular plate has radius 14 cm . What is the area of plate?'},
 {'question': 'The diameter of a circular field is 7 m . Find the area of the field.'},
 {'question': 'A triangular cardboard has a base of 8 cm and its height upto vertex is 4 cm . What is the area of cardboard?'},
 {'question': 'The measure of hotness or coldness of a body is called its \\qquad .'},
 {'question': 'A device used to measure the temperature of an object is called \\qquad .'},
 {'question': 'The SI unit of temperature is \\qquad .'},
 {'question': 'The amount of surface occupied by an object or place is called its \\qquad .'},
 {'question': 'The liquid used in a laboratory thermometer is \\qquad .'},
 {'question': 'The thermometer consists of a very fine glass tube having a very small bore commonly called capillary tube.'},
 {'question': 'The capillary tube is protected by a thick glass tube called stem.'},
 {'question': 'The last limit of temperature $237^{\\circ} \\mathrm{C}$ was named as absolute zero.'},
 {'question': 'A clinical thermometer is marked between $95^{\\circ} \\mathrm{C}$ to $110^{\\circ} \\mathrm{C}$.'},
 {'question': 'A clinical thermometer should be sterilised in boiling water.'},
 {'question': 'The measure of hotness or coldness is called heat energy.'},
 {'question': 'Water is used as liquid in laboratory thermometer.'},
 {'question': '$20^{\\circ} \\mathrm{C}$ on celsius scale is equal to 20 K on kelvin scale.'},
 {'question': 'The temperature below $37^{\\circ} \\mathrm{C}$ on clinical thermometer means fever.'},
 {'question': 'Estimations are generally reliable.'},
 {'question': 'The correct temperature of celsius scale is given by'},
 {'question': 'The clinical thermometer after washing is jerked so as to :'},
 {'question': 'A rise in temperature of $50^{\\circ} \\mathrm{C}$ on celsius scale is equal to rise in temperature of \\qquad on kelvin scale.'},
 {'question': 'The normal temperature of a healthy human being is:'},
 {'question': '(al What do you understand by the term temperature?'},
 {'question': '(b) Name the device used in laboratory for measuring temperature of a body.'},
 {'question': '(al What do you understand by area?'},
 {'question': '(b) How can you measure area of regular shape by using graph paper?'},
 {'question': 'What are the standard points on a laboratory thermometer? State their value in \\{a) celsius scale \\{b$ ) kelvin scale.'},
 {'question': '(a) Into how many degrees is the scale of laboratory thermometer divided on celsius scale?'},
 {'question': '(b) The mercury in the common laboratory thermometer stands at $2 / 5$ of the length between the standard points, as measured from the lower standard point. What is the temperature in degree celsius? [40 ${ }^{\\circ} \\mathrm{C}$ ]'},
 {'question': 'A celsius thermometer reads $27^{\\circ} \\mathrm{C}$. What is the corresponding temperature on kelvin scale?'},
 {'question': 'Kelvin temperature is 373 K . What is the corresponding temperature on celsius scale?'},
 {'question': '(a) What is a clinical thermometer?'},
 {'question': '(b) Why is this thermometer marked between $35^{\\circ} \\mathrm{C}$ and $42^{\\circ} \\mathrm{C}$ ?'},
 {'question': '(a) Draw a neat and labelled diagram of clinical thermometer.'},
 {'question': '(b) What conclusions can be drawn, if the temperature of a patient is (i) $40^{\\circ} \\mathrm{C}$ (ii) $35.5^{\\circ} \\mathrm{C}$ ?'},
 {'question': '(c) Why is a clinical thermometer not sterilised in boiling water?'},
 {'question': '(a) What do you understand by the term estimation?'},
 {'question': '(b) Is estimation a reliable way of measurement? Support your answer by two examples.'},
 {'question': '(c) When do we do estimations in general and why, even when tools of measurement are available? Support your answer with examples.'},
 {'question': 'State the magnitude of following quantities in SI units.'},
 {'question': '(a) Megawatt'},
 {'question': '(b) Kilometre'},
 {'question': '(c) Metric tonne'},
 {'question': '(d) Millisecond'},
 {'question': 'The length of a square room is 13 m . What is the floor area of the room?'},
 {'question': 'The length of a school compound is 450 m and breadth is 145 m . Find the area of compound in (a) $\\mathrm{m}^{2}(\\mathrm{~b})$ hectares.'},
 {'question': 'A district has a length of 20 km and breadth 17 km . Find the area of district in (a) $\\mathrm{km}^{2}$, (b) hectares.'},
 {'question': 'A triangular cardboard is of base 20 cm and height from its base is 15 cm . What is the area of cardboard?'},
 {'question': 'A coin of radius 28 mm . What is the area in (a) $\\mathrm{mm}^{2}(\\mathrm{~b}) \\mathrm{cm}^{2}$ ?'},
 {'question': '\\begin{aligned} &\\text{The tool used to take body measurements for stitching clothes is} \\quad \\text{[metre scale/measuring tape]} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{The SI unit of mass is} \\quad \\text{-. [kilogram/gram]} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Twelve inches equal one} \\quad \\text{.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{The symbol for 100 metres is} \\quad \\text{[100M/100m]} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Sundials are} \\quad \\text{clocks which work only when there is the Sun in the sky. [ancient/modern]} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Appropriate unit to measure the length of a football ground is :} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Sl unit of time is} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{The mercury in the capillary tube of clinical thermometer does not flow back because:} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Which of these are basic quantities of measurement?} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Which of these is the measure of distance between two points?} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{The distances of stars from the earth are measured in kilometres.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{A pendulum of length 100 cm which is swinging freely has a time period of one second.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{A clinical thermometer should be sterilised in boiling water.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Assertion (A) : Time is defined as an interval between two events.} \\ &\\text{Reason (R): The interval between two successive noons is called a solar day.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Assertion (A): Clinical thermometer is marked from $35^{\\circ} \\mathrm{C}$ to $42^{\\circ} \\mathrm{C}$.} \\ &\\text{Reason (R) : Temperature of the human body does not fall below $35^{\\circ} \\mathrm{C}$, nor does it rise above $42^{\\circ} \\mathrm{C}$.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Assertion (A): The symbols for the units of quantities are written in capital letter.} \\ &\\text{Reason (R) : Symbol for kilogram is kg .} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Assertion (A) : The SI unit of area is square metre.} \\ &\\text{Reason (R) : The area of a square surface, whose each side is equal to one metre is called one square metre.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Which of these is the basis of all scientific study and experimentation?} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{A physical quantity is a quantity that can be:} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{The measurement of every physical quantity requires a/an:} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{(a) Name two organisations which use 24 hour clock.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{(b) The time on 24 hour clock is 10:48. Express the time on 12 hour clock.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{Why do we need standard units for measurement? Explain clearly.} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{(a) How many decades make (i) one century (ii) one millennium?} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{(b) How many seconds are there in one hour?} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{(a) Why is a clinical thermometer marked between $35^{\\circ} \\mathrm{C}$ and $42^{\\circ} \\mathrm{C}$ ?} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{(b) What conclusions can be drawn, if the temperature of a patient is $39.4^{\\circ} \\mathrm{C}$ and why?} \\end{aligned}'},
 {'question': '\\begin{aligned} &\\text{The normal body temperature of a healthy human being is $37^{\\circ} \\mathrm{C}$. Surprisingly, when you measure the body temperature of your ten class-mates, then you find that their body temperature vary under a certain limit. It may be either less than $37^{\\circ} \\mathrm{C}$ or more than $37^{\\circ} \\mathrm{C}$. Try to find the basic cause behind it and also find the average body temperature of body temperatures of ten class-mates. It may be nearly $37^{\\circ} \\mathrm{C}$.} \\end{aligned}'}]

In [15]:
# extracted_raw_questions_json
for json in clean_rephrased_questions_json[conf_data['chapter_name']]:
    print(json['question'])

\begin{aligned} &\text{If a thin copper wire is wound around a pencil to form a coil with 25 turns, and the length of the coil is measured to be 2 cm, what is the diameter of the wire?} \end{aligned}
\begin{aligned} &\text{Which of the following were early units of measurement for length?} \end{aligned}
\begin{aligned} &\text{Why is it important to have standard units for measurement?} \end{aligned}
\begin{aligned} &\text{What are the standard international units of measurement, and what is the unit of length in this system?} \end{aligned}
\begin{aligned} &\text{How is the term metre defined, and what are one multiple and two submultiples of metre?} \end{aligned}
\begin{aligned} &\text{Which position of the eye records the accurate length of a pencil, and what is the magnitude of this length?} \end{aligned}
\begin{aligned} &\text{What are two characteristics of a standard unit for measuring a physical quantity?} \end{aligned}
\begin{aligned} &\text{How can you determine the length of a curved line using a thin cotton thread?} \end{aligned}
\begin{aligned} &\text{If four identical wooden rods placed side by side have a total thickness of 6 cm, what is the thickness of one rod, correct to two decimal places?} \end{aligned}
\begin{aligned} &\text{When 30 coins are stacked and their total thickness is measured as 5.4 cm, what is the thickness of each coin in millimeters?} \end{aligned}
\begin{aligned} &\text{Which unit is used to measure the distance of a star from the Earth, and how many kilometers does it represent?} \end{aligned}
\begin{aligned} &\text{Identify two units used to measure the diameter of a bacterial cell or atomic nucleus, and express their values in millimeters.} \end{aligned}
\begin{aligned} &\text{How would you convert the following 24-hour time format to a 12-hour time format?} \end{aligned}
\begin{aligned} &\text{How would you convert the following 12-hour time format to a 24-hour time format?} \end{aligned}
\begin{aligned} &\text{What is meant by the term 'mass' and what is its SI unit?} \end{aligned}
\begin{aligned} &\text{Which of the following are two multiples and two submultiples of the SI unit of mass?} \end{aligned}
\begin{aligned} &\text{What type of balance is typically used for measuring the mass of (a) a gold ornament and (b) vegetables?} \end{aligned}
\begin{aligned} &\text{What is meant by the term 'time' and what is its SI unit?} \end{aligned}
\begin{aligned} &\text{How many centuries are there in one millennium?} \end{aligned}
\begin{aligned} &\text{How many decades constitute one millennium?} \end{aligned}
\begin{aligned} &\text{How many years are equivalent to one millennium?} \end{aligned}
\begin{aligned} &\text{What is meant by the term 'mean solar day'?} \end{aligned}
\begin{aligned} &\text{How many hours constitute a mean solar day?} \end{aligned}
\begin{aligned} &\text{How many minutes are there in a mean solar day?} \end{aligned}
\begin{aligned} &\text{How many seconds make up a mean solar day?} \end{aligned}
\begin{aligned} &\text{Which of the following best describes a simple pendulum?} \end{aligned}
\begin{aligned} &\text{What is the definition of oscillation in the context of pendulums?} \end{aligned}
\begin{aligned} &\text{How is the length of a pendulum defined?} \end{aligned}
\begin{aligned} &\text{What is the time period of a pendulum and how is it measured?} \end{aligned}
\begin{aligned} &\text{If the time period of a pendulum is 3 s, what is the length of the pendulum?} \end{aligned}
\begin{aligned} &\text{If a boy completes a race and the pendulum makes 40 oscillations,} \\ &\text{what is the time taken by the boy in seconds to finish the race?} \end{aligned}
\begin{aligned} &\text{Which of the following best describes a 24-hour clock?} \end{aligned}
\begin{aligned} &\text{Identify two organizations that commonly use a 24-hour clock system.} \end{aligned}
\begin{aligned} &\text{Convert the following 24-hour clock time to a 12-hour clock format:} \\ &\text{(i) 09:45} \end{aligned}
\begin{aligned} &\text{Convert the following 24-hour clock time to a 12-hour clock format:} \\ &\text{(ii) 22:30} \end{aligned}
\begin{aligned} &\text{Which of the following best describes a 12-hour clock system?} \end{aligned}
\begin{aligned} &\text{What do the indications a.m. and p.m. represent on a 12-hour clock?} \end{aligned}
\begin{aligned} &\text{Convert the following times from a 12-hour clock to a 24-hour clock:} \\ &\text{(i) 4:45 p.m.} \\ &\text{(ii) 8:20 a.m.} \end{aligned}
\begin{aligned} &\text{Convert the following temperatures from Celsius to Kelvin:} \\ &\text{(i) 25°C} \\ &\text{(ii) -10°C} \end{aligned}
\begin{aligned} &\text{Convert the following temperatures from Kelvin to Celsius:} \\ &\text{(i) 300 K} \\ &\text{(ii) 250 K} \end{aligned}
\begin{aligned} & \text{Which method would you use to determine which piece of cloth is rougher without any tools?} \end{aligned}
\begin{aligned} & \text{How would you estimate the amount of sugar to add to milk to make it sweet according to your taste?} \end{aligned}
\begin{aligned} & \text{In what situations do we typically make estimations?} \end{aligned}
\begin{aligned} & \text{What are the common methods used to make estimations?} \end{aligned}
\begin{aligned} & \text{How do you calculate the average pulse rate and the range of pulse rates in a class?} \end{aligned}
\begin{aligned} &\text{What is the area of a cardboard in } \quad (a) \quad \mathrm{cm}^{2}, \quad (b) \quad \mathrm{mm}^{2}, \quad \text{and} \quad (c) \quad \mathrm{m}^{2} \text{?} \end{aligned}
\begin{aligned} &\text{The length of a hall is } \quad 18 \quad \text{m and breadth } \quad 5 \quad \text{m. What is the area of the hall in } \quad (a) \quad \mathrm{m}^{2} \quad \text{and} \quad (b) \quad \text{hectares?} \end{aligned}
\begin{aligned} &\text{A flat circular plate has a radius of } \quad 16 \quad \text{cm. What is the area of the plate?} \end{aligned}
\begin{aligned} &\text{The diameter of a circular field is } \quad 9 \quad \text{m. What is the area of the field?} \end{aligned}
\begin{aligned} &\text{A triangular cardboard has a base of } \quad 10 \quad \text{cm and its height up to the vertex is } \quad 5 \quad \text{cm. What is the area of the cardboard?} \end{aligned}
\begin{aligned} &\text{What is the term used to describe the degree of hotness or coldness of a body?} \end{aligned}
\begin{aligned} &\text{What is the name of the device used to measure the temperature of an object?} \end{aligned}
\begin{aligned} &\text{What is the SI unit for measuring temperature?} \end{aligned}
\begin{aligned} &\text{What is the term for the amount of surface occupied by an object or place?} \end{aligned}
\begin{aligned} &\text{Which liquid is commonly used in laboratory thermometers?} \end{aligned}
\begin{aligned} &\text{Which component of a thermometer is a fine glass tube with a small bore?} \end{aligned}
\begin{aligned} &\text{What is the name of the thick glass tube that protects the capillary tube in a thermometer?} \end{aligned}
\begin{aligned} &\text{What is the term used for the temperature limit of } \quad -273^{\circ} \mathrm{C} \quad \text{?} \end{aligned}
\begin{aligned} &\text{What is the temperature range marked on a clinical thermometer?} \end{aligned}
\begin{aligned} &\text{How should a clinical thermometer be sterilized?} \end{aligned}
\begin{aligned} &\text{Which of the following terms is used to describe the measure of hotness or coldness?} \end{aligned}
\begin{aligned} &\text{Which liquid is commonly used in laboratory thermometers?} \end{aligned}
\begin{aligned} &\text{What is the equivalent of } \quad 25^{\circ} \mathrm{C} \quad \text{on the Kelvin scale?} \end{aligned}
\begin{aligned} &\text{What does a temperature reading below } \quad 36^{\circ} \mathrm{C} \quad \text{on a clinical thermometer indicate?} \end{aligned}
\begin{aligned} &\text{How reliable are general estimations considered to be?} \end{aligned}
\begin{aligned} &\text{Which of the following correctly represents the temperature on the Celsius scale?} \end{aligned}
\begin{aligned} &\text{Why is a clinical thermometer shaken after washing?} \end{aligned}
\begin{aligned} &\text{A temperature increase of } 60^{\circ} \mathrm{C} \text{ on the Celsius scale corresponds to what increase on the Kelvin scale?} \end{aligned}
\begin{aligned} &\text{What is the normal body temperature of a healthy human?} \end{aligned}
\begin{aligned} &\text{Which statement best describes the concept of temperature?} \end{aligned}
\begin{aligned} &\text{Which device is commonly used in laboratories to measure the temperature of a body?} \end{aligned}
\begin{aligned} &\text{What is the concept of area in the context of physical measurements?} \end{aligned}
\begin{aligned} &\text{How can the area of a regular shape be determined using graph paper?} \end{aligned}
\begin{aligned} &\text{What are the standard reference points on a laboratory thermometer, and what are their values on the} \\ &\text{(a) Celsius scale and (b) Kelvin scale?} \end{aligned}
\begin{aligned} &\text{Into how many degrees is the scale of a laboratory thermometer divided on the Celsius scale?} \end{aligned}
\begin{aligned} &\text{If the mercury in a laboratory thermometer is at } \frac{3}{5} \text{ of the length between the standard points,} \\ &\text{what is the temperature in degree Celsius?} \end{aligned}
\begin{aligned} &\text{A Celsius thermometer shows } 30^{\circ} \mathrm{C}. \text{ What is the equivalent temperature on the Kelvin scale?} \end{aligned}
\begin{aligned} &\text{If the Kelvin temperature is 363 K, what is the corresponding temperature on the Celsius scale?} \end{aligned}
\begin{aligned} &\text{Which type of thermometer is used for measuring human body temperature?} \end{aligned}
\begin{aligned} &\text{Why is a clinical thermometer typically marked between } 34^{\circ} \mathrm{C} \text{ and } 43^{\circ} \mathrm{C}? \end{aligned}
\begin{aligned} &\text{What conclusions can be drawn if the temperature of a patient is measured as} \\ & (i) \quad 42^{\circ} \mathrm{C} \quad \text{and} \quad (ii) \quad 34.5^{\circ} \mathrm{C} \text{?} \end{aligned}
\begin{aligned} &\text{Why should a clinical thermometer not be sterilized in boiling water?} \end{aligned}
\begin{aligned} &\text{What is meant by the term estimation in the context of measurement?} \end{aligned}
\begin{aligned} &\text{Is estimation a dependable method for measurement? Provide two examples to support your answer.} \end{aligned}
\begin{aligned} &\text{What is the SI unit for measuring a distance of 5 kilometers?} \end{aligned}
\begin{aligned} &\text{Which of the following represents the SI unit for a mass of 3 metric tonnes?} \end{aligned}
\begin{aligned} &\text{Identify the SI unit for a power output of 2 megawatts.} \end{aligned}
\begin{aligned} &\text{Which of the following is a unit of time?} \end{aligned}
\begin{aligned} &\text{What is the floor area of a square room with a side length of 15 m?} \end{aligned}
\begin{aligned} &\text{Calculate the area of a school compound with a length of 480 m and a breadth of 160 m in} \\ &\text{(a) } \mathrm{m}^{2} \text{ and (b) hectares.} \end{aligned}
\begin{aligned} &\text{Determine the area of a district with a length of 22 km and a breadth of 19 km in} \\ &\text{(a) } \mathrm{km}^{2} \text{ and (b) hectares.} \end{aligned}
\begin{aligned} &\text{What is the area of a triangular cardboard with a base of 25 cm and a height of 18 cm?} \end{aligned}
\begin{aligned} &\text{Calculate the area of a coin with a radius of 35 mm in} \quad \text{(a) } \mathrm{mm}^{2} \text{ and (b) } \mathrm{cm}^{2} \text{?} \end{aligned}
\begin{aligned} &\text{Which tool is commonly used to measure body dimensions for tailoring?} \end{aligned}
\begin{aligned} &\text{What is the SI unit of mass?} \end{aligned}
\begin{aligned} &\text{How many inches are there in one foot?} \end{aligned}
\begin{aligned} &\text{What is the symbol for 100 meters?} \end{aligned}
\begin{aligned} &\text{Which type of clocks function only when the Sun is visible in the sky?} \end{aligned}
\begin{aligned} &\text{What is the suitable unit to measure the length of a soccer field?} \end{aligned}
\begin{aligned} &\text{What is the SI unit of time?} \end{aligned}
\begin{aligned} &\text{Why does the mercury in a clinical thermometer not flow back into the bulb?} \end{aligned}
\begin{aligned} &\text{Which of the following are considered basic quantities of measurement?} \end{aligned}
\begin{aligned} &\text{Which of the following represents the distance between two points?} \end{aligned}
\begin{aligned} &\text{The distances of stars from the earth are typically measured in which unit?} \end{aligned}
\begin{aligned} &\text{What is the time period of a pendulum with a length of 120 cm swinging freely?} \end{aligned}
\begin{aligned} &\text{Which of the following statements is true about sterilizing a clinical thermometer?} \end{aligned}
\begin{aligned} &\text{Read the Assertion (A) and Reason (R) statements carefully and choose the correct option:} \\ &\text{Assertion (A): Time is defined as an interval between two events.} \\ &\text{Reason (R): The interval between two successive noons is called a solar day.} \end{aligned}
\begin{aligned} &\text{Read the Assertion (A) and Reason (R) statements carefully and choose the correct option:} \\ &\text{Assertion (A): A clinical thermometer is calibrated from $34^{\circ} \mathrm{C}$ to $43^{\circ} \mathrm{C}$.} \\ &\text{Reason (R): The human body temperature does not typically fall below $34^{\circ} \mathrm{C}$ or rise above $43^{\circ} \mathrm{C}$.} \end{aligned}
\begin{aligned} &\text{Read the Assertion (A) and Reason (R) statements carefully and choose the correct option:} \\ &\text{Assertion (A): Unit symbols are often written in uppercase letters.} \\ &\text{Reason (R): The symbol for kilogram is written as kg.} \end{aligned}
\begin{aligned} &\text{Read the Assertion (A) and Reason (R) statements carefully and choose the correct option:} \\ &\text{Assertion (A): The SI unit for measuring area is the square meter.} \\ &\text{Reason (R): A square with each side measuring one meter has an area of one square meter.} \end{aligned}
\begin{aligned} &\text{Which of the following forms the foundation of all scientific research and experiments?} \end{aligned}
\begin{aligned} &\text{A physical quantity is a type of quantity that can be:} \end{aligned}
\begin{aligned} &\text{What is required for the measurement of any physical quantity?} \end{aligned}
\begin{aligned} &\text{Which organizations commonly use the 24-hour clock system?} \end{aligned}
\begin{aligned} &\text{Convert the time 15:30 from a 24-hour clock to a 12-hour clock format.} \end{aligned}
\begin{aligned} &\text{Why is it important to have standard units for measurement?} \end{aligned}
\begin{aligned} &\text{How many decades are there in (i) a century and (ii) a millennium?} \end{aligned}
\begin{aligned} &\text{How many seconds are there in two hours?} \end{aligned}
\begin{aligned} &\text{Why is a clinical thermometer marked between $34^{\circ} \mathrm{C}$ and $43^{\circ} \mathrm{C}$?} \end{aligned}
\begin{aligned} &\text{What can be inferred if a patient's temperature is $38.5^{\circ} \mathrm{C}$ and why?} \end{aligned}
\begin{aligned} &\text{If the normal body temperature is $37^{\circ} \mathrm{C}$, why might the body temperature of ten classmates vary around this value?} \end{aligned}

# Solution and Distractors(Based on misconceptions)

In [17]:
llm = ChatOpenAI(model="gpt-4o", temperature=0.2, api_key = OPENAI_API_KEY ,  request_timeout=30.0)

In [18]:
questions_df = pd.DataFrame(clean_rephrased_questions_json[conf_data["chapter_name"]])
questions_df

,topic,topic_id,question
0,Measurement of Length,6_physics_physical quantities and measurement_1,\begin{aligned} &\text{If a thin copper wire i...
1,Measurement of Length,6_physics_physical quantities and measurement_1,\begin{aligned} &\text{Which of the following ...
2,Measurement of Length,6_physics_physical quantities and measurement_1,\begin{aligned} &\text{Why is it important to ...
3,Measurement of Length,6_physics_physical quantities and measurement_1,\begin{aligned} &\text{What are the standard i...
4,Measurement of Length,6_physics_physical quantities and measurement_1,\begin{aligned} &\text{How is the term metre d...
...,...,...,...
116,Measurement of Time,6_physics_physical quantities and measurement_3,\begin{aligned} &\text{How many decades are th...
117,Measurement of Time,6_physics_physical quantities and measurement_3,\begin{aligned} &\text{How many seconds are th...
118,Types of Thermometers,6_physics_physical quantities and measurement_5,\begin{aligned} &\text{Why is a clinical therm...
119,Temperature and its Measurement,6_physics_physical quantities and measurement_4,\begin{aligned} &\text{What can be inferred if...
120,Temperature and its Measurement,6_physics_physical quantities and measurement_4,\begin{aligned} &\text{If the normal body temp...

In [19]:
import json
def parse_Response(response):
    if isinstance(response, str):
        # print(response)
        start_index = response.find("{")
        end_index = response.rfind("}")
        if start_index != -1 and end_index != -1:
            valid_json_content = response[start_index : end_index + 1]
            try:
                JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
                # append_list_to_file(JSON_response)
                return JSON_response
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON response: {e.__class__.__name__} - {e}\n\n Still trying to work on particular exceptions ...")
                if str(e).startswith("Extra data"):
                    json_parts = valid_json_content.split('}\n{')
                    if json_parts:
                        first_json = json_parts[0] + '}'
                        return parse_Response(first_json)  
                elif str(e).startswith("Invalid \escape"):
                    print("Before removing \\ issue: ", valid_json_content)
                    str1 = valid_json_content.replace("\\\\\\\\\\", "fvback")
                    str1 = str1.replace("\\\\\\\\", "frback")
                    str1 = str1.replace("\\\\\\", "trlback")
                    str1 = str1.replace("\\\\", "dblback")
                    str1 = str1.replace("\\", "\\\\")
                    str1 = str1.replace("fvback","\\\\\\\\\\")
                    str1 = str1.replace("frback", "\\\\\\\\")
                    str1 = str1.replace("trlback","\\\\\\")
                    strfinal = str1.replace("dblback","\\\\")
                    print("After removing \\ issue: ", strfinal)
                    JSON_response = json.loads(strfinal.replace("\n", ""))
                    return JSON_response
                else:
                    print("Actual Content: ", valid_json_content)
        else:
            print("No valid JSON content found in the response.")
        # time.sleep(50)
    elif isinstance(response, dict):
        return response
    else:
        print("No response message found", type(response))

<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_3636\3339088456.py:10: SyntaxWarning: invalid escape sequence '\('
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_3636\3339088456.py:10: SyntaxWarning: invalid escape sequence '\)'
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_3636\3339088456.py:20: SyntaxWarning: invalid escape sequence '\e'
  elif str(e).startswith("Invalid \escape"):

In [20]:
## Generating solutions
prompt_template = PromptTemplate(
    input_variables=["system_prompt", "question", "topic", "topic_id", "lulist"],
    template="{system_prompt}\n\n\nGenerate a hint, and solution for the given question. Also rephrase the given question according to the specified steps.\nHere are the required context:\nQuestion: {question}\nLearning unit data which defines scope from which solution should be generated: {lulist}\nTopic: {topic}\nTopic ID: {topic_id}\n\nReturn the output in the specified JSON format."
)

chain = LLMChain(llm=llm, prompt=prompt_template)
# chain = prompt_template | llm
# Function to process each question and generate hint, solution, and final answer
def generate_explanation(subject, question, topic, topic_id):
    try:
        match subject:
            case "mathematics":
                system = MATHEMATICS_SOLUTION_SYSTEM_PROMPT
            case "biology":
                system = BIOLOGY_SOLUTION_SYSTEM_PROMPT
            case "physics":
                system = PHYSICS_SOLUTION_SYSTEM_PROMPT
            case "chemistry":
                system = CHEMISTRY_SOLUTION_SYSTEM_PROMPT

        response = chain.run(
            system_prompt=system,
            lulist=total_LUs,
            question=question,
            topic=topic,
            topic_id=topic_id
        )
        return response
    except Exception as e:
        print(f"Error processing question: {question}\nError: {str(e)}")
        return None
# parser = PydanticOutputParser(pydantic_object=sol_data)
# global explanations
explanations = []
def loopForSolution(subject, questions_df):
    counter = 0
    retries_counter = 0
    maxCounter = len(questions_df)
    while counter < maxCounter:
        row = questions_df.iloc[counter]
        question = row['question']
        topic = row['topic']
        topic_id = row['topic_id']
        print(f"Processing question {counter + 1} out of {len(questions_df)}")
        explanation = generate_explanation(subject, question, topic, topic_id)
        parsed_explanation = parse_Response(explanation)
        if parsed_explanation:
            parsed_explanation["question"] = question
            parsed_explanation["topic"] = topic
            parsed_explanation["topic_id"] = topic_id
            explanations.append(parsed_explanation)
            counter += 1
            retries_counter = 0
        else:
            print("Issue in openai response", explanation, "\n\n Inputs: \n\n", question, "\n\n Topic: ", topic)
            print(f"Failed to parse explanation or generate solution for question {counter + 1}, retrying...")
            retries_counter += 1
        if retries_counter == 3:
            counter += 1

loopForSolution(subject, questions_df)

C:\Users\aniket singh\AppData\Local\Temp\ipykernel_3636\1295566236.py:7: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  chain = LLMChain(llm=llm, prompt=prompt_template)
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_3636\1295566236.py:22: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  response = chain.run(

Processing question 1 out of 121
Processing question 2 out of 121
Processing question 3 out of 121
Processing question 4 out of 121
Processing question 5 out of 121
Processing question 6 out of 121
Processing question 7 out of 121
Processing question 8 out of 121
Processing question 9 out of 121
Processing question 10 out of 121
Processing question 11 out of 121
Processing question 12 out of 121
Processing question 13 out of 121
Processing question 14 out of 121
Processing question 15 out of 121
Processing question 16 out of 121
Processing question 17 out of 121
Processing question 18 out of 121
Processing question 19 out of 121
Processing question 20 out of 121
Processing question 21 out of 121
Processing question 22 out of 121
Processing question 23 out of 121
Processing question 24 out of 121
Processing question 25 out of 121
Processing question 26 out of 121
Processing question 27 out of 121
Processing question 28 out of 121
Processing question 29 out of 121
Processing question 30 out of 121
Processing question 31 out of 121
Processing question 32 out of 121
Processing question 33 out of 121
Processing question 34 out of 121
Processing question 35 out of 121
Processing question 36 out of 121
Processing question 37 out of 121
Processing question 38 out of 121
Processing question 39 out of 121
Processing question 40 out of 121
Processing question 41 out of 121
Processing question 42 out of 121
Processing question 43 out of 121
Processing question 44 out of 121
Processing question 45 out of 121
Processing question 46 out of 121
Processing question 47 out of 121
Processing question 48 out of 121
Processing question 49 out of 121
Processing question 50 out of 121
Processing question 51 out of 121
Processing question 52 out of 121
Processing question 53 out of 121
Processing question 54 out of 121
Processing question 55 out of 121
Processing question 56 out of 121
Processing question 57 out of 121
Processing question 58 out of 121
Processing question 59 out of 121
Processing question 60 out of 121
Processing question 61 out of 121
Processing question 62 out of 121
Processing question 63 out of 121
Processing question 64 out of 121
Processing question 65 out of 121
Processing question 66 out of 121
Processing question 67 out of 121
Processing question 68 out of 121
Processing question 69 out of 121
Processing question 70 out of 121
Processing question 71 out of 121
Processing question 72 out of 121
Processing question 73 out of 121
Processing question 74 out of 121
Processing question 75 out of 121
Processing question 76 out of 121
Processing question 77 out of 121
Processing question 78 out of 121
Processing question 79 out of 121
Processing question 80 out of 121
Processing question 81 out of 121
Processing question 82 out of 121
Processing question 83 out of 121
Processing question 84 out of 121
Processing question 85 out of 121
Processing question 86 out of 121
Processing question 87 out of 121
Processing question 88 out of 121
Processing question 89 out of 121
Processing question 90 out of 121
Processing question 91 out of 121
Processing question 92 out of 121
Processing question 93 out of 121
Processing question 94 out of 121
Processing question 95 out of 121
Processing question 96 out of 121
Processing question 97 out of 121
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 305 (char 304)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Consider the standard unit of length in the metric system and how it is represented.} \\\\ &\\text{Think about how multiples of this unit are denoted.} \\\\ \\end{aligned}",
    "solution": "\\begin{aligned} &\\text{The symbol for 100 meters is represented as } 100 \, \\text{m}. \\\\ &\\text{In the metric system, the basic unit of length is the meter, denoted by the symbol } \\text{m}. \\\\ &\\text{When expressing multiples of a unit, such as 100 meters, the number is written followed by the unit symbol.} \\\\ \\end{aligned}"
}
After removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Consider the standard unit of length in the metric system and how it is represented.} \\\\ &\\text{Think about how multiples of this unit are denoted.} \\\\ \\end{aligned}",
    "solution": "\\begin{aligned} &\\text{The symbol for 100 meters is represented as } 100 \\, \\text{m}. \\\\ &\\text{In the metric system, the basic unit of length is the meter, denoted by the symbol } \\text{m}. \\\\ &\\text{When expressing multiples of a unit, such as 100 meters, the number is written followed by the unit symbol.} \\\\ \\end{aligned}"
}
Processing question 98 out of 121
Processing question 99 out of 121
Processing question 100 out of 121
Processing question 101 out of 121
Processing question 102 out of 121
Processing question 103 out of 121
Processing question 104 out of 121
Processing question 105 out of 121
Processing question 106 out of 121
Processing question 107 out of 121
Processing question 108 out of 121
Processing question 109 out of 121
Processing question 110 out of 121
Processing question 111 out of 121
Processing question 112 out of 121
Processing question 113 out of 121
Processing question 114 out of 121
Processing question 115 out of 121
Processing question 116 out of 121
Processing question 117 out of 121
Processing question 118 out of 121
Processing question 119 out of 121
Processing question 120 out of 121
Processing question 121 out of 121

In [21]:
for i in explanations:
    print(i['question'])
    print(i['solution'])
    print("-------------")

\begin{aligned} &\text{If a thin copper wire is wound around a pencil to form a coil with 25 turns, and the length of the coil is measured to be 2 cm, what is the diameter of the wire?} \end{aligned}
\begin{aligned} &\text{The length of the coil is given as 2 cm, and there are 25 turns.} \\ &\text{The length of the coil is equal to the number of turns multiplied by the circumference of the wire.} \\ &\text{Let } d \text{ be the diameter of the wire. The circumference of the wire is } \pi d. \\ &\text{Thus, the total length of the coil is } 25 \times \pi d = 2 \text{ cm.} \\ &\text{Solving for } d, \text{ we have:} \\ &\pi d = \frac{2}{25} \\ &d = \frac{2}{25 \pi} \\ &\text{Therefore, the diameter of the wire is } \frac{2}{25 \pi} \text{ cm.} \\ \end{aligned}
-------------
\begin{aligned} &\text{Which of the following were early units of measurement for length?} \end{aligned}
\begin{aligned} &\text{In ancient times, people used various units of measurement for length based on familiar objects or body parts.} \\ &\text{Some of these early units included the cubit, which was the length of the forearm from the elbow to the tip of the middle finger, and the foot, which was based on the length of a human foot.} \\ &\text{These units were not standardized and varied from place to place, but they were practical for everyday use.} \\ \end{aligned}
-------------
\begin{aligned} &\text{Why is it important to have standard units for measurement?} \end{aligned}
\begin{aligned} &\text{Standard units of measurement are crucial because they provide a consistent framework for communication and comparison.} \\ &\text{Without standard units, it would be challenging to compare measurements accurately, as different regions might use different units.} \\ &\text{This consistency is essential in scientific research, trade, and daily life to ensure that measurements are understood universally.} \\ \end{aligned}
-------------
\begin{aligned} &\text{What are the standard international units of measurement, and what is the unit of length in this system?} \end{aligned}
\begin{aligned} &\text{The International System of Units (SI) is the globally accepted system for measurement. It includes seven base units for different physical quantities.} \\\ &\text{The unit of length in the SI system is the meter (m). This unit is used to measure the distance between two points.} \\\ &\text{The meter is defined by the distance light travels in a vacuum in 1/299,792,458 of a second.} \end{aligned}
-------------
\begin{aligned} &\text{How is the term metre defined, and what are one multiple and two submultiples of metre?} \end{aligned}
\begin{aligned} &\text{The metre is defined as the distance travelled by light in vacuum in } \quad \text{1/299,792,458 of a second.} \\\ &\text{One multiple of a metre is a kilometre, which is equal to 1000 metres.} \\\ &\text{Two submultiples of a metre are a centimetre and a millimetre.} \\\ &\text{A centimetre is } \quad \text{1/100 of a metre, and a millimetre is } \quad \text{1/1000 of a metre.} \end{aligned}
-------------
\begin{aligned} &\text{Which position of the eye records the accurate length of a pencil, and what is the magnitude of this length?} \end{aligned}
\begin{aligned} &\text{The accurate length of a pencil is recorded when the eye is positioned directly perpendicular to the scale at the point of measurement.} \\ &\text{This position helps avoid parallax error, which occurs when the eye is not aligned with the measurement mark, leading to inaccurate readings.} \\ &\text{The magnitude of the length is determined by reading the scale where the pencil ends, typically measured in centimeters (cm) or millimeters (mm).} \\ \end{aligned}
-------------
\begin{aligned} &\text{What are two characteristics of a standard unit for measuring a physical quantity?} \end{aligned}
\begin{aligned} &\text{A standard unit for measuring a physical quantity should have two main characteristics: it should be universally accepted and invariable.} \\ &\text{Universally accepted means that the unit should be recognized and used globally, ensuring consistency in measurements across different regions.} \\ &\text{Invariable means that the unit should not change over time or with environmental conditions, ensuring reliability and accuracy in measurements.} \end{aligned}
-------------
\begin{aligned} &\text{How can you determine the length of a curved line using a thin cotton thread?} \end{aligned}
\begin{aligned} &\text{To determine the length of a curved line using a thin cotton thread, first place the thread along the curve carefully, ensuring it follows the exact path of the curve.} \\ &\text{Once the thread has been laid out along the entire curve, mark the points on the thread that correspond to the start and end of the curve.} \\ &\text{Next, straighten the thread and measure the distance between the two marked points using a ruler.} \\ &\text{This measured length on the ruler will give you the length of the curved line.} \end{aligned}
-------------
\begin{aligned} &\text{If four identical wooden rods placed side by side have a total thickness of 6 cm, what is the thickness of one rod, correct to two decimal places?} \end{aligned}
\begin{aligned} &\text{Given that the total thickness of four identical rods is 6 cm.} \\ &\text{To find the thickness of one rod, divide the total thickness by the number of rods:} \\ &\text{Thickness of one rod} = \frac{6 \text{ cm}}{4} = 1.50 \text{ cm} \\ &\text{Therefore, the thickness of one rod is 1.50 cm, correct to two decimal places.} \\ \end{aligned}
-------------
\begin{aligned} &\text{When 30 coins are stacked and their total thickness is measured as 5.4 cm, what is the thickness of each coin in millimeters?} \end{aligned}
\begin{aligned} &\text{The total thickness of 30 coins is given as 5.4 cm. To find the thickness of each coin, we divide the total thickness by the number of coins.} \\\ &\text{Thickness of each coin} = \frac{5.4 \text{ cm}}{30} = 0.18 \text{ cm} \\\ &\text{To convert the thickness from centimeters to millimeters, we multiply by 10 (since 1 cm = 10 mm).} \\\ &\text{Thickness of each coin in millimeters} = 0.18 \times 10 = 1.8 \text{ mm} \end{aligned}
-------------
\begin{aligned} &\text{Which unit is used to measure the distance of a star from the Earth, and how many kilometers does it represent?} \end{aligned}
\begin{aligned} &\text{The unit used to measure the distance of a star from the Earth is the light year.} \\ &\text{A light year is the distance that light travels in one year.} \\ &\text{Since light travels at a speed of approximately } 299,792,458 \text{ meters per second,} \\ &\text{a light year is equivalent to about } 9.46 \times 10^{12} \text{ kilometers.} \\ \end{aligned}
-------------
\begin{aligned} &\text{Identify two units used to measure the diameter of a bacterial cell or atomic nucleus, and express their values in millimeters.} \end{aligned}
\begin{aligned} &\text{The two units commonly used to measure the diameter of a bacterial cell or atomic nucleus are the micrometer and the nanometer.} \\ &\text{A micrometer is } 10^{-3} \text{ millimeters, and a nanometer is } 10^{-6} \text{ millimeters.} \\ \end{aligned}
-------------
\begin{aligned} &\text{How would you convert the following 24-hour time format to a 12-hour time format?} \end{aligned}
\begin{aligned} &\text{To convert a 24-hour time format to a 12-hour time format, you need to check the hour value. If the hour is greater than 12, subtract 12 from the hour and add PM to indicate the time is in the afternoon or evening. For example, if the time is 14:00 in 24-hour format, subtract 12 from 14 to get 2, and then add PM, resulting in 2:00 PM. If the hour is 12 or less, simply add AM or PM based on the context. For example, 09:00 in 24-hour format is 9:00 AM in 12-hour format.} \end{aligned}
-------------
\begin{aligned} &\text{How would you convert the following 12-hour time format to a 24-hour time format?} \end{aligned}
\begin{aligned} &\text{To convert a 12-hour time format to a 24-hour time format, follow these steps:} \\\ &\text{1. If the time is in AM and not 12 AM, the 24-hour format is the same as the 12-hour format.} \\\ &\text{2. If the time is 12 AM, it converts to 00 in the 24-hour format.} \\\ &\text{3. If the time is in PM and not 12 PM, add 12 to the hour to convert it to the 24-hour format.} \\\ &\text{4. If the time is 12 PM, it remains 12 in the 24-hour format.} \end{aligned}
-------------
\begin{aligned} &\text{What is meant by the term 'mass' and what is its SI unit?} \end{aligned}
\begin{aligned} &\text{Mass is a fundamental property of a material that measures the amount of matter it contains.} \\ &\text{The SI unit of mass is the kilogram (kg).} \\ \end{aligned}
-------------
\begin{aligned} &\text{Which of the following are two multiples and two submultiples of the SI unit of mass?} \end{aligned}
\begin{aligned} &\text{The SI unit of mass is the kilogram (kg). Multiples of the kilogram include the metric ton (1000 kg) and the quintal (100 kg).} \\ &\text{Submultiples of the kilogram include the gram (0.001 kg) and the milligram (0.000001 kg).} \\ &\text{Thus, two multiples of the SI unit of mass are the metric ton and the quintal, while two submultiples are the gram and the milligram.} \\ \end{aligned}
-------------
\begin{aligned} &\text{What type of balance is typically used for measuring the mass of (a) a gold ornament and (b) vegetables?} \end{aligned}
\begin{aligned} &\text{For measuring the mass of a gold ornament, a beam balance or an electronic balance is typically used. These balances provide high precision and accuracy, which is essential for measuring valuable items like gold.} \\\ &\text{On the other hand, for measuring the mass of vegetables, a simple spring balance or a kitchen scale is often used. These balances are sufficient for measuring larger quantities where high precision is not as critical.} \end{aligned}
-------------
\begin{aligned} &\text{What is meant by the term 'time' and what is its SI unit?} \end{aligned}
\begin{aligned} &\text{Time is a fundamental physical quantity that represents the ongoing sequence of events taking place.} \\ &\text{It is used to quantify the duration of events and the intervals between them.} \\ &\text{The SI unit of time is the second, symbolized as 's'.} \\ \end{aligned}
-------------
\begin{aligned} &\text{How many centuries are there in one millennium?} \end{aligned}
\begin{aligned} &\text{A millennium is defined as a period of 1000 years.} \\ &\text{A century is defined as a period of 100 years.} \\ &\text{To find how many centuries are in a millennium, divide the number of years in a millennium by the number of years in a century:} \\ &\quad \frac{1000}{100} = 10 \\ &\text{Therefore, there are 10 centuries in one millennium.} \\ \end{aligned}
-------------
\begin{aligned} &\text{How many decades constitute one millennium?} \end{aligned}
\begin{aligned} &\text{A decade consists of 10 years.} \\ &\text{A millennium consists of 1000 years.} \\ &\text{To find out how many decades are in a millennium, divide the number of years in a millennium by the number of years in a decade:} \\ &\frac{1000}{10} = 100 \\ &\text{Therefore, there are 100 decades in one millennium.} \\ \end{aligned}
-------------
\begin{aligned} &\text{How many years are equivalent to one millennium?} \end{aligned}
\begin{aligned} &\text{A millennium is defined as a period of 1000 years. Therefore, one millennium is equivalent to 1000 years.} \\ \end{aligned}
-------------
\begin{aligned} &\text{What is meant by the term 'mean solar day'?} \end{aligned}
\begin{aligned} &\text{A 'mean solar day' is the average time taken by the Earth to complete one rotation on its axis with respect to the Sun.} \\ &\text{It is approximately 24 hours and is used as a standard unit of time measurement.} \\ \end{aligned}
-------------
\begin{aligned} &\text{How many hours constitute a mean solar day?} \end{aligned}
\begin{aligned} &\text{A mean solar day is defined as the average time it takes for the Earth to complete one full rotation on its axis relative to the Sun.} \\ &\text{This period is divided into 24 equal parts, each part being one hour.} \\ &\text{Therefore, a mean solar day consists of 24 hours.} \\ \end{aligned}
-------------
\begin{aligned} &\text{How many minutes are there in a mean solar day?} \end{aligned}
\begin{aligned} &\text{A mean solar day is defined as the average time it takes for the Earth to rotate once on its axis.} \\ &\text{This duration is approximately 24 hours.} \\ &\text{Since there are 60 minutes in an hour, the total number of minutes in a mean solar day is calculated as follows:} \\ &24 \times 60 = 1440 \\ &\text{Therefore, there are 1440 minutes in a mean solar day.} \\ \end{aligned}
-------------
\begin{aligned} &\text{How many seconds make up a mean solar day?} \end{aligned}
\begin{aligned} &\text{A mean solar day is defined as the average time it takes for the Earth to complete one full rotation on its axis.} \\\ &\text{This duration is conventionally divided into 24 hours.} \\\ &\text{Each hour consists of 60 minutes, and each minute consists of 60 seconds.} \\\ &\text{Therefore, the total number of seconds in a mean solar day is calculated as follows:} \\\ &24 \quad \text{hours} \times 60 \quad \text{minutes/hour} \times 60 \quad \text{seconds/minute} = 86400 \quad \text{seconds.} \\\ &\text{Thus, a mean solar day is made up of 86400 seconds.} \end{aligned}
-------------
\begin{aligned} &\text{Which of the following best describes a simple pendulum?} \end{aligned}
\begin{aligned} &\text{A simple pendulum consists of a small, dense bob suspended from a fixed point by a string or rod of negligible mass.} \\ &\text{The pendulum swings back and forth under the influence of gravity, with the motion being periodic.} \\ &\text{The simplicity comes from the assumption that the string or rod does not stretch and air resistance is negligible.} \\ \end{aligned}
-------------
\begin{aligned} &\text{What is the definition of oscillation in the context of pendulums?} \end{aligned}
\begin{aligned} &\text{Oscillation in the context of pendulums refers to the repetitive back and forth motion about a central point or equilibrium position.} \\ &\text{This motion is periodic, meaning it occurs at regular intervals of time.} \\ \end{aligned}
-------------
\begin{aligned} &\text{How is the length of a pendulum defined?} \end{aligned}
\begin{aligned} &\text{The length of a pendulum is defined as the distance from the point of suspension to the center of the bob.} \\ &\text{This is measured along the string or rod that connects the fixed point to the bob.} \\ \end{aligned}
-------------
\begin{aligned} &\text{What is the time period of a pendulum and how is it measured?} \end{aligned}
\begin{aligned} &\text{The time period of a pendulum is the time taken for it to complete one full oscillation, which means swinging from one side to the other and back again.} \\ &\text{It is measured using a stopwatch or a clock, and the unit of time is seconds.} \\ &\text{To measure it, start the stopwatch when the pendulum is at its highest point on one side and stop it when it returns to the same point after swinging to the other side.} \\ \end{aligned}
-------------
\begin{aligned} &\text{If the time period of a pendulum is 3 s, what is the length of the pendulum?} \end{aligned}
\begin{aligned} &\text{The formula for the time period } T \text{ of a simple pendulum is given by:} \\\ &T = 2\pi \sqrt{\frac{L}{g}} \\\ &\text{where } T \text{ is the time period, } L \text{ is the length of the pendulum, and } g \text{ is the acceleration due to gravity.} \\\ &\text{Given } T = 3 \text{ s, we need to find } L. \\\ &\text{Rearrange the formula to solve for } L: \\\ &L = \frac{gT^2}{4\pi^2} \\\ &\text{Assuming } g = 9.8 \text{ m/s}^2, \\\ &L = \frac{9.8 \times 3^2}{4\pi^2} \\\ &L \approx 2.24 \text{ m} \\\ &\text{Thus, the length of the pendulum is approximately } 2.24 \text{ meters.} \\\ \end{aligned}
-------------
\begin{aligned} &\text{If a boy completes a race and the pendulum makes 40 oscillations,} \\ &\text{what is the time taken by the boy in seconds to finish the race?} \end{aligned}
\begin{aligned} &\text{The time period of a pendulum is the time taken for one complete oscillation.} \\ &\text{If the pendulum makes 40 oscillations, and the time period of one oscillation is } T \text{ seconds,} \\ &\text{then the total time taken is given by } 40 \times T. \\ &\text{Assuming the time period } T \text{ is known, the total time taken by the boy is } 40T \text{ seconds.} \\ \end{aligned}
-------------
\begin{aligned} &\text{Which of the following best describes a 24-hour clock?} \end{aligned}
\begin{aligned} &\text{A 24-hour clock describes time using a continuous count of hours from 0 to 23.} \\ &\text{This means that midnight is represented as 00:00 and the last minute of the day is 23:59.} \\ &\text{Unlike the 12-hour clock, it does not use AM or PM to differentiate between morning and evening.} \\ \end{aligned}
-------------
\begin{aligned} &\text{Identify two organizations that commonly use a 24-hour clock system.} \end{aligned}
\begin{aligned} &\text{The two organizations that commonly use a 24-hour clock system are the military and hospitals.} \\ &\text{The military uses the 24-hour clock to avoid confusion between AM and PM times, which is crucial for operations that require precise timing.} \\ &\text{Hospitals use the 24-hour clock to ensure accurate scheduling of medical procedures and medication administration, reducing the risk of errors.} \\ \end{aligned}
-------------
\begin{aligned} &\text{Convert the following 24-hour clock time to a 12-hour clock format:} \\ &\text{(i) 09:45} \end{aligned}
\begin{aligned} &\text{The given time is 09:45 in 24-hour format.} \\ &\text{Since 9 is less than 12, the time remains the same in 12-hour format.} \\ &\text{Therefore, 09:45 in 24-hour format is 9:45 AM in 12-hour format.} \\ \end{aligned}
-------------
\begin{aligned} &\text{Convert the following 24-hour clock time to a 12-hour clock format:} \\ &\text{(ii) 22:30} \end{aligned}
\begin{aligned} &\text{The given time is 22:30 in a 24-hour format.} \\\ &\text{To convert it to a 12-hour format, subtract 12 from the hour:} \\\ &22 - 12 = 10. \\\ &\text{Thus, the time in a 12-hour format is 10:30 PM.} \end{aligned}
-------------
\begin{aligned} &\text{Which of the following best describes a 12-hour clock system?} \end{aligned}
\begin{aligned} &\text{The 12-hour clock system divides the day into two periods: AM and PM.} \\ &\text{Each period consists of 12 hours, starting from 12 and ending at 11.} \\ &\text{This system repeats every 12 hours, making a full day 24 hours long.} \\ \end{aligned}
-------------
\begin{aligned} &\text{What do the indications a.m. and p.m. represent on a 12-hour clock?} \end{aligned}
\begin{aligned} &\text{The indications 'a.m.' and 'p.m.' on a 12-hour clock represent the two halves of a day.} \\ &\text{'a.m.' stands for 'ante meridiem', which means before midday, referring to the time from midnight to noon.} \\ &\text{'p.m.' stands for 'post meridiem', which means after midday, referring to the time from noon to midnight.} \\ \end{aligned}
-------------
\begin{aligned} &\text{Convert the following times from a 12-hour clock to a 24-hour clock:} \\ &\text{(i) 4:45 p.m.} \\ &\text{(ii) 8:20 a.m.} \end{aligned}
\begin{aligned} &\text{For part (i), 4:45 p.m. is converted by adding 12 to the hour:} \\ &4 + 12 = 16 \\ &\text{Thus, 4:45 p.m. is 16:45 in a 24-hour clock.} \\ &\text{For part (ii), 8:20 a.m. remains the same as it is already in the morning:} \\ &\text{Thus, 8:20 a.m. is 08:20 in a 24-hour clock.} \end{aligned}
-------------
\begin{aligned} &\text{Convert the following temperatures from Celsius to Kelvin:} \\ &\text{(i) 25°C} \\ &\text{(ii) -10°C} \end{aligned}

### Generating Distractors

In [22]:
data = pd.DataFrame(explanations)

In [23]:
data['misconception_options'] = ''
data

,hint,solution,question,topic,topic_id,misconception_options
0,\begin{aligned} &\text{To find the diameter of...,\begin{aligned} &\text{The length of the coil ...,\begin{aligned} &\text{If a thin copper wire i...,Measurement of Length,6_physics_physical quantities and measurement_1,
1,\begin{aligned} &\text{Think about the histori...,"\begin{aligned} &\text{In ancient times, peopl...",\begin{aligned} &\text{Which of the following ...,Measurement of Length,6_physics_physical quantities and measurement_1,
2,\begin{aligned} &\text{Consider how having a c...,\begin{aligned} &\text{Standard units of measu...,\begin{aligned} &\text{Why is it important to ...,Measurement of Length,6_physics_physical quantities and measurement_1,
3,\begin{aligned} &\text{The International Syste...,\begin{aligned} &\text{The International Syste...,\begin{aligned} &\text{What are the standard i...,Measurement of Length,6_physics_physical quantities and measurement_1,
4,\begin{aligned} &\text{Think about the definit...,\begin{aligned} &\text{The metre is defined as...,\begin{aligned} &\text{How is the term metre d...,Measurement of Length,6_physics_physical quantities and measurement_1,
...,...,...,...,...,...,...
116,\begin{aligned} &\text{To find the number of d...,\begin{aligned} &\text{A decade consists of 10...,\begin{aligned} &\text{How many decades are th...,Measurement of Time,6_physics_physical quantities and measurement_3,
117,\begin{aligned} &\text{To find the total secon...,\begin{aligned} &\text{To calculate the number...,\begin{aligned} &\text{How many seconds are th...,Measurement of Time,6_physics_physical quantities and measurement_3,
118,\begin{aligned} &\text{Consider the normal ran...,\begin{aligned} &\text{A clinical thermometer ...,\begin{aligned} &\text{Why is a clinical therm...,Types of Thermometers,6_physics_physical quantities and measurement_5,
119,\begin{aligned} &\text{Consider the normal bod...,\begin{aligned} &\text{A normal human body tem...,\begin{aligned} &\text{What can be inferred if...,Temperature and its Measurement,6_physics_physical quantities and measurement_4,
120,\begin{aligned} &\text{Consider the factors th...,\begin{aligned} &\text{The normal body tempera...,\begin{aligned} &\text{If the normal body temp...,Temperature and its Measurement,6_physics_physical quantities and measurement_4,

In [24]:
for i in range(len(data)):
    print(data['solution'][i].split("\n"))

['\\begin{aligned} &\\text{The length of the coil is given as 2 cm, and there are 25 turns.} \\\\ &\\text{The length of the coil is equal to the number of turns multiplied by the circumference of the wire.} \\\\ &\\text{Let } d \\text{ be the diameter of the wire. The circumference of the wire is } \\pi d. \\\\ &\\text{Thus, the total length of the coil is } 25 \\times \\pi d = 2 \\text{ cm.} \\\\ &\\text{Solving for } d, \\text{ we have:} \\\\ &\\pi d = \\frac{2}{25} \\\\ &d = \\frac{2}{25 \\pi} \\\\ &\\text{Therefore, the diameter of the wire is } \\frac{2}{25 \\pi} \\text{ cm.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{In ancient times, people used various units of measurement for length based on familiar objects or body parts.} \\\\ &\\text{Some of these early units included the cubit, which was the length of the forearm from the elbow to the tip of the middle finger, and the foot, which was based on the length of a human foot.} \\\\ &\\text{These units were not standardized and varied from place to place, but they were practical for everyday use.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Standard units of measurement are crucial because they provide a consistent framework for communication and comparison.} \\\\ &\\text{Without standard units, it would be challenging to compare measurements accurately, as different regions might use different units.} \\\\ &\\text{This consistency is essential in scientific research, trade, and daily life to ensure that measurements are understood universally.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The International System of Units (SI) is the globally accepted system for measurement. It includes seven base units for different physical quantities.} \\\\\\ &\\text{The unit of length in the SI system is the meter (m). This unit is used to measure the distance between two points.} \\\\\\ &\\text{The meter is defined by the distance light travels in a vacuum in 1/299,792,458 of a second.} \\end{aligned}']
['\\begin{aligned} &\\text{The metre is defined as the distance travelled by light in vacuum in } \\quad \\text{1/299,792,458 of a second.} \\\\\\ &\\text{One multiple of a metre is a kilometre, which is equal to 1000 metres.} \\\\\\ &\\text{Two submultiples of a metre are a centimetre and a millimetre.} \\\\\\ &\\text{A centimetre is } \\quad \\text{1/100 of a metre, and a millimetre is } \\quad \\text{1/1000 of a metre.} \\end{aligned}']
['\\begin{aligned} &\\text{The accurate length of a pencil is recorded when the eye is positioned directly perpendicular to the scale at the point of measurement.} \\\\ &\\text{This position helps avoid parallax error, which occurs when the eye is not aligned with the measurement mark, leading to inaccurate readings.} \\\\ &\\text{The magnitude of the length is determined by reading the scale where the pencil ends, typically measured in centimeters (cm) or millimeters (mm).} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{A standard unit for measuring a physical quantity should have two main characteristics: it should be universally accepted and invariable.} \\\\ &\\text{Universally accepted means that the unit should be recognized and used globally, ensuring consistency in measurements across different regions.} \\\\ &\\text{Invariable means that the unit should not change over time or with environmental conditions, ensuring reliability and accuracy in measurements.} \\end{aligned}']
['\\begin{aligned} &\\text{To determine the length of a curved line using a thin cotton thread, first place the thread along the curve carefully, ensuring it follows the exact path of the curve.} \\\\ &\\text{Once the thread has been laid out along the entire curve, mark the points on the thread that correspond to the start and end of the curve.} \\\\ &\\text{Next, straighten the thread and measure the distance between the two marked points using a ruler.} \\\\ &\\text{This measured length on the ruler will give you the length of the curved line.} \\end{aligned}']
['\\begin{aligned} &\\text{Given that the total thickness of four identical rods is 6 cm.} \\\\ &\\text{To find the thickness of one rod, divide the total thickness by the number of rods:} \\\\ &\\text{Thickness of one rod} = \\frac{6 \\text{ cm}}{4} = 1.50 \\text{ cm} \\\\ &\\text{Therefore, the thickness of one rod is 1.50 cm, correct to two decimal places.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The total thickness of 30 coins is given as 5.4 cm. To find the thickness of each coin, we divide the total thickness by the number of coins.} \\\\\\ &\\text{Thickness of each coin} = \\frac{5.4 \\text{ cm}}{30} = 0.18 \\text{ cm} \\\\\\ &\\text{To convert the thickness from centimeters to millimeters, we multiply by 10 (since 1 cm = 10 mm).} \\\\\\ &\\text{Thickness of each coin in millimeters} = 0.18 \\times 10 = 1.8 \\text{ mm} \\end{aligned}']
['\\begin{aligned} &\\text{The unit used to measure the distance of a star from the Earth is the light year.} \\\\ &\\text{A light year is the distance that light travels in one year.} \\\\ &\\text{Since light travels at a speed of approximately } 299,792,458 \\text{ meters per second,} \\\\ &\\text{a light year is equivalent to about } 9.46 \\times 10^{12} \\text{ kilometers.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The two units commonly used to measure the diameter of a bacterial cell or atomic nucleus are the micrometer and the nanometer.} \\\\ &\\text{A micrometer is } 10^{-3} \\text{ millimeters, and a nanometer is } 10^{-6} \\text{ millimeters.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{To convert a 24-hour time format to a 12-hour time format, you need to check the hour value. If the hour is greater than 12, subtract 12 from the hour and add PM to indicate the time is in the afternoon or evening. For example, if the time is 14:00 in 24-hour format, subtract 12 from 14 to get 2, and then add PM, resulting in 2:00 PM. If the hour is 12 or less, simply add AM or PM based on the context. For example, 09:00 in 24-hour format is 9:00 AM in 12-hour format.} \\end{aligned}']
['\\begin{aligned} &\\text{To convert a 12-hour time format to a 24-hour time format, follow these steps:} \\\\\\ &\\text{1. If the time is in AM and not 12 AM, the 24-hour format is the same as the 12-hour format.} \\\\\\ &\\text{2. If the time is 12 AM, it converts to 00 in the 24-hour format.} \\\\\\ &\\text{3. If the time is in PM and not 12 PM, add 12 to the hour to convert it to the 24-hour format.} \\\\\\ &\\text{4. If the time is 12 PM, it remains 12 in the 24-hour format.} \\end{aligned}']
['\\begin{aligned} &\\text{Mass is a fundamental property of a material that measures the amount of matter it contains.} \\\\ &\\text{The SI unit of mass is the kilogram (kg).} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The SI unit of mass is the kilogram (kg). Multiples of the kilogram include the metric ton (1000 kg) and the quintal (100 kg).} \\\\ &\\text{Submultiples of the kilogram include the gram (0.001 kg) and the milligram (0.000001 kg).} \\\\ &\\text{Thus, two multiples of the SI unit of mass are the metric ton and the quintal, while two submultiples are the gram and the milligram.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{For measuring the mass of a gold ornament, a beam balance or an electronic balance is typically used. These balances provide high precision and accuracy, which is essential for measuring valuable items like gold.} \\\\\\ &\\text{On the other hand, for measuring the mass of vegetables, a simple spring balance or a kitchen scale is often used. These balances are sufficient for measuring larger quantities where high precision is not as critical.} \\end{aligned}']
["\\begin{aligned} &\\text{Time is a fundamental physical quantity that represents the ongoing sequence of events taking place.} \\\\ &\\text{It is used to quantify the duration of events and the intervals between them.} \\\\ &\\text{The SI unit of time is the second, symbolized as 's'.} \\\\ \\end{aligned}"]
['\\begin{aligned} &\\text{A millennium is defined as a period of 1000 years.} \\\\ &\\text{A century is defined as a period of 100 years.} \\\\ &\\text{To find how many centuries are in a millennium, divide the number of years in a millennium by the number of years in a century:} \\\\ &\\quad \\frac{1000}{100} = 10 \\\\ &\\text{Therefore, there are 10 centuries in one millennium.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{A decade consists of 10 years.} \\\\ &\\text{A millennium consists of 1000 years.} \\\\ &\\text{To find out how many decades are in a millennium, divide the number of years in a millennium by the number of years in a decade:} \\\\ &\\frac{1000}{10} = 100 \\\\ &\\text{Therefore, there are 100 decades in one millennium.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{A millennium is defined as a period of 1000 years. Therefore, one millennium is equivalent to 1000 years.} \\\\ \\end{aligned}']
["\\begin{aligned} &\\text{A 'mean solar day' is the average time taken by the Earth to complete one rotation on its axis with respect to the Sun.} \\\\ &\\text{It is approximately 24 hours and is used as a standard unit of time measurement.} \\\\ \\end{aligned}"]
['\\begin{aligned} &\\text{A mean solar day is defined as the average time it takes for the Earth to complete one full rotation on its axis relative to the Sun.} \\\\ &\\text{This period is divided into 24 equal parts, each part being one hour.} \\\\ &\\text{Therefore, a mean solar day consists of 24 hours.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{A mean solar day is defined as the average time it takes for the Earth to rotate once on its axis.} \\\\ &\\text{This duration is approximately 24 hours.} \\\\ &\\text{Since there are 60 minutes in an hour, the total number of minutes in a mean solar day is calculated as follows:} \\\\ &24 \\times 60 = 1440 \\\\ &\\text{Therefore, there are 1440 minutes in a mean solar day.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{A mean solar day is defined as the average time it takes for the Earth to complete one full rotation on its axis.} \\\\\\ &\\text{This duration is conventionally divided into 24 hours.} \\\\\\ &\\text{Each hour consists of 60 minutes, and each minute consists of 60 seconds.} \\\\\\ &\\text{Therefore, the total number of seconds in a mean solar day is calculated as follows:} \\\\\\ &24 \\quad \\text{hours} \\times 60 \\quad \\text{minutes/hour} \\times 60 \\quad \\text{seconds/minute} = 86400 \\quad \\text{seconds.} \\\\\\ &\\text{Thus, a mean solar day is made up of 86400 seconds.} \\end{aligned}']
['\\begin{aligned} &\\text{A simple pendulum consists of a small, dense bob suspended from a fixed point by a string or rod of negligible mass.} \\\\ &\\text{The pendulum swings back and forth under the influence of gravity, with the motion being periodic.} \\\\ &\\text{The simplicity comes from the assumption that the string or rod does not stretch and air resistance is negligible.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Oscillation in the context of pendulums refers to the repetitive back and forth motion about a central point or equilibrium position.} \\\\ &\\text{This motion is periodic, meaning it occurs at regular intervals of time.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The length of a pendulum is defined as the distance from the point of suspension to the center of the bob.} \\\\ &\\text{This is measured along the string or rod that connects the fixed point to the bob.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The time period of a pendulum is the time taken for it to complete one full oscillation, which means swinging from one side to the other and back again.} \\\\ &\\text{It is measured using a stopwatch or a clock, and the unit of time is seconds.} \\\\ &\\text{To measure it, start the stopwatch when the pendulum is at its highest point on one side and stop it when it returns to the same point after swinging to the other side.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The formula for the time period } T \\text{ of a simple pendulum is given by:} \\\\\\ &T = 2\\pi \\sqrt{\\frac{L}{g}} \\\\\\ &\\text{where } T \\text{ is the time period, } L \\text{ is the length of the pendulum, and } g \\text{ is the acceleration due to gravity.} \\\\\\ &\\text{Given } T = 3 \\text{ s, we need to find } L. \\\\\\ &\\text{Rearrange the formula to solve for } L: \\\\\\ &L = \\frac{gT^2}{4\\pi^2} \\\\\\ &\\text{Assuming } g = 9.8 \\text{ m/s}^2, \\\\\\ &L = \\frac{9.8 \\times 3^2}{4\\pi^2} \\\\\\ &L \\approx 2.24 \\text{ m} \\\\\\ &\\text{Thus, the length of the pendulum is approximately } 2.24 \\text{ meters.} \\\\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The time period of a pendulum is the time taken for one complete oscillation.} \\\\ &\\text{If the pendulum makes 40 oscillations, and the time period of one oscillation is } T \\text{ seconds,} \\\\ &\\text{then the total time taken is given by } 40 \\times T. \\\\ &\\text{Assuming the time period } T \\text{ is known, the total time taken by the boy is } 40T \\text{ seconds.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{A 24-hour clock describes time using a continuous count of hours from 0 to 23.} \\\\ &\\text{This means that midnight is represented as 00:00 and the last minute of the day is 23:59.} \\\\ &\\text{Unlike the 12-hour clock, it does not use AM or PM to differentiate between morning and evening.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The two organizations that commonly use a 24-hour clock system are the military and hospitals.} \\\\ &\\text{The military uses the 24-hour clock to avoid confusion between AM and PM times, which is crucial for operations that require precise timing.} \\\\ &\\text{Hospitals use the 24-hour clock to ensure accurate scheduling of medical procedures and medication administration, reducing the risk of errors.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The given time is 09:45 in 24-hour format.} \\\\ &\\text{Since 9 is less than 12, the time remains the same in 12-hour format.} \\\\ &\\text{Therefore, 09:45 in 24-hour format is 9:45 AM in 12-hour format.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{The given time is 22:30 in a 24-hour format.} \\\\\\ &\\text{To convert it to a 12-hour format, subtract 12 from the hour:} \\\\\\ &22 - 12 = 10. \\\\\\ &\\text{Thus, the time in a 12-hour format is 10:30 PM.} \\end{aligned}']
['\\begin{aligned} &\\text{The 12-hour clock system divides the day into two periods: AM and PM.} \\\\ &\\text{Each period consists of 12 hours, starting from 12 and ending at 11.} \\\\ &\\text{This system repeats every 12 hours, making a full day 24 hours long.} \\\\ \\end{aligned}']
["\\begin{aligned} &\\text{The indications 'a.m.' and 'p.m.' on a 12-hour clock represent the two halves of a day.} \\\\ &\\text{'a.m.' stands for 'ante meridiem', which means before midday, referring to the time from midnight to noon.} \\\\ &\\text{'p.m.' stands for 'post meridiem', which means after midday, referring to the time from noon to midnight.} \\\\ \\end{aligned}"]
['\\begin{aligned} &\\text{For part (i), 4:45 p.m. is converted by adding 12 to the hour:} \\\\ &4 + 12 = 16 \\\\ &\\text{Thus, 4:45 p.m. is 16:45 in a 24-hour clock.} \\\\ &\\text{For part (ii), 8:20 a.m. remains the same as it is already in the morning:} \\\\ &\\text{Thus, 8:20 a.m. is 08:20 in a 24-hour clock.} \\end{aligned}']
['\\begin{aligned} &\\text{To convert temperatures from Celsius to Kelvin, we use the formula:} \\\\ &\\text{Kelvin} = \\text{Celsius} + 273.15. \\\\ &\\text{(i) For 25°C:} \\\\ &\\text{Kelvin} = 25 + 273.15 = 298.15 \\\\ &\\text{(ii) For -10°C:} \\\\ &\\text{Kelvin} = -10 + 273.15 = 263.15 \\\\ &\\text{Thus, the temperatures in Kelvin are 298.15 K and 263.15 K respectively.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{To convert temperatures from Kelvin to Celsius, we use the formula:} \\\\ &C = K - 273.15 \\\\ &\\text{(i) For 300 K:} \\\\ &C = 300 - 273.15 = 26.85 \\\\ &\\text{Thus, 300 K is equal to 26.85} \\degree C. \\\\ &\\text{(ii) For 250 K:} \\\\ &C = 250 - 273.15 = -23.15 \\\\ &\\text{Thus, 250 K is equal to -23.15} \\degree C. \\\\ \\end{aligned}']
['\\begin{aligned} & \\text{To determine which piece of cloth is rougher without any tools, you can use your sense of touch. By feeling the surface of each cloth, you can compare their textures. The cloth that feels more abrasive or coarse to your fingers is the rougher one. This method relies on the tactile feedback your skin provides, which can effectively distinguish between different surface textures.} \\end{aligned}']
["\\begin{aligned} & \\text{To estimate the amount of sugar to add to milk to make it sweet according to your taste, you can use a balance to measure the mass of sugar.} \\\\ & \\text{First, decide the level of sweetness you prefer based on previous experiences.} \\\\ & \\text{Then, use a beam balance or an electronic balance to measure the mass of sugar.} \\\\ & \\text{Add the measured sugar to the milk and taste it. If it's not sweet enough, gradually add more sugar, measuring each time, until the desired sweetness is achieved.} \\\\ & \\text{This method ensures that you can consistently achieve the same level of sweetness each time.} \\\\ \\end{aligned}"]
['\\begin{aligned} & \\text{Estimations are typically made in situations where precise measurements are either not possible or not necessary.} \\\\ & \\text{For example, when measuring the length of a large object like a room or a field, it might be more practical to estimate the length rather than measure it exactly.} \\\\ & \\text{Similarly, in everyday life, we often estimate time, distance, or quantity when exact values are not required.} \\\\ & \\text{Estimations help in making quick decisions and are useful in situations where a rough idea is sufficient.} \\\\ \\end{aligned}']
['\\begin{aligned} & \\text{Estimations are often made using tools like rulers, measuring tapes, and clocks.} \\\\ & \\text{For length, a ruler or measuring tape is commonly used to estimate the distance between two points.} \\\\ & \\text{These tools provide a quick way to approximate measurements without needing precise instruments.} \\\\ & \\text{Similarly, for time, a clock or stopwatch helps in estimating the duration of events.} \\\\ \\end{aligned}']
['\\begin{aligned} & \\text{To calculate the average pulse rate, you need to add up all the pulse rates recorded in the class and then divide this sum by the total number of students. This gives you the mean pulse rate.} \\\\\\ & \\text{Mathematically, it can be expressed as:} \\\\\\ & \\quad \\text{Average Pulse Rate} = \\frac{\\text{Sum of all pulse rates}}{\\text{Number of students}} \\\\\\ & \\text{To find the range of pulse rates, identify the highest and lowest pulse rates in the class. The range is the difference between these two values.} \\\\\\ & \\text{Mathematically, it can be expressed as:} \\\\\\ & \\quad \\text{Range} = \\text{Highest Pulse Rate} - \\text{Lowest Pulse Rate} \\end{aligned}']
['\\begin{aligned} &\\text{Given the dimensions of the cardboard, first calculate the area in } \\ \\text{cm}^2. \\\\ &\\text{Suppose the length is } l \\ \\text{cm and the width is } w \\ \\text{cm.} \\\\ &\\text{Area in } \\ \\text{cm}^2 = l \\times w. \\\\ &\\text{To convert this area to } \\ \\text{mm}^2, \\text{ use the conversion:} \\\\ &1 \\ \\text{cm}^2 = 100 \\ \\text{mm}^2. \\\\ &\\text{Area in } \\ \\text{mm}^2 = (l \\times w) \\times 100. \\\\ &\\text{To convert the area to } \\ \\text{m}^2, \\text{ use the conversion:} \\\\ &1 \\ \\text{m}^2 = 10,000 \\ \\text{cm}^2. \\\\ &\\text{Area in } \\ \\text{m}^2 = \\frac{l \\times w}{10,000}. \\end{aligned}']

In [27]:
# Define the prompt template for generating misconceptions
prompt_template = PromptTemplate(
    input_variables=["system_prompt","topic", "topic_id", "question", "hint", "solution"],
    template="{system_prompt}\n\nGenerate one correct option and appropriate incorrect options in latex using given solution, hint, and misconceptions for the given question.\n\nTopic ID: {topic_id}\nTopic: {topic}\nQuestion: {question}\nHint: {hint}\nSolution: {solution}\n\nReturn the output in the specified JSON format."
)

# Extract relevant information from the 'explanation' column

def extract_explanation_details(explanation):
    try:
        explanation_data = json.loads(explanation)
        hint = explanation_data.get('hint', 'No hint available')
        solution = explanation_data.get('solution', 'No solution available')
        return hint, solution
    except json.JSONDecodeError:
        return 'No hint available', 'No solution available'

# Function to generate misconceptions-based incorrect options

def generate_incorrect_options(row):

    chain = LLMChain(llm=llm, prompt=prompt_template)
    try:
        response = chain.run(
            system_prompt=DISTRACTOR_SYSTEM_PROMPT,
            topic=row['topic'],
            topic_id=row['topic_id'],
            question=row['question'],
            hint=row['hint'],
            solution=row['solution']
        )
        # if response.strip().startswith("```json"):
        #     response = response.strip().strip("```json").strip("```").strip()
        return response
    except Exception as e:
        print(f"Unexpected error: {str(e)}")
        return None

# Apply the function to generate misconceptions-based incorrect options for each question
misconception_options = []
def loopForDistractor(data):
    distractor_counter = 0
    retries_counter = 0
    maxCounter = len(data)
    while distractor_counter<maxCounter:
        row = data.loc[distractor_counter]
        print(f"Processing question {distractor_counter + 1} out of {len(data)}")
        misconception_option = generate_incorrect_options(row)
        parsed_response = parse_Response(misconception_option)

        if parsed_response:
            # misconception_options.append(parsed_response)
            # row['misconception_options'] = parsed_response
            # print(distractor_counter)
            # print(data.loc[distractor_counter , 'misconception_options'])
            # print(parsed_response)

            data.loc[distractor_counter , 'misconception_options'] =[parsed_response]
            distractor_counter += 1
            retries_counter = 0
        else:
            print(f"Failed to parse response or generate distractors for question {distractor_counter + 1}, retrying...")
            retries_counter += 1
        if retries_counter == 3:
            # misconception_option.append("")
            data.loc[distractor_counter , 'misconception_options'] = ""
            distractor_counter += 1

loopForDistractor(data)
# data['misconception_options'] = misconception_options

Processing question 1 out of 121
Processing question 2 out of 121
Processing question 3 out of 121
Processing question 4 out of 121
Processing question 5 out of 121
Processing question 6 out of 121
Processing question 7 out of 121
Processing question 8 out of 121
Processing question 9 out of 121
Processing question 10 out of 121
Processing question 11 out of 121
Processing question 12 out of 121
Processing question 13 out of 121
Processing question 14 out of 121
Processing question 15 out of 121
Processing question 16 out of 121
Processing question 17 out of 121
Processing question 18 out of 121
Processing question 19 out of 121
Processing question 20 out of 121
Processing question 21 out of 121
Processing question 22 out of 121
Processing question 23 out of 121
Processing question 24 out of 121
Processing question 25 out of 121
Processing question 26 out of 121
Processing question 27 out of 121
Processing question 28 out of 121
Processing question 29 out of 121
Processing question 30 out of 121
Processing question 31 out of 121
Processing question 32 out of 121
Processing question 33 out of 121
Processing question 34 out of 121
Processing question 35 out of 121
Processing question 36 out of 121
Processing question 37 out of 121
Processing question 38 out of 121
Processing question 39 out of 121
Processing question 40 out of 121
Processing question 41 out of 121
Processing question 42 out of 121
Processing question 43 out of 121
Processing question 44 out of 121
Processing question 45 out of 121
Processing question 46 out of 121
Processing question 47 out of 121
Processing question 48 out of 121
Processing question 49 out of 121
Processing question 50 out of 121
Processing question 51 out of 121
Processing question 52 out of 121
Processing question 53 out of 121
Processing question 54 out of 121
Processing question 55 out of 121
Processing question 56 out of 121
Processing question 57 out of 121
Processing question 58 out of 121
Processing question 59 out of 121
Processing question 60 out of 121
Processing question 61 out of 121
Processing question 62 out of 121
Processing question 63 out of 121
Processing question 64 out of 121
Processing question 65 out of 121
Processing question 66 out of 121
Processing question 67 out of 121
Processing question 68 out of 121
Processing question 69 out of 121
Processing question 70 out of 121
Processing question 71 out of 121
Processing question 72 out of 121
Processing question 73 out of 121
Processing question 74 out of 121
Processing question 75 out of 121
Processing question 76 out of 121
Processing question 77 out of 121
Processing question 78 out of 121
Processing question 79 out of 121
Processing question 80 out of 121
Processing question 81 out of 121
Processing question 82 out of 121
Processing question 83 out of 121
Processing question 84 out of 121
Processing question 85 out of 121
Processing question 86 out of 121
Processing question 87 out of 121
Processing question 88 out of 121
Processing question 89 out of 121
Processing question 90 out of 121
Processing question 91 out of 121
Processing question 92 out of 121
Processing question 93 out of 121
Processing question 94 out of 121
Processing question 95 out of 121
Processing question 96 out of 121
Processing question 97 out of 121
Processing question 98 out of 121
Processing question 99 out of 121
Processing question 100 out of 121
Processing question 101 out of 121
Processing question 102 out of 121
Processing question 103 out of 121
Processing question 104 out of 121
Processing question 105 out of 121
Processing question 106 out of 121
Processing question 107 out of 121
Processing question 108 out of 121
Processing question 109 out of 121
Processing question 110 out of 121
Processing question 111 out of 121
Processing question 112 out of 121
Processing question 113 out of 121
Processing question 114 out of 121
Processing question 115 out of 121
Processing question 116 out of 121
Processing question 117 out of 121
Processing question 118 out of 121
Processing question 119 out of 121
Processing question 120 out of 121
Processing question 121 out of 121

In [28]:
for i in range(len(data)):
    print(data['misconception_options'][i])

[{'correct_option': '\\begin{aligned} &\\quad 3.84 \\mathrm{~m}^3 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\quad 3.84 \\mathrm{~cm}^3 \\end{aligned}', 'rationale': '\\begin{aligned} &\\quad \\text{Confused the units by not converting all dimensions to meters before calculating volume.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\quad 38.4 \\mathrm{~m}^3 \\end{aligned}', 'rationale': '\\begin{aligned} &\\quad \\text{Forgot to correctly multiply the dimensions, leading to an incorrect volume calculation.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\quad 3.2 \\mathrm{~m}^3 \\end{aligned}', 'rationale': '\\begin{aligned} &\\quad \\text{Ignored converting the height from centimeters to meters, using incorrect dimensions.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} & \\text{1200} \\ \\mathrm{cm}^{3} \\ \\text{or} \\ 0.0012 \\ \\mathrm{m}^{3} \\end{aligned}', 'option1': {'option': '\\begin{aligned} & \\text{600} \\ \\mathrm{cm}^{3} \\ \\text{or} \\ 0.0006 \\ \\mathrm{m}^{3} \\end{aligned}', 'rationale': '\\begin{aligned} & \\text{Confused the conversion by dividing by} \\ 2 \\ \\text{instead of calculating the full volume.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} & \\text{1200} \\ \\mathrm{cm}^{3} \\ \\text{or} \\ 0.012 \\ \\mathrm{m}^{3} \\end{aligned}', 'rationale': '\\begin{aligned} & \\text{Forgot to divide by} \\ 10^6 \\ \\text{correctly when converting to} \\ \\mathrm{m}^{3}. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} & \\text{2400} \\ \\mathrm{cm}^{3} \\ \\text{or} \\ 0.0024 \\ \\mathrm{m}^{3} \\end{aligned}', 'rationale': '\\begin{aligned} & \\text{Ignored the correct dimensions, doubling the volume calculation.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &10 \\ \\mathrm{cm}^{3} \\ \\text{or} \\ 10^{-5} \\ \\mathrm{m}^{3} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &10 \\ \\mathrm{cm}^{3} \\ \\text{or} \\ 10^{-6} \\ \\mathrm{m}^{3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the conversion factor by dividing by } 10^{7} \\ \\text{instead of } 10^{6}. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &20 \\ \\mathrm{cm}^{3} \\ \\text{or} \\ 2 \\times 10^{-5} \\ \\mathrm{m}^{3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to subtract the initial water level from the final water level.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &5 \\ \\mathrm{cm}^{3} \\ \\text{or} \\ 5 \\times 10^{-6} \\ \\mathrm{m}^{3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct difference by mistakenly using } 30 \\ \\mathrm{mL} \\ \\text{instead of } 10 \\ \\mathrm{mL}. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} & 400\\pi \\text{ square meters} \\end{aligned}', 'option1': {'option': '\\begin{aligned} & 200\\pi \\text{ square meters} \\end{aligned}', 'rationale': '\\begin{aligned} & \\text{Confused the radius with the diameter, using } r = 40 \\text{ instead of } r = 20. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} & 800\\pi \\text{ square meters} \\end{aligned}', 'rationale': '\\begin{aligned} & \\text{Forgot to divide the diameter by 2, using } r = 40 \\text{ instead of } r = 20. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} & 100\\pi \\text{ square meters} \\end{aligned}', 'rationale': '\\begin{aligned} & \\text{Ignored squaring the radius, calculating } \\pi \\times 20 \\text{ instead of } \\pi \\times 20^2. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{7 g cm}^{-3} \\text{ and } 7000 \\text{ kg m}^{-3} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{7 g cm}^{-3} \\text{ and } 700 \\text{ kg m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to convert volume correctly from cm}^3 \\text{ to m}^3, leading to an incorrect density in kg m}^{-3}. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{21 g cm}^{-3} \\text{ and } 21000 \\text{ kg m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the division in the density formula, using mass directly as density.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{0.7 g cm}^{-3} \\text{ and } 7000 \\text{ kg m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct mass-to-volume ratio, leading to an incorrect density in g cm}^{-3}. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} & \\text{2625} \\mathrm{~g} \\end{aligned}', 'option1': {'option': '\\begin{aligned} & \\text{2500} \\mathrm{~g} \\end{aligned}', 'rationale': '\\begin{aligned} & \\text{Forgot to multiply the density by the volume correctly, leading to an underestimated mass.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} & \\text{2630} \\mathrm{~g} \\end{aligned}', 'rationale': '\\begin{aligned} & \\text{Confused by rounding errors or miscalculation during multiplication.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} & \\text{1050} \\mathrm{~g} \\end{aligned}', 'rationale': '\\begin{aligned} & \\text{Ignored the correct multiplication and used density value as mass.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\quad 66.67 \\text{ cm}^3 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\quad 54 \\text{ cm}^3 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the division operation by multiplying mass and density instead of dividing.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\quad 60 \\text{ cm}^3 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the density formula correctly, using mass as volume directly.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\quad 72 \\text{ cm}^3 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct density value, using an incorrect density in calculations.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &1 \\quad \\mathrm{g} \\mathrm{cm}^{-3} \\quad \\text{and} \\quad 1000 \\quad \\mathrm{kg} \\mathrm{m}^{-3} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &0.1 \\quad \\mathrm{g} \\mathrm{cm}^{-3} \\quad \\text{and} \\quad 100 \\quad \\mathrm{kg} \\mathrm{m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the conversion factor between} \\quad \\mathrm{cm}^{3} \\quad \\text{and} \\quad \\mathrm{m}^{3}. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &10 \\quad \\mathrm{g} \\mathrm{cm}^{-3} \\quad \\text{and} \\quad 10000 \\quad \\mathrm{kg} \\mathrm{m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to divide by the correct volume conversion factor.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &0.01 \\quad \\mathrm{g} \\mathrm{cm}^{-3} \\quad \\text{and} \\quad 10 \\quad \\mathrm{kg} \\mathrm{m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct mass to volume ratio in calculations.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{202.5 kg} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{180 kg} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the calculation by using an incorrect volume or density value.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{225 kg} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to multiply the correct density with the calculated volume.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{250 kg} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct density value, using a rounded or incorrect figure.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &10 \\ \\ &\\text{mL} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &12 \\ \\ &\\text{mL} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the initial water level with the volume of the copper piece.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &22 \\ \\ &\\text{mL} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to subtract the initial water level from the final water level.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &32 \\ \\ &\\text{mL} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Added the initial and final water levels instead of finding the difference.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &9 \\quad \\text{g/mL} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &10 \\quad \\text{g/mL} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the division by using the volume as 9 instead of 10, leading to an incorrect density calculation.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &8 \\quad \\text{g/mL} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly divide the mass by the volume, possibly using an incorrect mass value.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &11 \\quad \\text{g/mL} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct volume and used a higher volume value, resulting in a higher density.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{400}{6} \\mathrm{~m} \\mathrm{s}^{-1} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{4000}{60} \\mathrm{~m} \\mathrm{s}^{-1} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to simplify the fraction, leading to an unsimplified answer.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &66.67 \\mathrm{~m} \\mathrm{s}^{-1} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the exact fraction with its approximate decimal form.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{400}{60} \\mathrm{~m} \\mathrm{s}^{-1} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct simplification of the fraction.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &11.11 \\quad \\mathrm{m} \\mathrm{s}^{-1} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &10.00 \\quad \\mathrm{m} \\mathrm{s}^{-1} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the conversion factor by using } \\quad 1 \\mathrm{~h} = 3000 \\mathrm{~s} \\quad \\text{instead of } \\quad 3600 \\mathrm{~s}. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &12.50 \\quad \\mathrm{m} \\mathrm{s}^{-1} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to divide by 3600, using } \\quad 1 \\mathrm{~h} = 3000 \\mathrm{~s} \\quad \\text{instead.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &13.33 \\quad \\mathrm{m} \\mathrm{s}^{-1} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct multiplication factor, using } \\quad 1 \\mathrm{~km} = 1100 \\mathrm{~m}. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &12.5 \\quad \\text{m/s} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &50 \\quad \\text{m/s} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the conversion by not converting hours to seconds correctly, leading to a larger speed value.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &5 \\quad \\text{m/s} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to convert kilometers to meters, resulting in a smaller speed value.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &18 \\quad \\text{m/s} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the conversion of time from hours to seconds, using minutes instead.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{1}{9} \\quad \\text{hours} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{1}{8} \\quad \\text{hours} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the division by using 16 instead of 18, leading to an incorrect simplification.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{1}{10} \\quad \\text{hours} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly simplify the fraction, using 20 instead of 18 in the denominator.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{2}{9} \\quad \\text{hours} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct formula by doubling the numerator, leading to an incorrect result.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\quad 30 \\text{ km} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\quad 60 \\text{ km} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the time conversion, using 1 hour instead of 0.5 hours for calculation.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\quad 15 \\text{ km} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to multiply the speed by the correct time in hours, using 0.25 hours instead.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\quad 45 \\text{ km} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct time conversion, using 0.75 hours instead of 0.5 hours.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{Body B has a higher speed.} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{Body A has a higher speed.} \\end{aligned}', 'rationale': "\\begin{aligned} &\\text{Confused the conversion of units for body A's speed, leading to an incorrect comparison.} \\end{aligned}"}, 'option2': {'option': '\\begin{aligned} &\\text{Both bodies have the same speed.} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the calculation differences and assumed equal speeds without computation.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{Body A has a speed of 40 m/s.} \\end{aligned}', 'rationale': "\\begin{aligned} &\\text{Forgot to correctly calculate body A's speed, leading to a miscalculation.} \\end{aligned}"}}]
[{'correct_option': '\\begin{aligned} &\\text{True} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{False} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the S.I. unit of volume with a non-standard unit, like liters.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{Partially true} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood that cubic meter is only partially correct, not fully.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{Depends on context} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the standardization of S.I. units, thinking context changes the unit.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{250 mL} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{300 mL} \\end{aligned}', 'rationale': "\\begin{aligned} &\\text{Confused the beaker's capacity with a larger volume it cannot measure.} \\end{aligned}"}, 'option2': {'option': '\\begin{aligned} &\\text{200 mL} \\end{aligned}', 'rationale': "\\begin{aligned} &\\text{Ignored the maximum capacity and underestimated the beaker's limit.} \\end{aligned}"}, 'option3': {'option': '\\begin{aligned} &\\text{500 mL} \\end{aligned}', 'rationale': "\\begin{aligned} &\\text{Misunderstood the beaker's capacity as being able to measure beyond its limit.} \\end{aligned}"}}]
[{'correct_option': '\\begin{aligned} &\\text{True} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{False} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the conversion factor between } \\mathrm{cm}^{2} \\text{ and } \\mathrm{m}^{2}, \\text{ leading to the incorrect conclusion that } \\mathrm{cm}^{2} \\text{ is larger.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{Equal} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot that } 1 \\mathrm{m}^{2} = 10000 \\mathrm{cm}^{2}, \\text{ mistakenly thinking the units are equivalent.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{Not comparable} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the standard conversion between } \\mathrm{cm}^{2} \\text{ and } \\mathrm{m}^{2}, \\text{ assuming they cannot be compared.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{False} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{True} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the concept of density with volume, assuming equal volumes imply equal masses.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{Sometimes true} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the role of density, thinking it might occasionally result in equal masses.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{Depends on the substances} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood the relationship between density and mass, thinking it varies by substance.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\mathrm{kg} \\mathrm{m}^{-3} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\mathrm{g} \\mathrm{cm}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the S.I. unit with the cgs unit of density, which is } \\mathrm{g} \\mathrm{cm}^{-3}. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\mathrm{kg} \\mathrm{cm}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot that the S.I. unit of volume is cubic meter, not cubic centimeter.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\mathrm{g} \\mathrm{m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct unit of mass in the S.I. system, which is kilogram, not gram.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{1000 } \\mathrm{kg} \\mathrm{~m}^{-3} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{1 } \\mathrm{kg} \\mathrm{~m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the conversion factor for grams to kilograms, leading to an incorrect density value.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{10 } \\mathrm{kg} \\mathrm{~m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to convert cubic centimeters to cubic meters correctly, resulting in a lower density.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{100 } \\mathrm{kg} \\mathrm{~m}^{-3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct conversion of volume units, leading to a tenfold error in density.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &4 \\degree \\text{C} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &0 \\degree \\text{C} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the freezing point of water with the temperature of maximum density.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &100 \\degree \\text{C} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the fact that water is in gaseous state at this temperature, not maximum density.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &10 \\degree \\text{C} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood the temperature range where water density is relatively high but not maximum.} \\end{aligned}'}}]

### Output Formatting & Pushing into the DB

In [28]:
# Function to process each row and extract required fields
def process_row(row, index):
    try:
        misconception_data = row["misconception_options"]
        # Extract topic, question, and solution details
        topic_id = row["topic_id"]
        topic_name = row["topic"]
        question = row["question"]
        hint = row["hint"]
        explanation = row["solution"]
        # correct_answer = row["final_answer"]
        chapter = conf_data['chapter_name']

        # Extract option and rationale details
        options = {}
        for i in range(1, 4):  # Assuming there are 4 options for each question
            options["correct_answer"] = misconception_data[0]["correct_option"]
            option_key = f'option{i}'
            option_info = misconception_data[0][option_key]
            options[f'option{i}'] = option_info.get('option', '')
            options[f'dr{i}'] = option_info.get('rationale', '')
        
        # Construct the final JSON structure
        start = "\\begin{aligned}"
        end = "\\end{aligned}"
        
        combined_data = {
            'topic_id': topic_id,
            'topic_name': topic_name,
            'grade' : conf_data['grade'],
            'board' : "ICSE",
            
            'subject' : subject,
            'chapter_name' : chapter,
            'publication' : conf_data['publication'],
            'question': [{"content": question}],
            # if (str(question).startswith("\\begin{aligned}") and str(question).endswith("\\end{aligned}")) else [{"content": start + question + end}],

            'hint': [{"content": hint}],
            # if (str(hint).startswith("\\begin{aligned}") and str(hint).endswith("\\end{aligned}")) else [{"content": start + hint + end}],

            'solution': [{"content": explanation}],
            # if (str(explanation).startswith("\\begin{aligned}") and str(explanation).endswith("\\end{aligned}")) else [{"content": start + explanation + end}],

            'final_answer': [{"content": options.get('correct_answer', '')}],
            # if (str(options.get('correct_answer', '')).startswith("\\begin{aligned}") and str(options.get('correct_answer', '')).endswith("\\end{aligned}")) else [{"content": start + options.get('correct_answer', '') + end}],

            'option1': [{"content": options.get('option1', '')}],
            # if (str(options.get('option1')).startswith("\\begin{aligned}") and str(options.get('option1')).endswith("\\end{aligned}")) else [{"content": start + str(options.get('option1', '')) + end} ],
            'dr1': [{"content": options.get('dr1', '')}],
            'option2': [{"content": options.get('option2', '')}],
            # if (str(options.get('option2')).startswith("\\begin{aligned}") and str(options.get('option2')).endswith("\\end{aligned}")) else [{"content": start + str(options.get('option2', '')) + end}],
            'dr2': [{"content": options.get('dr2', '')}],
            'option3': [{"content": options.get('option3', '')}],
            # if (str(options.get('option3')).startswith("\\begin{aligned}") and str(options.get('option3')).endswith("\\end{aligned}")) else [{"content": start + str(options.get('option3', '')) + end}],
            'dr3': [{"content": options.get('dr3', '')}]


        }

        return combined_data
    except Exception as e:
        # If there is an error, return an empty structure with an error message
        return {
            'topic_id': row.get('topic_id', f"Topic {index + 1}"),
            'error': f"Exception Occurred: {type(e).__name__} – {e} \n {traceback.format_exc()}"
        }

# Process all rows in the dataframe
final_output = [process_row(row, idx) for idx, row in data.iterrows()]
final_output[2]

{'topic_id': '6_physics_physical quantities and measurement_1',
 'topic_name': 'Measurement of Length',
 'grade': '6',
 'board': 'ICSE',
 'subject': 'physics',
 'chapter_name': 'Physical Quantities and Measurement',
 'publication': 'goyal',
 'question': [{'content': '\\begin{aligned} &\\text{Why is it important to have standard units for measurement?} \\end{aligned}'}],
 'hint': [{'content': '\\begin{aligned} &\\text{Consider how having a common standard for measurement helps in ensuring consistency and accuracy across different regions and fields.} \\\\ &\\text{Think about the difficulties that might arise if everyone used different units for the same quantity.} \\\\ \\end{aligned}'}],
 'solution': [{'content': '\\begin{aligned} &\\text{Standard units of measurement are crucial because they provide a consistent framework for communication and comparison.} \\\\ &\\text{Without standard units, it would be challenging to compare measurements accurately, as different regions might use different units.} \\\\ &\\text{This consistency is essential in scientific research, trade, and daily life to ensure that measurements are understood universally.} \\\\ \\end{aligned}'}],
 'final_answer': [{'content': '\\begin{aligned} &\\text{Ensure consistency and accuracy} \\end{aligned}'}],
 'option1': [{'content': '\\begin{aligned} &\\text{Allow for personal interpretation} \\end{aligned}'}],
 'dr1': [{'content': '\\begin{aligned} &\\text{Confused the need for standardization with flexibility, which would lead to inconsistency.} \\end{aligned}'}],
 'option2': [{'content': '\\begin{aligned} &\\text{Facilitate regional variations} \\end{aligned}'}],
 'dr2': [{'content': '\\begin{aligned} &\\text{Ignored that standard units aim to eliminate regional differences, not support them.} \\end{aligned}'}],
 'option3': [{'content': '\\begin{aligned} &\\text{Promote individual measurement systems} \\end{aligned}'}],
 'dr3': [{'content': '\\begin{aligned} &\\text{Misunderstood that standard units are meant to unify, not diversify measurement systems.} \\end{aligned}'}]}

In [29]:
final_output

[{'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{If a thin copper wire is wound around a pencil to form a coil with 25 turns, and the length of the coil is measured to be 2 cm, what is the diameter of the wire?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{To find the diameter of the wire, consider the total length of the coil and the number of turns.} \\\\ &\\text{The length of the coil is the product of the number of turns and the circumference of the wire.} \\\\ &\\text{Use the formula for circumference to find the diameter.} \\\\ \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{The length of the coil is given as 2 cm, and there are 25 turns.} \\\\ &\\text{The length of the coil is equal to the number of turns multiplied by the circumference of the wire.} \\\\ &\\text{Let } d \\text{ be the diameter of the wire. The circumference of the wire is } \\pi d. \\\\ &\\text{Thus, the total length of the coil is } 25 \\times \\pi d = 2 \\text{ cm.} \\\\ &\\text{Solving for } d, \\text{ we have:} \\\\ &\\pi d = \\frac{2}{25} \\\\ &d = \\frac{2}{25 \\pi} \\\\ &\\text{Therefore, the diameter of the wire is } \\frac{2}{25 \\pi} \\text{ cm.} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\frac{2}{25 \\pi} \\text{ cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\frac{2}{25} \\text{ cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Forgot to include } \\pi \\text{ in the denominator, leading to an incorrect calculation of the diameter.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\frac{25}{2 \\pi} \\text{ cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Confused the roles of the numerator and denominator, reversing the fraction incorrectly.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\frac{2 \\pi}{25} \\text{ cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the correct placement of } \\pi \\text{, placing it in the numerator instead of the denominator.} \\end{aligned}'}]},
 {'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{Which of the following were early units of measurement for length?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Think about the historical methods people used to measure length before modern units like meters were established.} \\\\ &\\text{Consider units that were based on human body parts or everyday objects.} \\\\ \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{In ancient times, people used various units of measurement for length based on familiar objects or body parts.} \\\\ &\\text{Some of these early units included the cubit, which was the length of the forearm from the elbow to the tip of the middle finger, and the foot, which was based on the length of a human foot.} \\\\ &\\text{These units were not standardized and varied from place to place, but they were practical for everyday use.} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{Cubit and foot} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{Meter and yard} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused modern units with historical ones, as meters and yards are standardized units developed later.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{Inch and centimeter} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that centimeters are part of the metric system, which was not used in ancient times.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{Hand and meter} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored that meters are modern units, while hands were used historically for measuring horses.} \\end{aligned}'}]},
 {'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{Why is it important to have standard units for measurement?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Consider how having a common standard for measurement helps in ensuring consistency and accuracy across different regions and fields.} \\\\ &\\text{Think about the difficulties that might arise if everyone used different units for the same quantity.} \\\\ \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Standard units of measurement are crucial because they provide a consistent framework for communication and comparison.} \\\\ &\\text{Without standard units, it would be challenging to compare measurements accurately, as different regions might use different units.} \\\\ &\\text{This consistency is essential in scientific research, trade, and daily life to ensure that measurements are understood universally.} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{Ensure consistency and accuracy} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{Allow for personal interpretation} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the need for standardization with flexibility, which would lead to inconsistency.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{Facilitate regional variations} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored that standard units aim to eliminate regional differences, not support them.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{Promote individual measurement systems} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Misunderstood that standard units are meant to unify, not diversify measurement systems.} \\end{aligned}'}]},
 {'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{What are the standard international units of measurement, and what is the unit of length in this system?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{The International System of Units (SI) is the standard for measurement worldwide. Consider the basic unit used for measuring length in this system.} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{The International System of Units (SI) is the globally accepted system for measurement. It includes seven base units for different physical quantities.} \\\\\\ &\\text{The unit of length in the SI system is the meter (m). This unit is used to measure the distance between two points.} \\\\\\ &\\text{The meter is defined by the distance light travels in a vacuum in 1/299,792,458 of a second.} \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{Meter (m)} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{Kilogram (kg)} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the unit of mass with the unit of length in the SI system.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{Second (s)} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that second is the unit of time, not length, in the SI system.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{Liter (L)} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored that liter is a unit of volume, not length, in the SI system.} \\end{aligned}'}]},
 {'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{How is the term metre defined, and what are one multiple and two submultiples of metre?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Think about the definition of a metre and its relation to other units of length. Consider the prefixes used for multiples and submultiples of metre.} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{The metre is defined as the distance travelled by light in vacuum in } \\quad \\text{1/299,792,458 of a second.} \\\\\\ &\\text{One multiple of a metre is a kilometre, which is equal to 1000 metres.} \\\\\\ &\\text{Two submultiples of a metre are a centimetre and a millimetre.} \\\\\\ &\\text{A centimetre is } \\quad \\text{1/100 of a metre, and a millimetre is } \\quad \\text{1/1000 of a metre.} \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{Metre is defined by the distance light travels in vacuum in } \\quad \\text{1/299,792,458 of a second.} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{Metre is defined as the length of a pendulum with a period of 1 second.} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the definition of metre with a historical definition related to pendulums.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{Metre is defined as the length of a path travelled by sound in air in 1 second.} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that the definition of metre is based on the speed of light, not sound.} \\end{aligned}'}],
  'option3': [{'content': "\\begin{aligned} &\\text{Metre is defined as the distance between two points on Earth's surface.} \\end{aligned}"}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the modern definition and confused it with a geodetic measurement.} \\end{aligned}'}]},
 {'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{Which position of the eye records the accurate length of a pencil, and what is the magnitude of this length?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{To measure the accurate length of a pencil, ensure your eye is directly in line with the end of the pencil to avoid parallax error.} \\\\ &\\text{Consider the units of length typically used in measurements.} \\\\ \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{The accurate length of a pencil is recorded when the eye is positioned directly perpendicular to the scale at the point of measurement.} \\\\ &\\text{This position helps avoid parallax error, which occurs when the eye is not aligned with the measurement mark, leading to inaccurate readings.} \\\\ &\\text{The magnitude of the length is determined by reading the scale where the pencil ends, typically measured in centimeters (cm) or millimeters (mm).} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{Eye perpendicular, 15 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{Eye at angle, 15 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the correct eye position with an angled view, which can cause parallax error.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{Eye perpendicular, 10 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot the correct length measurement, assuming a shorter length than actual.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{Eye at angle, 10 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored both the correct eye position and length, leading to a compounded error.} \\end{aligned}'}]},
 {'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{What are two characteristics of a standard unit for measuring a physical quantity?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Consider the characteristics that make a unit reliable and consistent for measuring a physical quantity. Think about what makes a unit universally acceptable and easy to use.} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{A standard unit for measuring a physical quantity should have two main characteristics: it should be universally accepted and invariable.} \\\\ &\\text{Universally accepted means that the unit should be recognized and used globally, ensuring consistency in measurements across different regions.} \\\\ &\\text{Invariable means that the unit should not change over time or with environmental conditions, ensuring reliability and accuracy in measurements.} \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{Universally accepted and invariable} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{Universally accepted and variable} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the concept of invariability with variability, which would lead to unreliable measurements.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{Regionally accepted and invariable} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that a standard unit must be universally, not just regionally, accepted for consistency.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{Universally accepted and changeable} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the need for the unit to be invariable, leading to potential measurement errors over time.} \\end{aligned}'}]},
 {'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{How can you determine the length of a curved line using a thin cotton thread?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{To measure the length of a curved line, think about how you can use a flexible material to trace the curve and then measure it using a standard tool.} \\\\ &\\text{Consider the properties of a thin cotton thread and how it can be used to follow the curve.} \\\\ &\\text{Once the thread has traced the curve, how can you use a ruler to find the length?} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{To determine the length of a curved line using a thin cotton thread, first place the thread along the curve carefully, ensuring it follows the exact path of the curve.} \\\\ &\\text{Once the thread has been laid out along the entire curve, mark the points on the thread that correspond to the start and end of the curve.} \\\\ &\\text{Next, straighten the thread and measure the distance between the two marked points using a ruler.} \\\\ &\\text{This measured length on the ruler will give you the length of the curved line.} \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{Straighten the thread and measure with a ruler} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{Measure the thread directly on the curve} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the method by thinking the thread can be measured while still on the curve, ignoring the need to straighten it first.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{Use a protractor to measure the curve} \\end{aligned}'}],
  'dr2': [{'content': "\\begin{aligned} &\\text{Forgot that a protractor measures angles, not lengths, misunderstanding the tool's purpose.} \\end{aligned}"}],
  'option3': [{'content': '\\begin{aligned} &\\text{Estimate the length by eye} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the need for precision in measurement, relying on estimation instead of using a thread and ruler.} \\end{aligned}'}]},
 {'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{If four identical wooden rods placed side by side have a total thickness of 6 cm, what is the thickness of one rod, correct to two decimal places?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{To find the thickness of one rod, divide the total thickness by the number of rods.} \\\\ &\\text{This will give the thickness of a single rod.} \\\\ \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given that the total thickness of four identical rods is 6 cm.} \\\\ &\\text{To find the thickness of one rod, divide the total thickness by the number of rods:} \\\\ &\\text{Thickness of one rod} = \\frac{6 \\text{ cm}}{4} = 1.50 \\text{ cm} \\\\ &\\text{Therefore, the thickness of one rod is 1.50 cm, correct to two decimal places.} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &1.50\\quad\\text{cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &1.25\\quad\\text{cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the division by using 5 rods instead of 4, leading to an incorrect thickness.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &1.75\\quad\\text{cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to divide the total thickness correctly, assuming a larger thickness per rod.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &1.00\\quad\\text{cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the correct division and assumed an even distribution of thickness.} \\end{aligned}'}]},
 {'topic_id': '6_physics_physical quantities and measurement_1',
  'topic_name': 'Measurement of Length',
  'grade': '6',
  'board': 'ICSE',
  'subject': 'physics',
  'chapter_name': 'Physical Quantities and Measurement',
  'publication': 'goyal',
  'question': [{'content': '\\begin{aligned} &\\text{When 30 coins are stacked and their total thickness is measured as 5.4 cm, what is the thickness of each coin in millimeters?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{To find the thickness of each coin, divide the total thickness by the number of coins. Remember to convert the result from centimeters to millimeters.} \\end{aligned}'}],

#### Latex Formatting to store in DB

In [30]:
from config import MONGO_URL , DB_NAME

In [31]:
dbCollection = "LatexTest"
client = AsyncIOMotorClient(MONGO_URL)

In [32]:
async def pushToDB(dbContent, subject):
    try:
        db = client[DB_NAME]
        que_collection = db[dbCollection]

        dbContent["status"] = "not_reviewed"
        dbContent["comment"] = ""
        dbContent["testFlag"] = "true"
        dbContent["subject"] = subject
        await que_collection.insert_one(dbContent)
        print("Data Uploaded to the database successfully.")
    except Exception as e:
        print("Exception Occurred: ", type(e).__name__, "–", e, "\n", traceback.format_exc())

In [33]:
for doc in final_output:
    await pushToDB(doc, subject)
client.close()

Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.