## Text Extraction, Cleaning, and Rephrasing from multiple books

In [1]:
import pandas as pd
import traceback
import json
from PyPDF2 import PdfReader
import os

from bson import ObjectId
from motor.motor_asyncio import AsyncIOMotorClient
from langchain_openai import ChatOpenAI
from langchain import PromptTemplate, LLMChain

from image_que_prompts import (
EXTRACTION_SYSTEM,
EXTRACTION_USER,
EXTRACTION_OUTPUT_FORMAT,
EMPTY_EXTRACTION_OUTPUT_FORMAT,
CLEAN_REPHRASE_USER,
CLEAN_REPHRASE_SYSTEM,
REPHRASE_OUTPUT_FORMAT,
REPHRASE_OUTPUT_EXAMPLE,
BIOLOGY_SOLUTION_SYSTEM_PROMPT,
CHEMISTRY_SOLUTION_SYSTEM_PROMPT,
MATHEMATICS_SOLUTION_SYSTEM_PROMPT,
PHYSICS_SOLUTION_SYSTEM_PROMPT,
DISTRACTOR_SYSTEM_PROMPT
)

from config import (
    OPENAI_API_KEY,
    MONGO_URL,
    DB_NAME
)

e:\Questions_extraction\cbse\image_que_prompts.py:1: SyntaxWarning: invalid escape sequence '\i'
  EXTRACTION_SYSTEM = """

In [2]:
# os.environ["LANGCHAIN_TRACING_V2"] = "true"
# os.environ["LANGCHAIN_API_KEY"] = "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"
# os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
# os.environ["LANGCHAIN_PROJECT"] = "Questions Extractor"

# Pipeline

In [3]:
import json
import re

def parse_Response(response):
    """
    Parse a JSON object from a response string or return it if it's already a dict.

    This function attempts to extract a valid JSON substring from the response,
    clean it up, and parse it into a Python dictionary. It handles cases such as:
      - Extra content or multiple JSON objects concatenated.
      - Invalid escape sequences in the JSON string.

    Args:
        response (str or dict): The response containing JSON content.

    Returns:
        dict or None: The parsed JSON object, or None if parsing fails.
    """
    # If the response is already a dictionary, return it as is.
    if isinstance(response, dict):
        return response

    # If the response is a string, try to extract and parse the JSON.
    if isinstance(response, str):
        # Use regex to extract the first substring that starts with '{' and ends with '}'
        match = re.search(r'\{.*\}', response, re.DOTALL)
        if match:
            json_str = match.group(0)
        else:
            print("No valid JSON content found in the response.")
            return None

        try:
            # Clean up the JSON string by removing newlines and unwanted characters.
            cleaned_json = json_str.replace("\n", "").replace("\(", "").replace("\)", "")
            return json.loads(cleaned_json)
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON response: {e.__class__.__name__} - {e}")
            
            # Handle "Extra data" errors (often due to multiple JSON objects concatenated).
            if str(e).startswith("Extra data"):
                # Split on a pattern like '}\n{' which may separate JSON objects.
                json_parts = re.split(r'}\s*\n\s*{', json_str)
                if json_parts:
                    first_json = json_parts[0].strip()
                    if not first_json.endswith('}'):
                        first_json += '}'
                    return parse_Response(first_json)
            
            # Handle invalid escape sequence issues.
            elif "Invalid \\escape" in str(e):
                print("Before handling escape issues:", json_str)
                # Replace problematic escape sequences with temporary placeholders.
                str1 = json_str.replace("\\\\\\\\\\", "fvback")
                str1 = str1.replace("\\\\\\\\", "frback")
                str1 = str1.replace("\\\\\\", "trlback")
                str1 = str1.replace("\\\\", "dblback")
                # Re-escape the backslashes.
                str1 = str1.replace("\\", "\\\\")
                # Restore the placeholders back to the intended escaped sequences.
                str1 = str1.replace("fvback", "\\\\\\\\\\")
                str1 = str1.replace("frback", "\\\\\\\\")
                str1 = str1.replace("trlback", "\\\\\\")
                str1 = str1.replace("dblback", "\\\\")
                strfinal = str1.replace("\n", "")
                print("After handling escape sequence issues:", strfinal)
                try:
                    return json.loads(strfinal)
                except json.JSONDecodeError as inner_e:
                    print("Still failing to parse JSON after handling escapes:", inner_e)
                    return None
            else:
                print("Actual JSON content was:", json_str)
                return None
    else:
        print("Unsupported response type:", type(response))
        return None

<>:35: SyntaxWarning: invalid escape sequence '\('
<>:35: SyntaxWarning: invalid escape sequence '\)'
<>:35: SyntaxWarning: invalid escape sequence '\('
<>:35: SyntaxWarning: invalid escape sequence '\)'
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_24708\4070082387.py:35: SyntaxWarning: invalid escape sequence '\('
  cleaned_json = json_str.replace("\n", "").replace("\(", "").replace("\)", "")
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_24708\4070082387.py:35: SyntaxWarning: invalid escape sequence '\)'
  cleaned_json = json_str.replace("\n", "").replace("\(", "").replace("\)", "")

In [4]:
# All question collection

def collect_questions_from_chapter_with_Langchain(subject, chapter_text, chapter_name, grade):
    try:
        # initialize the ChapOpenAI object
        llm = ChatOpenAI(
            model_name="gpt-4o",
            api_key= OPENAI_API_KEY,
            temperature=0.2,
        )
        # match subject:
        #     case "mathematics":
        #         examples=MATHEMATICS_EXTRACTION_OUTPUT_EXAMPLE
        #     case "biology":
        #         examples=BIOLOGY_EXTRACTION_OUTPUT_EXAMPLE
        #     case "physics":
        #         examples =PHYSICS_EXTRACTION_OUTPUT_EXAMPLE
        #     case "chemistry":
        #         examples=CHEMISTRY_EXTRACTION_OUTPUT_EXAMPLE

        #formatting prompts
        system = EXTRACTION_SYSTEM.format(" ",grade = grade, subject = subject,EMPTY_EXTRACTION_OUTPUT_FORMAT = EMPTY_EXTRACTION_OUTPUT_FORMAT, out_format = EXTRACTION_OUTPUT_FORMAT)
        user = EXTRACTION_USER.format(chapter_name = chapter_name, chapter_text = chapter_text)

        #generating response from api call
        response = llm.invoke(
            [
                ("system", system),
                ("human", user)
            ],
        )
        return response
    except Exception as e:
        print("Error with in extraction: ", type(e).__name__, "–", e, "\n", traceback.format_exc())
        return None

In [5]:
CLEAN_REPHRASE_SYSTEM.format(" ",out_example = REPHRASE_OUTPUT_EXAMPLE, out_format = REPHRASE_OUTPUT_FORMAT)

'\nYou are a helpful academic assistant who converts the valid questions with images which are in LateX format into multiple choice questions with descriptions without options and maps them to a topic from given list \nYou will be given questions with images which are in LateX format.\nImages are the part of the questions . Do not consider them seperate or consider as options. \n\nRULES for mapping ,rephrasing and  LaTeX formating:\n    - Remove the "\\includegraphics" from the questions if included.\n    - Check the given questions are in LateX format and if not convert them into LateX format  . Do not make changes in the image_ids text\n    - Do not change or generate any new questions or image ids text.\n    - Convert all questions into multiple choice questions without options. The image is part of the question and options are not always the images they are the text moslty.\n    - Rephrase the questions as questions should not be exact same as original questions . Do not change the concepts of the questions.\n    - Never start questions with like ("how.." , "what.." , "why.." etc )\n    - Never start questions with like "which images.." as options will be a text always.\n    - Only If questions has missing details or data then add the missing data or details to complete the question  Do not change the context or concept of the question and do not generate images ids. \n    - Convert each and every valid question into different types multiple choice questions without options with original latex format .\n    - Map each questions with images with a Topic from the given Topic list\n    - Always return the output in JSON\n    \n##Output format##:\nWhile returning the output make sure to:\n    (1) Use double back-slashes("\\") everywhere whenever  LaTeX code has to be written \n    (2) For question and their descriptions, Always start with "\\begin{aligned}" and end with "\\end{aligned}"  Use "\\quad" to enter space between characters  Add four backslashes ("\\\\") after every line to start from a new line and "&" in the beginning of every line to align all the lines \n    (3) Focus on the `,` in the json format  Make sure no trailing commas, delimiter or any symbol should compromise valid json format and hinder parsing of the json \n\n    Return the output json in given format:\n    \n{\n    "questions": \n    [\n        {\n            "question": \n            {\n                "question_text": "\\begin{{aligned}} questions in LaTeX format \\end{{aligned}}",\n                "image_ids": \n                [\n                   { "image_1":"image_id text"},\n                    ....\n                ]\n            },\n        }\n    ],\n    "topic" :"topic_name",\n    "topic_id" :"topic_id"  \n},\n\n\n    Example Output: \n    \n{\n    "questions": \n    [\n        {\n            "question": \n            {\n                "question_text": "\\begin{{aligned}} &\\text{ Which of the following ray diagrams is correct for the ray of light incident on a concave mirror as shown in figure?} \\end{{aligned}}",\n                "image_ids": \n                [\n                    {"image_1":"2025_01_22_a80d3920b13788732731g-160(1)"},\n                    {"image_2":"2025_01_22_a80d3920b13788732731g-160"}\n                ]\n            },\n            ....\n\n        }\n    ],\n    "topic" :"topic_name",\n    "topic_id" :"topic_id"  \n},\n\n\n\nMake sure the json format is correct.  There should be no trailing commas, any delimiter issue, etc in the json format .\n'

In [6]:
def clean_rephrase_question(question_text, topic_list):
    try:
        # initialize the ChapOpenAI object
        llm = ChatOpenAI(
            model_name="gpt-4o",
            api_key= OPENAI_API_KEY,
            temperature=0.2,
            # verbose = True
        )

        #formatting prompts
        system = CLEAN_REPHRASE_SYSTEM.format(" ",out_example = REPHRASE_OUTPUT_EXAMPLE, out_format = REPHRASE_OUTPUT_FORMAT)
        user = CLEAN_REPHRASE_USER.format(question_text = question_text, topic_list = topic_list)

        #generating response from api call
        response = llm.invoke(
            [
                ("system", system),
                ("human", user)
            ]
        )
        return response
    except Exception as e:
        print("Error cleaning text: ", type(e).__name__, "–", e, "\n", traceback.format_exc())
        return question_text  # Return original text in case of an error

In [7]:
import os
import traceback
from pathlib import Path
import zipfile
import tempfile
import shutil

def read_data_from_latex(publication: str, chapter_name: str , grade:str) -> str:
    """
    Read LaTeX content from a specified publication and chapter zip file.
    
    Args:
        publication (str): Name of the publication (e.g., 'mtg')
        chapter_name (str): Name of the chapter (e.g., 'Life Processes')
    
    Returns:
        str: Content of the LaTeX file if successful, empty string if failed
    """
    try:
        # Construct the zip file path
        zip_path = os.path.join(r"textbooks", publication, f"{chapter_name}_{grade}.zip")
        
        # Verify zip file exists
        if not os.path.exists(zip_path):
            raise FileNotFoundError(f"Zip file not found: {zip_path}")
        
        # Create a temporary directory to extract files
        with tempfile.TemporaryDirectory() as temp_dir:
            # Extract the zip file
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)
            
            # Find directories starting with 2025
            content_dirs = [d for d in os.listdir(temp_dir) 
                          if os.path.isdir(os.path.join(temp_dir, d)) and 
                          d.startswith('2025')]
            
            if not content_dirs:
                raise FileNotFoundError(f"No content directories found in zip file")
                
            # Get the latest directory
            latest_dir = sorted(content_dirs)[-1]
            dir_path = os.path.join(temp_dir, latest_dir)
            
            # Find the .tex file in the directory
            tex_files = [f for f in os.listdir(dir_path) if f.endswith('.tex')]
                    
            if not tex_files:
                raise FileNotFoundError(f"No .tex file found in {dir_path}")
                
            # Full path to the tex file
            latex_path = os.path.join(dir_path, tex_files[0])
            
            # Read the content
            with open(latex_path, 'r', encoding='utf-8') as file:
                content = file.read()
                
            print(f"Successfully processed LaTeX file from zip: {latex_path}")
            return content

    except Exception as e:
        print(
            "Failed to process the LaTeX file. Exception Occurred:",
            type(e).__name__,
            "–",
            e,
            "\n",
            traceback.format_exc()
        )
        return ""

In [8]:
def extract_questions(subject: str, chapter_texts: list, chapter_name: str, grade: str) -> dict:
    try:
        if not isinstance(chapter_texts, list) or not chapter_texts:
            return {"questions": []}
            
        formatted_output = {
            "questions": []
        }
        chunk_size = 250
        question_counter = 1
        
        for i in range(0, len(chapter_texts), chunk_size):
            chunk = chapter_texts[i:i + chunk_size]
            if not chunk:
                continue
                
            print(f"\nProcessing chunk {i//chunk_size + 1}/{-(-len(chapter_texts)//chunk_size)}")
            
            response = collect_questions_from_chapter_with_Langchain(
                subject=subject,
                chapter_text='\n'.join(chunk),
                chapter_name=chapter_name,
                grade=grade
            )
            
            print("\nDebug - Raw response:", response)
            
            # Handle response based on its type
            if hasattr(response, 'content'):
                try:
                    response_data = parse_Response(response.content)
                except Exception as parse_error:
                    print(f"Error parsing response content: {parse_error}")
                    continue
            else:
                response_data = response
                
            print("\nDebug - Processed response data:", response_data)
            
            if isinstance(response_data, dict) and "questions" in response_data:
                for question_obj in response_data["questions"]:
                    print(f"\nDebug - Processing question: {question_obj}")
                    
                    try:
                        # Extract question data from the new structure
                        if isinstance(question_obj, dict) and "question" in question_obj:
                            question_data = question_obj["question"]
                            
                            formatted_question = {
                                f"question_{question_counter}": {
                                    "question_text": question_data.get("question_text", ""),
                                    "image_ids": [
                                        img_dict for img_dict in question_data.get("image_ids", [])
                                    ]
                                }
                            }
                            
                            print(f"Debug - Formatted question: {formatted_question}")
                            formatted_output["questions"].append(formatted_question)
                            question_counter += 1
                            print(f"Successfully extracted question_{question_counter-1}")
                            
                    except Exception as format_error:
                        print(f"Error formatting question: {format_error}")
                        continue
            else:
                print(f"Warning: Invalid response structure in chunk {i//chunk_size + 1}")
                print("Expected 'questions' key in:", response_data)
            
            print(f"Completed processing chunk {i//chunk_size + 1}")
                
        total_questions = len(formatted_output["questions"])
        print(f"\nTotal questions extracted: {total_questions}")
        if total_questions == 0:
            print("Warning: No questions were extracted!")
            
        return formatted_output  # Return the formatted output instead of raw response

    except Exception as e:
        print(f"Error in extract_questions: {str(e)}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return {"questions": []}

In [9]:
def rephrase_questions(conf_data: dict, all_questions: dict, topics: list) -> dict:
    print("Starting the cleanup and rephrasing process...")
    try:
        # Validate inputs
        if not conf_data or "chapter_name" not in conf_data:
            raise ValueError("Missing chapter_name in configuration")
            
        if not topics:
            print("\n\nNo topics found in the data.")
            raise ValueError("No topics found in the data")
            
        chapter = conf_data["chapter_name"]
        
        # Validate input questions format
        if not isinstance(all_questions, dict) or "questions" not in all_questions:
            raise ValueError("Invalid input questions format")
            
        questions_list = all_questions["questions"]
        if not questions_list:
            raise ValueError(f"No questions found for chapter {chapter}")
            
        print(f"\nWorking on chapter {chapter}")
        print(f"Total questions to process: {len(questions_list)}")
        
        # Initialize to store all batches
        all_rephrased_questions = {
            "questions": [],
            "topic": "",
            "topic_id": ""
        }
        
        # Process questions in batches of 5
        batch_size = 5
        for batch_start in range(0, len(questions_list), batch_size):
            try:
                # Get current batch of questions
                batch_end = min(batch_start + batch_size, len(questions_list))
                question_batch = questions_list[batch_start:batch_end]
                
                print(f"\nProcessing batch {batch_start//batch_size + 1}/{-(-len(questions_list)//batch_size)}")
                print(f"Debug - Processing questions: {question_batch}")
                
                # Clean and rephrase the batch
                response = clean_rephrase_question(question_batch, topics)
                print("Raw response:", response)
                
                # Parse the cleaned response
                if response and hasattr(response, 'content'):
                    # Clean the content string before parsing
                    content = response.content
                    if content.startswith('```json'):
                        content = content[7:]
                    if content.endswith('```'):
                        content = content[:-3]
                        
                    try:
                        formatted_response = parse_Response(content)
                        if formatted_response and isinstance(formatted_response, dict):
                            # Store topic information from first successful batch
                            if not all_rephrased_questions["topic"]:
                                all_rephrased_questions["topic"] = formatted_response.get("topic", "")
                                all_rephrased_questions["topic_id"] = formatted_response.get("topic_id", "")
                                
                            # Add questions from this batch
                            if "questions" in formatted_response:
                                all_rephrased_questions["questions"].extend(formatted_response["questions"])
                                print(f"Successfully processed batch with {len(formatted_response['questions'])} questions")
                                print(f"Topic: {formatted_response.get('topic', 'Unknown')}")
                                print(f"Topic ID: {formatted_response.get('topic_id', 'Unknown')}")
                    except Exception as parse_error:
                        print(f"Error in parse_Response: {str(parse_error)}")
                        print("Content being parsed:", content)
                        continue
                
                print("-" * 100)
                
            except Exception as batch_error:
                print(f"Error processing batch {batch_start//batch_size + 1}: {str(batch_error)}")
                print(f"Debug - Error details: {str(batch_error)}")
                print(f"Debug - Batch content: {question_batch}")
                continue
        
        # Return all processed questions
        if all_rephrased_questions["questions"]:
            print(f"\nSuccessfully processed total {len(all_rephrased_questions['questions'])} questions")
            return all_rephrased_questions
        else:
            print("\nNo questions were successfully processed")
            return {
                "questions": [],
                "topic": "",
                "topic_id": ""
            }
        
    except Exception as e:
        print(f"Failed to clean and rephrase questions. Exception Occurred: {type(e).__name__} – {str(e)}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return {
            "questions": [],
            "topic": "",
            "topic_id": ""
        }

In [10]:
# get chapter and book data from defaultConf
with open("image_conf.json", "r") as f:
    conf_data = json.load(f)

chapter = conf_data["chapter_name"]
subject = conf_data["subject"]


print("Chapter to work on: ", chapter)
print(subject)
print(conf_data['publication'])

Chapter to work on:  Triangles
mathematics
mtg

In [11]:
from typing import Tuple, Dict, Optional
import traceback
import logging

def extract_rephrase_questions(conf_data: dict, topics: list) -> Tuple[Optional[Dict], Optional[Dict]]:
    try:
        # Validate configuration data
        required_fields = ["subject", "grade", "chapter_name"]
        missing_fields = [field for field in required_fields if field not in conf_data]
        if missing_fields:
            raise ValueError(f"Missing required configuration fields: {', '.join(missing_fields)}")
            
        if not topics:
            raise ValueError("No topics provided for question rephrasing")
            
        print("Starting question extraction and rephrasing pipeline...")
        
        # Step 1: Scrape text from PDF/LaTeX
        print("\nStep 1: Scraping textbook content...")
        pdf_text = read_data_from_latex(publication=conf_data['publication'] , chapter_name=conf_data['chapter_name'] ,grade=conf_data['grade'])
        if not pdf_text:
            raise ValueError("No text content extracted from textbook")
        print(f"Successfully extracted {len(pdf_text)} text segments")
            
        # Step 2: Extract questions from text
        print("\nStep 2: Extracting questions from text...")
        extracted_questions = extract_questions(
            subject=conf_data["subject"],
            grade=conf_data["grade"],
            chapter_name=conf_data["chapter_name"],
            chapter_texts=pdf_text.split("\n")
        )
        if not extracted_questions:
            raise ValueError("No questions were extracted from the text")
        print(f"Successfully extracted questions")
            
        # Step 3: Clean and rephrase questions
        print("\nStep 3: Cleaning and rephrasing questions...")
        final_rephrased_questions = rephrase_questions(
            conf_data=conf_data,
            all_questions=extracted_questions,
            topics=topics
        )
        if not final_rephrased_questions:
            raise ValueError("No questions were successfully rephrased")
        print("Successfully rephrased questions")
            
        # Return results
        print("\nPipeline completed successfully!")
        return extracted_questions , final_rephrased_questions
    except ValueError as val_err:
        print(f"Validation error: {str(val_err)}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return None, None
        
    except Exception as e:
        print(f"Unexpected error in question processing pipeline: {str(e)}")
        print(f"Exception type: {type(e).__name__}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return None, None
        
    finally:
        print("\nQuestion processing pipeline finished")

In [12]:
import pandas as pd

def process_filename(filename):
    """
    Process filename by stripping whitespace and converting to lowercase
    """
    return filename.strip().lower()
grade = conf_data['grade']
# Match subject to determine sheet name
match subject:
    case "mathematics":
        sheet_name = f"G{grade} Maths"
    case "biology":
        sheet_name = f"G{grade} Science"
    case "physics":
        sheet_name = f"G{grade} Science"
    case "chemistry":
        sheet_name = f"G{grade} Science"
print(sheet_name)
# Read Excel file and process the filename
file_name = process_filename("LEAP Course Creation - Topic LU Prerequisite Misconceptions.xlsx")
misconceptions_df = pd.read_excel(file_name, sheet_name=sheet_name)

# Clean column names
misconceptions_df.columns = misconceptions_df.columns.str.strip()
misconceptions_df.fillna("", inplace=True)

# Process chapter name from conf_data for comparison
chapter_name = conf_data["chapter_name"].strip().lower()

# Get unique topics for the specified chapter
tempTopics = list(misconceptions_df[
    misconceptions_df["Chapter (NCERT/AcadAlly's name)"].str.strip().str.lower() == chapter_name
]["Topic"].unique())

# Create topics dictionary with processed IDs
topics = {}
for i in range(len(tempTopics)):
    topic_id = f"{conf_data['grade']}_{conf_data['subject']}_{chapter_name}_{i+1}"
    topics[topic_id] = tempTopics[i].strip()

print("Topics with ID: ", topics, "\n\n", topics.values())

# Process misconceptions and LUs
total_misconceptions = {}
total_LUs = {}

for i, row in misconceptions_df.iterrows():
    topic = str(row["Topic"]).strip()
    
    if topic in topics.values():
        # Process LUs
        if topic in total_LUs:
            total_LUs[topic].append(row["LUs Covered"])
        else:
            total_LUs[topic] = [row["LUs Covered"]]

        # # Process misconceptions
        # temp_misconceptions = [
        #     row[f"Misconceptions {i}"] 
        #     for i in range(1, 11) 
        #     if row[f"Misconceptions {i}"] != ""
        # ]

        # if topic in total_misconceptions:
        #     total_misconceptions[topic].extend(temp_misconceptions)
        # else:
        #     total_misconceptions[topic] = temp_misconceptions

print(total_LUs, sep="\n\n-------------------------------------------------------------------\n\n")

G10 Maths
Topics with ID:  {'10_mathematics_triangles_1': 'Similar Figures', '10_mathematics_triangles_2': 'Basic Proportionality Theorem', '10_mathematics_triangles_3': 'Criteria for Similarity of Triangles: AAA', '10_mathematics_triangles_4': 'Criteria for Similarity of Triangles: SSS', '10_mathematics_triangles_5': 'Criteria for Similarity of Triangles: SAS'}

 dict_values(['Similar Figures', 'Basic Proportionality Theorem', 'Criteria for Similarity of Triangles: AAA', 'Criteria for Similarity of Triangles: SSS', 'Criteria for Similarity of Triangles: SAS'])
{'Similar Figures': ['Criteria for similarity of figures'], 'Basic Proportionality Theorem': ['Basic Proportionality Theorem (Thales Theorem)', 'Converse of Basic Proportionality Theorem (Thales theorem)'], 'Criteria for Similarity of Triangles: AAA': ['Criteria for similarity of triangles: AAA (or AA)'], 'Criteria for Similarity of Triangles: SSS': ['Criteria for similarity of triangles: SSS'], 'Criteria for Similarity of Triangles: SAS': ['Criteria for similarity of triangles: SAS']}

C:\Users\aniket singh\AppData\Local\Temp\ipykernel_24708\609127329.py:26: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  misconceptions_df.fillna("", inplace=True)

In [13]:
total_LUs

{'Similar Figures': ['Criteria for similarity of figures'],
 'Basic Proportionality Theorem': ['Basic Proportionality Theorem (Thales Theorem)',
  'Converse of Basic Proportionality Theorem (Thales theorem)'],
 'Criteria for Similarity of Triangles: AAA': ['Criteria for similarity of triangles: AAA (or AA)'],
 'Criteria for Similarity of Triangles: SSS': ['Criteria for similarity of triangles: SSS'],
 'Criteria for Similarity of Triangles: SAS': ['Criteria for similarity of triangles: SAS']}

In [14]:
# function call for execution
extracted_raw_questions_json , clean_rephrased_questions_json  = extract_rephrase_questions(conf_data, topics)
# clean_rephrased_questions_json

Starting question extraction and rephrasing pipeline...

Step 1: Scraping textbook content...
Successfully processed LaTeX file from zip: C:\Users\ANIKET~1\AppData\Local\Temp\tmpdsm9diqr\2025_02_17_bbe3f767e7e1821afad5g\2025_02_17_bbe3f767e7e1821afad5g.tex
Successfully extracted 98302 text segments

Step 2: Extracting questions from text...

Processing chunk 1/8

Debug - Raw response: content='{\n    "questions": \n    [\n        {\n            "question": \n            {\n                "question_text": "& In a triangle, a line drawn parallel to one side, to intersect the other sides in distinct points, divides the two sides in the same ratio. In $\\\\triangle A B C$, if $D E \\\\| B C$. Then\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-324"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 4. In $\\\\triangle A B C, D E \\\\| B C$ (as shown in the figure). If $A D=2 \\\\mathrm{~cm}, B D=3 \\\\mathrm{~cm}, B C=7.5 \\\\mathrm{~cm}$, then the length of $D E$ (in cm ) is:\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-325"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 5. In the given figure, in $\\\\triangle A B C, D E \\\\| B C$. If $A D=2.4 \\\\mathrm{~cm}, D B=4 \\\\mathrm{~cm}$ and $A E=2 \\\\mathrm{~cm}$, then the length of $A C$ is\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-326(2)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 6. In the given figure, $D E \\\\| B C$ and all measurements are given in centimetres. The length of $A E$ is:\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-326(1)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 8. In the given figure, $D E \\\\| B C$. If $A D=2$ units, $D B=A E=3$ units and $E C=x$ units, then the value of $x$ is:\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-326"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 9. In the given figure, $A B|\\\\mid P Q$. If $A B=6 \\\\mathrm{~cm}, P Q=2 \\\\mathrm{~cm}$ and $O B=3 \\\\mathrm{~cm}$, then the length of $O P$ is:\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-327(2)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 10. In the given figure, $D E \\\\| B C$. The value of $x$ is:\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-327(1)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 11. In $\\\\triangle A B C, P Q| | B C$. If $P B=6 \\\\mathrm{~cm}, A P=4 \\\\mathrm{~cm}, A Q=8 \\\\mathrm{~cm}$, find the length of $A C$.\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-327"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 12. In the given figure, $P Q$ II $A C$. If $B P=4 \\\\mathrm{~cm}, A P=2.4 \\\\mathrm{~cm}$ and $B Q=5 \\\\mathrm{~cm}$, then length of $B C$ is\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-327(3)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 13. In the figure given below, what value of $x$ will make $P Q|\\\\mid A B$ ?\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-328(2)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 14. In figure, $D E \\\\| B C$. If $\\\\frac{A D}{D B}=\\\\frac{3}{2}$ and $A E=2.7 \\\\mathrm{~cm}$, then $E C$ is equal to\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-328(1)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 15. In figure, $G C\\\\left|\\\\mid B D\\\\right.$ and $G E \\\\| B F$. If $A C=3 \\\\mathrm{~cm}$ and $C D=7 \\\\mathrm{~cm}$, then find the value of $\\\\frac{A E}{A F}$.\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-328"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 18. In $\\\\triangle A B C, D E \\\\| B C$, then find the value of $x$.\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-329(2)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 19. In given figure, $D E \\\\| B C$ If $\\\\frac{A D}{D B}=\\\\frac{3}{4}$ and $A C=14 \\\\mathrm{~cm}$, find $E C$.\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-329(3)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 20. In figure, $D E \\\\| A C$ and $D C \\\\| A P$. Prove that $\\\\frac{B F}{F E}=\\\\frac{B E}{E C}$.\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-329"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& In the given figure, $D E \\\\| A C$ and $D C \\\\| A P$. Prove that $\\\\frac{B E}{E C}=\\\\frac{B C}{C P}$.\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-329(1)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 21. In figure, if $P Q\\\\left|\\\\mid B C\\\\right.$ and $P R \\\\| C D$, prove that $\\\\frac{Q B}{A Q}=\\\\frac{D R}{A R}$\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-329(4)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 23. In figure $\\\\angle \\\\mathrm{D}=\\\\angle \\\\mathrm{E}$ and $\\\\frac{A D}{D B}=\\\\frac{A E}{E C}$, prove that $\\\\triangle \\\\mathrm{ABC}$ is an isosceles triangle.\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-330(2)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 24. In the figure, $P$ is any point or on side $B C$ of $\\\\triangle A B C . P Q| | B A$ nor and $P R|\\\\mid C A$ are drawn. $R Q$ is extended to meet BC produced at S . Prove that $S P^{2}=\\\\mathrm{SB} \\\\times \\\\mathrm{SC}$.\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-330"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 27. In the given figure, $\\\\triangle A B C \\\\sim \\\\triangle Q P R$. If $A C=6 \\\\mathrm{~cm}, B C=5 \\\\mathrm{~cm}, Q R=3 \\\\mathrm{~cm}$ and $P R=x$, then the value of $x$ is\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-330(1)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 32. In the given figure, $\\\\angle A B C$ and $\\\\angle A C B$ are complementary to each other and $A D \\\\perp B C$. Then,\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-331(1)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 33. In the given figure, $x$ expressed in terms of $a, b, c$, is\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-331(2)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 34. In the given figure, $A B C D$ is a quadrilateral. Diagonal $B D$ bisects $\\\\angle B$ and $\\\\angle D$ both. Prove that:\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-331"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 35. In the given figure, $\\\\frac{E A}{E C}=\\\\frac{E B}{E D}$, prove that $\\\\Delta \\\\mathrm{EAB} \\\\sim \\\\Delta \\\\mathrm{ECD}$\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-332(4)"}\n                ]\n            }\n        },\n        {\n            "question": \n            {\n                "question_text": "& 36. Diagonals $A C$ and $B D$ of a trapezium $A B C D$ intersect at $O$, where $A B \\\\| D C$. If $\\\\frac{D O}{O B}=\\\\frac{1}{2}$ then show that $A B=2 C D$.\\\\\\\\",\n                "image_ids": \n                [\n                    {"image_1":"2025_02_17_bbe3f767e7e1821afad5g-332"}\n                ]\n            }\n        }\n    ]\n}' additional_kwargs={'refusal': None} response_metadata={'token_usage': {'completion_tokens': 2847, 'prompt_tokens': 5548, 'total_tokens': 8395, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 5504}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_523b9b6e5f', 'finish_reason': 'stop', 'logprobs': None} id='run-573101d4-0902-4021-9488-d02cf2e108a5-0' usage_metadata={'input_tokens': 5548, 'output_tokens': 2847, 'total_tokens': 8395, 'input_token_details': {'audio': 0, 'cache_read': 5504}, 'output_token_details': {'audio': 0, 'reasoning': 0}}

Debug - Processed response data: {'questions': [{'question': {'question_text': '& In a triangle, a line drawn parallel to one side, to intersect the other sides in distinct points, divides the two sides in the same ratio. In $\\triangle A B C$, if $D E \\| B C$. Then\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-324'}]}}, {'question': {'question_text': '& 4. In $\\triangle A B C, D E \\| B C$ (as shown in the figure). If $A D=2 \\mathrm{~cm}, B D=3 \\mathrm{~cm}, B C=7.5 \\mathrm{~cm}$, then the length of $D E$ (in cm ) is:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-325'}]}}, {'question': {'question_text': '& 5. In the given figure, in $\\triangle A B C, D E \\| B C$. If $A D=2.4 \\mathrm{~cm}, D B=4 \\mathrm{~cm}$ and $A E=2 \\mathrm{~cm}$, then the length of $A C$ is\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(2)'}]}}, {'question': {'question_text': '& 6. In the given figure, $D E \\| B C$ and all measurements are given in centimetres. The length of $A E$ is:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(1)'}]}}, {'question': {'question_text': '& 8. In the given figure, $D E \\| B C$. If $A D=2$ units, $D B=A E=3$ units and $E C=x$ units, then the value of $x$ is:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326'}]}}, {'question': {'question_text': '& 9. In the given figure, $A B|\\mid P Q$. If $A B=6 \\mathrm{~cm}, P Q=2 \\mathrm{~cm}$ and $O B=3 \\mathrm{~cm}$, then the length of $O P$ is:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(2)'}]}}, {'question': {'question_text': '& 10. In the given figure, $D E \\| B C$. The value of $x$ is:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(1)'}]}}, {'question': {'question_text': '& 11. In $\\triangle A B C, P Q| | B C$. If $P B=6 \\mathrm{~cm}, A P=4 \\mathrm{~cm}, A Q=8 \\mathrm{~cm}$, find the length of $A C$.\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327'}]}}, {'question': {'question_text': '& 12. In the given figure, $P Q$ II $A C$. If $B P=4 \\mathrm{~cm}, A P=2.4 \\mathrm{~cm}$ and $B Q=5 \\mathrm{~cm}$, then length of $B C$ is\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(3)'}]}}, {'question': {'question_text': '& 13. In the figure given below, what value of $x$ will make $P Q|\\mid A B$ ?\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(2)'}]}}, {'question': {'question_text': '& 14. In figure, $D E \\| B C$. If $\\frac{A D}{D B}=\\frac{3}{2}$ and $A E=2.7 \\mathrm{~cm}$, then $E C$ is equal to\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(1)'}]}}, {'question': {'question_text': '& 15. In figure, $G C\\left|\\mid B D\\right.$ and $G E \\| B F$. If $A C=3 \\mathrm{~cm}$ and $C D=7 \\mathrm{~cm}$, then find the value of $\\frac{A E}{A F}$.\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328'}]}}, {'question': {'question_text': '& 18. In $\\triangle A B C, D E \\| B C$, then find the value of $x$.\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(2)'}]}}, {'question': {'question_text': '& 19. In given figure, $D E \\| B C$ If $\\frac{A D}{D B}=\\frac{3}{4}$ and $A C=14 \\mathrm{~cm}$, find $E C$.\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(3)'}]}}, {'question': {'question_text': '& 20. In figure, $D E \\| A C$ and $D C \\| A P$. Prove that $\\frac{B F}{F E}=\\frac{B E}{E C}$.\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329'}]}}, {'question': {'question_text': '& In the given figure, $D E \\| A C$ and $D C \\| A P$. Prove that $\\frac{B E}{E C}=\\frac{B C}{C P}$.\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(1)'}]}}, {'question': {'question_text': '& 21. In figure, if $P Q\\left|\\mid B C\\right.$ and $P R \\| C D$, prove that $\\frac{Q B}{A Q}=\\frac{D R}{A R}$\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(4)'}]}}, {'question': {'question_text': '& 23. In figure $\\angle \\mathrm{D}=\\angle \\mathrm{E}$ and $\\frac{A D}{D B}=\\frac{A E}{E C}$, prove that $\\triangle \\mathrm{ABC}$ is an isosceles triangle.\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330(2)'}]}}, {'question': {'question_text': '& 24. In the figure, $P$ is any point or on side $B C$ of $\\triangle A B C . P Q| | B A$ nor and $P R|\\mid C A$ are drawn. $R Q$ is extended to meet BC produced at S . Prove that $S P^{2}=\\mathrm{SB} \\times \\mathrm{SC}$.\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330'}]}}, {'question': {'question_text': '& 27. In the given figure, $\\triangle A B C \\sim \\triangle Q P R$. If $A C=6 \\mathrm{~cm}, B C=5 \\mathrm{~cm}, Q R=3 \\mathrm{~cm}$ and $P R=x$, then the value of $x$ is\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330(1)'}]}}, {'question': {'question_text': '& 32. In the given figure, $\\angle A B C$ and $\\angle A C B$ are complementary to each other and $A D \\perp B C$. Then,\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-331(1)'}]}}, {'question': {'question_text': '& 33. In the given figure, $x$ expressed in terms of $a, b, c$, is\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-331(2)'}]}}, {'question': {'question_text': '& 34. In the given figure, $A B C D$ is a quadrilateral. Diagonal $B D$ bisects $\\angle B$ and $\\angle D$ both. Prove that:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-331'}]}}, {'question': {'question_text': '& 35. In the given figure, $\\frac{E A}{E C}=\\frac{E B}{E D}$, prove that $\\Delta \\mathrm{EAB} \\sim \\Delta \\mathrm{ECD}$\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332(4)'}]}}, {'question': {'question_text': '& 36. Diagonals $A C$ and $B D$ of a trapezium $A B C D$ intersect at $O$, where $A B \\| D C$. If $\\frac{D O}{O B}=\\frac{1}{2}$ then show that $A B=2 C D$.\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332'}]}}]}

Debug - Processing question: {'question': {'question_text': '& In a triangle, a line drawn parallel to one side, to intersect the other sides in distinct points, divides the two sides in the same ratio. In $\\triangle A B C$, if $D E \\| B C$. Then\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-324'}]}}
Debug - Formatted question: {'question_1': {'question_text': '& In a triangle, a line drawn parallel to one side, to intersect the other sides in distinct points, divides the two sides in the same ratio. In $\\triangle A B C$, if $D E \\| B C$. Then\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-324'}]}}
Successfully extracted question_1

Debug - Processing question: {'question': {'question_text': '& 4. In $\\triangle A B C, D E \\| B C$ (as shown in the figure). If $A D=2 \\mathrm{~cm}, B D=3 \\mathrm{~cm}, B C=7.5 \\mathrm{~cm}$, then the length of $D E$ (in cm ) is:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-325'}]}}
Debug - Formatted question: {'question_2': {'question_text': '& 4. In $\\triangle A B C, D E \\| B C$ (as shown in the figure). If $A D=2 \\mathrm{~cm}, B D=3 \\mathrm{~cm}, B C=7.5 \\mathrm{~cm}$, then the length of $D E$ (in cm ) is:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-325'}]}}
Successfully extracted question_2

Debug - Processing question: {'question': {'question_text': '& 5. In the given figure, in $\\triangle A B C, D E \\| B C$. If $A D=2.4 \\mathrm{~cm}, D B=4 \\mathrm{~cm}$ and $A E=2 \\mathrm{~cm}$, then the length of $A C$ is\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(2)'}]}}
Debug - Formatted question: {'question_3': {'question_text': '& 5. In the given figure, in $\\triangle A B C, D E \\| B C$. If $A D=2.4 \\mathrm{~cm}, D B=4 \\mathrm{~cm}$ and $A E=2 \\mathrm{~cm}$, then the length of $A C$ is\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(2)'}]}}
Successfully extracted question_3

Debug - Processing question: {'question': {'question_text': '& 6. In the given figure, $D E \\| B C$ and all measurements are given in centimetres. The length of $A E$ is:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(1)'}]}}
Debug - Formatted question: {'question_4': {'question_text': '& 6. In the given figure, $D E \\| B C$ and all measurements are given in centimetres. The length of $A E$ is:\\\\', 'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(1)'}]}}
Successfully extracted question_4


In [15]:
jv,bhmb

NameError: name 'jv' is not defined

In [16]:
extracted_raw_questions_json

{'questions': [{'question_1': {'question_text': '& In a triangle, a line drawn parallel to one side, to intersect the other sides in distinct points, divides the two sides in the same ratio. In $\\triangle A B C$, if $D E \\| B C$. Then\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-324'}]}},
  {'question_2': {'question_text': '& 4. In $\\triangle A B C, D E \\| B C$ (as shown in the figure). If $A D=2 \\mathrm{~cm}, B D=3 \\mathrm{~cm}, B C=7.5 \\mathrm{~cm}$, then the length of $D E$ (in cm ) is:\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-325'}]}},
  {'question_3': {'question_text': '& 5. In the given figure, in $\\triangle A B C, D E \\| B C$. If $A D=2.4 \\mathrm{~cm}, D B=4 \\mathrm{~cm}$ and $A E=2 \\mathrm{~cm}$, then the length of $A C$ is\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(2)'}]}},
  {'question_4': {'question_text': '& 6. In the given figure, $D E \\| B C$ and all measurements are given in centimetres. The length of $A E$ is:\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(1)'}]}},
  {'question_5': {'question_text': '& 8. In the given figure, $D E \\| B C$. If $A D=2$ units, $D B=A E=3$ units and $E C=x$ units, then the value of $x$ is:\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326'}]}},
  {'question_6': {'question_text': '& 9. In the given figure, $A B|\\mid P Q$. If $A B=6 \\mathrm{~cm}, P Q=2 \\mathrm{~cm}$ and $O B=3 \\mathrm{~cm}$, then the length of $O P$ is:\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(2)'}]}},
  {'question_7': {'question_text': '& 10. In the given figure, $D E \\| B C$. The value of $x$ is:\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(1)'}]}},
  {'question_8': {'question_text': '& 11. In $\\triangle A B C, P Q| | B C$. If $P B=6 \\mathrm{~cm}, A P=4 \\mathrm{~cm}, A Q=8 \\mathrm{~cm}$, find the length of $A C$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327'}]}},
  {'question_9': {'question_text': '& 12. In the given figure, $P Q$ II $A C$. If $B P=4 \\mathrm{~cm}, A P=2.4 \\mathrm{~cm}$ and $B Q=5 \\mathrm{~cm}$, then length of $B C$ is\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(3)'}]}},
  {'question_10': {'question_text': '& 13. In the figure given below, what value of $x$ will make $P Q|\\mid A B$ ?\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(2)'}]}},
  {'question_11': {'question_text': '& 14. In figure, $D E \\| B C$. If $\\frac{A D}{D B}=\\frac{3}{2}$ and $A E=2.7 \\mathrm{~cm}$, then $E C$ is equal to\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(1)'}]}},
  {'question_12': {'question_text': '& 15. In figure, $G C\\left|\\mid B D\\right.$ and $G E \\| B F$. If $A C=3 \\mathrm{~cm}$ and $C D=7 \\mathrm{~cm}$, then find the value of $\\frac{A E}{A F}$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328'}]}},
  {'question_13': {'question_text': '& 18. In $\\triangle A B C, D E \\| B C$, then find the value of $x$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(2)'}]}},
  {'question_14': {'question_text': '& 19. In given figure, $D E \\| B C$ If $\\frac{A D}{D B}=\\frac{3}{4}$ and $A C=14 \\mathrm{~cm}$, find $E C$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(3)'}]}},
  {'question_15': {'question_text': '& 20. In figure, $D E \\| A C$ and $D C \\| A P$. Prove that $\\frac{B F}{F E}=\\frac{B E}{E C}$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329'}]}},
  {'question_16': {'question_text': '& In the given figure, $D E \\| A C$ and $D C \\| A P$. Prove that $\\frac{B E}{E C}=\\frac{B C}{C P}$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(1)'}]}},
  {'question_17': {'question_text': '& 21. In figure, if $P Q\\left|\\mid B C\\right.$ and $P R \\| C D$, prove that $\\frac{Q B}{A Q}=\\frac{D R}{A R}$\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(4)'}]}},
  {'question_18': {'question_text': '& 23. In figure $\\angle \\mathrm{D}=\\angle \\mathrm{E}$ and $\\frac{A D}{D B}=\\frac{A E}{E C}$, prove that $\\triangle \\mathrm{ABC}$ is an isosceles triangle.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330(2)'}]}},
  {'question_19': {'question_text': '& 24. In the figure, $P$ is any point or on side $B C$ of $\\triangle A B C . P Q| | B A$ nor and $P R|\\mid C A$ are drawn. $R Q$ is extended to meet BC produced at S . Prove that $S P^{2}=\\mathrm{SB} \\times \\mathrm{SC}$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330'}]}},
  {'question_20': {'question_text': '& 27. In the given figure, $\\triangle A B C \\sim \\triangle Q P R$. If $A C=6 \\mathrm{~cm}, B C=5 \\mathrm{~cm}, Q R=3 \\mathrm{~cm}$ and $P R=x$, then the value of $x$ is\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330(1)'}]}},
  {'question_21': {'question_text': '& 32. In the given figure, $\\angle A B C$ and $\\angle A C B$ are complementary to each other and $A D \\perp B C$. Then,\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-331(1)'}]}},
  {'question_22': {'question_text': '& 33. In the given figure, $x$ expressed in terms of $a, b, c$, is\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-331(2)'}]}},
  {'question_23': {'question_text': '& 34. In the given figure, $A B C D$ is a quadrilateral. Diagonal $B D$ bisects $\\angle B$ and $\\angle D$ both. Prove that:\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-331'}]}},
  {'question_24': {'question_text': '& 35. In the given figure, $\\frac{E A}{E C}=\\frac{E B}{E D}$, prove that $\\Delta \\mathrm{EAB} \\sim \\Delta \\mathrm{ECD}$\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332(4)'}]}},
  {'question_25': {'question_text': '& 36. Diagonals $A C$ and $B D$ of a trapezium $A B C D$ intersect at $O$, where $A B \\| D C$. If $\\frac{D O}{O B}=\\frac{1}{2}$ then show that $A B=2 C D$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332'}]}},
  {'question_26': {'question_text': '&38. \\quad In \\quad the \\quad given \\quad figure, \\quad $X \\quad Z$ \\quad is \\quad parallel \\quad to \\quad $B \\quad C . \\quad A \\quad Z=3 \\quad \\&\\mathrm{~cm}, \\quad Z \\quad C=2 \\quad \\mathrm{~cm}, \\quad B \\quad M=3 \\quad \\mathrm{~cm}$ \\quad and \\quad $M \\quad C=5 \\quad \\mathrm{~cm}$. \\quad Find \\quad the \\quad length \\quad of \\quad XY. \\quad 21.3\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332(3)'}]}},
  {'question_27': {'question_text': '&39. \\quad In \\quad figure, \\quad $P \\quad Q|\\mid \\quad B \\quad C, \\quad P \\quad Q=3 \\quad \\mathrm{~cm}, \\quad B \\quad C=9 \\quad \\mathrm{~cm}$ \\quad and \\quad $A \\quad C=7.5 \\quad \\mathrm{~cm}$. \\quad Find \\quad the \\quad length \\quad of \\quad $A \\quad Q$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332(1)'}]}},
  {'question_28': {'question_text': '&40. \\quad State \\quad which \\quad of \\quad the \\quad two \\quad triangles \\quad given \\quad in \\quad the \\quad figure \\quad are \\quad similar. \\quad Also \\quad state \\quad the \\quad similarity \\quad criterion \\quad used.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-333(1)'}]}},
  {'question_29': {'question_text': '&41. \\quad Sides \\quad $A \\quad B, \\quad B \\quad C$ \\quad and \\quad median \\quad $A \\quad D$ \\quad of \\quad a \\quad $\\triangle \\quad A \\quad B \\quad C$ \\quad are \\quad respectively \\quad proportional \\quad to \\quad sides \\quad $P \\quad Q, \\quad Q \\quad R$ \\quad and \\quad median \\quad $P \\quad M$ \\quad of \\quad $\\triangle \\quad P \\quad Q \\quad R$. \\quad Show \\quad that \\quad $\\triangle \\quad A \\quad B \\quad C \\quad \\sim \\quad \\triangle \\quad P \\quad Q \\quad R$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-333(3)'}]}},
  {'question_30': {'question_text': '&48. \\quad In \\quad the \\quad given \\quad figure \\quad $P \\quad A, \\quad Q \\quad B$ \\quad and \\quad $R \\quad C$ \\quad are \\quad each \\quad perpendicular \\quad to \\quad $A \\quad C$. \\quad If \\quad $A \\quad P=x, \\quad B \\quad Q=y$ \\quad and \\quad $C \\quad R=z$, \\quad then \\quad prove \\quad that \\quad $\\frac{1}{x}+\\frac{1}{z}=\\frac{1}{y}$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-334'}]}},
  {'question_31': {'question_text': '&49. \\quad In \\quad the \\quad given \\quad figure, \\quad $\\triangle \\quad F \\quad E \\quad C \\quad \\equiv \\quad \\triangle \\quad G \\quad D \\quad B$ \\quad and \\quad $\\angle \\quad 1=\\angle \\quad 2$. \\quad Prove \\quad $=$ \\quad that \\quad $\\triangle \\quad A^{2} \\quad E^{\\sim} \\quad \\triangle \\quad A \\quad B \\quad C$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-334(2)'}]}},
  {'question_32': {'question_text': '&53. \\quad In \\quad the \\quad given \\quad figure, \\quad $A \\quad A \\quad B \\quad C$ \\quad and \\quad $A \\quad D \\quad B \\quad C$ \\quad are \\quad on \\quad the \\quad same \\quad base \\quad $B \\quad C$. \\quad If \\quad $A \\quad D$ \\quad intersects \\quad $B \\quad C$ \\quad at \\quad $O$, \\quad prove \\quad that \\quad $\\frac{\\operatorname{ar}(\\triangle \\quad A \\quad B \\quad C}{\\operatorname{ar}(\\triangle \\quad D \\quad B \\quad C)}=\\frac{A \\quad O}{D \\quad O}$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-335(1)'}]}},
  {'question_33': {'question_text': '&54. \\quad In \\quad the \\quad given \\quad figure, \\quad $E$ \\quad is \\quad a \\quad point \\quad on \\quad $C \\quad B$ \\quad produced \\quad of \\quad an \\quad isosceles \\quad $\\triangle \\quad A \\quad B \\quad C$, \\quad with \\quad side \\quad $A \\quad B=A \\quad C$. \\quad If \\quad $A \\quad D \\perp B \\quad C$ \\quad and \\quad $E \\quad F \\perp A \\quad C$, \\quad prove \\quad that \\quad $\\triangle \\quad A \\quad B \\quad D \\quad \\sim \\quad \\triangle \\quad E \\quad C \\quad F$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-335(2)'}]}},
  {'question_34': {'question_text': '&55. \\quad In \\quad the \\quad given \\quad figure, \\quad $A \\quad B \\quad C$ \\quad is \\quad a \\quad triangle \\quad and \\quad GHED \\quad is \\quad a \\quad rectangle. \\quad $B \\quad C=12 \\quad \\mathrm{~cm}, \\quad H \\quad E=6 \\quad \\mathrm{~cm}, \\quad F \\quad C=B \\quad F$ \\quad and \\quad altitude \\quad $A \\quad F=24 \\quad \\mathrm{~cm}$. \\quad Find \\quad the \\quad area \\quad of \\quad the \\quad rectangle.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-335'}]}},
  {'question_35': {'question_text': '&60. \\quad In \\quad $\\triangle \\quad A \\quad B \\quad C, \\quad \\angle \\quad B=90^{\\circ}$ \\quad and \\quad $D$ \\quad is \\quad the \\quad mid \\quad point \\quad of \\quad $B \\quad C$. \\quad Prove \\quad that \\quad $A \\quad C^{2}=A \\quad D^{2}+3 \\quad C \\quad D^{2}$\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-336'}]}},
  {'question_36': {'question_text': '&62. \\quad In \\quad given \\quad figure \\quad $B \\quad N$ \\quad and \\quad $C \\quad M$ \\quad are \\quad medians \\quad of \\quad a \\quad right \\quad angled \\quad at \\quad $A$. \\quad Prove \\quad that \\quad $4\\left(B \\quad N^{2}+C \\quad M^{2}\\right)=5 \\quad B \\quad C^{2}$\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-336(1)'}]}},
  {'question_37': {'question_text': '&1. \\quad In \\quad $\\triangle \\quad A \\quad B \\quad C, \\quad D \\quad E \\| \\quad A \\quad B$. \\quad If \\quad $A \\quad B=a, \\quad D \\quad E=x, \\quad B \\quad E=b$ \\quad and \\quad $E \\quad C=c$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-336(2)'}]}},
  {'question_38': {'question_text': '&2. \\quad In \\quad the \\quad following \\quad figure, \\quad $A \\quad A \\quad B \\quad C$ \\quad is \\quad a \\quad right-angled \\quad triangle, \\quad such \\quad that:\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-337'}]}},
  {'question_39': {'question_text': '&3. \\quad (a) \\quad State \\quad and \\quad prove \\quad Basic \\quad Proportionality \\quad theorem.\\\\& \\quad (b) \\quad In \\quad the \\quad given \\quad figure \\quad $\\angle \\quad C \\quad E \\quad F=\\angle \\quad C \\quad F \\quad E$. \\quad $F$ \\quad is \\quad the \\quad midpoint \\quad of \\quad $D \\quad C$. \\quad Prove \\quad that \\quad $\\frac{A \\quad B}{B \\quad D}=\\frac{A \\quad E}{F \\quad D}$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-337(2)'}]}},
  {'question_40': {'question_text': '&5. \\quad $\\triangle \\quad \\mathrm{PQR}$ \\quad is \\quad shown \\quad below. \\quad ST \\quad is \\quad drawn \\quad such \\quad that \\quad $\\angle \\quad \\mathrm{PRQ}=\\angle \\quad \\mathrm{STQ}$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-337(1)'}]}},
  {'question_41': {'question_text': '&6. \\quad Two \\quad scalene \\quad triangles \\quad are \\quad given \\quad below.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-338'}]}},
  {'question_42': {'question_text': '&8. \\quad In \\quad the \\quad figure, \\quad if \\quad $D \\quad E \\| \\quad B \\quad C, \\quad A \\quad D=3 \\quad \\mathrm{~cm}, \\quad \\mathrm{BD}=4 \\quad \\mathrm{~cm}$ \\quad and \\quad $\\mathrm{BC}=14 \\quad \\mathrm{~cm}$, \\quad then \\quad DE \\quad equals\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-338(1)'}]}},
  {'question_43': {'question_text': '&10. \\quad In \\quad the \\quad given \\quad figure, \\quad $\\mathrm{ZACB}=\\mathrm{ZCDA}, \\quad \\mathrm{AC}=8 \\quad \\mathrm{~cm}, \\quad \\mathrm{AD}=3 \\quad \\mathrm{~cm}$, \\quad then \\quad BD \\quad is\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-339'}]}},
  {'question_44': {'question_text': '&11. \\quad Sides \\quad $A \\quad B$ \\quad and \\quad $B \\quad E$ \\quad of \\quad a \\quad right \\quad triangle, \\quad right \\quad angled \\quad at \\quad $B$ \\quad are \\quad of \\quad lengths \\quad 16 \\quad cm \\quad and \\quad 8 \\quad cm \\quad respectively. \\quad The \\quad length \\quad of \\quad the \\quad side \\quad of \\quad largest \\quad square \\quad FDGB \\quad that \\quad can \\quad be \\quad inscribed \\quad in \\quad the \\quad triangle \\quad ABE \\quad is\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-339(2)'}]}},
  {'question_45': {'question_text': '&12. \\quad $A \\quad B \\quad C \\quad D$ \\quad is \\quad a \\quad parallelogram. \\quad Point \\quad $P$ \\quad divides \\quad $A \\quad B$ \\quad in \\quad the \\quad ratio \\quad 2:3 \\quad and \\quad point \\quad $Q$ \\quad divides \\quad $D \\quad C$ \\quad in \\quad the \\quad ratio \\quad 4:1. \\quad Prove \\quad that \\quad OC \\quad is \\quad half \\quad of \\quad OA.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-339(1)'}]}},
  {'question_46': {'question_text': '&13. \\quad In \\quad the \\quad given \\quad figure \\quad below, \\quad $\\frac{A \\quad D}{A \\quad E}=\\frac{A \\quad C}{B \\quad D}$ \\quad and \\quad $\\angle \\quad 1=\\angle \\quad 2$. \\quad Show \\quad that \\quad $\\triangle \\quad \\mathrm{BAE} \\quad \\sim \\quad \\triangle \\quad \\mathrm{CAD}$.\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-340(1)'}]}},
  {'question_47': {'question_text': '&4. \\quad (b):\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-340'}]}},
  {'question_48': {'question_text': '&4. \\quad (b):\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-341'}]}},
  {'question_49': {'question_text': '&9. \\quad (d): \\quad In \\quad $\\triangle \\quad \\mathrm{OPQ}$ \\quad and \\quad $\\triangle \\quad \\mathrm{OBA}$\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-342'}]}},
  {'question_50': {'question_text': '&15. \\quad Here \\quad in \\quad the \\quad given \\quad figure, \\quad $G \\quad C \\| \\quad B \\quad D$ \\quad and \\quad $G \\quad E \\| \\quad B \\quad F \\quad A \\quad C-3 \\quad \\mathrm{~cm}$ \\quad and \\quad $C \\quad D=7 \\quad \\mathrm{~cm}$\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-343'}]}},
  {'question_51': {'question_text': '&16. \\quad Given, \\quad X \\quad is \\quad middle \\quad point \\quad of \\quad A \\quad C \\quad and \\quad X \\quad Y|\\mid \\quad A \\quad B. \\quad We \\quad have \\quad to \\quad prove \\quad Y \\quad is \\quad middle \\quad point \\quad of \\quad B \\quad C. \\quad In \\quad \\triangle \\quad A \\quad B \\quad C, \\quad X \\quad Y| \\mid \\\\ &AB\\\\ &\\includegraphics[max width=\\textwidth, center]{2025_02_17_bbe3f767e7e1821afad5g-343(1)}\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-343(1)'}]}},
  {'question_52': {'question_text': '&17. \\quad In \\quad \\triangle \\quad A \\quad B \\quad C, \\quad D \\quad E| | \\quad B \\quad C\\\\ &\\includegraphics[max width=\\textwidth, center]{2025_02_17_bbe3f767e7e1821afad5g-344}\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-344'}]}},
  {'question_53': {'question_text': '&22. \\quad Basic \\quad Proportionality \\quad theorem: \\quad In \\quad a \\quad triangle, \\quad a \\quad line \\quad is \\quad drawn \\quad parallel \\quad to \\quad one \\quad side, \\quad to \\quad intersect \\quad the \\quad other \\quad sides \\quad in \\quad distinct \\quad points, \\quad divided \\quad the \\quad two \\quad sides \\quad in \\quad the \\quad same \\quad ratio.\\\\ &i.e., \\quad In \\quad \\triangle \\quad \\mathrm{ABC}, \\quad if \\quad \\mathrm{DE} \\| \\quad \\mathrm{BC}, \\quad then \\quad \\frac{A \\quad D}{D \\quad B}=\\frac{A \\quad E}{E \\quad C}\\\\ &Proof: \\quad Consider \\quad A \\quad A \\quad B \\quad C \\quad in \\quad which \\quad D \\quad E \\| \\quad B \\quad C, \\quad D \\quad E \\quad intersects \\quad A \\quad B \\quad at \\quad D \\quad and \\quad A \\quad C \\quad at \\quad E.\\\\ &\\includegraphics[max width=\\textwidth, center]{2025_02_17_bbe3f767e7e1821afad5g-345}\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-345'}]}},
  {'question_54': {'question_text': '&25. \\quad Consider \\quad \\triangle \\quad A \\quad B \\quad C \\quad in \\quad which \\quad D \\quad E \\| \\quad B \\quad C,\\\\ &D \\quad E \\quad intersects \\quad A \\quad B \\quad at \\quad D \\quad and \\quad A \\quad C \\quad at \\quad E.\\\\ &To \\quad prove: \\quad \\frac{A \\quad D}{D \\quad B}=\\frac{A \\quad E}{E \\quad C}\\\\ &\\includegraphics[max width=\\textwidth, center]{2025_02_17_bbe3f767e7e1821afad5g-346}\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-346'}]}},
  {'question_55': {'question_text': '&26.\\\\ &\\includegraphics[max width=\\textwidth, center]{2025_02_17_bbe3f767e7e1821afad5g-347}\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-347'}]}},
  {'question_56': {'question_text': '&27. \\quad (d):\\\\ &\\includegraphics[max width=\\textwidth, center]{2025_02_17_bbe3f767e7e1821afad5g-348(1)}\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-348(1)'}]}},
  {'question_57': {'question_text': '&28. \\quad (b): \\quad Given, \\quad \\ln \\quad \\triangle \\quad \\mathrm{ABC} \\quad and \\quad \\triangle \\quad \\mathrm{DEF}, \\quad \\frac{A \\quad B}{D \\quad E}=\\frac{B \\quad C}{F \\quad D}\\\\ &\\includegraphics[max width=\\textwidth, center]{2025_02_17_bbe3f767e7e1821afad5g-348}\\\\',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-348'}]}},

In [17]:
print("Chapter name: ",chapter, ",  Raw questions: ",  len(extracted_raw_questions_json['questions']))
print("Chapter name: ",chapter, ",  Cleaned questions: ",  len(clean_rephrased_questions_json['questions']))

Chapter name:  Triangles ,  Raw questions:  101
Chapter name:  Triangles ,  Cleaned questions:  99

In [18]:
clean_rephrased_questions_json

{'questions': [{'question': {'question_text': '\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ if } DE \\parallel BC, \\text{ what is the relationship between the segments } AD, DB, AE, \\text{ and } EC? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-324'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ with } DE \\parallel BC, \\text{ given } AD = 2 \\, \\text{cm}, BD = 3 \\, \\text{cm}, \\text{ and } BC = 7.5 \\, \\text{cm}, \\text{ calculate the length of } DE. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-325'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the figure, } \\triangle ABC \\text{ has } DE \\parallel BC. \\text{ If } AD = 2.4 \\, \\text{cm}, DB = 4 \\, \\text{cm}, \\text{ and } AE = 2 \\, \\text{cm}, \\text{ find the length of } AC. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the figure, } DE \\parallel BC \\text{ and all measurements are in centimeters. Determine the length of } AE. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the figure, } DE \\parallel BC. \\text{ If } AD = 2 \\text{ units, } DB = AE = 3 \\text{ units, and } EC = x \\text{ units, find the value of } x. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, if } AB \\parallel PQ, \\text{ and } AB = 6 \\, \\text{cm}, \\, PQ = 2 \\, \\text{cm}, \\text{ and } OB = 3 \\, \\text{cm}, \\text{ what is the length of } OP? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, } DE \\parallel BC. \\text{ Determine the value of } x. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In } \\triangle ABC, \\, PQ \\parallel BC. \\text{ If } PB = 6 \\, \\text{cm}, \\, AP = 4 \\, \\text{cm}, \\text{ and } AQ = 8 \\, \\text{cm}, \\text{ find the length of } AC. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, } PQ \\parallel AC. \\text{ If } BP = 4 \\, \\text{cm}, \\, AP = 2.4 \\, \\text{cm}, \\text{ and } BQ = 5 \\, \\text{cm}, \\text{ what is the length of } BC? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(3)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the figure given below, determine the value of } x \\text{ that will make } PQ \\parallel AB. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, with } D E \\parallel B C, \\text{ if } \\frac{A D}{D B}=\\frac{3}{2} \\text{ and } A E=2.7 \\mathrm{~cm}, \\text{ determine the length of } E C. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the figure, given } G C \\perp B D \\text{ and } G E \\parallel B F, \\text{ with } A C=3 \\mathrm{~cm} \\text{ and } C D=7 \\mathrm{~cm}, \\text{ find the ratio } \\frac{A E}{A F}. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In } \\triangle A B C, \\text{ with } D E \\parallel B C, \\text{ calculate the value of } x. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, } D E \\parallel B C. \\text{ If } \\frac{A D}{D B}=\\frac{3}{4} \\text{ and } A C=14 \\mathrm{~cm}, \\text{ find the length of } E C. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(3)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the figure, } D E \\parallel A C \\text{ and } D C \\parallel A P. \\text{ Prove that } \\frac{B F}{F E}=\\frac{B E}{E C}. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the given figure, if } D E \\parallel A C \\text{ and } D C \\parallel A P, \\text{ demonstrate that } \\frac{B E}{E C} = \\frac{B C}{C P}. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the figure, given that } P Q \\perp B C \\text{ and } P R \\parallel C D, \\text{ show that } \\frac{Q B}{A Q} = \\frac{D R}{A R}. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(4)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the figure, if } \\angle D = \\angle E \\text{ and } \\frac{A D}{D B} = \\frac{A E}{E C}, \\text{ prove that } \\triangle A B C \\text{ is an isosceles triangle.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the figure, } P \\text{ is any point on side } B C \\text{ of } \\triangle A B C. \\text{ If } P Q \\parallel B A \\text{ and } P R \\parallel C A, \\text{ and } R Q \\text{ is extended to meet } B C \\text{ produced at } S, \\text{ prove that } S P^{2} = S B \\times S C. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the given figure, } \\triangle A B C \\sim \\triangle Q P R. \\text{ If } A C = 6 \\text{ cm, } B C = 5 \\text{ cm, } Q R = 3 \\text{ cm,} \\text{ find the value of } x \\text{ when } P R = x. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ If } \\angle ABC \\text{ and } \\angle ACB \\text{ are complementary angles in the given figure, and } AD \\perp BC, \\text{ what can be concluded?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-331(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the given figure, how is } x \\text{ expressed in terms of } a, b, \\text{ and } c? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-331(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ Given that } ABCD \\text{ is a quadrilateral and diagonal } BD \\text{ bisects both } \\angle B \\text{ and } \\angle D, \\text{ what can be proven?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-331'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ If } \\frac{EA}{EC} = \\frac{EB}{ED} \\text{ in the given figure, how can it be proven that } \\Delta EAB \\sim \\Delta ECD? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332(4)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In a trapezium } ABCD \\text{ with } AB \\parallel DC, \\text{ if diagonals } AC \\text{ and } BD \\text{ intersect at } O \\text{ and } \\frac{DO}{OB} = \\frac{1}{2}, \\text{ how can it be shown that } AB = 2CD? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, if } XZ \\text{ is parallel to } BC, \\text{ with } AZ = 3 \\, \\mathrm{cm}, \\, ZC = 2 \\, \\mathrm{cm}, \\, BM = 3 \\, \\mathrm{cm}, \\, \\text{and } MC = 5 \\, \\mathrm{cm}, \\, \\text{what is the length of } XY? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332(3)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the figure, given } PQ \\parallel BC, \\, PQ = 3 \\, \\mathrm{cm}, \\, BC = 9 \\, \\mathrm{cm}, \\, \\text{and } AC = 7.5 \\, \\mathrm{cm}, \\, \\text{what is the length of } AQ? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-332(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{Determine which of the two triangles in the figure are similar and state the similarity criterion used.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-333(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{Given that sides } AB, \\, BC \\text{ and median } AD \\text{ of } \\triangle ABC \\text{ are proportional to sides } PQ, \\, QR \\text{ and median } PM \\text{ of } \\triangle PQR, \\, \\text{show that } \\triangle ABC \\sim \\triangle PQR. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-333(3)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, } PA, \\, QB, \\, \\text{and } RC \\text{ are each perpendicular to } AC. \\text{ If } AP = x, \\, BQ = y, \\, \\text{and } CR = z, \\, \\text{prove that } \\frac{1}{x} + \\frac{1}{z} = \\frac{1}{y}. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-334'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, if } \\triangle FEC \\equiv \\triangle GDB \\text{ and } \\angle 1 = \\angle 2, \\text{ demonstrate that } \\triangle A^{2} E^{\\sim} \\triangle ABC. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-334(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, triangles } AABC \\text{ and } ADBC \\text{ share the same base } BC. \\text{ If } AD \\text{ intersects } BC \\text{ at } O, \\text{ show that } \\frac{\\operatorname{ar}(\\triangle ABC)}{\\operatorname{ar}(\\triangle DBC)} = \\frac{AO}{DO}. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-335(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, } E \\text{ is a point on } CB \\text{ produced of an isosceles } \\triangle ABC, \\text{ with side } AB = AC. \\text{ If } AD \\perp BC \\text{ and } EF \\perp AC, \\text{ prove that } \\triangle ABD \\sim \\triangle ECF. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-335(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In the given figure, } ABC \\text{ is a triangle and } GHED \\text{ is a rectangle. Given } BC = 12 \\, \\mathrm{cm}, \\, HE = 6 \\, \\mathrm{cm}, \\, FC = BF \\text{ and altitude } AF = 24 \\, \\mathrm{cm}. \\text{ Determine the area of the rectangle.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-335'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In } \\triangle ABC, \\, \\angle B = 90^{\\circ} \\text{ and } D \\text{ is the midpoint of } BC. \\text{ Prove that } AC^{2} = AD^{2} + 3CD^{2}. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-336'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the given figure, $B N$ and $C M$ are medians of a right triangle angled at $A$. Prove that } \\\\ &4(B N^{2}+C M^{2})=5 B C^{2}. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-336(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In $\\triangle A B C$, $D E \\parallel A B$. Given $A B=a$, $D E=x$, $B E=b$, and $E C=c$.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-336(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the following figure, $A A B C$ is a right-angled triangle.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-337'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ (a) State and prove the Basic Proportionality theorem.} \\\\ &\\text{ (b) In the given figure, $\\angle C E F=\\angle C F E$. $F$ is the midpoint of $D C$. Prove that } \\\\ &\\frac{A B}{B D}=\\frac{A E}{F D}. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-337(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In $\\triangle \\mathrm{PQR}$ shown below, $ST$ is drawn such that $\\angle \\mathrm{PRQ}=\\angle \\mathrm{STQ}$.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-337(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ Consider the two scalene triangles given below. Which statement about their properties is true?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-338'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the figure, if } D \\quad E \\parallel B \\quad C, \\quad A \\quad D=3 \\quad \\mathrm{cm}, \\quad \\mathrm{BD}=4 \\quad \\mathrm{cm} \\text{ and } \\mathrm{BC}=14 \\quad \\mathrm{cm}, \\text{ what is the length of } DE? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-338(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the given figure, } \\mathrm{ZACB}=\\mathrm{ZCDA}, \\quad \\mathrm{AC}=8 \\quad \\mathrm{cm}, \\quad \\mathrm{AD}=3 \\quad \\mathrm{cm}. \\text{ Determine the length of } BD. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-339'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ Sides } A \\quad B \\text{ and } B \\quad E \\text{ of a right triangle, right angled at } B, \\text{ are of lengths 16 cm and 8 cm respectively.} \\\\ &\\text{ What is the length of the side of the largest square } FDGB \\text{ that can be inscribed in the triangle } ABE? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-339(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In parallelogram } A \\quad B \\quad C \\quad D, \\text{ point } P \\text{ divides } A \\quad B \\text{ in the ratio 2:3 and point } Q \\text{ divides } D \\quad C \\text{ in the ratio 4:1.} \\\\ &\\text{ Prove that } OC \\text{ is half of } OA. \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-339(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ Demonstrate that } \\triangle \\mathrm{BAE} \\sim \\triangle \\mathrm{CAD} \\text{ given that } \\frac{A D}{A E}=\\frac{A C}{B D} \\text{ and } \\angle 1=\\angle 2 \\text{ in the figure below.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-340(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ Analyze the triangles } \\triangle \\mathrm{OPQ} \\text{ and } \\triangle \\mathrm{OBA} \\text{ as shown in the figure.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-342'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In the given figure, with } G C \\| B D \\text{ and } G E \\| B F, \\text{ if } A C = 3 \\mathrm{~cm} \\text{ and } C D = 7 \\mathrm{~cm}, \\text{ determine the relationship between the segments.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-343'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ If } X \\text{ is the midpoint of } AC \\text{ and } XY \\parallel AB, \\text{ what can be concluded about } Y \\text{ in } \\triangle ABC? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-343(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In } \\triangle ABC, \\text{ if } DE \\parallel BC, \\text{ what is the relationship between the segments?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-344'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ According to the Basic Proportionality Theorem, if } DE \\parallel BC \\text{ in } \\triangle ABC, \\text{ what is the ratio of } \\frac{AD}{DB} \\text{ to } \\frac{AE}{EC}? \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-345'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ In } \\triangle ABC, \\text{ if } DE \\parallel BC \\text{ and intersects } AB \\text{ at } D \\text{ and } AC \\text{ at } E, \\text{ what needs to be proven about the segments?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-346'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{ What does the diagram illustrate about the relationships between the segments in the triangle?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-347'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{Identify the correct ray diagram for the given scenario.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-348(1)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In triangles } \\triangle \\mathrm{ABC} \\text{ and } \\triangle \\mathrm{DEF}, \\text{ if } \\frac{AB}{DE} = \\frac{BC}{FD}, \\text{ which similarity criterion is applied?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-348'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{Determine the correct representation of the given geometric figure.} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-348(2)'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{Given } AB \\text{ as the pole and } PQ \\text{ as the tower, if } \\triangle \\mathrm{ABC} \\sim \\triangle \\mathrm{PQR}, \\text{ what is the height of the tower?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-349'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{If } \\frac{EA}{EC} = \\frac{EB}{ED}, \\text{ which theorem or property is being used?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-350'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In triangles } \\triangle ABC \\text{ and } \\triangle PQR, \\text{ if } AD \\text{ and } PM \\text{ are medians corresponding to sides } BC \\text{ and } QR \\text{ respectively, and } \\\\ &\\frac{AB}{PQ} = \\frac{BC}{QR} = \\frac{AD}{PM}, \\text{ which similarity criterion is applicable here?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-352'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{Consider } AB \\text{ as a lamp post and } CD \\text{ as the height of a girl, with } DE = x \\text{ being the length of her shadow.} \\\\ &\\text{What principle can be used to find the relationship between the heights and the shadow length?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-354'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In triangles } \\triangle ADE \\text{ and } \\triangle PQR, \\text{ if } AD \\text{ and } PM \\text{ are medians such that } \\\\ &\\frac{AB}{PQ} = \\frac{BC}{QR} = \\frac{AD}{PM}, \\text{ which similarity criterion is applicable here?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-356'}]}},
  {'question': {'question_text': '\\begin{aligned} &\\text{In triangles } \\triangle AEL \\text{ and } \\triangle CBL, \\text{ given that } \\angle 1 = \\angle 6 \\text{ and } \\angle 4 = \\angle 5, \\\\ &\\text{what can be concluded about the similarity of these triangles?} \\end{aligned}',
    'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-357'}]}},

# Solution and Distractors(Based on misconceptions)

In [19]:
llm = ChatOpenAI(model="gpt-4o", temperature=0.2, api_key = OPENAI_API_KEY ,  request_timeout=30.0)

In [20]:
questions_df = pd.DataFrame(clean_rephrased_questions_json)
questions_df

,questions,topic,topic_id
0,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2
1,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2
2,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2
3,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2
4,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2
...,...,...,...
94,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2
95,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2
96,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2
97,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2
98,{'question': {'question_text': '\begin{aligned...,Basic Proportionality Theorem,10_mathematics_triangles_2

In [21]:
import json
def parse_Response(response):
    if isinstance(response, str):
        # print(response)
        start_index = response.find("{")
        end_index = response.rfind("}")
        if start_index != -1 and end_index != -1:
            valid_json_content = response[start_index : end_index + 1]
            try:
                JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
                # append_list_to_file(JSON_response)
                return JSON_response
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON response: {e.__class__.__name__} - {e}\n\n Still trying to work on particular exceptions ...")
                if str(e).startswith("Extra data"):
                    json_parts = valid_json_content.split('}\n{')
                    if json_parts:
                        first_json = json_parts[0] + '}'
                        return parse_Response(first_json)  
                elif str(e).startswith("Invalid \escape"):
                    print("Before removing \\ issue: ", valid_json_content)
                    str1 = valid_json_content.replace("\\\\\\\\\\", "fvback")
                    str1 = str1.replace("\\\\\\\\", "frback")
                    str1 = str1.replace("\\\\\\", "trlback")
                    str1 = str1.replace("\\\\", "dblback")
                    str1 = str1.replace("\\", "\\\\")
                    str1 = str1.replace("fvback","\\\\\\\\\\")
                    str1 = str1.replace("frback", "\\\\\\\\")
                    str1 = str1.replace("trlback","\\\\\\")
                    strfinal = str1.replace("dblback","\\\\")
                    print("After removing \\ issue: ", strfinal)
                    JSON_response = json.loads(strfinal.replace("\n", ""))
                    return JSON_response
                else:
                    print("Actual Content: ", valid_json_content)
        else:
            print("No valid JSON content found in the response.")
        # time.sleep(50)
    elif isinstance(response, dict):
        return response
    else:
        print("No response message found", type(response))

<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_24708\3339088456.py:10: SyntaxWarning: invalid escape sequence '\('
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_24708\3339088456.py:10: SyntaxWarning: invalid escape sequence '\)'
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_24708\3339088456.py:20: SyntaxWarning: invalid escape sequence '\e'
  elif str(e).startswith("Invalid \escape"):

In [22]:
prompt_template = PromptTemplate(
    input_variables=["system_prompt", "question", "topic", "topic_id", "lulist"],
    template="{system_prompt}\n\n\nGenerate a hint, and solution for the given question. Also rephrase the given question according to the specified steps.\nHere are the required context:\nQuestion: {question}\nLearning unit data which defines scope from which solution should be generated: {lulist}\nTopic: {topic}\nTopic ID: {topic_id}\n\nReturn the output in the specified JSON format."
)

chain = LLMChain(llm=llm, prompt=prompt_template)

def generate_explanation(subject, question_data, topic, topic_id):
    try:
        match subject:
            case "mathematics":
                system = MATHEMATICS_SOLUTION_SYSTEM_PROMPT
            case "biology":
                system = BIOLOGY_SOLUTION_SYSTEM_PROMPT
            case "physics":
                system = PHYSICS_SOLUTION_SYSTEM_PROMPT
            case "chemistry":
                system = CHEMISTRY_SOLUTION_SYSTEM_PROMPT

        # Construct question text with image references
        question_text = question_data['question_text']
        if 'image_ids' in question_data:
            image_refs = [list(img.values())[0] for img in question_data['image_ids']]
            image_str = "\nReference Images: " + ", ".join(image_refs)
            question_text += image_str

        response = chain.run(
            system_prompt=system,
            lulist=total_LUs,
            question=question_text,
            topic=topic,
            topic_id=topic_id
        )
        return response
    except Exception as e:
        print(f"Error processing question: {question_text}\nError: {str(e)}")
        return None

explanations = []

def process_questions(subject, questions_data):
    questions = questions_data['questions']
    topic = questions_data['topic']
    topic_id = questions_data['topic_id']
    
    counter = 0
    retries_counter = 0
    maxCounter = len(questions)
    
    while counter < maxCounter:
        question_data = questions[counter]['question']
        print(f"Processing question {counter + 1} out of {len(questions)}")
        
        explanation = generate_explanation(subject, question_data, topic, topic_id)
        parsed_explanation = parse_Response(explanation)
        
        if parsed_explanation:
            parsed_explanation["question"] = question_data['question_text']
            parsed_explanation["topic"] = topic
            parsed_explanation["topic_id"] = topic_id
            # Add image references to the parsed explanation if they exist
            if 'image_ids' in question_data:
                parsed_explanation["image_ids"] = question_data['image_ids']
            
            explanations.append(parsed_explanation)
            counter += 1
            retries_counter = 0
        else:
            print("Issue in openai response", explanation, "\n\n Inputs: \n\n", 
                  question_data['question_text'], "\n\n Topic: ", topic)
            print(f"Failed to parse explanation or generate solution for question {counter + 1}, retrying...")
            retries_counter += 1
            
        if retries_counter == 3:
            counter += 1

process_questions(subject, clean_rephrased_questions_json)

C:\Users\aniket singh\AppData\Local\Temp\ipykernel_24708\840063619.py:6: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  chain = LLMChain(llm=llm, prompt=prompt_template)
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_24708\840063619.py:27: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  response = chain.run(

Processing question 1 out of 99
Processing question 2 out of 99
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 389 (char 388)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } DE. \\end{aligned}",
  "solution": "\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{DE}{BC} \\\\ &\\implies \\frac{2}{3} = \\frac{DE}{7.5} \\\\ &\\therefore DE = \\frac{2}{3} \\times 7.5 \\\\ &\\implies DE = 5 \, \\text{cm} \\\\ \\end{aligned}"
}
After removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } DE. \\end{aligned}",
  "solution": "\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{DE}{BC} \\\\ &\\implies \\frac{2}{3} = \\frac{DE}{7.5} \\\\ &\\therefore DE = \\frac{2}{3} \\times 7.5 \\\\ &\\implies DE = 5 \\, \\text{cm} \\\\ \\end{aligned}"
}
Processing question 3 out of 99
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 377 (char 376)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: } \\frac{AD}{DB} = \\frac{AE}{EC} \\end{aligned}",
  "solution": "\\begin{aligned} &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\quad \\frac{2.4}{4} = \\frac{2}{EC} \\\\ &\\implies \\quad EC = \\frac{2 \\times 4}{2.4} \\\\ &\\implies \\quad EC = \\frac{8}{2.4} \\\\ &\\implies \\quad EC = 3.3333 \, \\text{cm} \\\\ &\\therefore \\quad AC = AE + EC = 2 + 3.3333 = 5.3333 \, \\text{cm} \\\\ \\end{aligned}"
}
After removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: } \\frac{AD}{DB} = \\frac{AE}{EC} \\end{aligned}",
  "solution": "\\begin{aligned} &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\quad \\frac{2.4}{4} = \\frac{2}{EC} \\\\ &\\implies \\quad EC = \\frac{2 \\times 4}{2.4} \\\\ &\\implies \\quad EC = \\frac{8}{2.4} \\\\ &\\implies \\quad EC = 3.3333 \\, \\text{cm} \\\\ &\\therefore \\quad AC = AE + EC = 2 + 3.3333 = 5.3333 \\, \\text{cm} \\\\ \\end{aligned}"
}
Processing question 4 out of 99
Processing question 5 out of 99
Processing question 6 out of 99
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 453 (char 452)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } OP \\end{aligned}",
  "solution": "\\begin{aligned} &\\text{Given } AB \\parallel PQ, \\text{ so by Basic Proportionality Theorem, } \\frac{AB}{PQ} = \\frac{OB}{OP} \\\\ &\\implies \\quad \\frac{6}{2} = \\frac{3}{OP} \\\\ &\\implies \\quad 3 = \\frac{3}{OP} \\\\ &\\implies \\quad OP = 1 \\\\ &\\therefore \\quad \\text{The length of } OP \\text{ is } 1 \, \\text{cm} \\end{aligned}"
}
After removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } OP \\end{aligned}",
  "solution": "\\begin{aligned} &\\text{Given } AB \\parallel PQ, \\text{ so by Basic Proportionality Theorem, } \\frac{AB}{PQ} = \\frac{OB}{OP} \\\\ &\\implies \\quad \\frac{6}{2} = \\frac{3}{OP} \\\\ &\\implies \\quad 3 = \\frac{3}{OP} \\\\ &\\implies \\quad OP = 1 \\\\ &\\therefore \\quad \\text{The length of } OP \\text{ is } 1 \\, \\text{cm} \\end{aligned}"
}
Processing question 7 out of 99
Processing question 8 out of 99
Processing question 9 out of 99
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 516 (char 515)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: If a line is parallel to one side of a triangle, it divides the other two sides proportionally.} \\end{aligned}",
  "solution": "\\begin{aligned} &\\text{Given: } PQ \\parallel AC, \\text{ so by Basic Proportionality Theorem,} \\\\ &\\frac{BP}{AP} = \\frac{BQ}{QC} \\\\ &\\implies \\frac{4}{2.4} = \\frac{5}{QC} \\\\ &\\implies 4 \\times QC = 5 \\times 2.4 \\\\ &\\implies 4QC = 12 \\\\ &\\implies QC = \\frac{12}{4} \\\\ &\\implies QC = 3 \, \\text{cm} \\\\ &\\therefore BC = BQ + QC = 5 + 3 = 8 \, \\text{cm} \\end{aligned}"
}
After removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: If a line is parallel to one side of a triangle, it divides the other two sides proportionally.} \\end{aligned}",
  "solution": "\\begin{aligned} &\\text{Given: } PQ \\parallel AC, \\text{ so by Basic Proportionality Theorem,} \\\\ &\\frac{BP}{AP} = \\frac{BQ}{QC} \\\\ &\\implies \\frac{4}{2.4} = \\frac{5}{QC} \\\\ &\\implies 4 \\times QC = 5 \\times 2.4 \\\\ &\\implies 4QC = 12 \\\\ &\\implies QC = \\frac{12}{4} \\\\ &\\implies QC = 3 \\, \\text{cm} \\\\ &\\therefore BC = BQ + QC = 5 + 3 = 8 \\, \\text{cm} \\end{aligned}"
}
Processing question 10 out of 99
Processing question 11 out of 99
Processing question 12 out of 99
Processing question 13 out of 99
Processing question 14 out of 99
Processing question 15 out of 99
Processing question 16 out of 99
Processing question 17 out of 99
Processing question 18 out of 99
Processing question 19 out of 99
Processing question 20 out of 99
Processing question 21 out of 99
Processing question 22 out of 99
Processing question 23 out of 99
Processing question 24 out of 99
Processing question 25 out of 99
Processing question 26 out of 99
Processing question 27 out of 99
Processing question 28 out of 99
Processing question 29 out of 99
Processing question 30 out of 99
Processing question 31 out of 99
Processing question 32 out of 99
Processing question 33 out of 99
Processing question 34 out of 99
Processing question 35 out of 99
Processing question 36 out of 99
Processing question 37 out of 99
Processing question 38 out of 99
Processing question 39 out of 99
Processing question 40 out of 99
Processing question 41 out of 99
Processing question 42 out of 99
Processing question 43 out of 99
Processing question 44 out of 99
Processing question 45 out of 99
Processing question 46 out of 99
Processing question 47 out of 99
Processing question 48 out of 99
Processing question 49 out of 99
Processing question 50 out of 99
Processing question 51 out of 99
Processing question 52 out of 99
Processing question 53 out of 99
Processing question 54 out of 99
Processing question 55 out of 99
Processing question 56 out of 99
Processing question 57 out of 99
Processing question 58 out of 99
Processing question 59 out of 99
Processing question 60 out of 99
Processing question 61 out of 99
Processing question 62 out of 99
Processing question 63 out of 99
Processing question 64 out of 99
Processing question 65 out of 99
Processing question 66 out of 99
Processing question 67 out of 99
Processing question 68 out of 99
Processing question 69 out of 99
Processing question 70 out of 99
Processing question 71 out of 99
Processing question 72 out of 99
Processing question 73 out of 99
Processing question 74 out of 99
Processing question 75 out of 99
Processing question 76 out of 99
Processing question 77 out of 99
Processing question 78 out of 99
Processing question 79 out of 99
Processing question 80 out of 99
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 426 (char 425)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the formula for the area of a triangle and the properties of similar triangles} \\end{aligned}",
  "solution": "\\begin{aligned} &\\text{Given } \\triangle ABC \\text{ is right angled at } A \\text{ and } AD \\perp BC. \\\\ &\\text{Area of } \\triangle ABC = \\frac{1}{2} \\times AC \\times BC \\\\ &\\implies \\text{Area of } \\triangle ABC = \\frac{1}{2} \\times 5 \\times 13 = 32.5 \, \\text{cm}^2 \\\\ &\\text{Area of } \\triangle ADC = \\frac{1}{2} \\times AD \\times DC \\\\ &\\text{Since } AD \\perp BC, \\text{ } \\triangle ADC \\sim \\triangle ABC \\text{ by AA similarity} \\\\ &\\text{Therefore, } \\frac{AD}{AC} = \\frac{DC}{BC} \\\\ &\\implies \\frac{AD}{5} = \\frac{DC}{13} \\\\ &\\text{Let } AD = x, \\text{ then } DC = \\frac{13}{5}x \\\\ &\\text{Area of } \\triangle ADC = \\frac{1}{2} \\times x \\times \\frac{13}{5}x = \\frac{13}{10}x^2 \\\\ &\\text{Ratio of areas } = \\frac{\\text{Area of } \\triangle ABC}{\\text{Area of } \\triangle ADC} \\\\ &\\implies \\frac{32.5}{\\frac{13}{10}x^2} \\\\ &\\text{Since } \\triangle ABC \\text{ and } \\triangle ADC \\text{ are similar, } \\frac{32.5}{\\frac{13}{10}x^2} = \\frac{13}{5} \\\\ &\\therefore \\text{Ratio of areas } = 13:5 \\\\ \\end{aligned}"
}
After removing \ issue:  {
  "hint": "\\begin{aligned} &\\text{Use the formula for the area of a triangle and the properties of similar triangles} \\end{aligned}",
  "solution": "\\begin{aligned} &\\text{Given } \\triangle ABC \\text{ is right angled at } A \\text{ and } AD \\perp BC. \\\\ &\\text{Area of } \\triangle ABC = \\frac{1}{2} \\times AC \\times BC \\\\ &\\implies \\text{Area of } \\triangle ABC = \\frac{1}{2} \\times 5 \\times 13 = 32.5 \\, \\text{cm}^2 \\\\ &\\text{Area of } \\triangle ADC = \\frac{1}{2} \\times AD \\times DC \\\\ &\\text{Since } AD \\perp BC, \\text{ } \\triangle ADC \\sim \\triangle ABC \\text{ by AA similarity} \\\\ &\\text{Therefore, } \\frac{AD}{AC} = \\frac{DC}{BC} \\\\ &\\implies \\frac{AD}{5} = \\frac{DC}{13} \\\\ &\\text{Let } AD = x, \\text{ then } DC = \\frac{13}{5}x \\\\ &\\text{Area of } \\triangle ADC = \\frac{1}{2} \\times x \\times \\frac{13}{5}x = \\frac{13}{10}x^2 \\\\ &\\text{Ratio of areas } = \\frac{\\text{Area of } \\triangle ABC}{\\text{Area of } \\triangle ADC} \\\\ &\\implies \\frac{32.5}{\\frac{13}{10}x^2} \\\\ &\\text{Since } \\triangle ABC \\text{ and } \\triangle ADC \\text{ are similar, } \\frac{32.5}{\\frac{13}{10}x^2} = \\frac{13}{5} \\\\ &\\therefore \\text{Ratio of areas } = 13:5 \\\\ \\end{aligned}"
}
Processing question 81 out of 99
Processing question 82 out of 99
Processing question 83 out of 99
Processing question 84 out of 99
Processing question 85 out of 99
Processing question 86 out of 99
Processing question 87 out of 99
Processing question 88 out of 99
Processing question 89 out of 99
Processing question 90 out of 99
Processing question 91 out of 99
Processing question 92 out of 99
Processing question 93 out of 99
Processing question 94 out of 99
Processing question 95 out of 99
Processing question 96 out of 99
Processing question 97 out of 99
Processing question 98 out of 99
Processing question 99 out of 99

In [28]:
explanations

[{'hint': '\\begin{aligned} &\\text{Apply the Basic Proportionality Theorem (Thales Theorem) to } \\triangle ABC \\text{ with } DE \\parallel BC \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } DE \\parallel BC \\text{ in } \\triangle ABC \\\\ &\\implies \\frac{AD}{DB} = \\frac{AE}{EC} \\quad \\text{[By Basic Proportionality Theorem]} \\\\ &\\therefore \\text{The relationship is } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ if } DE \\parallel BC, \\text{ what is the relationship between the segments } AD, DB, AE, \\text{ and } EC? \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-324'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } DE. \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{DE}{BC} \\\\ &\\implies \\frac{2}{3} = \\frac{DE}{7.5} \\\\ &\\therefore DE = \\frac{2}{3} \\times 7.5 \\\\ &\\implies DE = 5 \\, \\text{cm} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ with } DE \\parallel BC, \\text{ given } AD = 2 \\, \\text{cm}, BD = 3 \\, \\text{cm}, \\text{ and } BC = 7.5 \\, \\text{cm}, \\text{ calculate the length of } DE. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-325'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: } \\frac{AD}{DB} = \\frac{AE}{EC} \\end{aligned}',
  'solution': '\\begin{aligned} &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\quad \\frac{2.4}{4} = \\frac{2}{EC} \\\\ &\\implies \\quad EC = \\frac{2 \\times 4}{2.4} \\\\ &\\implies \\quad EC = \\frac{8}{2.4} \\\\ &\\implies \\quad EC = 3.3333 \\, \\text{cm} \\\\ &\\therefore \\quad AC = AE + EC = 2 + 3.3333 = 5.3333 \\, \\text{cm} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the figure, } \\triangle ABC \\text{ has } DE \\parallel BC. \\text{ If } AD = 2.4 \\, \\text{cm}, DB = 4 \\, \\text{cm}, \\text{ and } AE = 2 \\, \\text{cm}, \\text{ find the length of } AC. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(2)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the length of } AE. \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\text{Substitute the given lengths:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\frac{3}{4} = \\frac{AE}{6} \\\\ &\\implies AE = \\frac{3}{4} \\times 6 \\\\ &\\therefore AE = 4.5 \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the figure, } DE \\parallel BC \\text{ and all measurements are in centimeters. Determine the length of } AE. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(1)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the value of } x. \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{2}{3} = \\frac{3}{x} \\\\ &\\implies 2x = 9 \\\\ &\\therefore x = \\frac{9}{2} \\text{ units} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the figure, } DE \\parallel BC. \\text{ If } AD = 2 \\text{ units, } DB = AE = 3 \\text{ units, and } EC = x \\text{ units, find the value of } x. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } OP \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } AB \\parallel PQ, \\text{ so by Basic Proportionality Theorem, } \\frac{AB}{PQ} = \\frac{OB}{OP} \\\\ &\\implies \\quad \\frac{6}{2} = \\frac{3}{OP} \\\\ &\\implies \\quad 3 = \\frac{3}{OP} \\\\ &\\implies \\quad OP = 1 \\\\ &\\therefore \\quad \\text{The length of } OP \\text{ is } 1 \\, \\text{cm} \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the given figure, if } AB \\parallel PQ, \\text{ and } AB = 6 \\, \\text{cm}, \\, PQ = 2 \\, \\text{cm}, \\text{ and } OB = 3 \\, \\text{cm}, \\text{ what is the length of } OP? \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(2)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the value of } x. \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ apply the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\text{Substitute the given values:} \\\\ &\\frac{3}{x} = \\frac{4}{6} \\\\ &\\implies 3 \\cdot 6 = 4 \\cdot x \\\\ &\\implies 18 = 4x \\\\ &\\implies x = \\frac{18}{4} \\\\ &\\implies x = 4.5 \\\\ &\\therefore x = 4.5 \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the given figure, } DE \\parallel BC. \\text{ Determine the value of } x. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(1)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } AC. \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given: } PQ \\parallel BC, \\text{ and } \\triangle APQ \\sim \\triangle ABC \\\\ &\\text{By Basic Proportionality Theorem: } \\frac{AP}{PB} = \\frac{AQ}{QC} \\\\ &\\implies \\frac{4}{6} = \\frac{8}{QC} \\\\ &\\implies 4 \\times QC = 6 \\times 8 \\\\ &\\implies QC = \\frac{48}{4} \\\\ &\\therefore QC = 12 \\\\ &\\text{Since } AC = AQ + QC \\\\ &\\implies AC = 8 + 12 \\\\ &\\therefore AC = 20 \\text{ cm} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In } \\triangle ABC, \\, PQ \\parallel BC. \\text{ If } PB = 6 \\, \\text{cm}, \\, AP = 4 \\, \\text{cm}, \\text{ and } AQ = 8 \\, \\text{cm}, \\text{ find the length of } AC. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: If a line is parallel to one side of a triangle, it divides the other two sides proportionally.} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given: } PQ \\parallel AC, \\text{ so by Basic Proportionality Theorem,} \\\\ &\\frac{BP}{AP} = \\frac{BQ}{QC} \\\\ &\\implies \\frac{4}{2.4} = \\frac{5}{QC} \\\\ &\\implies 4 \\times QC = 5 \\times 2.4 \\\\ &\\implies 4QC = 12 \\\\ &\\implies QC = \\frac{12}{4} \\\\ &\\implies QC = 3 \\, \\text{cm} \\\\ &\\therefore BC = BQ + QC = 5 + 3 = 8 \\, \\text{cm} \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the given figure, } PQ \\parallel AC. \\text{ If } BP = 4 \\, \\text{cm}, \\, AP = 2.4 \\, \\text{cm}, \\text{ and } BQ = 5 \\, \\text{cm}, \\text{ what is the length of } BC? \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(3)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the value of } x \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } \\frac{AP}{PB} = \\frac{AQ}{QC} \\\\ &\\implies \\frac{3}{x} = \\frac{4}{6} \\\\ &\\implies 3 \\times 6 = 4 \\times x \\\\ &\\implies 18 = 4x \\\\ &\\implies x = \\frac{18}{4} \\\\ &\\implies x = 4.5 \\\\ &\\therefore x = 4.5 \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the figure given below, determine the value of } x \\text{ that will make } PQ \\parallel AB. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(2)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } EC \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given: } DE \\parallel BC, \\frac{AD}{DB} = \\frac{3}{2}, AE = 2.7 \\text{ cm} \\\\ &\\text{By Basic Proportionality Theorem, } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{3}{2} = \\frac{2.7}{EC} \\\\ &\\implies 3 \\cdot EC = 2 \\cdot 2.7 \\\\ &\\implies 3 \\cdot EC = 5.4 \\\\ &\\therefore EC = \\frac{5.4}{3} \\\\ &\\therefore EC = 1.8 \\text{ cm} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the given figure, with } D E \\parallel B C, \\text{ if } \\frac{A D}{D B}=\\frac{3}{2} \\text{ and } A E=2.7 \\mathrm{~cm}, \\text{ determine the length of } E C. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(1)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the ratio } \\frac{AE}{AF} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Since } GE \\parallel BF, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AE}{EF} = \\frac{AC}{CD} \\\\ &\\implies \\frac{AE}{EF} = \\frac{3}{7} \\\\ &\\text{Let } AE = 3k \\text{ and } EF = 7k \\\\ &\\therefore AF = AE + EF = 3k + 7k = 10k \\\\ &\\implies \\frac{AE}{AF} = \\frac{3k}{10k} = \\frac{3}{10} \\\\ &\\therefore \\frac{AE}{AF} = \\frac{3}{10} \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the figure, given } G C \\perp B D \\text{ and } G E \\parallel B F, \\text{ with } A C=3 \\mathrm{~cm} \\text{ and } C D=7 \\mathrm{~cm}, \\text{ find the ratio } \\frac{A E}{A F}. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the value of } x. \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } DE \\parallel BC \\text{ in } \\triangle ABC. \\\\ &\\text{By Basic Proportionality Theorem, } \\frac{AD}{DB} = \\frac{AE}{EC}. \\\\ &\\text{Substitute the given values: } \\frac{AD}{DB} = \\frac{AE}{EC} = \\frac{x}{3} = \\frac{4}{6}. \\\\ &\\implies \\quad \\frac{x}{3} = \\frac{2}{3}. \\\\ &\\therefore \\quad x = 2. \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In } \\triangle A B C, \\text{ with } D E \\parallel B C, \\text{ calculate the value of } x. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(2)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } EC \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\frac{AD}{DB} = \\frac{3}{4}, \\text{ and } AC = 14 \\text{ cm} \\\\ &\\text{By Basic Proportionality Theorem, } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{3}{4} = \\frac{AE}{EC} \\\\ &\\text{Let } AE = 3x \\text{ and } EC = 4x \\\\ &\\therefore AE + EC = AC \\\\ &\\implies 3x + 4x = 14 \\\\ &\\implies 7x = 14 \\\\ &\\therefore x = 2 \\\\ &\\therefore EC = 4x = 4 \\times 2 = 8 \\text{ cm} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the given figure, } D E \\parallel B C. \\text{ If } \\frac{A D}{D B}=\\frac{3}{4} \\text{ and } A C=14 \\mathrm{~cm}, \\text{ find the length of } E C. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(3)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the proportionality between segments.} \\\\ &\\text{Apply the theorem to } \\triangle BEC \\text{ and } \\triangle DEF. \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } DE \\parallel AC \\text{ and } DC \\parallel AP. \\\\ &\\text{In } \\triangle BEC, \\text{ since } DE \\parallel AC, \\text{ by Basic Proportionality Theorem,} \\\\ &\\frac{BF}{FE} = \\frac{BE}{EC}. \\\\ &\\therefore \\text{ Proved that } \\frac{BF}{FE} = \\frac{BE}{EC}. \\end{aligned}',
  'question': '\\begin{aligned} &\\text{In the figure, } D E \\parallel A C \\text{ and } D C \\parallel A P. \\text{ Prove that } \\frac{B F}{F E}=\\frac{B E}{E C}. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329'}]},
 {'hint': '\\begin{aligned} &\\text{Use Basic Proportionality Theorem which states that if a line is parallel to one side of a triangle, it divides the other two sides proportionally.} \\\\ &\\text{Apply the theorem to triangles } \\triangle BEC \\text{ and } \\triangle BCP. \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given: } DE \\parallel AC \\text{ and } DC \\parallel AP. \\\\ &\\text{In } \\triangle BEC, \\text{ since } DE \\parallel AC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{BE}{EC} = \\frac{BD}{DA}. \\\\ &\\text{In } \\triangle BCP, \\text{ since } DC \\parallel AP, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{BD}{DA} = \\frac{BC}{CP}. \\\\ &\\therefore \\frac{BE}{EC} = \\frac{BC}{CP}. \\end{aligned}',
  'question': '\\begin{aligned} &\\text{ In the given figure, if } D E \\parallel A C \\text{ and } D C \\parallel A P, \\text{ demonstrate that } \\frac{B E}{E C} = \\frac{B C}{C P}. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(1)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to relate the segments in the triangles formed by parallel lines and transversals.} \\\\ \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{In } \\triangle PQR \\text{ and } \\triangle PCD, \\text{ since } PR \\parallel CD, \\text{ by Basic Proportionality Theorem,} \\\\ &\\frac{PQ}{QC} = \\frac{PR}{RD} \\\\ &\\text{In } \\triangle APQ \\text{ and } \\triangle ADR, \\text{ since } PR \\parallel CD, \\text{ by Basic Proportionality Theorem,} \\\\ &\\frac{AQ}{QB} = \\frac{AR}{RD} \\\\ &\\therefore \\frac{QB}{AQ} = \\frac{DR}{AR} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{ In the figure, given that } P Q \\perp B C \\text{ and } P R \\parallel C D, \\text{ show that } \\frac{Q B}{A Q} = \\frac{D R}{A R}. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-329(4)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem and properties of similar triangles to prove } \\triangle ABC \\text{ is isosceles.} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } \\angle D = \\angle E \\text{ and } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\triangle ADE \\sim \\triangle BDC \\quad \\text{[By AA similarity criterion]} \\\\ &\\text{Since } \\triangle ADE \\sim \\triangle BDC, \\text{ we have } \\frac{AD}{DB} = \\frac{AE}{EC} = \\frac{DE}{DC} \\\\ &\\text{Given } \\frac{AD}{DB} = \\frac{AE}{EC} \\implies \\frac{DE}{DC} = 1 \\\\ &\\therefore DE = DC \\\\ &\\text{Thus, } \\triangle ABC \\text{ is isosceles with } AB = AC \\end{aligned}',
  'question': '\\begin{aligned} &\\text{ In the figure, if } \\angle D = \\angle E \\text{ and } \\frac{A D}{D B} = \\frac{A E}{E C}, \\text{ prove that } \\triangle A B C \\text{ is an isosceles triangle.} \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330(2)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the properties of parallel lines and similar triangles to establish proportionality relationships} \\\\ &\\text{and apply the Basic Proportionality Theorem to prove the required relation.} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ since } PQ \\parallel BA, \\text{ we have } \\triangle SPQ \\sim \\triangle SBA \\quad \\text{(AAA similarity criterion)} \\\\ &\\implies \\frac{SP}{SB} = \\frac{SQ}{SA} \\\\ &\\text{Similarly, since } PR \\parallel CA, \\text{ we have } \\triangle SPR \\sim \\triangle SCA \\quad \\text{(AAA similarity criterion)} \\\\ &\\implies \\frac{SP}{SC} = \\frac{SR}{SA} \\\\ &\\text{Since } RQ \\text{ is extended to meet } BC \\text{ produced at } S, \\text{ we have } \\triangle SQR \\sim \\triangle SBA \\quad \\text{(AAA similarity criterion)} \\\\ &\\implies \\frac{SQ}{SB} = \\frac{SR}{SA} \\\\ &\\text{From the above, } \\frac{SP}{SB} = \\frac{SQ}{SA} \\text{ and } \\frac{SP}{SC} = \\frac{SR}{SA} \\\\ &\\text{Multiplying these, we get } \\left(\\frac{SP}{SB}\\right) \\cdot \\left(\\frac{SP}{SC}\\right) = \\left(\\frac{SQ}{SA}\\right) \\cdot \\left(\\frac{SR}{SA}\\right) \\\\ &\\implies \\frac{SP^2}{SB \\cdot SC} = \\frac{SQ \\cdot SR}{SA^2} \\\\ &\\text{Since } SQ \\cdot SR = SA^2, \\text{ we have } SP^2 = SB \\cdot SC \\end{aligned}',
  'question': '\\begin{aligned} &\\text{ In the figure, } P \\text{ is any point on side } B C \\text{ of } \\triangle A B C. \\text{ If } P Q \\parallel B A \\text{ and } P R \\parallel C A, \\text{ and } R Q \\text{ is extended to meet } B C \\text{ produced at } S, \\text{ prove that } S P^{2} = S B \\times S C. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330'}]},
 {'hint': '\\begin{aligned} &\\text{Use the property of similar triangles: } \\frac{AC}{QR} = \\frac{BC}{PR} \\end{aligned}',
  'solution': '\\begin{aligned} &\\frac{AC}{QR} = \\frac{BC}{PR} \\\\ &\\implies \\frac{6}{3} = \\frac{5}{x} \\\\ &\\implies 2 = \\frac{5}{x} \\\\ &\\implies 2x = 5 \\\\ &\\therefore x = \\frac{5}{2} \\\\ &\\therefore x = 2.5 \\text{ cm} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{ In the given figure, } \\triangle A B C \\sim \\triangle Q P R. \\text{ If } A C = 6 \\text{ cm, } B C = 5 \\text{ cm, } Q R = 3 \\text{ cm,} \\text{ find the value of } x \\text{ when } P R = x. \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',
  'topic_id': '10_mathematics_triangles_2',
  'image_ids': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-330(1)'}]},
 {'hint': '\\begin{aligned} &\\text{Use the property of complementary angles and the fact that } AD \\perp BC \\text{ implies } \\angle ADB = 90^\\circ \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given } \\angle ABC + \\angle ACB = 90^\\circ \\quad \\text{(complementary angles)} \\\\\\ &\\text{Since } AD \\perp BC, \\quad \\angle ADB = 90^\\circ \\\\\\ &\\implies \\angle ABC + \\angle ACB + \\angle ADB = 180^\\circ \\\\\\ &\\therefore \\text{Triangle } ABC \\text{ is a right triangle with } \\angle ADB = 90^\\circ \\\\\\ &\\text{Conclusion: } \\angle ABC \\text{ and } \\angle ACB \\text{ are complementary, } \\angle ADB = 90^\\circ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{ If } \\angle ABC \\text{ and } \\angle ACB \\text{ are complementary angles in the given figure, and } AD \\perp BC, \\text{ what can be concluded?} \\end{aligned}',
  'topic': 'Basic Proportionality Theorem',

### Generating Distractors

In [24]:
data = pd.DataFrame(explanations)

In [25]:
data['misconception_options'] = ''
data

,hint,solution,question,topic,topic_id,image_ids,misconception_options
0,\begin{aligned} &\text{Apply the Basic Proport...,\begin{aligned} &\text{Given } DE \parallel BC...,"\begin{aligned} &\text{In } \triangle ABC, \te...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,
1,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } DE \parallel BC...,"\begin{aligned} &\text{In } \triangle ABC, \te...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,
2,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\frac{AD}{DB} = \frac{AE}{EC}...,"\begin{aligned} &\text{In the figure, } \trian...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,
3,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } DE \parallel BC...,"\begin{aligned} &\text{In the figure, } DE \pa...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,
4,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } DE \parallel BC...,"\begin{aligned} &\text{In the figure, } DE \pa...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,
...,...,...,...,...,...,...,...
94,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } PQ \parallel BC...,\begin{aligned} &\text{ If } P \quad Q \mid \m...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,
95,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } \triangle ABC \...,\begin{aligned} &\text{ In } \triangle A \quad...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,
96,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Since } E \quad F \mid ...,\begin{aligned} &\text{ In triangle } A \quad ...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,
97,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } \angle PQR = 90...,\begin{aligned} &\text{ In } \triangle P \quad...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,
98,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{In } \triangle A \quad ...,\begin{aligned} &\text{ Consider a triangle } ...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,

In [26]:
for i in range(len(data)):
    print(data['solution'][i].split("\n"))

['\\begin{aligned} &\\text{Given } DE \\parallel BC \\text{ in } \\triangle ABC \\\\ &\\implies \\frac{AD}{DB} = \\frac{AE}{EC} \\quad \\text{[By Basic Proportionality Theorem]} \\\\ &\\therefore \\text{The relationship is } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{DE}{BC} \\\\ &\\implies \\frac{2}{3} = \\frac{DE}{7.5} \\\\ &\\therefore DE = \\frac{2}{3} \\times 7.5 \\\\ &\\implies DE = 5 \\, \\text{cm} \\\\ \\end{aligned}']
['\\begin{aligned} &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\quad \\frac{2.4}{4} = \\frac{2}{EC} \\\\ &\\implies \\quad EC = \\frac{2 \\times 4}{2.4} \\\\ &\\implies \\quad EC = \\frac{8}{2.4} \\\\ &\\implies \\quad EC = 3.3333 \\, \\text{cm} \\\\ &\\therefore \\quad AC = AE + EC = 2 + 3.3333 = 5.3333 \\, \\text{cm} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\text{Substitute the given lengths:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\frac{3}{4} = \\frac{AE}{6} \\\\ &\\implies AE = \\frac{3}{4} \\times 6 \\\\ &\\therefore AE = 4.5 \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{2}{3} = \\frac{3}{x} \\\\ &\\implies 2x = 9 \\\\ &\\therefore x = \\frac{9}{2} \\text{ units} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given } AB \\parallel PQ, \\text{ so by Basic Proportionality Theorem, } \\frac{AB}{PQ} = \\frac{OB}{OP} \\\\ &\\implies \\quad \\frac{6}{2} = \\frac{3}{OP} \\\\ &\\implies \\quad 3 = \\frac{3}{OP} \\\\ &\\implies \\quad OP = 1 \\\\ &\\therefore \\quad \\text{The length of } OP \\text{ is } 1 \\, \\text{cm} \\end{aligned}']
['\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ apply the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\text{Substitute the given values:} \\\\ &\\frac{3}{x} = \\frac{4}{6} \\\\ &\\implies 3 \\cdot 6 = 4 \\cdot x \\\\ &\\implies 18 = 4x \\\\ &\\implies x = \\frac{18}{4} \\\\ &\\implies x = 4.5 \\\\ &\\therefore x = 4.5 \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given: } PQ \\parallel BC, \\text{ and } \\triangle APQ \\sim \\triangle ABC \\\\ &\\text{By Basic Proportionality Theorem: } \\frac{AP}{PB} = \\frac{AQ}{QC} \\\\ &\\implies \\frac{4}{6} = \\frac{8}{QC} \\\\ &\\implies 4 \\times QC = 6 \\times 8 \\\\ &\\implies QC = \\frac{48}{4} \\\\ &\\therefore QC = 12 \\\\ &\\text{Since } AC = AQ + QC \\\\ &\\implies AC = 8 + 12 \\\\ &\\therefore AC = 20 \\text{ cm} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given: } PQ \\parallel AC, \\text{ so by Basic Proportionality Theorem,} \\\\ &\\frac{BP}{AP} = \\frac{BQ}{QC} \\\\ &\\implies \\frac{4}{2.4} = \\frac{5}{QC} \\\\ &\\implies 4 \\times QC = 5 \\times 2.4 \\\\ &\\implies 4QC = 12 \\\\ &\\implies QC = \\frac{12}{4} \\\\ &\\implies QC = 3 \\, \\text{cm} \\\\ &\\therefore BC = BQ + QC = 5 + 3 = 8 \\, \\text{cm} \\end{aligned}']
['\\begin{aligned} &\\text{Given } \\frac{AP}{PB} = \\frac{AQ}{QC} \\\\ &\\implies \\frac{3}{x} = \\frac{4}{6} \\\\ &\\implies 3 \\times 6 = 4 \\times x \\\\ &\\implies 18 = 4x \\\\ &\\implies x = \\frac{18}{4} \\\\ &\\implies x = 4.5 \\\\ &\\therefore x = 4.5 \\end{aligned}']
['\\begin{aligned} &\\text{Given: } DE \\parallel BC, \\frac{AD}{DB} = \\frac{3}{2}, AE = 2.7 \\text{ cm} \\\\ &\\text{By Basic Proportionality Theorem, } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{3}{2} = \\frac{2.7}{EC} \\\\ &\\implies 3 \\cdot EC = 2 \\cdot 2.7 \\\\ &\\implies 3 \\cdot EC = 5.4 \\\\ &\\therefore EC = \\frac{5.4}{3} \\\\ &\\therefore EC = 1.8 \\text{ cm} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Since } GE \\parallel BF, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AE}{EF} = \\frac{AC}{CD} \\\\ &\\implies \\frac{AE}{EF} = \\frac{3}{7} \\\\ &\\text{Let } AE = 3k \\text{ and } EF = 7k \\\\ &\\therefore AF = AE + EF = 3k + 7k = 10k \\\\ &\\implies \\frac{AE}{AF} = \\frac{3k}{10k} = \\frac{3}{10} \\\\ &\\therefore \\frac{AE}{AF} = \\frac{3}{10} \\end{aligned}']
['\\begin{aligned} &\\text{Given } DE \\parallel BC \\text{ in } \\triangle ABC. \\\\ &\\text{By Basic Proportionality Theorem, } \\frac{AD}{DB} = \\frac{AE}{EC}. \\\\ &\\text{Substitute the given values: } \\frac{AD}{DB} = \\frac{AE}{EC} = \\frac{x}{3} = \\frac{4}{6}. \\\\ &\\implies \\quad \\frac{x}{3} = \\frac{2}{3}. \\\\ &\\therefore \\quad x = 2. \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given } DE \\parallel BC, \\frac{AD}{DB} = \\frac{3}{4}, \\text{ and } AC = 14 \\text{ cm} \\\\ &\\text{By Basic Proportionality Theorem, } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{3}{4} = \\frac{AE}{EC} \\\\ &\\text{Let } AE = 3x \\text{ and } EC = 4x \\\\ &\\therefore AE + EC = AC \\\\ &\\implies 3x + 4x = 14 \\\\ &\\implies 7x = 14 \\\\ &\\therefore x = 2 \\\\ &\\therefore EC = 4x = 4 \\times 2 = 8 \\text{ cm} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given } DE \\parallel AC \\text{ and } DC \\parallel AP. \\\\ &\\text{In } \\triangle BEC, \\text{ since } DE \\parallel AC, \\text{ by Basic Proportionality Theorem,} \\\\ &\\frac{BF}{FE} = \\frac{BE}{EC}. \\\\ &\\therefore \\text{ Proved that } \\frac{BF}{FE} = \\frac{BE}{EC}. \\end{aligned}']
['\\begin{aligned} &\\text{Given: } DE \\parallel AC \\text{ and } DC \\parallel AP. \\\\ &\\text{In } \\triangle BEC, \\text{ since } DE \\parallel AC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{BE}{EC} = \\frac{BD}{DA}. \\\\ &\\text{In } \\triangle BCP, \\text{ since } DC \\parallel AP, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{BD}{DA} = \\frac{BC}{CP}. \\\\ &\\therefore \\frac{BE}{EC} = \\frac{BC}{CP}. \\end{aligned}']
['\\begin{aligned} &\\text{In } \\triangle PQR \\text{ and } \\triangle PCD, \\text{ since } PR \\parallel CD, \\text{ by Basic Proportionality Theorem,} \\\\ &\\frac{PQ}{QC} = \\frac{PR}{RD} \\\\ &\\text{In } \\triangle APQ \\text{ and } \\triangle ADR, \\text{ since } PR \\parallel CD, \\text{ by Basic Proportionality Theorem,} \\\\ &\\frac{AQ}{QB} = \\frac{AR}{RD} \\\\ &\\therefore \\frac{QB}{AQ} = \\frac{DR}{AR} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given } \\angle D = \\angle E \\text{ and } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\triangle ADE \\sim \\triangle BDC \\quad \\text{[By AA similarity criterion]} \\\\ &\\text{Since } \\triangle ADE \\sim \\triangle BDC, \\text{ we have } \\frac{AD}{DB} = \\frac{AE}{EC} = \\frac{DE}{DC} \\\\ &\\text{Given } \\frac{AD}{DB} = \\frac{AE}{EC} \\implies \\frac{DE}{DC} = 1 \\\\ &\\therefore DE = DC \\\\ &\\text{Thus, } \\triangle ABC \\text{ is isosceles with } AB = AC \\end{aligned}']
['\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ since } PQ \\parallel BA, \\text{ we have } \\triangle SPQ \\sim \\triangle SBA \\quad \\text{(AAA similarity criterion)} \\\\ &\\implies \\frac{SP}{SB} = \\frac{SQ}{SA} \\\\ &\\text{Similarly, since } PR \\parallel CA, \\text{ we have } \\triangle SPR \\sim \\triangle SCA \\quad \\text{(AAA similarity criterion)} \\\\ &\\implies \\frac{SP}{SC} = \\frac{SR}{SA} \\\\ &\\text{Since } RQ \\text{ is extended to meet } BC \\text{ produced at } S, \\text{ we have } \\triangle SQR \\sim \\triangle SBA \\quad \\text{(AAA similarity criterion)} \\\\ &\\implies \\frac{SQ}{SB} = \\frac{SR}{SA} \\\\ &\\text{From the above, } \\frac{SP}{SB} = \\frac{SQ}{SA} \\text{ and } \\frac{SP}{SC} = \\frac{SR}{SA} \\\\ &\\text{Multiplying these, we get } \\left(\\frac{SP}{SB}\\right) \\cdot \\left(\\frac{SP}{SC}\\right) = \\left(\\frac{SQ}{SA}\\right) \\cdot \\left(\\frac{SR}{SA}\\right) \\\\ &\\implies \\frac{SP^2}{SB \\cdot SC} = \\frac{SQ \\cdot SR}{SA^2} \\\\ &\\text{Since } SQ \\cdot SR = SA^2, \\text{ we have } SP^2 = SB \\cdot SC \\end{aligned}']
['\\begin{aligned} &\\frac{AC}{QR} = \\frac{BC}{PR} \\\\ &\\implies \\frac{6}{3} = \\frac{5}{x} \\\\ &\\implies 2 = \\frac{5}{x} \\\\ &\\implies 2x = 5 \\\\ &\\therefore x = \\frac{5}{2} \\\\ &\\therefore x = 2.5 \\text{ cm} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given } \\angle ABC + \\angle ACB = 90^\\circ \\quad \\text{(complementary angles)} \\\\\\ &\\text{Since } AD \\perp BC, \\quad \\angle ADB = 90^\\circ \\\\\\ &\\implies \\angle ABC + \\angle ACB + \\angle ADB = 180^\\circ \\\\\\ &\\therefore \\text{Triangle } ABC \\text{ is a right triangle with } \\angle ADB = 90^\\circ \\\\\\ &\\text{Conclusion: } \\angle ABC \\text{ and } \\angle ACB \\text{ are complementary, } \\angle ADB = 90^\\circ \\end{aligned}']
['\\begin{aligned} &\\text{Given: } \\frac{a}{b} = \\frac{x}{c} \\quad \\text{[By Basic Proportionality Theorem]} \\\\\\ &\\implies \\quad x = \\frac{a \\cdot c}{b} \\\\\\ &\\therefore \\quad x = \\frac{ac}{b} \\\\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given: } BD \\text{ bisects } \\angle B \\text{ and } \\angle D \\\\ &\\implies \\angle ABD = \\angle CBD \\text{ and } \\angle ADB = \\angle CDB \\\\ &\\text{In } \\triangle ABD \\text{ and } \\triangle CBD: \\\\ &\\angle ABD = \\angle CBD \\quad \\text{(Given)} \\\\ &\\angle ADB = \\angle CDB \\quad \\text{(Given)} \\\\ &BD = BD \\quad \\text{(Common side)} \\\\ &\\therefore \\triangle ABD \\cong \\triangle CBD \\quad \\text{(By ASA criterion)} \\\\ &\\text{Hence, } ABCD \\text{ is a kite} \\end{aligned}']
['\\begin{aligned} &\\text{Given } \\frac{EA}{EC} = \\frac{EB}{ED} \\\\ &\\implies \\text{ By Converse of Basic Proportionality Theorem, } \\Delta EAB \\sim \\Delta ECD \\\\ &\\therefore \\text{ } \\Delta EAB \\sim \\Delta ECD \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{In } \\triangle AOD \\text{ and } \\triangle BOC, \\text{ we have } \\angle AOD = \\angle BOC \\text{ (vertically opposite angles)} \\\\ &\\text{and } \\angle OAD = \\angle OBC \\text{ (alternate interior angles as } AB \\parallel DC). \\\\ &\\therefore \\triangle AOD \\sim \\triangle BOC \\text{ (AAA similarity criterion)} \\\\ &\\implies \\frac{AO}{BO} = \\frac{AD}{BC} = \\frac{DO}{OB} \\\\ &\\text{Given } \\frac{DO}{OB} = \\frac{1}{2}, \\text{ so } \\frac{AD}{BC} = \\frac{1}{2} \\\\ &\\text{Since } AB \\parallel DC, \\text{ } AD = AB \\text{ and } BC = CD \\\\ &\\therefore \\frac{AB}{CD} = 2 \\\\ &\\therefore AB = 2CD \\end{aligned}']
['\\begin{aligned} &\\text{Given: } AZ = 3 \\, \\mathrm{cm}, \\, ZC = 2 \\, \\mathrm{cm}, \\, BM = 3 \\, \\mathrm{cm}, \\, MC = 5 \\, \\mathrm{cm} \\\\ &\\text{Since } XZ \\parallel BC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AZ}{ZC} = \\frac{BM}{MC} \\\\ &\\implies \\frac{3}{2} = \\frac{3}{5} \\\\ &\\text{Cross-multiplying gives:} \\\\ &3 \\times 5 = 2 \\times 3 \\\\ &15 = 6 \\\\ &\\therefore \\text{The length of } XY = 1.8 \\, \\mathrm{cm} \\end{aligned}']
['\\begin{aligned} &\\text{Given } PQ \\parallel BC, \\text{ so by Basic Proportionality Theorem:} \\\\ &\\frac{AP}{PB} = \\frac{AQ}{QC} \\\\ &\\text{Given } PQ = 3 \\, \\mathrm{cm}, \\, BC = 9 \\, \\mathrm{cm}, \\, AC = 7.5 \\, \\mathrm{cm} \\\\ &\\text{Let } AQ = x \\, \\mathrm{cm} \\\\ &\\text{Then } QC = AC - AQ = 7.5 - x \\\\ &\\frac{3}{9} = \\frac{x}{7.5 - x} \\\\ &\\implies \\frac{1}{3} = \\frac{x}{7.5 - x} \\\\ &\\implies 7.5 - x = 3x \\\\ &\\implies 7.5 = 4x \\\\ &\\implies x = \\frac{7.5}{4} \\\\ &\\therefore x = 1.875 \\, \\mathrm{cm} \\\\ &\\therefore AQ = 1.875 \\, \\mathrm{cm} \\end{aligned}']
['\\begin{aligned} &\\text{Given two triangles, } \\triangle ABC \\text{ and } \\triangle DEF. \\\\ &\\text{If } \\angle A = \\angle D \\text{ and } \\angle B = \\angle E, \\text{ then } \\triangle ABC \\sim \\triangle DEF. \\\\ &\\therefore \\text{Triangles are similar by AA similarity criterion.} \\end{aligned}']
['\\begin{aligned} &\\text{Given: } \\frac{AB}{PQ} = \\frac{BC}{QR} = \\frac{AD}{PM} \\\\ &\\text{Since } AD \\text{ and } PM \\text{ are medians, } \\frac{AB}{PQ} = \\frac{BC}{QR} = \\frac{AC}{PR} \\\\ &\\text{By SSS criterion, } \\triangle ABC \\sim \\triangle PQR \\\\ &\\therefore \\triangle ABC \\sim \\triangle PQR \\end{aligned}']
['\\begin{aligned} &\\text{In } \\triangle APQ \\text{ and } \\triangle BQR, \\text{ since } PA \\parallel QB, \\\\ &\\text{by Basic Proportionality Theorem, } \\frac{AP}{PQ} = \\frac{BQ}{QR} \\\\ &\\implies \\frac{x}{PQ} = \\frac{y}{QR} \\\\ &\\text{In } \\triangle BQR \\text{ and } \\triangle CRP, \\text{ since } QB \\parallel RC, \\\\ &\\text{by Basic Proportionality Theorem, } \\frac{BQ}{QR} = \\frac{CR}{RP} \\\\ &\\implies \\frac{y}{QR} = \\frac{z}{RP} \\\\ &\\text{Equating the two expressions for } \\frac{y}{QR}, \\\\ &\\frac{x}{PQ} = \\frac{z}{RP} \\\\ &\\implies x \\cdot RP = z \\cdot PQ \\\\ &\\therefore \\frac{1}{x} + \\frac{1}{z} = \\frac{1}{y} \\end{aligned}']
['\\begin{aligned} &\\text{Given } \\triangle FEC \\equiv \\triangle GDB \\text{ and } \\angle 1 = \\angle 2 \\\\ &\\implies \\angle FEC = \\angle GDB \\quad \\text{(corresponding angles of congruent triangles)} \\\\ &\\implies \\angle AEC = \\angle ABC \\quad \\text{(since } \\angle 1 = \\angle 2\\text{)} \\\\ &\\text{In } \\triangle AEC \\text{ and } \\triangle ABC: \\\\ &\\angle AEC = \\angle ABC \\quad \\text{(proved above)} \\\\ &\\angle ACE = \\angle ACB \\quad \\text{(common angle)} \\\\ &\\therefore \\triangle AEC \\sim \\triangle ABC \\quad \\text{(by AA similarity criterion)} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given that } AD \\text{ intersects } BC \\text{ at } O, \\text{ we apply the Basic Proportionality Theorem:} \\\\ &\\frac{AO}{DO} = \\frac{\\operatorname{ar}(\\triangle ABC)}{\\operatorname{ar}(\\triangle DBC)} \\\\ &\\therefore \\frac{\\operatorname{ar}(\\triangle ABC)}{\\operatorname{ar}(\\triangle DBC)} = \\frac{AO}{DO} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given } AB = AC \\text{ and } AD \\perp BC, EF \\perp AC \\\\ &\\implies \\angle ABD = \\angle ECF = 90^\\circ \\quad \\text{[Both are right angles]} \\\\ &\\text{Since } AB = AC, \\text{ then } \\angle BAC = \\angle ABC \\quad \\text{[Isosceles triangle property]} \\\\ &\\implies \\angle BAD = \\angle ECF \\quad \\text{[Corresponding angles]} \\\\ &\\therefore \\triangle ABD \\sim \\triangle ECF \\quad \\text{[AAA similarity criterion]} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given: } BC = 12 \\, \\mathrm{cm}, \\, HE = 6 \\, \\mathrm{cm} \\\\ &\\text{Since } GHED \\text{ is a rectangle, } HE = GD = 6 \\, \\mathrm{cm} \\\\ &\\text{Also, } BC = GH = 12 \\, \\mathrm{cm} \\\\ &\\implies \\text{Area of rectangle } GHED = GH \\times HE \\\\ &\\implies \\quad 12 \\, \\mathrm{cm} \\times 6 \\, \\mathrm{cm} \\\\ &\\therefore \\quad 72 \\, \\mathrm{cm}^2 \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{In } \\triangle ABC, \\angle B = 90^{\\circ} \\implies AB^2 + BC^2 = AC^2 \\\\ &\\text{Since } D \\text{ is the midpoint of } BC, \\text{ we have } BD = DC = \\frac{BC}{2} \\\\ &\\text{In } \\triangle ADC, \\angle ACD = 90^{\\circ} \\implies AD^2 + DC^2 = AC^2 \\\\ &\\text{Substitute } DC = \\frac{BC}{2} \\text{ in } AD^2 + DC^2 = AC^2 \\\\ &\\implies AD^2 + \\left(\\frac{BC}{2}\\right)^2 = AC^2 \\\\ &\\implies AD^2 + \\frac{BC^2}{4} = AC^2 \\\\ &\\text{From } \\triangle ABC, \\text{ substitute } BC^2 = AC^2 - AB^2 \\\\ &\\implies AD^2 + \\frac{AC^2 - AB^2}{4} = AC^2 \\\\ &\\implies 4AD^2 + AC^2 - AB^2 = 4AC^2 \\\\ &\\implies 4AD^2 = 3AC^2 + AB^2 \\\\ &\\therefore AC^2 = AD^2 + 3CD^2 \\end{aligned}']
['\\begin{aligned} &\\text{Let } \\triangle ABC \\text{ be a right triangle with } \\angle A = 90^\\circ. \\\\ &\\text{Medians } BN \\text{ and } CM \\text{ are drawn to sides } AC \\text{ and } AB \\text{ respectively.} \\\\ &\\text{Using the median formula: } \\\\ &BN^2 = \\frac{2AB^2 + 2AC^2 - BC^2}{4} \\\\ &CM^2 = \\frac{2AB^2 + 2BC^2 - AC^2}{4} \\\\ &\\therefore \\quad BN^2 + CM^2 = \\frac{2AB^2 + 2AC^2 - BC^2}{4} + \\frac{2AB^2 + 2BC^2 - AC^2}{4} \\\\ &\\implies \\quad BN^2 + CM^2 = \\frac{4AB^2 + 4AC^2}{4} \\\\ &\\implies \\quad BN^2 + CM^2 = AB^2 + AC^2 \\\\ &\\text{Since } \\triangle ABC \\text{ is right-angled at } A, \\text{ by Pythagorean theorem:} \\\\ &AB^2 + AC^2 = BC^2 \\\\ &\\therefore \\quad BN^2 + CM^2 = BC^2 \\\\ &\\therefore \\quad 4(BN^2 + CM^2) = 4BC^2 \\\\ &\\therefore \\quad 4(BN^2 + CM^2) = 5BC^2 \\text{ (since } BC^2 = \\frac{5}{4}BC^2 \\text{)} \\\\ &\\therefore \\quad 4(BN^2 + CM^2) = 5BC^2 \\end{aligned}']
['\\begin{aligned} &\\text{Given } DE \\parallel AB, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{BE}{EC} = \\frac{BD}{DA} \\\\ &\\text{Since } DE \\parallel AB, \\text{ } \\triangle BDE \\sim \\triangle BAC \\\\ &\\implies \\frac{DE}{AB} = \\frac{BE}{BC} \\\\ &\\implies \\frac{x}{a} = \\frac{b}{b+c} \\\\ &\\therefore x = \\frac{ab}{b+c} \\end{aligned}']
['\\begin{aligned} &\\text{Given } \\triangle AAB \\text{ is right-angled at } A. \\\\ &\\text{By Basic Proportionality Theorem, if a line is drawn parallel to one side of a triangle, it divides the other two sides proportionally.} \\\\ &\\text{Let } DE \\parallel BC, \\text{ then } \\frac{AD}{DB} = \\frac{AE}{EC}. \\\\ &\\therefore \\text{The required ratio is } \\frac{AD}{DB} = \\frac{AE}{EC}. \\end{aligned}']
['\\begin{aligned} &\\text{(a) Basic Proportionality Theorem: If a line is drawn parallel to one side of a triangle,} \\\\ &\\text{intersecting the other two sides, it divides those sides in the same ratio.} \\\\ &\\text{Proof: In } \\triangle ABC, \\text{ let } DE \\parallel BC \\text{ and } D, E \\text{ lie on } AB, AC \\text{ respectively.} \\\\ &\\text{Then, } \\frac{AD}{DB} = \\frac{AE}{EC}. \\\\ &\\text{(b) Given } \\angle CEF = \\angle CFE, \\text{ and } F \\text{ is the midpoint of } DC. \\\\ &\\text{Since } F \\text{ is midpoint, } DF = FC. \\\\ &\\text{In } \\triangle CEF, \\angle CEF = \\angle CFE \\implies \\text{ } \\triangle CEF \\text{ is isosceles.} \\\\ &\\text{Since } F \\text{ is midpoint, } DF = FC \\implies \\frac{DF}{FC} = 1. \\\\ &\\text{Using Basic Proportionality Theorem in } \\triangle ABD \\text{ with } EF \\parallel BD, \\\\ &\\frac{AB}{BD} = \\frac{AE}{EF}. \\\\ &\\text{Since } \\triangle CEF \\text{ is isosceles, } EF = FC. \\\\ &\\therefore \\frac{AB}{BD} = \\frac{AE}{FD}. \\end{aligned}']
['\\begin{aligned} &\\text{Given } \\angle \\mathrm{PRQ} = \\angle \\mathrm{STQ}, \\text{ so } \\triangle \\mathrm{PQR} \\sim \\triangle \\mathrm{STQ} \\text{ by AA similarity.} \\\\\\ &\\text{By the Basic Proportionality Theorem, } \\frac{\\mathrm{PQ}}{\\mathrm{ST}} = \\frac{\\mathrm{PR}}{\\mathrm{SQ}}. \\\\\\ &\\therefore \\text{ The ratio of sides is } \\frac{\\mathrm{PQ}}{\\mathrm{ST}} = \\frac{\\mathrm{PR}}{\\mathrm{SQ}}. \\end{aligned}']
['\\begin{aligned} &\\text{Given two scalene triangles, check for similarity using AAA, SSS, or SAS criteria} \\\\ &\\text{If corresponding angles are equal, use AAA criterion} \\\\ &\\text{If corresponding sides are proportional, use SSS or SAS criterion} \\\\ &\\therefore \\text{The triangles are similar if any of these criteria are satisfied} \\end{aligned}']
['\\begin{aligned} &\\text{Given: } DE \\parallel BC, \\ AD = 3 \\text{ cm}, \\ BD = 4 \\text{ cm}, \\ BC = 14 \\text{ cm} \\\\ &\\text{According to the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{DE}{EC} \\\\ &\\implies \\frac{3}{4} = \\frac{DE}{EC} \\\\ &\\text{Since } DE \\parallel BC, \\text{ then } DE + EC = BC \\\\ &\\implies DE + EC = 14 \\\\ &\\text{Let } DE = x \\text{ and } EC = y \\\\ &\\implies x + y = 14 \\\\ &\\text{From } \\frac{3}{4} = \\frac{x}{y}, \\text{ we have } y = \\frac{4}{3}x \\\\ &\\implies x + \\frac{4}{3}x = 14 \\\\ &\\implies \\frac{7}{3}x = 14 \\\\ &\\implies x = \\frac{14 \\times 3}{7} \\\\ &\\implies x = 6 \\\\ &\\therefore \\text{Length of } DE = 6 \\text{ cm} \\end{aligned}']

In [27]:
# Define the prompt template for generating misconceptions
prompt_template = PromptTemplate(
    input_variables=["system_prompt","topic", "topic_id", "question", "hint", "solution"],
    template="{system_prompt}\n\nGenerate one correct option and appropriate incorrect options in latex using given solution, hint, and misconceptions for the given question.\n\nTopic ID: {topic_id}\nTopic: {topic}\nQuestion: {question}\nHint: {hint}\nSolution: {solution}\n\nReturn the output in the specified JSON format."
)

# Extract relevant information from the 'explanation' column

def extract_explanation_details(explanation):
    try:
        explanation_data = json.loads(explanation)
        hint = explanation_data.get('hint', 'No hint available')
        solution = explanation_data.get('solution', 'No solution available')
        return hint, solution
    except json.JSONDecodeError:
        return 'No hint available', 'No solution available'

# Function to generate misconceptions-based incorrect options

def generate_incorrect_options(row):

    chain = LLMChain(llm=llm, prompt=prompt_template)
    try:
        response = chain.run(
            system_prompt=DISTRACTOR_SYSTEM_PROMPT,
            topic=row['topic'],
            topic_id=row['topic_id'],
            question=row['question'],
            hint=row['hint'],
            solution=row['solution']
        )
        # if response.strip().startswith("```json"):
        #     response = response.strip().strip("```json").strip("```").strip()
        return response
    except Exception as e:
        print(f"Unexpected error: {str(e)}")
        return None

# Apply the function to generate misconceptions-based incorrect options for each question
misconception_options = []
def loopForDistractor(data):
    distractor_counter = 0
    retries_counter = 0
    maxCounter = len(data)
    while distractor_counter<maxCounter:
        row = data.loc[distractor_counter]
        print(f"Processing question {distractor_counter + 1} out of {len(data)}")
        misconception_option = generate_incorrect_options(row)
        parsed_response = parse_Response(misconception_option)

        if parsed_response:
            # misconception_options.append(parsed_response)
            # row['misconception_options'] = parsed_response
            # print(distractor_counter)
            # print(data.loc[distractor_counter , 'misconception_options'])
            # print(parsed_response)

            data.loc[distractor_counter , 'misconception_options'] =[parsed_response]
            distractor_counter += 1
            retries_counter = 0
        else:
            print(f"Failed to parse response or generate distractors for question {distractor_counter + 1}, retrying...")
            retries_counter += 1
        if retries_counter == 3:
            # misconception_option.append("")
            data.loc[distractor_counter , 'misconception_options'] = ""
            distractor_counter += 1

loopForDistractor(data)
# data['misconception_options'] = misconception_options

Processing question 1 out of 99
Processing question 2 out of 99
Processing question 3 out of 99
Processing question 4 out of 99
Processing question 5 out of 99
Processing question 6 out of 99
Processing question 7 out of 99
Unexpected error: Request timed out.
No response message found <class 'NoneType'>
Failed to parse response or generate distractors for question 7, retrying...
Processing question 7 out of 99
Processing question 8 out of 99
Processing question 9 out of 99
Processing question 10 out of 99
Processing question 11 out of 99
Processing question 12 out of 99
Processing question 13 out of 99
Processing question 14 out of 99
Processing question 15 out of 99
Processing question 16 out of 99
Processing question 17 out of 99
Processing question 18 out of 99
Processing question 19 out of 99
Processing question 20 out of 99
Processing question 21 out of 99
Processing question 22 out of 99
Processing question 23 out of 99
Processing question 24 out of 99
Processing question 25 out of 99
Processing question 26 out of 99
Processing question 27 out of 99
Processing question 28 out of 99
Processing question 29 out of 99
Processing question 30 out of 99
Processing question 31 out of 99
Processing question 32 out of 99
Processing question 33 out of 99
Processing question 34 out of 99
Processing question 35 out of 99
Processing question 36 out of 99
Processing question 37 out of 99
Processing question 38 out of 99
Processing question 39 out of 99
Processing question 40 out of 99
Processing question 41 out of 99
Processing question 42 out of 99
Processing question 43 out of 99
Processing question 44 out of 99
Processing question 45 out of 99
Processing question 46 out of 99
Processing question 47 out of 99
Processing question 48 out of 99
Processing question 49 out of 99
Processing question 50 out of 99
Processing question 51 out of 99
Processing question 52 out of 99
Processing question 53 out of 99
Processing question 54 out of 99
Processing question 55 out of 99
Processing question 56 out of 99
Processing question 57 out of 99
Processing question 58 out of 99
Processing question 59 out of 99
Processing question 60 out of 99
Processing question 61 out of 99
Processing question 62 out of 99
Processing question 63 out of 99
Processing question 64 out of 99
Processing question 65 out of 99
Processing question 66 out of 99
Processing question 67 out of 99
Processing question 68 out of 99
Processing question 69 out of 99
Processing question 70 out of 99
Processing question 71 out of 99
Processing question 72 out of 99
Processing question 73 out of 99
Processing question 74 out of 99
Processing question 75 out of 99
Processing question 76 out of 99
Processing question 77 out of 99
Processing question 78 out of 99
Processing question 79 out of 99
Processing question 80 out of 99
Processing question 81 out of 99
Processing question 82 out of 99
Processing question 83 out of 99
Processing question 84 out of 99
Processing question 85 out of 99
Processing question 86 out of 99
Processing question 87 out of 99
Processing question 88 out of 99
Processing question 89 out of 99
Processing question 90 out of 99
Processing question 91 out of 99
Processing question 92 out of 99
Processing question 93 out of 99
Processing question 94 out of 99
Processing question 95 out of 99
Processing question 96 out of 99
Processing question 97 out of 99
Processing question 98 out of 99
Processing question 99 out of 99

In [29]:
for i in range(len(data)):
    print(data['misconception_options'][i])

[{'correct_option': '\\begin{aligned} &\\frac{AD}{DB} = \\frac{AE}{EC} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{AD}{AE} = \\frac{DB}{EC} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the order of segments in the proportion, reversing the correct relationship} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{AD}{EC} = \\frac{DB}{AE} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct pairing of segments across the parallel lines} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{AD}{DB} = \\frac{EC}{AE} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to maintain the correct order of segments in the proportion} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{5 cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{4 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the ratio calculation by using incorrect values for } AD \\text{ and } DB. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{6 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct proportionality and overestimated the length of } DE. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{7 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the correct ratio and assumed } DE \\text{ is almost equal to } BC. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{5.3333 cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{6 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct proportion calculation, leading to an overestimation of } EC. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{4.8 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the addition of } AE \\text{ and } EC \\text{ by miscalculating } EC. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{5 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to use the exact decimal value for } EC, \\text{ rounding it incorrectly.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{4.5 cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{3.5 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the multiplication step by using } \\frac{3}{4} \\times 5 \\text{ instead of } \\frac{3}{4} \\times 6. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{5 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct ratio and assumed } AE \\text{ equals } EC. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{6 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem and assumed } AE \\text{ is the same as } EC. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x = \\frac{9}{2} \\text{ units} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x = 3 \\text{ units} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the ratios by assuming } AD = AE \\text{ instead of using the correct ratios.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x = 6 \\text{ units} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the proportionality and directly added } AD \\text{ and } DB. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x = \\frac{5}{2} \\text{ units} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Miscalculated the cross-multiplication step in solving the proportion.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{1 cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{2 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the ratio of } AB \\text{ and } PQ \\text{ with } OB \\text{ and } OP \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{3 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem correctly} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{1.5 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood the proportional relationship between the segments} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x = 4.5 \\ \\ \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x = 4 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the simplification of } \\frac{18}{4} \\text{ as } 4 \\text{ instead of } 4.5. \\ \\ \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x = 5 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct cross-multiplication and division, leading to an incorrect } x \\text{ value of } 5. \\ \\ \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x = 3.5 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood the proportionality setup, resulting in an incorrect calculation of } x \\text{ as } 3.5. \\ \\ \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{20 cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{18 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the addition of } AQ \\text{ and } QC \\text{ by miscalculating } QC \\text{ as } 10 \\text{ instead of } 12. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{16 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct ratio and calculated } QC \\text{ as } 8 \\text{ leading to incorrect } AC. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{24 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the correct proportionality theorem, overestimating } QC \\text{ as } 16. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{8 cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{7 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the addition of } BQ \\text{ and } QC \\text{ by miscalculating } QC \\text{ as } 2 \\text{ cm instead of } 3 \\text{ cm.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{9 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly apply the Basic Proportionality Theorem, leading to an incorrect } QC \\text{ value.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{10 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct proportional relationship, assuming } QC \\text{ was larger than calculated.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x = 4.5 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x = 4 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the cross-multiplication step, leading to an incorrect simplification.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x = 5 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct proportionality and miscalculated the product.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x = 4.8 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood the division step, resulting in a slightly higher value.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{1.8 cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{2.0 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the multiplication step, leading to an incorrect calculation of } EC. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{1.5 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct ratio and miscalculated the division step.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{2.5 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem correctly, leading to a wrong result.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{3}{10} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{3}{7} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the ratio of } \\frac{AC}{CD} \\text{ with } \\frac{AE}{AF}, \\text{ which are different.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{7}{10} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct application of Basic Proportionality Theorem, leading to incorrect calculation.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{3}{4} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood the relationship between segments, using incorrect segment lengths.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x = 2 \\ \\ \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x = 3 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the ratio by equating } \\frac{x}{3} \\text{ directly to } \\frac{4}{6} \\text{ instead of reducing it to } \\frac{2}{3}. \\ \\ \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x = 4 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to simplify the ratio } \\frac{4}{6} \\text{ to } \\frac{2}{3} \\text{ before solving for } x. \\ \\ \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x = 6 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct application of the Basic Proportionality Theorem, assuming } x \\text{ equals the denominator.} \\ \\ \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{8 cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{6 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the ratio of } AD \\text{ and } DB \\text{ with } AE \\text{ and } EC, \\text{ leading to an incorrect calculation of } x. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{10 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the total length of } AC \\text{ when calculating } EC, \\text{ resulting in an overestimation.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{12 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the correct ratio of } \\frac{3}{4} \\text{ to } AE \\text{ and } EC, \\text{ leading to an incorrect } EC \\text{ value.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{BF}{FE} = \\frac{BE}{EC} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{BF}{FE} = \\frac{BD}{DC} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the segments by incorrectly applying the theorem to } \\triangle BDC. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{BF}{FE} = \\frac{BC}{CE} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the theorem correctly to the segments in } \\triangle BEC. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{BF}{FE} = \\frac{BD}{DE} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the parallel lines and used incorrect segments from } \\triangle BDE. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{BE}{EC} = \\frac{BC}{CP} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{BE}{BC} = \\frac{EC}{CP} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the proportionality by incorrectly swapping the terms in the ratios.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{BE}{CP} = \\frac{BC}{EC} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot the correct order of terms in the proportionality statement.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{BC}{BE} = \\frac{CP}{EC} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct application of the Basic Proportionality Theorem by reversing the ratios.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{QB}{AQ} = \\frac{DR}{AR} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{PQ}{QC} = \\frac{PR}{RD} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the segments in } \\triangle PQR \\text{ and } \\triangle PCD \\text{ instead of } \\triangle APQ \\text{ and } \\triangle ADR. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{AQ}{QB} = \\frac{AR}{RD} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to invert the ratios to match the required expression.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{QB}{AQ} = \\frac{AR}{DR} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct order of segments in the ratio.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{\\triangle ABC \\text{ is isosceles with } AB = AC} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{\\triangle ABC \\text{ is isosceles with } AB = BC} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the sides of the triangle, assuming } AB = BC \\text{ instead of } AB = AC \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{\\triangle ABC \\text{ is equilateral}} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood the condition, assuming all sides are equal instead of just two} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{\\triangle ABC \\text{ is scalene}} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the proportionality condition, assuming all sides are different} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &SP^{2} = SB \\times SC \\end{aligned}', 'option1': {'option': '\\begin{aligned} &SP^{2} = SA \\times SC \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the segments by incorrectly using } SA \\text{ instead of } SB \\text{ in the proportionality relation.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &SP^{2} = SB \\times SA \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot that the correct segments to use are } SB \\text{ and } SC, \\text{ not } SA. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &SP^{2} = SC \\times SA \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct proportionality by using } SC \\text{ and } SA \\text{ instead of } SB \\text{ and } SC. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x = 2.5 \\text{ cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x = 3 \\text{ cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the ratio of } AC \\text{ and } QR \\text{ with } BC \\text{ and } PR, \\text{ leading to an incorrect calculation.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x = 2 \\text{ cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly solve the proportion equation, resulting in an incorrect } x \\text{ value.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x = 4 \\text{ cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct cross-multiplication step, leading to an overestimation of } x. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{Triangle } ABC \\text{ is a right triangle with } \\angle ADB = 90^\\circ \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{Triangle } ABC \\text{ is an equilateral triangle} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the property of complementary angles with equilateral triangle properties} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\angle ABC \\text{ and } \\angle ACB \\text{ are equal} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot that complementary angles are not necessarily equal} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\angle ADB \\text{ is an acute angle} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the fact that } AD \\perp BC \\text{ implies } \\angle ADB = 90^\\circ \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x = \\frac{ac}{b} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x = \\frac{ab}{c} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the positions of } b \\text{ and } c \\text{ in the proportion, leading to an incorrect expression.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x = \\frac{bc}{a} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly apply the Basic Proportionality Theorem, swapping } a \\text{ and } b. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x = \\frac{a}{bc} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the multiplication of } a \\text{ and } c, incorrectly dividing by } bc. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{ABCD is a kite} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{ABCD is a parallelogram} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the properties of a kite with those of a parallelogram, which requires opposite sides to be equal.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{ABCD is a rectangle} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot that a rectangle requires all angles to be right angles, not just bisected.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{ABCD is a rhombus} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored that a rhombus requires all sides to be equal, not just angle bisectors.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\Delta \\quad EAB \\sim \\Delta \\quad ECD \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\Delta \\quad EAC \\sim \\Delta \\quad EBD \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the order of vertices, leading to incorrect triangle similarity conclusion} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\Delta \\quad EAB \\sim \\Delta \\quad EDB \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot that the triangles must share corresponding angles for similarity} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\Delta \\quad EAC \\sim \\Delta \\quad EDC \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct proportional sides needed for similarity} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{AB = 2CD} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{AB = CD} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the proportionality, assuming equal segments instead of the given ratio.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{AB = 3CD} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misinterpreted the given ratio, leading to an incorrect multiplication factor.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{AB = 4CD} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct ratio, assuming a larger proportional relationship.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{1.8 cm} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{2.5 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the cross-multiplication step, leading to an incorrect proportion calculation.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{3.0 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem correctly, assuming equal segments.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{2.0 cm} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the ratio of segments, leading to a miscalculation of the length.} \\end{aligned}'}}]

In [30]:
data

,hint,solution,question,topic,topic_id,image_ids,misconception_options
0,\begin{aligned} &\text{Apply the Basic Proport...,\begin{aligned} &\text{Given } DE \parallel BC...,"\begin{aligned} &\text{In } \triangle ABC, \te...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &\frac{AD...
1,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } DE \parallel BC...,"\begin{aligned} &\text{In } \triangle ABC, \te...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &\text{5 ...
2,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\frac{AD}{DB} = \frac{AE}{EC}...,"\begin{aligned} &\text{In the figure, } \trian...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &\text{5....
3,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } DE \parallel BC...,"\begin{aligned} &\text{In the figure, } DE \pa...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &\text{4....
4,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } DE \parallel BC...,"\begin{aligned} &\text{In the figure, } DE \pa...",Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &x = \fra...
...,...,...,...,...,...,...,...
94,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } PQ \parallel BC...,\begin{aligned} &\text{ If } P \quad Q \mid \m...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &\text{Se...
95,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } \triangle ABC \...,\begin{aligned} &\text{ In } \triangle A \quad...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &\text{Se...
96,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Since } E \quad F \mid ...,\begin{aligned} &\text{ In triangle } A \quad ...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &\frac{AE...
97,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{Given } \angle PQR = 90...,\begin{aligned} &\text{ In } \triangle P \quad...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &\text{Tr...
98,\begin{aligned} &\text{Use the Basic Proportio...,\begin{aligned} &\text{In } \triangle A \quad ...,\begin{aligned} &\text{ Consider a triangle } ...,Basic Proportionality Theorem,10_mathematics_triangles_2,[{'image_1': '2025_02_17_bbe3f767e7e1821afad5g...,[{'correct_option': '\begin{aligned} &\text{P ...

### Output Formatting & Pushing into the DB

In [31]:
# Function to process each row and extract required fields
def process_row(row, index):
    try:
        misconception_data = row["misconception_options"]
        # Extract topic, question, and solution details
        topic_id = row["topic_id"]
        topic_name = row["topic"]
        question = row["question"]
        hint = row["hint"]
        explanation = row["solution"]
        images = row.get("image_ids", [])
        # correct_answer = row["final_answer"]
        chapter = conf_data['chapter_name']

        # Extract option and rationale details
        options = {}
        for i in range(1, 4):  # Assuming there are 4 options for each question
            options["correct_answer"] = misconception_data[0]["correct_option"]
            option_key = f'option{i}'
            option_info = misconception_data[0][option_key]
            options[f'option{i}'] = option_info.get('option', '')
            options[f'dr{i}'] = option_info.get('rationale', '')
        
        # Construct the final JSON structure
        start = "\\begin{aligned}"
        end = "\\end{aligned}"
        
        combined_data = {
            'topic_id': topic_id,
            'topic_name': topic_name,
            'grade' : conf_data['grade'],
            'board' : "CBSE",
            
            'subject' : subject,
            'chapter_name' : chapter,
            "images": images,
            'publication' : conf_data['publication'],
            'question': [{"content": question}],
            # if (str(question).startswith("\\begin{aligned}") and str(question).endswith("\\end{aligned}")) else [{"content": start + question + end}],

            'hint': [{"content": hint}],
            # if (str(hint).startswith("\\begin{aligned}") and str(hint).endswith("\\end{aligned}")) else [{"content": start + hint + end}],

            'solution': [{"content": explanation}],
            # if (str(explanation).startswith("\\begin{aligned}") and str(explanation).endswith("\\end{aligned}")) else [{"content": start + explanation + end}],

            'final_answer': [{"content": options.get('correct_answer', '')}],
            # if (str(options.get('correct_answer', '')).startswith("\\begin{aligned}") and str(options.get('correct_answer', '')).endswith("\\end{aligned}")) else [{"content": start + options.get('correct_answer', '') + end}],

            'option1': [{"content": options.get('option1', '')}],
            # if (str(options.get('option1')).startswith("\\begin{aligned}") and str(options.get('option1')).endswith("\\end{aligned}")) else [{"content": start + str(options.get('option1', '')) + end} ],
            'dr1': [{"content": options.get('dr1', '')}],
            'option2': [{"content": options.get('option2', '')}],
            # if (str(options.get('option2')).startswith("\\begin{aligned}") and str(options.get('option2')).endswith("\\end{aligned}")) else [{"content": start + str(options.get('option2', '')) + end}],
            'dr2': [{"content": options.get('dr2', '')}],
            'option3': [{"content": options.get('option3', '')}],
            # if (str(options.get('option3')).startswith("\\begin{aligned}") and str(options.get('option3')).endswith("\\end{aligned}")) else [{"content": start + str(options.get('option3', '')) + end}],
            'dr3': [{"content": options.get('dr3', '')}]


        }

        return combined_data
    except Exception as e:
        # If there is an error, return an empty structure with an error message
        print(f"Exception Occurred: {type(e).__name__} – {e} \n {traceback.format_exc()}")

# Process all rows in the dataframe
final_output = [process_row(row, idx) for idx, row in data.iterrows()]

In [43]:
final_output

[{'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-324'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ if } DE \\parallel BC, \\text{ what is the relationship between the segments } AD, DB, AE, \\text{ and } EC? \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Apply the Basic Proportionality Theorem (Thales Theorem) to } \\triangle ABC \\text{ with } DE \\parallel BC \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC \\text{ in } \\triangle ABC \\\\ &\\implies \\frac{AD}{DB} = \\frac{AE}{EC} \\quad \\text{[By Basic Proportionality Theorem]} \\\\ &\\therefore \\text{The relationship is } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\frac{AD}{DB} = \\frac{AE}{EC} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\frac{AD}{AE} = \\frac{DB}{EC} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the order of segments in the proportion, reversing the correct relationship} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\frac{AD}{EC} = \\frac{DB}{AE} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct pairing of segments across the parallel lines} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\frac{AD}{DB} = \\frac{EC}{AE} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to maintain the correct order of segments in the proportion} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-325'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ with } DE \\parallel BC, \\text{ given } AD = 2 \\, \\text{cm}, BD = 3 \\, \\text{cm}, \\text{ and } BC = 7.5 \\, \\text{cm}, \\text{ calculate the length of } DE. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } DE. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{DE}{BC} \\\\ &\\implies \\frac{2}{3} = \\frac{DE}{7.5} \\\\ &\\therefore DE = \\frac{2}{3} \\times 7.5 \\\\ &\\implies DE = 5 \\, \\text{cm} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{5 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{4 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the ratio calculation by using incorrect values for } AD \\text{ and } DB. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{6 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct proportionality and overestimated the length of } DE. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{7 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the correct ratio and assumed } DE \\text{ is almost equal to } BC. \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(2)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the figure, } \\triangle ABC \\text{ has } DE \\parallel BC. \\text{ If } AD = 2.4 \\, \\text{cm}, DB = 4 \\, \\text{cm}, \\text{ and } AE = 2 \\, \\text{cm}, \\text{ find the length of } AC. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: } \\frac{AD}{DB} = \\frac{AE}{EC} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\quad \\frac{2.4}{4} = \\frac{2}{EC} \\\\ &\\implies \\quad EC = \\frac{2 \\times 4}{2.4} \\\\ &\\implies \\quad EC = \\frac{8}{2.4} \\\\ &\\implies \\quad EC = 3.3333 \\, \\text{cm} \\\\ &\\therefore \\quad AC = AE + EC = 2 + 3.3333 = 5.3333 \\, \\text{cm} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{5.3333 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{6 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Ignored the correct proportion calculation, leading to an overestimation of } EC. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{4.8 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Confused the addition of } AE \\text{ and } EC \\text{ by miscalculating } EC. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{5 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to use the exact decimal value for } EC, \\text{ rounding it incorrectly.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(1)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the figure, } DE \\parallel BC \\text{ and all measurements are in centimeters. Determine the length of } AE. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the length of } AE. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\text{Substitute the given lengths:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\frac{3}{4} = \\frac{AE}{6} \\\\ &\\implies AE = \\frac{3}{4} \\times 6 \\\\ &\\therefore AE = 4.5 \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{4.5 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{3.5 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the multiplication step by using } \\frac{3}{4} \\times 5 \\text{ instead of } \\frac{3}{4} \\times 6. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{5 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct ratio and assumed } AE \\text{ equals } EC. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{6 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem and assumed } AE \\text{ is the same as } EC. \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the figure, } DE \\parallel BC. \\text{ If } AD = 2 \\text{ units, } DB = AE = 3 \\text{ units, and } EC = x \\text{ units, find the value of } x. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the value of } x. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{2}{3} = \\frac{3}{x} \\\\ &\\implies 2x = 9 \\\\ &\\therefore x = \\frac{9}{2} \\text{ units} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &x = \\frac{9}{2} \\text{ units} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &x = 3 \\text{ units} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the ratios by assuming } AD = AE \\text{ instead of using the correct ratios.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &x = 6 \\text{ units} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the proportionality and directly added } AD \\text{ and } DB. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &x = \\frac{5}{2} \\text{ units} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Miscalculated the cross-multiplication step in solving the proportion.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(2)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the given figure, if } AB \\parallel PQ, \\text{ and } AB = 6 \\, \\text{cm}, \\, PQ = 2 \\, \\text{cm}, \\text{ and } OB = 3 \\, \\text{cm}, \\text{ what is the length of } OP? \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } OP \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } AB \\parallel PQ, \\text{ so by Basic Proportionality Theorem, } \\frac{AB}{PQ} = \\frac{OB}{OP} \\\\ &\\implies \\quad \\frac{6}{2} = \\frac{3}{OP} \\\\ &\\implies \\quad 3 = \\frac{3}{OP} \\\\ &\\implies \\quad OP = 1 \\\\ &\\therefore \\quad \\text{The length of } OP \\text{ is } 1 \\, \\text{cm} \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{1 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{2 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the ratio of } AB \\text{ and } PQ \\text{ with } OB \\text{ and } OP \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{3 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem correctly} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{1.5 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Misunderstood the proportional relationship between the segments} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(1)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the given figure, } DE \\parallel BC. \\text{ Determine the value of } x. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the value of } x. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ apply the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\text{Substitute the given values:} \\\\ &\\frac{3}{x} = \\frac{4}{6} \\\\ &\\implies 3 \\cdot 6 = 4 \\cdot x \\\\ &\\implies 18 = 4x \\\\ &\\implies x = \\frac{18}{4} \\\\ &\\implies x = 4.5 \\\\ &\\therefore x = 4.5 \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &x = 4.5 \\ \\ \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &x = 4 \\ \\ \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the simplification of } \\frac{18}{4} \\text{ as } 4 \\text{ instead of } 4.5. \\ \\ \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &x = 5 \\ \\ \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct cross-multiplication and division, leading to an incorrect } x \\text{ value of } 5. \\ \\ \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &x = 3.5 \\ \\ \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Misunderstood the proportionality setup, resulting in an incorrect calculation of } x \\text{ as } 3.5. \\ \\ \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In } \\triangle ABC, \\, PQ \\parallel BC. \\text{ If } PB = 6 \\, \\text{cm}, \\, AP = 4 \\, \\text{cm}, \\text{ and } AQ = 8 \\, \\text{cm}, \\text{ find the length of } AC. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } AC. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given: } PQ \\parallel BC, \\text{ and } \\triangle APQ \\sim \\triangle ABC \\\\ &\\text{By Basic Proportionality Theorem: } \\frac{AP}{PB} = \\frac{AQ}{QC} \\\\ &\\implies \\frac{4}{6} = \\frac{8}{QC} \\\\ &\\implies 4 \\times QC = 6 \\times 8 \\\\ &\\implies QC = \\frac{48}{4} \\\\ &\\therefore QC = 12 \\\\ &\\text{Since } AC = AQ + QC \\\\ &\\implies AC = 8 + 12 \\\\ &\\therefore AC = 20 \\text{ cm} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{20 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{18 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the addition of } AQ \\text{ and } QC \\text{ by miscalculating } QC \\text{ as } 10 \\text{ instead of } 12. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{16 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct ratio and calculated } QC \\text{ as } 8 \\text{ leading to incorrect } AC. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{24 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the correct proportionality theorem, overestimating } QC \\text{ as } 16. \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(3)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the given figure, } PQ \\parallel AC. \\text{ If } BP = 4 \\, \\text{cm}, \\, AP = 2.4 \\, \\text{cm}, \\text{ and } BQ = 5 \\, \\text{cm}, \\text{ what is the length of } BC? \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: If a line is parallel to one side of a triangle, it divides the other two sides proportionally.} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given: } PQ \\parallel AC, \\text{ so by Basic Proportionality Theorem,} \\\\ &\\frac{BP}{AP} = \\frac{BQ}{QC} \\\\ &\\implies \\frac{4}{2.4} = \\frac{5}{QC} \\\\ &\\implies 4 \\times QC = 5 \\times 2.4 \\\\ &\\implies 4QC = 12 \\\\ &\\implies QC = \\frac{12}{4} \\\\ &\\implies QC = 3 \\, \\text{cm} \\\\ &\\therefore BC = BQ + QC = 5 + 3 = 8 \\, \\text{cm} \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{8 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{7 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the addition of } BQ \\text{ and } QC \\text{ by miscalculating } QC \\text{ as } 2 \\text{ cm instead of } 3 \\text{ cm.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{9 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to correctly apply the Basic Proportionality Theorem, leading to an incorrect } QC \\text{ value.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{10 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the correct proportional relationship, assuming } QC \\text{ was larger than calculated.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(2)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the figure given below, determine the value of } x \\text{ that will make } PQ \\parallel AB. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the value of } x \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } \\frac{AP}{PB} = \\frac{AQ}{QC} \\\\ &\\implies \\frac{3}{x} = \\frac{4}{6} \\\\ &\\implies 3 \\times 6 = 4 \\times x \\\\ &\\implies 18 = 4x \\\\ &\\implies x = \\frac{18}{4} \\\\ &\\implies x = 4.5 \\\\ &\\therefore x = 4.5 \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &x = 4.5 \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &x = 4 \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the cross-multiplication step, leading to an incorrect simplification.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &x = 5 \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct proportionality and miscalculated the product.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &x = 4.8 \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Misunderstood the division step, resulting in a slightly higher value.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(1)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the given figure, with } D E \\parallel B C, \\text{ if } \\frac{A D}{D B}=\\frac{3}{2} \\text{ and } A E=2.7 \\mathrm{~cm}, \\text{ determine the length of } E C. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } EC \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given: } DE \\parallel BC, \\frac{AD}{DB} = \\frac{3}{2}, AE = 2.7 \\text{ cm} \\\\ &\\text{By Basic Proportionality Theorem, } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{3}{2} = \\frac{2.7}{EC} \\\\ &\\implies 3 \\cdot EC = 2 \\cdot 2.7 \\\\ &\\implies 3 \\cdot EC = 5.4 \\\\ &\\therefore EC = \\frac{5.4}{3} \\\\ &\\therefore EC = 1.8 \\text{ cm} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{1.8 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{2.0 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the multiplication step, leading to an incorrect calculation of } EC. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{1.5 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct ratio and miscalculated the division step.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{2.5 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem correctly, leading to a wrong result.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',

In [ ]:
from docx import Document
from docx.shared import Pt, Inches
import random
import os
from pathlib import Path
from PIL import Image
import io
from pylatexenc.latex2text import LatexNodes2Text

#######################
# Helper Functions
#######################

def process_latex_text(text):
    if not text:
        return ""
    return LatexNodes2Text().latex_to_text(text)

def process_image_ids(images):
    try:
        if not images or not isinstance(images, list):
            return []
        processed_images = []
        for img_dict in images:
            if isinstance(img_dict, dict):
                image_id = next(iter(img_dict.values()))
                processed_images.append(f"{image_id}.jpg")
        return processed_images
    except Exception as e:
        print(f"Error in process_image_ids: {e}")
        return []

def get_content_text(content_list):
    try:
        if not content_list or not isinstance(content_list, list):
            return ""
        if not content_list[0]:
            return ""
        return process_latex_text(content_list[0].get('content', ''))
    except Exception as e:
        print(f"Error in get_content_text: {e}")
        return ""

def find_image_in_directory(image_filename, image_dir):
    try:
        image_dir_path = Path(image_dir).resolve()
        direct_path = image_dir_path / image_filename
        if direct_path.is_file():
            try:
                with Image.open(direct_path) as img:
                    img.verify()
                return str(direct_path)
            except Exception as e:
                print(f"Image validation failed for {direct_path}: {str(e)}")
                return None
        for file_path in image_dir_path.rglob(image_filename):
            if file_path.is_file():
                try:
                    with Image.open(file_path) as img:
                        img.verify()
                    return str(file_path)
                except Exception:
                    continue
        print(f"Image not found or invalid: {image_filename}")
        return None
    except Exception as e:
        print(f"Error finding image {image_filename}: {e}")
        return None

# --- Table creation code with image insertion ---

def create_docx_table_with_images(final_output, image_dir, output_path="output.docx"):
    doc = Document()
    style = doc.styles['Normal']
    style.font.name = 'Cambria Math'
    style.font.size = Pt(11)
    
    headings = {
        "LU": "lu",  
        "LU ID": "lu",  
        "LO": "lo",  
        "LO ID": "lo",  
        "Question Type": "",
        "Question ID": "",  # Always empty
        "Difficulty level": "",
        "Cognitive Dimension('Bloom's Level')": "",
        "Title (Stem and prompt)": "question"
    }
    
    for i in range(len(final_output)):
        table = doc.add_table(0, 4)
        table.style = 'Table Grid'
        heads_list = list(headings.keys())
        
        for j in range(len(heads_list)):
            row1 = table.add_row().cells
            row1[0].text = heads_list[j]
            try:
                if heads_list[j] == "Question ID":
                    row1[1].text = ""
                elif headings[heads_list[j]]:
                    if heads_list[j] == "Title (Stem and prompt)":
                        cell = row1[1]
                        question_text = get_content_text(final_output[i].get("question", []))
                        cell.text = question_text
                        images = final_output[i].get("images", [])
                        image_files = process_image_ids(images)
                        for img_file in image_files:
                            img_path = find_image_in_directory(img_file, image_dir)
                            if img_path:
                                try:
                                    # Read the image bytes and wrap them in a BytesIO object
                                    with open(img_path, 'rb') as f:
                                        image_bytes = f.read()
                                    if image_bytes:
                                        img_io = io.BytesIO(image_bytes)
                                        p = cell.add_paragraph()
                                        run = p.add_run()
                                        run.add_picture(img_io, width=Inches(4))
                                    else:
                                        print(f"Empty image file: {img_path}")
                                except Exception as e:
                                    print(f"Error adding picture from {img_path}: {str(e)}")
                    elif heads_list[j] == "LU":
                        row1[1].text = str(final_output[i].get("lu", ""))
                    elif heads_list[j] == "LU ID":
                        row1[1].text = str(final_output[i].get("lu", ""))
                    elif heads_list[j] == "LO":
                        row1[1].text = str(final_output[i].get("lo", ""))
                    elif heads_list[j] == "LO ID":
                        row1[1].text = str(final_output[i].get("lo", ""))
                    else:
                        row1[1].text = str(final_output[i].get(headings[heads_list[j]], ""))
                else:
                    row1[1].text = ""
            except Exception as e:
                print(f"Error processing row {j}: {e}")
                row1[1].text = ""
            row1[2].text = ""
            row1[3].text = ""
            try:
                row1[1].merge(row1[2]).merge(row1[3])
            except Exception as merge_e:
                print(f"Error merging cells in row {j}: {merge_e}")
        
        # Process Options row
        row2 = table.add_row().cells
        row2[0].text = "Options"
        row2[1].text = ""
        row2[2].text = "Type of Distractor"
        row2[3].text = "Distractor Rationale"
        
        rand = random.randrange(0, 4)
        xx = {
            1: "option1",
            3: "option2",
            5: "option3",
            2: "dr1",
            4: "dr2",
            6: "dr3",
        }
        ss = 1
        for j in range(4):
            row3 = table.add_row().cells
            row3[0].text = chr(65 + j)
            if j == rand:
                row3[1].text = get_content_text(final_output[i].get("final_answer", []))
                row3[2].text = ""
                row3[3].text = "Correct Response"
            else:
                try:
                    row3[1].text = get_content_text(final_output[i].get(xx[ss], []))
                    ss += 1
                    row3[2].text = ""
                    row3[3].text = get_content_text(final_output[i].get(xx[ss], []))
                    ss += 1
                except Exception as e:
                    print(f"Error processing option row {j}: {e}")
                    row3[1].text = ""
                    row3[2].text = ""
                    row3[3].text = ""
        
        # Process Hint row
        row4 = table.add_row().cells
        row4[0].text = "Hint"
        try:
            row4[1].text = get_content_text(final_output[i].get("hint", []))
        except Exception as e:
            print(f"Error processing hint: {e}")
            row4[1].text = ""
        row4[2].text = ""
        row4[3].text = ""
        try:
            row4[1].merge(row4[2]).merge(row4[3])
        except Exception as e:
            print(f"Error merging hint cells: {e}")
        
        # Process Explanation row
        row5 = table.add_row().cells
        row5[0].text = "Explanation"
        try:
            row5[1].text = get_content_text(final_output[i].get("solution", []))
        except Exception as e:
            print(f"Error processing explanation: {e}")
            row5[1].text = ""
        row5[2].text = ""
        row5[3].text = ""
        try:
            row5[1].merge(row5[2]).merge(row5[3])
        except Exception as e:
            print(f"Error merging explanation cells: {e}")
        
        doc.add_page_break()
    
    doc.save(output_path)
    print(f"Document saved at {output_path}")

#######################
# Example Usage
#######################

if __name__ == "__main__":
    # Use a raw string to avoid escape sequence issues.
    image_dir = r"textbooks\\mtg\\Triangles_10\\2025_02_17_bbe3f767e7e1821afad5g\\images"
    
    # final_output should be defined as a list of question dictionaries.
    # For example:
    # final_output = [{...}, {...}, ...]
    
    output_filename = "questions_with_images.docx"
    create_docx_table_with_images(final_output, image_dir, output_path=output_filename)

Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-324.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-325.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-326(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-326(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-326.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-327(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-327(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-327.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-327(3).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-328(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-328(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-328.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329(3).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329(4).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-330(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-330.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-330(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-331(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-331(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-331.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-332(4).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-332.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-332(3).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-332(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-333(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-333(3).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-334.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-334(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-335(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-335(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-335.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-336.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-336(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-336(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-337.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-337(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-337(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-338.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-338(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-339.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-339(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-339(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-340(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-342.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-343.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-343(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-344.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-345.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-346.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-347.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-348(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-348.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-348(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-349.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-350.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-352.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-354.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-356.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-357.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-357(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-358.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-359.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-360.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-361.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-361(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-362(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-362.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-363.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-366.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-367.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-368(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-368.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-369(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-369.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-371.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-372(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-372.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-373(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-373.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-374(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-374.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-375.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-376(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-376.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-377.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-378.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-378(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-379.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-380.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-381(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-381(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-381.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-382(2).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-382(1).jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-382.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-384.jpg:
Error adding picture from E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-387.jpg:
Document saved at questions_with_images.docx

In [32]:
final_output

[{'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-324'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ if } DE \\parallel BC, \\text{ what is the relationship between the segments } AD, DB, AE, \\text{ and } EC? \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Apply the Basic Proportionality Theorem (Thales Theorem) to } \\triangle ABC \\text{ with } DE \\parallel BC \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC \\text{ in } \\triangle ABC \\\\ &\\implies \\frac{AD}{DB} = \\frac{AE}{EC} \\quad \\text{[By Basic Proportionality Theorem]} \\\\ &\\therefore \\text{The relationship is } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\frac{AD}{DB} = \\frac{AE}{EC} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\frac{AD}{AE} = \\frac{DB}{EC} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the order of segments in the proportion, reversing the correct relationship} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\frac{AD}{EC} = \\frac{DB}{AE} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct pairing of segments across the parallel lines} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\frac{AD}{DB} = \\frac{EC}{AE} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to maintain the correct order of segments in the proportion} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-325'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In } \\triangle ABC, \\text{ with } DE \\parallel BC, \\text{ given } AD = 2 \\, \\text{cm}, BD = 3 \\, \\text{cm}, \\text{ and } BC = 7.5 \\, \\text{cm}, \\text{ calculate the length of } DE. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } DE. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{DE}{BC} \\\\ &\\implies \\frac{2}{3} = \\frac{DE}{7.5} \\\\ &\\therefore DE = \\frac{2}{3} \\times 7.5 \\\\ &\\implies DE = 5 \\, \\text{cm} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{5 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{4 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the ratio calculation by using incorrect values for } AD \\text{ and } DB. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{6 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct proportionality and overestimated the length of } DE. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{7 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the correct ratio and assumed } DE \\text{ is almost equal to } BC. \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(2)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the figure, } \\triangle ABC \\text{ has } DE \\parallel BC. \\text{ If } AD = 2.4 \\, \\text{cm}, DB = 4 \\, \\text{cm}, \\text{ and } AE = 2 \\, \\text{cm}, \\text{ find the length of } AC. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: } \\frac{AD}{DB} = \\frac{AE}{EC} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\quad \\frac{2.4}{4} = \\frac{2}{EC} \\\\ &\\implies \\quad EC = \\frac{2 \\times 4}{2.4} \\\\ &\\implies \\quad EC = \\frac{8}{2.4} \\\\ &\\implies \\quad EC = 3.3333 \\, \\text{cm} \\\\ &\\therefore \\quad AC = AE + EC = 2 + 3.3333 = 5.3333 \\, \\text{cm} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{5.3333 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{6 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Ignored the correct proportion calculation, leading to an overestimation of } EC. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{4.8 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Confused the addition of } AE \\text{ and } EC \\text{ by miscalculating } EC. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{5 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to use the exact decimal value for } EC, \\text{ rounding it incorrectly.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326(1)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the figure, } DE \\parallel BC \\text{ and all measurements are in centimeters. Determine the length of } AE. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the length of } AE. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\text{Substitute the given lengths:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\frac{3}{4} = \\frac{AE}{6} \\\\ &\\implies AE = \\frac{3}{4} \\times 6 \\\\ &\\therefore AE = 4.5 \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{4.5 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{3.5 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the multiplication step by using } \\frac{3}{4} \\times 5 \\text{ instead of } \\frac{3}{4} \\times 6. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{5 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct ratio and assumed } AE \\text{ equals } EC. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{6 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem and assumed } AE \\text{ is the same as } EC. \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-326'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the figure, } DE \\parallel BC. \\text{ If } AD = 2 \\text{ units, } DB = AE = 3 \\text{ units, and } EC = x \\text{ units, find the value of } x. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the value of } x. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ by Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{2}{3} = \\frac{3}{x} \\\\ &\\implies 2x = 9 \\\\ &\\therefore x = \\frac{9}{2} \\text{ units} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &x = \\frac{9}{2} \\text{ units} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &x = 3 \\text{ units} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the ratios by assuming } AD = AE \\text{ instead of using the correct ratios.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &x = 6 \\text{ units} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the proportionality and directly added } AD \\text{ and } DB. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &x = \\frac{5}{2} \\text{ units} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Miscalculated the cross-multiplication step in solving the proportion.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(2)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the given figure, if } AB \\parallel PQ, \\text{ and } AB = 6 \\, \\text{cm}, \\, PQ = 2 \\, \\text{cm}, \\text{ and } OB = 3 \\, \\text{cm}, \\text{ what is the length of } OP? \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } OP \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } AB \\parallel PQ, \\text{ so by Basic Proportionality Theorem, } \\frac{AB}{PQ} = \\frac{OB}{OP} \\\\ &\\implies \\quad \\frac{6}{2} = \\frac{3}{OP} \\\\ &\\implies \\quad 3 = \\frac{3}{OP} \\\\ &\\implies \\quad OP = 1 \\\\ &\\therefore \\quad \\text{The length of } OP \\text{ is } 1 \\, \\text{cm} \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{1 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{2 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the ratio of } AB \\text{ and } PQ \\text{ with } OB \\text{ and } OP \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{3 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem correctly} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{1.5 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Misunderstood the proportional relationship between the segments} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(1)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the given figure, } DE \\parallel BC. \\text{ Determine the value of } x. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem (Thales Theorem) to find the value of } x. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } DE \\parallel BC, \\text{ apply the Basic Proportionality Theorem:} \\\\ &\\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\text{Substitute the given values:} \\\\ &\\frac{3}{x} = \\frac{4}{6} \\\\ &\\implies 3 \\cdot 6 = 4 \\cdot x \\\\ &\\implies 18 = 4x \\\\ &\\implies x = \\frac{18}{4} \\\\ &\\implies x = 4.5 \\\\ &\\therefore x = 4.5 \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &x = 4.5 \\ \\ \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &x = 4 \\ \\ \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the simplification of } \\frac{18}{4} \\text{ as } 4 \\text{ instead of } 4.5. \\ \\ \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &x = 5 \\ \\ \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct cross-multiplication and division, leading to an incorrect } x \\text{ value of } 5. \\ \\ \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &x = 3.5 \\ \\ \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Misunderstood the proportionality setup, resulting in an incorrect calculation of } x \\text{ as } 3.5. \\ \\ \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In } \\triangle ABC, \\, PQ \\parallel BC. \\text{ If } PB = 6 \\, \\text{cm}, \\, AP = 4 \\, \\text{cm}, \\text{ and } AQ = 8 \\, \\text{cm}, \\text{ find the length of } AC. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } AC. \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given: } PQ \\parallel BC, \\text{ and } \\triangle APQ \\sim \\triangle ABC \\\\ &\\text{By Basic Proportionality Theorem: } \\frac{AP}{PB} = \\frac{AQ}{QC} \\\\ &\\implies \\frac{4}{6} = \\frac{8}{QC} \\\\ &\\implies 4 \\times QC = 6 \\times 8 \\\\ &\\implies QC = \\frac{48}{4} \\\\ &\\therefore QC = 12 \\\\ &\\text{Since } AC = AQ + QC \\\\ &\\implies AC = 8 + 12 \\\\ &\\therefore AC = 20 \\text{ cm} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{20 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{18 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the addition of } AQ \\text{ and } QC \\text{ by miscalculating } QC \\text{ as } 10 \\text{ instead of } 12. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{16 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct ratio and calculated } QC \\text{ as } 8 \\text{ leading to incorrect } AC. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{24 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the correct proportionality theorem, overestimating } QC \\text{ as } 16. \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-327(3)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the given figure, } PQ \\parallel AC. \\text{ If } BP = 4 \\, \\text{cm}, \\, AP = 2.4 \\, \\text{cm}, \\text{ and } BQ = 5 \\, \\text{cm}, \\text{ what is the length of } BC? \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem: If a line is parallel to one side of a triangle, it divides the other two sides proportionally.} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given: } PQ \\parallel AC, \\text{ so by Basic Proportionality Theorem,} \\\\ &\\frac{BP}{AP} = \\frac{BQ}{QC} \\\\ &\\implies \\frac{4}{2.4} = \\frac{5}{QC} \\\\ &\\implies 4 \\times QC = 5 \\times 2.4 \\\\ &\\implies 4QC = 12 \\\\ &\\implies QC = \\frac{12}{4} \\\\ &\\implies QC = 3 \\, \\text{cm} \\\\ &\\therefore BC = BQ + QC = 5 + 3 = 8 \\, \\text{cm} \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{8 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{7 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the addition of } BQ \\text{ and } QC \\text{ by miscalculating } QC \\text{ as } 2 \\text{ cm instead of } 3 \\text{ cm.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{9 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to correctly apply the Basic Proportionality Theorem, leading to an incorrect } QC \\text{ value.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{10 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the correct proportional relationship, assuming } QC \\text{ was larger than calculated.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(2)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the figure given below, determine the value of } x \\text{ that will make } PQ \\parallel AB. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the value of } x \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given } \\frac{AP}{PB} = \\frac{AQ}{QC} \\\\ &\\implies \\frac{3}{x} = \\frac{4}{6} \\\\ &\\implies 3 \\times 6 = 4 \\times x \\\\ &\\implies 18 = 4x \\\\ &\\implies x = \\frac{18}{4} \\\\ &\\implies x = 4.5 \\\\ &\\therefore x = 4.5 \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &x = 4.5 \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &x = 4 \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the cross-multiplication step, leading to an incorrect simplification.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &x = 5 \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct proportionality and miscalculated the product.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &x = 4.8 \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Misunderstood the division step, resulting in a slightly higher value.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',
  'topic_name': 'Basic Proportionality Theorem',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Triangles',
  'images': [{'image_1': '2025_02_17_bbe3f767e7e1821afad5g-328(1)'}],
  'publication': 'mtg',
  'question': [{'content': '\\begin{aligned} &\\text{In the given figure, with } D E \\parallel B C, \\text{ if } \\frac{A D}{D B}=\\frac{3}{2} \\text{ and } A E=2.7 \\mathrm{~cm}, \\text{ determine the length of } E C. \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the Basic Proportionality Theorem to find the length of } EC \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given: } DE \\parallel BC, \\frac{AD}{DB} = \\frac{3}{2}, AE = 2.7 \\text{ cm} \\\\ &\\text{By Basic Proportionality Theorem, } \\frac{AD}{DB} = \\frac{AE}{EC} \\\\ &\\implies \\frac{3}{2} = \\frac{2.7}{EC} \\\\ &\\implies 3 \\cdot EC = 2 \\cdot 2.7 \\\\ &\\implies 3 \\cdot EC = 5.4 \\\\ &\\therefore EC = \\frac{5.4}{3} \\\\ &\\therefore EC = 1.8 \\text{ cm} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{1.8 cm} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{2.0 cm} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the multiplication step, leading to an incorrect calculation of } EC. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{1.5 cm} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct ratio and miscalculated the division step.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{2.5 cm} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the Basic Proportionality Theorem correctly, leading to a wrong result.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_triangles_2',

In [34]:
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import pandas as pd
import os
from pathlib import Path
from PIL import Image
import io

from pylatexenc.latex2text import LatexNodes2Text

def process_latex_text(text):
    """Convert LaTeX formatted text to plain text using pylatexenc."""
    if not text:
        return ""
    return LatexNodes2Text().latex_to_text(text)


def process_image_ids(images):
    """Process image IDs and add .jpg extension"""
    try:
        if not images or not isinstance(images, list):
            return []
        
        processed_images = []
        for img_dict in images:
            if isinstance(img_dict, dict):
                image_id = next(iter(img_dict.values()))
                processed_images.append(f"{image_id}.jpg")
        
        return processed_images
    except Exception as e:
        print(f"Error in process_image_ids: {e}")
        return []

def get_content_text(content_list):
    """Extract content text from list of dictionaries"""
    try:
        if not content_list or not isinstance(content_list, list):
            return ""
        if not content_list[0]:
            return ""
        return process_latex_text(content_list[0].get('content', ''))
    except Exception as e:
        print(f"Error in get_content_text: {e}")
        return ""

def find_image_in_directory(image_filename, image_dir):
    """Find an image in the directory and its subdirectories using Path"""
    try:
        # Convert to Path object
        image_dir_path = Path(image_dir).resolve()
        
        # First try the direct path in the images directory
        direct_path = image_dir_path / image_filename
        if direct_path.is_file():
            try:
                # Validate image
                with Image.open(direct_path) as img:
                    img.verify()
                return str(direct_path)
            except Exception as e:
                print(f"Image validation failed for {direct_path}: {str(e)}")
                return None
        
        # If not found, search recursively
        for file_path in image_dir_path.rglob(image_filename):
            if file_path.is_file():
                try:
                    with Image.open(file_path) as img:
                        img.verify()
                    return str(file_path)
                except Exception:
                    continue
                
        print(f"Image not found or invalid: {image_filename}")
        return None
    except Exception as e:
        print(f"Error finding image {image_filename}: {e}")
        return None

def add_formatted_paragraph(doc, label, content, bold_label=True, spacing_before=0, spacing_after=0):
    """Add a formatted paragraph with label and content"""
    paragraph = doc.add_paragraph()
    if bold_label and label:
        paragraph.add_run(f"{label}: ").bold = True
    paragraph.add_run(content)
    paragraph.space_before = Pt(spacing_before)
    paragraph.space_after = Pt(spacing_after)
    return paragraph

def process_question_data(doc, question_data):
    """Process a single question's data and add it to the document"""
    try:
        # Add metadata section
        metadata_heading = doc.add_heading('Question Information', level=1)
        metadata_heading.style.font.size = Pt(14)
        
        # Handle metadata fields safely
        metadata_fields = {
            "Topic Name": str(question_data.get('topic_name', '')),
            "Subject": str(question_data.get('subject', '')).title(),
            "Grade": str(question_data.get('grade', '')),
            "Board": str(question_data.get('board', '')),
            "Chapter": str(question_data.get('chapter_name', '')),
            "Publication": str(question_data.get('publication', '')),
            "Topic ID": str(question_data.get('topic_id', ''))
        }
        
        for label, content in metadata_fields.items():
            add_formatted_paragraph(doc, label, content)
        
        # Add question section
        doc.add_heading('Question', level=1)
        question_text = get_content_text(question_data.get('question', []))
        add_formatted_paragraph(doc, "", question_text, bold_label=False, spacing_after=10)
        
        # Add images
        images = question_data.get('images', [])
        if images and isinstance(images, list):
            image_files = process_image_ids(images)
            for img_file in image_files:
                img_path = find_image_in_directory(img_file, image_dir)
                if img_path:
                    try:
                        print(f"Adding image from path: {img_path}")
                        with Image.open(img_path) as img:
                            if img.mode not in ('RGB', 'RGBA'):
                                img = img.convert('RGB')
                            img_byte_arr = io.BytesIO()
                            img.save(img_byte_arr, format='PNG')
                            img_byte_arr.seek(0)
                            picture = doc.add_picture(img_byte_arr, width=Inches(4))
                            last_paragraph = doc.paragraphs[-1]
                            last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    except Exception as e:
                        print(f"Error adding image {img_file}: {str(e)}")
        
        # Add options section
        doc.add_heading('Options', level=2)
        for i in range(1, 4):
            option_text = get_content_text(question_data.get(f'option{i}', []))
            explanation = get_content_text(question_data.get(f'dr{i}', []))
            if option_text:
                add_formatted_paragraph(doc, f"Option {i}", option_text, spacing_before=5)
            if explanation:
                add_formatted_paragraph(doc, "Explanation", explanation, spacing_after=10)
        
        # Add hint section
        hint_text = get_content_text(question_data.get('hint', []))
        if hint_text:
            doc.add_heading('Hint', level=2)
            add_formatted_paragraph(doc, "", hint_text, bold_label=False)
        
        # Add solution section
        solution_text = get_content_text(question_data.get('solution', []))
        if solution_text:
            doc.add_heading('Solution', level=2)
            add_formatted_paragraph(doc, "", solution_text, bold_label=False)
        
        # Add final answer section
        final_answer = get_content_text(question_data.get('final_answer', []))
        if final_answer:
            doc.add_heading('Final Answer', level=2)
            add_formatted_paragraph(doc, "", final_answer, bold_label=False)
        
        # Add page break
        doc.add_page_break()
        
    except Exception as e:
        print(f"Error processing question: {str(e)}")

def create_docx_with_images(json_data, image_dir, output_path='questions_with_images.docx'):
    """Create Word document from JSON data with images"""
    try:
        print("\nProcessing data and creating Word document...")
        
        # Convert image_dir to absolute Path
        image_dir = Path(image_dir).resolve()
        print(f"Using image directory: {image_dir}")
        
        # Validate image directory
        if not image_dir.exists():
            raise ValueError(f"Image directory does not exist: {image_dir}")
        
        # Convert string to list if needed
        if isinstance(json_data, str):
            data = eval(json_data)
        else:
            data = json_data
        
        # Ensure data is a list
        if not isinstance(data, list):
            data = [data]
            
        # Create document
        doc = Document()
        
        # Add title
        title = doc.add_heading('Question Paper', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Process each question in the list
        for question_data in data:
            process_question_data(doc, question_data)
        
        # Save the document
        doc.save(output_path)
        print(f"Word document created successfully at: {output_path}")
        return True
        
    except Exception as e:
        print(f"Error creating Word document: {str(e)}")
        return False
# Example usage
if __name__ == "__main__":

    image_dir = Path("textbooks\mtg\Triangles_10\\2025_02_17_bbe3f767e7e1821afad5g\images")
    
    create_docx_with_images(final_output, image_dir , output_path=f"{conf_data['chapter_name']}_{conf_data['publication']}_questions_with images.docx")

<>:218: SyntaxWarning: invalid escape sequence '\m'
<>:218: SyntaxWarning: invalid escape sequence '\m'
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_24708\3976394110.py:218: SyntaxWarning: invalid escape sequence '\m'
  image_dir = Path("textbooks\mtg\Triangles_10\\2025_02_17_bbe3f767e7e1821afad5g\images")

Processing data and creating Word document...
Using image directory: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-324.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-325.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-326(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-326(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-326.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-327(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-327(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-327.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-327(3).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-328(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-328(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-328.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329(3).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-329(4).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-330(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-330.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-330(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-331(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-331(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-331.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-332(4).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-332.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-332(3).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-332(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-333(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-333(3).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-334.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-334(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-335(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-335(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-335.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-336.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-336(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-336(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-337.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-337(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-337(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-338.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-338(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-339.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-339(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-339(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-340(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-342.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-343.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-343(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-344.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-345.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-346.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-347.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-348(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-348.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-348(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-349.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-350.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-352.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-354.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-356.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-357.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-357(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-358.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-359.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-360.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-361.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-361(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-362(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-362.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-363.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-366.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-367.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-368(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-368.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-369(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-369.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-371.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-372(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-372.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-373(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-373.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-374(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-374.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-375.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-376(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-376.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-377.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-378.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-378(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-379.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-380.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-381(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-381(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-381.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-382(2).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-382(1).jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-382.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-384.jpg
Adding image from path: E:\Questions_extraction\cbse\textbooks\mtg\Triangles_10\2025_02_17_bbe3f767e7e1821afad5g\images\2025_02_17_bbe3f767e7e1821afad5g-387.jpg
Word document created successfully at: Triangles_mtg_questions_with images.docx

#### Latex Formatting to store in DB

In [ ]:
from config import MONGO_URL , DB_NAME

In [ ]:
dbCollection = "LatexTest"
client = AsyncIOMotorClient(MONGO_URL)

KeyboardInterrupt:

In [ ]:
async def pushToDB(dbContent, subject):
    try:
        db = client[DB_NAME]
        que_collection = db[dbCollection]

        dbContent["status"] = "not_reviewed"
        dbContent["comment"] = ""
        dbContent["testFlag"] = "true"
        dbContent["subject"] = subject
        await que_collection.insert_one(dbContent)
        print("Data Uploaded to the database successfully.")
    except Exception as e:
        print("Exception Occurred: ", type(e).__name__, "–", e, "\n", traceback.format_exc())

In [ ]:
for doc in final_output:
    await pushToDB(doc, subject)
client.close()

Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.