## Text Extraction, Cleaning, and Rephrasing from multiple books

In [1]:
import pandas as pd
import traceback
import json
from PyPDF2 import PdfReader
import os

from bson import ObjectId
from motor.motor_asyncio import AsyncIOMotorClient
from langchain_openai import ChatOpenAI
from langchain import PromptTemplate, LLMChain

from latext_Prompts import (
EXTRACTION_SYSTEM,
EXTRACTION_USER,
EXTRACTION_OUTPUT_FORMAT,
MATHEMATICS_EXTRACTION_OUTPUT_EXAMPLE,
BIOLOGY_EXTRACTION_OUTPUT_EXAMPLE,
PHYSICS_EXTRACTION_OUTPUT_EXAMPLE,
CHEMISTRY_EXTRACTION_OUTPUT_EXAMPLE,
EMPTY_EXTRACTION_OUTPUT_FORMAT,
CLEAN_REPHRASE_USER,
CLEAN_REPHRASE_SYSTEM,
REPHRASE_OUTPUT_FORMAT,
REPHRASE_OUTPUT_EXAMPLE,
BIOLOGY_SOLUTION_SYSTEM_PROMPT,
CHEMISTRY_SOLUTION_SYSTEM_PROMPT,
MATHEMATICS_SOLUTION_SYSTEM_PROMPT,
PHYSICS_SOLUTION_SYSTEM_PROMPT,
DISTRACTOR_SYSTEM_PROMPT
)

from config import (
    OPENAI_API_KEY,
    MONGO_URL,
    DB_NAME
)

In [2]:
# os.environ["LANGCHAIN_TRACING_V2"] = "true"
# os.environ["LANGCHAIN_API_KEY"] = "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"
# os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
# os.environ["LANGCHAIN_PROJECT"] = "Questions Extractor"

# Pipeline

In [3]:
import json
def parse_Response(response):
    if isinstance(response, str):
        # print(response)
        start_index = response.find("{")
        end_index = response.rfind("}")
        if start_index != -1 and end_index != -1:
            valid_json_content = response[start_index : end_index + 1]
            try:
                JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
                # append_list_to_file(JSON_response)
                return JSON_response
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON response: {e.__class__.__name__} - {e}\n\n Still trying to work on particular exceptions ...")
                if str(e).startswith("Extra data"):
                    json_parts = valid_json_content.split('}\n{')
                    if json_parts:
                        first_json = json_parts[0] + '}'
                        return parse_Response(first_json)  
                elif str(e).startswith("Invalid \escape"):
                    print("Before removing \\ issue: ", valid_json_content)
                    str1 = valid_json_content.replace("\\\\\\\\\\", "fvback")
                    str1 = str1.replace("\\\\\\\\", "frback")
                    str1 = str1.replace("\\\\\\", "trlback")
                    str1 = str1.replace("\\\\", "dblback")
                    str1 = str1.replace("\\", "\\\\")
                    str1 = str1.replace("fvback","\\\\\\\\\\")
                    str1 = str1.replace("frback", "\\\\\\\\")
                    str1 = str1.replace("trlback","\\\\\\")
                    strfinal = str1.replace("dblback","\\\\")
                    print("After removing \\ issue: ", strfinal)
                    JSON_response = json.loads(strfinal.replace("\n", ""))
                    return JSON_response
                else:
                    print("Actual Content: ", valid_json_content)
        else:
            print("No valid JSON content found in the response.")
        # time.sleep(50)
    elif isinstance(response, dict):
        return response
    else:
        print("No response message found", type(response))

<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_12884\3339088456.py:10: SyntaxWarning: invalid escape sequence '\('
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_12884\3339088456.py:10: SyntaxWarning: invalid escape sequence '\)'
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_12884\3339088456.py:20: SyntaxWarning: invalid escape sequence '\e'
  elif str(e).startswith("Invalid \escape"):

In [4]:
# All question collection

def collect_questions_from_chapter_with_Langchain(subject, chapter_text, chapter_name, grade):
    try:
        # initialize the ChapOpenAI object
        llm = ChatOpenAI(
            model_name="gpt-4o",
            api_key= OPENAI_API_KEY,
            temperature=0.2,
        )
        match subject:
            case "mathematics":
                examples=MATHEMATICS_EXTRACTION_OUTPUT_EXAMPLE
            case "biology":
                examples=BIOLOGY_EXTRACTION_OUTPUT_EXAMPLE
            case "physics":
                examples =PHYSICS_EXTRACTION_OUTPUT_EXAMPLE
            case "chemistry":
                examples=CHEMISTRY_EXTRACTION_OUTPUT_EXAMPLE

        #formatting prompts
        system = EXTRACTION_SYSTEM.format("",grade = grade, subject = subject,EMPTY_EXTRACTION_OUTPUT_FORMAT = EMPTY_EXTRACTION_OUTPUT_FORMAT, out_format = EXTRACTION_OUTPUT_FORMAT, out_example = examples)
        user = EXTRACTION_USER.format(chapter_name = chapter_name, chapter_text = chapter_text)

        #generating response from api call
        response = llm.invoke(
            [
                ("system", system),
                ("human", user)
            ],
        )
        return response
    except Exception as e:
        print("Error with in extraction: ", type(e).__name__, "–", e, "\n", traceback.format_exc())
        return None

In [5]:
def clean_rephrase_question(question_text, topic_list):
    try:
        llm = ChatOpenAI(
            model_name="gpt-4o",
            api_key= OPENAI_API_KEY,
            temperature=0.2,
            # verbose = True
        )
        # client = OpenAI(base_url='https://api.deepseek.com/v1', api_key='sk-c25c646d6e3a41c3801a44766a4baa48')



        #formatting prompts
        system = CLEAN_REPHRASE_SYSTEM.format("",out_example = REPHRASE_OUTPUT_EXAMPLE, out_format = REPHRASE_OUTPUT_FORMAT)
        user = CLEAN_REPHRASE_USER.format(question_text = question_text, topic_list = topic_list)

        # #generating response from api call
        response = llm.invoke(
            [
                ("system", system),
                ("human", user)
            ]
        )
        # response = client.chat.completions.create(model='deepseek-reasoner',
        #                             messages= [
        #                                 {'role':'system', 'content': system },
        #                                 {'role':'user', 'content': user },
        #                                         ],
        #                             # response_format={'type': 'json_object', 'schema': schema},
        #                             temperature=0.2,
        #                             )
        return response

    except Exception as e:
        print("Error cleaning text: ", type(e).__name__, "–", e, "\n", traceback.format_exc())
        return question_text  # Return original text in case of an error

In [6]:
import os
import traceback
from pathlib import Path
import zipfile
import tempfile
import shutil

def read_data_from_latex(publication: str, chapter_name: str , grade:str) -> str:
    """
    Read LaTeX content from a specified publication and chapter zip file.
    
    Args:
        publication (str): Name of the publication (e.g., 'mtg')
        chapter_name (str): Name of the chapter (e.g., 'Life Processes')
    
    Returns:
        str: Content of the LaTeX file if successful, empty string if failed
    """
    try:
        # Construct the zip file path
        zip_path = os.path.join(r"textbooks", publication, f"{chapter_name}_{grade}.zip")
        
        # Verify zip file exists
        if not os.path.exists(zip_path):
            raise FileNotFoundError(f"Zip file not found: {zip_path}")
        
        # Create a temporary directory to extract files
        with tempfile.TemporaryDirectory() as temp_dir:
            # Extract the zip file
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)
            
            # Find directories starting with 2025
            content_dirs = [d for d in os.listdir(temp_dir) 
                          if os.path.isdir(os.path.join(temp_dir, d)) and 
                          d.startswith('2025')]
            
            if not content_dirs:
                raise FileNotFoundError(f"No content directories found in zip file")
                
            # Get the latest directory
            latest_dir = sorted(content_dirs)[-1]
            dir_path = os.path.join(temp_dir, latest_dir)
            
            # Find the .tex file in the directory
            tex_files = [f for f in os.listdir(dir_path) if f.endswith('.tex')]
                    
            if not tex_files:
                raise FileNotFoundError(f"No .tex file found in {dir_path}")
                
            # Full path to the tex file
            latex_path = os.path.join(dir_path, tex_files[0])
            
            # Read the content
            with open(latex_path, 'r', encoding='utf-8') as file:
                content = file.read()
                
            print(f"Successfully processed LaTeX file from zip: {latex_path}")
            return content

    except Exception as e:
        print(
            "Failed to process the LaTeX file. Exception Occurred:",
            type(e).__name__,
            "–",
            e,
            "\n",
            traceback.format_exc()
        )
        return ""

In [7]:
def extract_questions(subject: str, chapter_texts: list, chapter_name: str, grade: str) -> list:
    try:
        # Validate inputs
        if not isinstance(chapter_texts, list):
            raise ValueError("chapter_texts must be a list of strings")
            
        if not chapter_texts:
            print(f"Warning: Empty chapter_texts for chapter {chapter_name}")
            return []
            
        all_questions = []
        
        # Process lines in chunks of 500
        chunk_size = 250
        for chunk_index in range(0, len(chapter_texts), chunk_size):
            try:
                # Get current chunk of lines
                chunk = chapter_texts[chunk_index:chunk_index + chunk_size]
                
                # Skip empty chunks
                if not chunk:
                    continue
                    
                print(f"Processing chunk {chunk_index//chunk_size + 1}/{-(-len(chapter_texts)//chunk_size)}")
                
                # Use the original collection function
                questions = collect_questions_from_chapter_with_Langchain(
                    subject=subject,
                    chapter_text="\n".join(chunk),
                    chapter_name=chapter_name,
                    grade=grade
                )
                
                # Parse and store valid questions
                if questions and questions.content:
                    parsed = parse_Response(questions.content)
                    if parsed and "questions" in parsed:
                        questions_list = parsed["questions"]
                        if questions_list:
                            all_questions.extend(questions_list)
                            print(f"Extracted {len(questions_list)} questions from chunk {chunk_index//chunk_size + 1}")
                
            except Exception as e:
                print(f"Error processing chunk {chunk_index//chunk_size + 1}: {str(e)}")
                continue
        
        print(f"Total questions extracted: {len(all_questions)}")
        return all_questions

    except Exception as e:
        print(f"Error in extract_questions: {str(e)}")
        return []

In [8]:
def rephrase_questions(conf_data: dict, all_questions: list, topics: list) -> dict:
    print("Starting the cleanup and rephrasing process...")
    try:
        # Validate inputs
        if not conf_data or "chapter_name" not in conf_data:
            raise ValueError("Missing chapter_name in configuration")
            
        if not topics:
            print("\n\nNo topics found in the data.")
            raise ValueError("No topics found in the data")
            
        chapter = conf_data["chapter_name"]
        clean_rephrased_questions = {}
        chapterwise_formatted_questions = []
        
        if not all_questions:
            raise ValueError(f"No questions found for chapter {chapter}")
            
        print(f"\nWorking on chapter {chapter}")
        print(f"Total questions to process: {len(all_questions)}")
        
        # Process questions in batches of 5
        batch_size = 5
        for batch_start in range(0, len(all_questions), batch_size):
            try:
                # Get current batch of questions
                question_batch = all_questions[batch_start:batch_start + batch_size]
                print(f"\nProcessing batch {batch_start//batch_size + 1}/{-(-len(all_questions)//batch_size)}")
                
                # Clean and rephrase the batch
                cleaned_rephrased_questions = clean_rephrase_question(question_batch, topics)
                print("Raw response:", cleaned_rephrased_questions)
                
                # Parse the cleaned response
                if cleaned_rephrased_questions and cleaned_rephrased_questions.content:
                    formatted_questions = parse_Response(cleaned_rephrased_questions.content)
                    if formatted_questions and "questions" in formatted_questions:
                        chapterwise_formatted_questions.extend(formatted_questions["questions"])
                        print(f"Successfully processed {len(formatted_questions['questions'])} questions in batch")
                    else:
                        print(f"Warning: No valid questions found in batch {batch_start//batch_size + 1}")
                
                print("-" * 100)
                
            except Exception as batch_error:
                print(f"Error processing batch {batch_start//batch_size + 1}: {str(batch_error)}")
                continue
        
        # Store processed questions if any were successful
        if chapterwise_formatted_questions:
            clean_rephrased_questions[chapter] = chapterwise_formatted_questions
            print(f"\nSuccessfully processed {len(chapterwise_formatted_questions)} questions for chapter {chapter}")
        else:
            print(f"\nWarning: No questions were successfully processed for chapter {chapter}")
        
        return clean_rephrased_questions
        
    except Exception as e:
        print(f"Failed to clean and rephrase questions. Exception Occurred: {type(e).__name__} – {str(e)}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return {}

In [9]:
from typing import Tuple, Dict, Optional
import traceback
import logging

def extract_rephrase_questions(conf_data: dict, topics: list) -> Tuple[Optional[Dict], Optional[Dict]]:
    try:
        # Validate configuration data
        required_fields = ["subject", "grade", "chapter_name"]
        missing_fields = [field for field in required_fields if field not in conf_data]
        if missing_fields:
            raise ValueError(f"Missing required configuration fields: {', '.join(missing_fields)}")
            
        if not topics:
            raise ValueError("No topics provided for question rephrasing")
            
        print("Starting question extraction and rephrasing pipeline...")
        
        # Step 1: Scrape text from PDF/LaTeX
        print("\nStep 1: Scraping textbook content...")
        pdf_text = read_data_from_latex(publication=conf_data['publication'] , chapter_name=conf_data['chapter_name'] ,grade=conf_data['grade'])
        if not pdf_text:
            raise ValueError("No text content extracted from textbook")
        print(f"Successfully extracted {len(pdf_text)} text segments")
            
        # Step 2: Extract questions from text
        print("\nStep 2: Extracting questions from text...")
        extracted_questions = extract_questions(
            subject=conf_data["subject"],
            grade=conf_data["grade"],
            chapter_name=conf_data["chapter_name"],
            chapter_texts=pdf_text.split("\n")
        )
        if not extracted_questions:
            raise ValueError("No questions were extracted from the text")
        print(f"Successfully extracted questions")
            
        # Step 3: Clean and rephrase questions
        print("\nStep 3: Cleaning and rephrasing questions...")
        final_rephrased_questions = rephrase_questions(
            conf_data=conf_data,
            all_questions=extracted_questions,
            topics=topics
        )
        if not final_rephrased_questions:
            raise ValueError("No questions were successfully rephrased")
        print("Successfully rephrased questions")
            
        # Return results
        print("\nPipeline completed successfully!")
        return extracted_questions, final_rephrased_questions
        
    except ValueError as val_err:
        print(f"Validation error: {str(val_err)}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return None, None
        
    except Exception as e:
        print(f"Unexpected error in question processing pipeline: {str(e)}")
        print(f"Exception type: {type(e).__name__}")
        print(f"Traceback:\n{traceback.format_exc()}")
        return None, None
        
    finally:
        print("\nQuestion processing pipeline finished")

In [10]:
# get chapter and book data from defaultConf
with open("defaultConf.json", "r") as f:
    conf_data = json.load(f)

chapter = conf_data["chapter_name"]
subject = conf_data["subject"]


print("Chapter to work on: ", chapter)
print(subject)
print(conf_data['publication'])

Chapter to work on:  Polynomials
mathematics
rsagarwal

In [11]:
import pandas as pd

def process_filename(filename):
    """
    Process filename by stripping whitespace and converting to lowercase
    """
    return filename.strip().lower()
grade = conf_data['grade']
# Match subject to determine sheet name
match subject:
    case "mathematics":
        sheet_name = f"G{grade} Maths"
    case "biology":
        sheet_name = f"G{grade} Science"
    case "physics":
        sheet_name = f"G{grade} Science"
    case "chemistry":
        sheet_name = f"G{grade} Science"
print(sheet_name)
# Read Excel file and process the filename
file_name = process_filename("LEAP Course Creation - Topic LU Prerequisite Misconceptions.xlsx")
misconceptions_df = pd.read_excel(file_name, sheet_name=sheet_name)

# Clean column names
misconceptions_df.columns = misconceptions_df.columns.str.strip()
misconceptions_df.fillna("", inplace=True)

# Process chapter name from conf_data for comparison
chapter_name = conf_data["chapter_name"].strip().lower()

# Get unique topics for the specified chapter
tempTopics = list(misconceptions_df[
    misconceptions_df["Chapter (NCERT/AcadAlly's name)"].str.strip().str.lower() == chapter_name
]["Topic"].unique())

# Create topics dictionary with processed IDs
topics = {}
for i in range(len(tempTopics)):
    topic_id = f"{conf_data['grade']}_{conf_data['subject']}_{chapter_name}_{i+1}"
    topics[topic_id] = tempTopics[i].strip()

print("Topics with ID: ", topics, "\n\n", topics.values())

# Process misconceptions and LUs
total_misconceptions = {}
total_LUs = {}

for i, row in misconceptions_df.iterrows():
    topic = str(row["Topic"]).strip()
    
    if topic in topics.values():
        # Process LUs
        if topic in total_LUs:
            total_LUs[topic].append(row["LUs Covered"])
        else:
            total_LUs[topic] = [row["LUs Covered"]]

        # # Process misconceptions
        # temp_misconceptions = [
        #     row[f"Misconceptions {i}"] 
        #     for i in range(1, 11) 
        #     if row[f"Misconceptions {i}"] != ""
        # ]

        # if topic in total_misconceptions:
        #     total_misconceptions[topic].extend(temp_misconceptions)
        # else:
        #     total_misconceptions[topic] = temp_misconceptions

print(total_LUs, sep="\n\n-------------------------------------------------------------------\n\n")

G10 Maths
Topics with ID:  {'10_mathematics_polynomials_1': 'Geometrical Interpretation of the Zeros of Linear and Quadratic Polynomials', '10_mathematics_polynomials_2': 'Geometrical Interpretation of the Zeros of Polynomials of Degree Greater Than 2', '10_mathematics_polynomials_3': 'Relationship between zeros and coefficients of a polynomial', '10_mathematics_polynomials_4': 'Formation of polynomial from given sum and product of zeroes'}

 dict_values(['Geometrical Interpretation of the Zeros of Linear and Quadratic Polynomials', 'Geometrical Interpretation of the Zeros of Polynomials of Degree Greater Than 2', 'Relationship between zeros and coefficients of a polynomial', 'Formation of polynomial from given sum and product of zeroes'])
{'Geometrical Interpretation of the Zeros of Linear and Quadratic Polynomials': ['Geometrical meaning of zero of a linear polynomial', 'Geometrical meaning of the zeroes of a quadratic polynomial'], 'Geometrical Interpretation of the Zeros of Polynomials of Degree Greater Than 2': ['Geometrical meaning of the zeroes of a cubic polynomial', 'Geometrical meaning of the zeroes of a polynomial p(x) of degree n (n>3)'], 'Relationship between zeros and coefficients of a polynomial': ['Relationship between zero and coefficients of a linear polynomial', 'Relationship between zeroes and coefficients of a quadratic polynomial', 'Relationship between zeroes and coefficients of a cubic polynomial'], 'Formation of polynomial from given sum and product of zeroes': ['Formation of quadratic polynomial from given sum and product of zeroes']}

C:\Users\aniket singh\AppData\Local\Temp\ipykernel_12884\609127329.py:26: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  misconceptions_df.fillna("", inplace=True)

In [12]:
total_LUs

{'Geometrical Interpretation of the Zeros of Linear and Quadratic Polynomials': ['Geometrical meaning of zero of a linear polynomial',
  'Geometrical meaning of the zeroes of a quadratic polynomial'],
 'Geometrical Interpretation of the Zeros of Polynomials of Degree Greater Than 2': ['Geometrical meaning of the zeroes of a cubic polynomial',
  'Geometrical meaning of the zeroes of a polynomial p(x) of degree n (n>3)'],
 'Relationship between zeros and coefficients of a polynomial': ['Relationship between zero and coefficients of a linear polynomial',
  'Relationship between zeroes and coefficients of a quadratic polynomial',
  'Relationship between zeroes and coefficients of a cubic polynomial'],
 'Formation of polynomial from given sum and product of zeroes': ['Formation of quadratic polynomial from given sum and product of zeroes']}

In [13]:
extracted_raw_questions_json ,clean_rephrased_questions_json = extract_rephrase_questions(conf_data, topics)

Starting question extraction and rephrasing pipeline...

Step 1: Scraping textbook content...
Successfully processed LaTeX file from zip: C:\Users\ANIKET~1\AppData\Local\Temp\tmpk6ie5v3y\2025_02_04_3785c2277acb8114accbg\2025_02_04_3785c2277acb8114accbg.tex
Successfully extracted 56030 text segments

Step 2: Extracting questions from text...
Processing chunk 1/6
Processing chunk 2/6
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 120 (char 119)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "questions": [
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad x^{2}+7x+12 \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad x^{2}-2x-8 \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad x^{2}+3x-10 \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad 4x^{2}-4x-3 \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad 5x^{2}-4-8x \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad 2\sqrt{3}x^{2}-5x+\sqrt{3} \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad 2x^{2}-11x+15 \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad 4x^{2}-4x+1 \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad x^{2}-5 \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad 8x^{2}-4 \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad 5y^{2}+10y \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the zeros of the quadratic polynomial} \quad 3x^{2}-x-4 \quad \text{and verify the relationship between the zeros and the coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the quadratic polynomial whose zeros are 2 and -6. Verify the relation between the coefficients and the zeros of the polynomial.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the quadratic polynomial whose zeros are} \quad \frac{2}{3} \quad \text{and} \quad \frac{-1}{4}. \quad \text{Verify the relation between the coefficients and the zeros of the polynomial.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the quadratic polynomial, sum of whose zeros is 8 and their product is 12. Hence, find the zeros of the polynomial.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the quadratic polynomial, the sum of whose zeros is 0 and their product is -1. Hence, find the zeros of the polynomial.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the quadratic polynomial, the sum of whose zeros is} \quad \left(\frac{5}{2}\right) \quad \text{and their product is 1. Hence, find the zeros of the polynomial.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the quadratic polynomial, the sum of whose roots is} \quad \sqrt{2} \quad \text{and their product is} \quad \frac{1}{3}. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{If} \quad x=\frac{2}{3} \quad \text{and} \quad x=-3 \quad \text{are the roots of the quadratic equation} \quad ax^{2}+7x+b=0, \quad \text{then find the values of} \quad a \quad \text{and} \quad b. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{If} \quad (x+a) \quad \text{is a factor of the polynomial} \quad 2x^{2}+2ax+5x+10, \quad \text{find the value of} \quad a. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{One zero of the polynomial} \quad 3x^{3}+16x^{2}+15x-18 \quad \text{is} \quad \frac{2}{3}. \quad \text{Find the other zeros of the polynomial.} \end{aligned}"
        }
    ]
}
After removing \ issue:  {
    "questions": [
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad x^{2}+7x+12 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad x^{2}-2x-8 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad x^{2}+3x-10 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 4x^{2}-4x-3 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 5x^{2}-4-8x \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 2\\sqrt{3}x^{2}-5x+\\sqrt{3} \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 2x^{2}-11x+15 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 4x^{2}-4x+1 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad x^{2}-5 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 8x^{2}-4 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 5y^{2}+10y \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 3x^{2}-x-4 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the quadratic polynomial whose zeros are 2 and -6. Verify the relation between the coefficients and the zeros of the polynomial.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the quadratic polynomial whose zeros are} \\quad \\frac{2}{3} \\quad \\text{and} \\quad \\frac{-1}{4}. \\quad \\text{Verify the relation between the coefficients and the zeros of the polynomial.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the quadratic polynomial, sum of whose zeros is 8 and their product is 12. Hence, find the zeros of the polynomial.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the quadratic polynomial, the sum of whose zeros is 0 and their product is -1. Hence, find the zeros of the polynomial.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the quadratic polynomial, the sum of whose zeros is} \\quad \\left(\\frac{5}{2}\\right) \\quad \\text{and their product is 1. Hence, find the zeros of the polynomial.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the quadratic polynomial, the sum of whose roots is} \\quad \\sqrt{2} \\quad \\text{and their product is} \\quad \\frac{1}{3}. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{If} \\quad x=\\frac{2}{3} \\quad \\text{and} \\quad x=-3 \\quad \\text{are the roots of the quadratic equation} \\quad ax^{2}+7x+b=0, \\quad \\text{then find the values of} \\quad a \\quad \\text{and} \\quad b. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{If} \\quad (x+a) \\quad \\text{is a factor of the polynomial} \\quad 2x^{2}+2ax+5x+10, \\quad \\text{find the value of} \\quad a. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{One zero of the polynomial} \\quad 3x^{3}+16x^{2}+15x-18 \\quad \\text{is} \\quad \\frac{2}{3}. \\quad \\text{Find the other zeros of the polynomial.} \\end{aligned}"
        }
    ]
}
Extracted 21 questions from chunk 2
Processing chunk 3/6
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 129 (char 128)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "questions": [
        {
            "question": "\begin{aligned} \text{EXAMPLE 6 Divide } 5x^{3}-13x^{2}+21x-14 \text{ by } \left(3-2x+x^{2}\right) \text{ and verify the division algorithm.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{EXAMPLE 7 What real number should be subtracted from the polynomial } \left(3x^{3}+10x^{2}-14x+9\right) \text{ so that } (3x-2) \text{ divides it exactly?} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{EXAMPLE 8 If the polynomial } \left(x^{4}+2x^{3}+8x^{2}+12x+18\right) \text{ is divided by another polynomial } \left(x^{2}+5\right), \text{ the remainder comes out to be } (px+q). \text{ Find the values of } p \text{ and } q. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{EXAMPLE 9 On dividing } \left(x^{3}-3x^{2}+x+2\right) \text{ by a polynomial } g(x), \text{ the quotient and remainder are } (x-2) \text{ and } (-2x+4) \text{ respectively. Find } g(x). \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{EXAMPLE 10 It being given that 1 is a zero of the polynomial } \left(7x-x^{3}-6\right), \text{ find its other zeros.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{EXAMPLE 11 Obtain all zeros of the polynomial } \left(2x^{3}-4x-x^{2}+2\right), \text{ if two of its zeros are } \sqrt{2} \text{ and } -\sqrt{2}. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{EXAMPLE 12 If two zeros of the polynomial } \left(x^{4}-6x^{3}-26x^{2}+138x-35\right) \text{ are } (2+\sqrt{3}) \text{ and } (2-\sqrt{3}), \text{ find other zeros.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{EXAMPLE 13 Obtain all zeros of } \left(3x^{4}-15x^{3}+13x^{2}+25x-30\right), \text{ if two of its zeros are } \sqrt{\frac{5}{3}} \text{ and } -\sqrt{\frac{5}{3}}. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Verify that } 3,-2,1 \text{ are the zeros of the cubic polynomial } p(x)=x^{3}-2x^{2}-5x+6 \text{ and verify the relation between its zeros and coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Verify that } 5,-2 \text{ and } \frac{1}{3} \text{ are the zeros of the cubic polynomial } p(x)=3x^{3}-10x^{2}-27x+10 \text{ and verify the relation between its zeros and coefficients.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find a cubic polynomial whose zeros are } 2, -3 \text{ and } 4. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find a cubic polynomial whose zeros are } \frac{1}{2}, 1 \text{ and } -3. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find a cubic polynomial with the sum, sum of the product of its zeros taken two at a time, and the product of its zeros as } 5,-2 \text{ and } -24 \text{ respectively.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the quotient and the remainder when } f(x)=x^{3}-3x^{2}+5x-3 \text{ is divided by } g(x)=x^{2}-2. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the quotient and the remainder when } f(x)=x^{4}-3x^{2}+4x+5 \text{ is divided by } g(x)=x^{2}+1-x. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Find the quotient and the remainder when } f(x)=x^{4}-5x+6 \text{ is divided by } g(x)=2-x^{2}. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{By actual division, show that } x^{2}-3 \text{ is a factor of } 2x^{4}+3x^{3}-2x^{2}-9x-12. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{On dividing } 3x^{3}+x^{2}+2x+5 \text{ by a polynomial } g(x), \text{ the quotient and remainder are } (3x-5) \text{ and } (9x+10) \text{ respectively. Find } g(x). \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{Verify division algorithm for the polynomials } f(x)=8+20x+x^{2}-6x^{3} \text{ and } g(x)=2+5x-3x^{2}. \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{It is given that -1 is one of the zeros of the polynomial } x^{3}+2x^{2}-11x-12. \text{ Find all the zeros of the given polynomial.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{If 1 and -2 are two zeros of the polynomial } \left(x^{3}-4x^{2}-7x+10\right), \text{ find its third zero.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{If 3 and -3 are two zeros of the polynomial } \left(x^{4}+x^{3}-11x^{2}-9x+18\right), \text{ find all the zeros of the given polynomial.} \end{aligned}"
        },
        {
            "question": "\begin{aligned} \text{If 2 and -2 are two zeros of the polynomial } \left(x^{4}+x^{3}-34x^{2}-4x+120\right), \text{ find all the zeros of the given polynomial.} \end{aligned}"
        }
    ]
}
After removing \ issue:  {
    "questions": [
        {
            "question": "\\begin{aligned} \\text{EXAMPLE 6 Divide } 5x^{3}-13x^{2}+21x-14 \\text{ by } \\left(3-2x+x^{2}\\right) \\text{ and verify the division algorithm.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{EXAMPLE 7 What real number should be subtracted from the polynomial } \\left(3x^{3}+10x^{2}-14x+9\\right) \\text{ so that } (3x-2) \\text{ divides it exactly?} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{EXAMPLE 8 If the polynomial } \\left(x^{4}+2x^{3}+8x^{2}+12x+18\\right) \\text{ is divided by another polynomial } \\left(x^{2}+5\\right), \\text{ the remainder comes out to be } (px+q). \\text{ Find the values of } p \\text{ and } q. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{EXAMPLE 9 On dividing } \\left(x^{3}-3x^{2}+x+2\\right) \\text{ by a polynomial } g(x), \\text{ the quotient and remainder are } (x-2) \\text{ and } (-2x+4) \\text{ respectively. Find } g(x). \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{EXAMPLE 10 It being given that 1 is a zero of the polynomial } \\left(7x-x^{3}-6\\right), \\text{ find its other zeros.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{EXAMPLE 11 Obtain all zeros of the polynomial } \\left(2x^{3}-4x-x^{2}+2\\right), \\text{ if two of its zeros are } \\sqrt{2} \\text{ and } -\\sqrt{2}. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{EXAMPLE 12 If two zeros of the polynomial } \\left(x^{4}-6x^{3}-26x^{2}+138x-35\\right) \\text{ are } (2+\\sqrt{3}) \\text{ and } (2-\\sqrt{3}), \\text{ find other zeros.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{EXAMPLE 13 Obtain all zeros of } \\left(3x^{4}-15x^{3}+13x^{2}+25x-30\\right), \\text{ if two of its zeros are } \\sqrt{\\frac{5}{3}} \\text{ and } -\\sqrt{\\frac{5}{3}}. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Verify that } 3,-2,1 \\text{ are the zeros of the cubic polynomial } p(x)=x^{3}-2x^{2}-5x+6 \\text{ and verify the relation between its zeros and coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Verify that } 5,-2 \\text{ and } \\frac{1}{3} \\text{ are the zeros of the cubic polynomial } p(x)=3x^{3}-10x^{2}-27x+10 \\text{ and verify the relation between its zeros and coefficients.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find a cubic polynomial whose zeros are } 2, -3 \\text{ and } 4. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find a cubic polynomial whose zeros are } \\frac{1}{2}, 1 \\text{ and } -3. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find a cubic polynomial with the sum, sum of the product of its zeros taken two at a time, and the product of its zeros as } 5,-2 \\text{ and } -24 \\text{ respectively.} \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the quotient and the remainder when } f(x)=x^{3}-3x^{2}+5x-3 \\text{ is divided by } g(x)=x^{2}-2. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the quotient and the remainder when } f(x)=x^{4}-3x^{2}+4x+5 \\text{ is divided by } g(x)=x^{2}+1-x. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Find the quotient and the remainder when } f(x)=x^{4}-5x+6 \\text{ is divided by } g(x)=2-x^{2}. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{By actual division, show that } x^{2}-3 \\text{ is a factor of } 2x^{4}+3x^{3}-2x^{2}-9x-12. \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{On dividing } 3x^{3}+x^{2}+2x+5 \\text{ by a polynomial } g(x), \\text{ the quotient and remainder are } (3x-5) \\text{ and } (9x+10) \\text{ respectively. Find } g(x). \\end{aligned}"
        },
        {
            "question": "\\begin{aligned} \\text{Verify division algorithm for the polynomials } f(x)=8+20x+x^{2}-6x^{3} \\text{ and } g(x)=2+5x-3x^{2}. \\end{aligned}"

In [14]:
print("Chapter name: ",chapter, ",  Raw questions: ",  len(extracted_raw_questions_json))
print("Chapter name: ",chapter, ",  Cleaned questions: ",  len(clean_rephrased_questions_json[chapter]))

Chapter name:  Polynomials ,  Raw questions:  121
Chapter name:  Polynomials ,  Cleaned questions:  121

In [15]:
extracted_raw_questions_json

[{'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad x^{2}+7x+12 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad x^{2}-2x-8 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad x^{2}+3x-10 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 4x^{2}-4x-3 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 5x^{2}-4-8x \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 2\\sqrt{3}x^{2}-5x+\\sqrt{3} \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 2x^{2}-11x+15 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 4x^{2}-4x+1 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad x^{2}-5 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 8x^{2}-4 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 5y^{2}+10y \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the quadratic polynomial} \\quad 3x^{2}-x-4 \\quad \\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the quadratic polynomial whose zeros are 2 and -6. Verify the relation between the coefficients and the zeros of the polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the quadratic polynomial whose zeros are} \\quad \\frac{2}{3} \\quad \\text{and} \\quad \\frac{-1}{4}. \\quad \\text{Verify the relation between the coefficients and the zeros of the polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the quadratic polynomial, sum of whose zeros is 8 and their product is 12. Hence, find the zeros of the polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the quadratic polynomial, the sum of whose zeros is 0 and their product is -1. Hence, find the zeros of the polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the quadratic polynomial, the sum of whose zeros is} \\quad \\left(\\frac{5}{2}\\right) \\quad \\text{and their product is 1. Hence, find the zeros of the polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the quadratic polynomial, the sum of whose roots is} \\quad \\sqrt{2} \\quad \\text{and their product is} \\quad \\frac{1}{3}. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If} \\quad x=\\frac{2}{3} \\quad \\text{and} \\quad x=-3 \\quad \\text{are the roots of the quadratic equation} \\quad ax^{2}+7x+b=0, \\quad \\text{then find the values of} \\quad a \\quad \\text{and} \\quad b. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If} \\quad (x+a) \\quad \\text{is a factor of the polynomial} \\quad 2x^{2}+2ax+5x+10, \\quad \\text{find the value of} \\quad a. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{One zero of the polynomial} \\quad 3x^{3}+16x^{2}+15x-18 \\quad \\text{is} \\quad \\frac{2}{3}. \\quad \\text{Find the other zeros of the polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{EXAMPLE 6 Divide } 5x^{3}-13x^{2}+21x-14 \\text{ by } \\left(3-2x+x^{2}\\right) \\text{ and verify the division algorithm.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{EXAMPLE 7 What real number should be subtracted from the polynomial } \\left(3x^{3}+10x^{2}-14x+9\\right) \\text{ so that } (3x-2) \\text{ divides it exactly?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{EXAMPLE 8 If the polynomial } \\left(x^{4}+2x^{3}+8x^{2}+12x+18\\right) \\text{ is divided by another polynomial } \\left(x^{2}+5\\right), \\text{ the remainder comes out to be } (px+q). \\text{ Find the values of } p \\text{ and } q. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{EXAMPLE 9 On dividing } \\left(x^{3}-3x^{2}+x+2\\right) \\text{ by a polynomial } g(x), \\text{ the quotient and remainder are } (x-2) \\text{ and } (-2x+4) \\text{ respectively. Find } g(x). \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{EXAMPLE 10 It being given that 1 is a zero of the polynomial } \\left(7x-x^{3}-6\\right), \\text{ find its other zeros.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{EXAMPLE 11 Obtain all zeros of the polynomial } \\left(2x^{3}-4x-x^{2}+2\\right), \\text{ if two of its zeros are } \\sqrt{2} \\text{ and } -\\sqrt{2}. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{EXAMPLE 12 If two zeros of the polynomial } \\left(x^{4}-6x^{3}-26x^{2}+138x-35\\right) \\text{ are } (2+\\sqrt{3}) \\text{ and } (2-\\sqrt{3}), \\text{ find other zeros.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{EXAMPLE 13 Obtain all zeros of } \\left(3x^{4}-15x^{3}+13x^{2}+25x-30\\right), \\text{ if two of its zeros are } \\sqrt{\\frac{5}{3}} \\text{ and } -\\sqrt{\\frac{5}{3}}. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Verify that } 3,-2,1 \\text{ are the zeros of the cubic polynomial } p(x)=x^{3}-2x^{2}-5x+6 \\text{ and verify the relation between its zeros and coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Verify that } 5,-2 \\text{ and } \\frac{1}{3} \\text{ are the zeros of the cubic polynomial } p(x)=3x^{3}-10x^{2}-27x+10 \\text{ and verify the relation between its zeros and coefficients.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find a cubic polynomial whose zeros are } 2, -3 \\text{ and } 4. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find a cubic polynomial whose zeros are } \\frac{1}{2}, 1 \\text{ and } -3. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find a cubic polynomial with the sum, sum of the product of its zeros taken two at a time, and the product of its zeros as } 5,-2 \\text{ and } -24 \\text{ respectively.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the quotient and the remainder when } f(x)=x^{3}-3x^{2}+5x-3 \\text{ is divided by } g(x)=x^{2}-2. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the quotient and the remainder when } f(x)=x^{4}-3x^{2}+4x+5 \\text{ is divided by } g(x)=x^{2}+1-x. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the quotient and the remainder when } f(x)=x^{4}-5x+6 \\text{ is divided by } g(x)=2-x^{2}. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{By actual division, show that } x^{2}-3 \\text{ is a factor of } 2x^{4}+3x^{3}-2x^{2}-9x-12. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{On dividing } 3x^{3}+x^{2}+2x+5 \\text{ by a polynomial } g(x), \\text{ the quotient and remainder are } (3x-5) \\text{ and } (9x+10) \\text{ respectively. Find } g(x). \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Verify division algorithm for the polynomials } f(x)=8+20x+x^{2}-6x^{3} \\text{ and } g(x)=2+5x-3x^{2}. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{It is given that -1 is one of the zeros of the polynomial } x^{3}+2x^{2}-11x-12. \\text{ Find all the zeros of the given polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If 1 and -2 are two zeros of the polynomial } \\left(x^{3}-4x^{2}-7x+10\\right), \\text{ find its third zero.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If 3 and -3 are two zeros of the polynomial } \\left(x^{4}+x^{3}-11x^{2}-9x+18\\right), \\text{ find all the zeros of the given polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If 2 and -2 are two zeros of the polynomial } \\left(x^{4}+x^{3}-34x^{2}-4x+120\\right), \\text{ find all the zeros of the given polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find all the zeros of } \\left(x^{4}+x^{3}-23 x^{2}-3 x+60\\right), \\text{ if it is given that two of its zeros are } \\sqrt{3} \\text{ and } -\\sqrt{3}. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find all the zeros of } \\left(2 x^{4}-3 x^{3}-5 x^{2}+9 x-3\\right), \\text{ it being given that two of its zeros are } \\sqrt{3} \\text{ and } -\\sqrt{3}. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Obtain all other zeros of } \\left(x^{4}+4 x^{3}-2 x^{2}-20 x-15\\right) \\text{ if two of its zeros are } \\sqrt{5} \\text{ and } -\\sqrt{5}. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find all the zeros of the polynomial } \\left(2 x^{4}-11 x^{3}+7 x^{2}+13 x-7\\right), \\text{ it being given that two of its zeros are } (3+\\sqrt{2}) \\text{ and } (3-\\sqrt{2}). \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If one zero of the polynomial } x^{2}-4 x+1 \\text{ is } (2+\\sqrt{3}), \\text{ write the other zero.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the polynomial } x^{2}+x-p(p+1). \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the polynomial } x^{2}-3 x-m(m+3). \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } \\alpha, \\beta \\text{ are the zeros of a polynomial such that } \\alpha+\\beta=6 \\text{ and } \\alpha \\beta=4 \\text{ then write the polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If one zero of the quadratic polynomial } k x^{2}+3 x+k \\text{ is 2 then find the value of } k. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If 3 is a zero of the polynomial } 2 x^{2}+x+k, \\text{ find the value of } k. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If -4 is a zero of the polynomial } x^{2}-x-(2 k+2) \\text{ then find the value of } k. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If 1 is a zero of the polynomial } a x^{2}-3(a-1) x-1 \\text{ then find the value of } a. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If -2 is a zero of the polynomial } 3 x^{2}+4 x+2 k \\text{ then find the value of } k. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Write the zeros of the polynomial } x^{2}-x-6. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If the sum of the zeros of the quadratic polynomial } k x^{2}-3 x+5 \\text{ is 1, write the value of } k. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If the product of the zeros of the quadratic polynomial } x^{2}-4 x+k \\text{ is 3 then write the value of } k. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } (x+a) \\text{ is a factor of } \\left(2 x^{2}+2 a x+5 x+10\\right), \\text{ find the value of } a. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } (a-b), a \\text{ and } (a+b) \\text{ are zeros of the polynomial } 2 x^{3}-6 x^{2}+5 x-7, \\text{ write the value of } a. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } x^{3}+x^{2}-a x+b \\text{ is divisible by } \\left(x^{2}-x\\right), \\text{ write the values of } a \\text{ and } b. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } \\alpha \\text{ and } \\beta \\text{ are the zeros of the polynomial } 2 x^{2}+7 x+5, \\text{ write the value of } \\alpha+\\beta+\\alpha \\beta. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{State division algorithm for polynomials.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{The sum of the zeros and the product of zeros of a quadratic polynomial are } \\frac{-1}{2} \\text{ and } -3 \\text{ respectively. Write the polynomial.} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Write the zeros of the quadratic polynomial } f(x)=6 x^{2}-3. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Write the zeros of the quadratic polynomial } f(x)=4 \\sqrt{3} x^{2}+5 x-2 \\sqrt{3}. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } \\alpha \\text{ and } \\beta \\text{ are the zeros of the polynomial } f(x)=x^{2}-5 x+k \\text{ such that } \\alpha-\\beta=1, \\text{ find the value of } k. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } \\alpha \\text{ and } \\beta \\text{ are the zeros of the polynomial } f(x)=6 x^{2}+x-2, \\text{ find the value of } \\left(\\frac{\\alpha}{\\beta}+\\frac{\\beta}{\\alpha}\\right). \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } \\alpha \\text{ and } \\beta \\text{ are the zeros of the polynomial } f(x)=5 x^{2}-7 x+1, \\text{ find the value of } \\left(\\frac{1}{\\alpha}+\\frac{1}{\\beta}\\right). \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } \\alpha \\text{ and } \\beta \\text{ are the zeros of the polynomial } f(x)=x^{2}+x-2, \\text{ find the value of } \\left(\\frac{1}{\\alpha}-\\frac{1}{\\beta}\\right). \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If the zeros of the polynomial } f(x)=x^{3}-3 x^{2}+x+1 \\text{ are } (a-b), a \\text{ and } (a+b), \\text{ find } a \\text{ and } b. \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Which of the following is a polynomial?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Which of the following is not a polynomial?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{The zeros of the polynomial } x^{2}-2 x-3 \\text{ are} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{The zeros of the polynomial } x^{2}-\\sqrt{2} x-12 \\text{ are} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{The zeros of the polynomial } 4 x^{2}+5 \\sqrt{2} x-3 \\text{ are} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{The zeros of the polynomial } x^{2}+\\frac{1}{6} x-2 \\text{ are} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{The zeros of the polynomial } 7 x^{2}-\\frac{11 x}{3}-\\frac{2}{3} \\text{ are} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{The sum and the product of the zeros of a quadratic polynomial are 3 and -10 respectively. The quadratic polynomial is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{A quadratic polynomial whose zeros are 5 and -3, is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{A quadratic polynomial whose zeros are} \\quad \\frac{3}{5} \\quad \\text{and} \\quad \\frac{-1}{2}, \\quad \\text{is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{The zeros of the quadratic polynomial} \\quad x^{2}+88 x+125 \\quad \\text{are} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If} \\quad \\alpha \\quad \\text{and} \\quad \\beta \\quad \\text{are the zeros of} \\quad x^{2}+5 x+8 \\quad \\text{then the value of} \\quad (\\alpha+\\beta) \\quad \\text{is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If} \\quad \\alpha \\quad \\text{and} \\quad \\beta \\quad \\text{are the zeros of} \\quad 2 x^{2}+5 x-9 \\quad \\text{then the value of} \\quad \\alpha \\beta \\quad \\text{is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If one zero of the quadratic polynomial} \\quad k x^{2}+3 x+k \\quad \\text{is 2 then the value of} \\quad k \\quad \\text{is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If one zero of the quadratic polynomial} \\quad (k-1) x^{2}+k x+1 \\quad \\text{is -4 then the value of} \\quad k \\quad \\text{is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If -2 and 3 are the zeros of the quadratic polynomial} \\quad x^{2}+(a+1) x+b \\quad \\text{then} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If one zero of} \\quad 3 x^{2}+8 x+k \\quad \\text{be the reciprocal of the other then} \\quad k= \\quad \\text{?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If the sum of the zeros of the quadratic polynomial} \\quad k x^{2}+2 x+3 k \\quad \\text{is equal to the product of its zeros then} \\quad k= \\quad \\text{?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If} \\quad \\alpha, \\beta \\quad \\text{are the zeros of the polynomial} \\quad x^{2}+6 x+2 \\quad \\text{then} \\quad \\left(\\frac{1}{\\alpha}+\\frac{1}{\\beta}\\right)= \\quad \\text{?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If} \\quad \\alpha, \\beta, \\gamma \\quad \\text{are the zeros of the polynomial} \\quad x^{3}-6 x^{2}-x+30 \\quad \\text{then} \\quad (\\alpha \\beta+\\beta \\gamma+\\gamma \\alpha)= \\quad \\text{?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If} \\quad \\alpha, \\beta, \\gamma \\quad \\text{are the zeros of the polynomial} \\quad 2 x^{3}+x^{2}-13 x+6 \\quad \\text{then} \\quad \\alpha \\beta \\gamma= \\quad \\text{?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If} \\quad \\alpha, \\beta, \\gamma \\quad \\text{be the zeros of the polynomial} \\quad p(x) \\quad \\text{such that} \\quad (\\alpha+\\beta+\\gamma)=3, \\quad (\\alpha \\beta+\\beta \\gamma+\\gamma \\alpha)=-10 \\quad \\text{and} \\quad \\alpha \\beta \\gamma=-24 \\quad \\text{then} \\quad p(x)= \\quad \\text{?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If two of the zeros of the cubic polynomial} \\quad a x^{3}+b x^{2}+c x+d \\quad \\text{are 0 then the third zero is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If one of the zeros of the cubic polynomial} \\quad a x^{3}+b x^{2}+c x+d \\quad \\text{is 0 then the product of the other two zeros is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If one of the zeros of the cubic polynomial} \\quad x^{3}+a x^{2}+b x+c \\quad \\text{is -1 then the product of the other two zeros is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If} \\quad \\alpha, \\beta \\quad \\text{be the zeros of the polynomial} \\quad 2 x^{2}+5 x+k \\quad \\text{such that} \\quad \\alpha^{2}+\\beta^{2}+\\alpha \\beta=\\frac{21}{4} \\quad \\text{then} \\quad k= \\quad \\text{?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{On dividing a polynomial} \\quad p(x) \\quad \\text{by a nonzero polynomial} \\quad q(x), \\quad \\text{let} \\quad g(x) \\quad \\text{be the quotient and} \\quad r(x) \\quad \\text{be the remainder then} \\quad p(x)=q(x) \\cdot g(x)+r(x), \\quad \\text{where} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Which of the following is a true statement?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Zeros of } p(x)=x^{2}-2x-3 \\text{ are} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } \\alpha, \\beta, \\gamma \\text{ are the zeros of the polynomial } x^{3}-6x^{2}-x+30 \\text{ then the value of } (\\alpha \\beta+\\beta \\gamma+\\gamma \\alpha) \\text{ is} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{If } \\alpha, \\beta \\text{ are the zeros of } kx^{2}-2x+3k \\text{ such that } \\alpha+\\beta=\\alpha \\beta \\text{ then } k= \\text{ ?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{It is given that the difference between the zeros of } 4x^{2}-8kx+9 \\text{ is 4 and } k>0. \\text{ Then, } k= \\text{ ?} \\end{aligned}'},
 {'question': '\\begin{aligned} \\text{Find the zeros of the polynomial } x^{2}+2x-195. \\end{aligned}'},

In [16]:
# extracted_raw_questions_json
for json in clean_rephrased_questions_json[conf_data['chapter_name']]:
    print(json['question'])

\begin{aligned} &\text{Determine the roots of the quadratic polynomial} \quad x^{2}+5x+6 \ \quad &\text{and confirm the relationship between the roots and the coefficients.} \end{aligned}
\begin{aligned} &\text{Identify the zeros of the quadratic polynomial} \quad x^{2}-3x-10 \ \quad &\text{and verify the relationship between the zeros and the coefficients.} \end{aligned}
\begin{aligned} &\text{Calculate the zeros of the quadratic polynomial} \quad x^{2}+4x-12 \ \quad &\text{and verify the relationship between the zeros and the coefficients.} \end{aligned}
\begin{aligned} &\text{Find the roots of the quadratic polynomial} \quad 3x^{2}-3x-2 \ \quad &\text{and confirm the relationship between the roots and the coefficients.} \end{aligned}
\begin{aligned} &\text{Determine the zeros of the quadratic polynomial} \quad 6x^{2}-5-9x \ \quad &\text{and verify the relationship between the zeros and the coefficients.} \end{aligned}
\begin{aligned} &\text{What are the zeros of the quadratic polynomial} \quad 3\sqrt{2}x^{2}-7x+\sqrt{2} \quad \text{and how do they relate to the coefficients?} \end{aligned}
\begin{aligned} &\text{Determine the zeros of the quadratic polynomial} \quad 3x^{2}-10x+12 \quad \text{and explain the relationship with the coefficients.} \end{aligned}
\begin{aligned} &\text{Identify the zeros of the quadratic polynomial} \quad 5x^{2}-5x+2 \quad \text{and verify the relationship with the coefficients.} \end{aligned}
\begin{aligned} &\text{What are the zeros of the quadratic polynomial} \quad x^{2}-7 \quad \text{and how do they relate to the coefficients?} \end{aligned}
\begin{aligned} &\text{Determine the zeros of the quadratic polynomial} \quad 9x^{2}-5 \quad \text{and explain the relationship with the coefficients.} \end{aligned}
\begin{aligned} &\text{What are the zeros of the quadratic polynomial} \quad 4y^{2}+8y \quad \text{and how do they relate to the coefficients?} \end{aligned}
\begin{aligned} &\text{Determine the zeros of the quadratic polynomial} \quad 2x^{2}-3x-5 \quad \text{and explain the relationship between the zeros and the coefficients.} \end{aligned}
\begin{aligned} &\text{What is the quadratic polynomial with zeros 3 and -5? Verify the relationship between the coefficients and the zeros.} \end{aligned}
\begin{aligned} &\text{Identify the quadratic polynomial whose zeros are} \quad \frac{1}{2} \quad \text{and} \quad \frac{-3}{5}. \quad \text{Verify the relationship between the coefficients and the zeros.} \end{aligned}
\begin{aligned} &\text{Find the quadratic polynomial where the sum of the zeros is 7 and their product is 10. What are the zeros of this polynomial?} \end{aligned}
\begin{aligned} &\text{Which quadratic polynomial has zeros such that their sum is 0 and their product is } \quad -2 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Which quadratic polynomial has zeros with a sum of } \quad \frac{3}{2} \quad \text{and a product of } \quad 2 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Which quadratic polynomial has roots with a sum of } \quad \sqrt{3} \quad \text{and a product of } \quad \frac{1}{4} \quad \text{?} \end{aligned}
\begin{aligned} &\text{If } \quad x=\frac{3}{4} \quad \text{and} \quad x=-4 \quad \text{are the roots of the quadratic equation} \quad ax^{2}+8x+b=0, \quad \text{what are the values of} \quad a \quad \text{and} \quad b \quad \text{?} \end{aligned}
\begin{aligned} &\text{If } \quad (x+b) \quad \text{is a factor of the polynomial} \quad 3x^{2}+3bx+6x+12, \quad \text{what is the value of} \quad b \quad \text{?} \end{aligned}
\begin{aligned} &\text{Given that one zero of the polynomial} \quad 4x^{3}+12x^{2}+9x-20 \quad \text{is} \quad \frac{3}{4}, \quad \text{what are the other zeros of the polynomial?} \end{aligned}
\begin{aligned} &\text{Divide } 6x^{3}-15x^{2}+25x-18 \text{ by } \left(4-3x+x^{2}\right) \text{ and verify the division algorithm.} \end{aligned}
\begin{aligned} &\text{What real number should be subtracted from the polynomial } \left(4x^{3}+12x^{2}-16x+11\right) \text{ so that } (4x-3) \text{ divides it exactly?} \end{aligned}
\begin{aligned} &\text{If the polynomial } \left(x^{4}+3x^{3}+9x^{2}+14x+20\right) \text{ is divided by another polynomial } \left(x^{2}+6\right), \text{ the remainder is } (px+q). \text{ What are the values of } p \text{ and } q? \end{aligned}
\begin{aligned} &\text{On dividing } \left(x^{3}-4x^{2}+2x+3\right) \text{ by a polynomial } g(x), \text{ the quotient and remainder are } (x-3) \text{ and } (-3x+5) \text{ respectively. What is } g(x)? \end{aligned}
\begin{aligned} &\text{Given that 1 is a zero of the polynomial } \quad 5x - x^{3} - 4, \quad \text{which are the other zeros?} \end{aligned}
\begin{aligned} &\text{Find all zeros of the polynomial } \quad 3x^{3} - 5x - x^{2} + 1, \quad \text{if two of its zeros are } \sqrt{3} \quad \text{and} \quad -\sqrt{3}. \end{aligned}
\begin{aligned} &\text{If two zeros of the polynomial } \quad x^{4} - 5x^{3} - 20x^{2} + 120x - 25 \quad \text{are } (3+\sqrt{2}) \quad \text{and} \quad (3-\sqrt{2}), \quad \text{what are the other zeros?} \end{aligned}
\begin{aligned} &\text{Determine all zeros of } \quad 4x^{4} - 12x^{3} + 11x^{2} + 20x - 25, \quad \text{if two of its zeros are } \sqrt{\frac{7}{4}} \quad \text{and} \quad -\sqrt{\frac{7}{4}}. \end{aligned}
\begin{aligned} &\text{Verify that } 2, -3, 1 \quad \text{are the zeros of the cubic polynomial } \quad p(x) = x^{3} - 3x^{2} - 4x + 6 \quad \text{and confirm the relation between its zeros and coefficients.} \end{aligned}
\begin{aligned} &\text{Which of the following are zeros of the cubic polynomial } \quad p(x)=3x^{3}-10x^{2}-27x+10 \\ &\text{and verify the relationship between its zeros and coefficients?} \end{aligned}
\begin{aligned} &\text{What is the cubic polynomial whose zeros are } \quad 3, -4 \quad \text{and} \quad 5 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Determine the cubic polynomial whose zeros are } \quad \frac{2}{3}, 2 \quad \text{and} \quad -4 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Find the cubic polynomial with the sum, sum of the product of its zeros taken two at a time,} \\ &\text{and the product of its zeros as } \quad 6, -3 \quad \text{and} \quad -30 \quad \text{respectively.} \end{aligned}
\begin{aligned} &\text{What are the quotient and remainder when } \quad f(x)=x^{3}-4x^{2}+6x-4 \\ &\text{is divided by } \quad g(x)=x^{2}-3 \quad \text{?} \end{aligned}
\begin{aligned} &\text{What are the quotient and remainder when } \\ &f(x)=x^{4}-2x^{2}+3x+7 \\ &\text{is divided by } \\ &g(x)=x^{2}+1-x? \\ \end{aligned}
\begin{aligned} &\text{Determine the quotient and remainder when } \\ &f(x)=x^{4}-4x+8 \\ &\text{is divided by } \\ &g(x)=3-x^{2}? \\ \end{aligned}
\begin{aligned} &\text{Using actual division, verify if } \\ &x^{2}-4 \\ &\text{is a factor of } \\ &2x^{4}+3x^{3}-2x^{2}-9x-15? \\ \end{aligned}
\begin{aligned} &\text{If the polynomial } \\ &3x^{3}+x^{2}+2x+7 \\ &\text{is divided by } \\ &g(x) \\ &\text{with quotient } \\ &(3x-4) \\ &\text{and remainder } \\ &(8x+9), \\ &\text{what is } g(x)? \\ \end{aligned}
\begin{aligned} &\text{How can you verify the division algorithm for the polynomials } \\ &f(x)=9+18x+x^{2}-5x^{3} \\ &\text{and } \\ &g(x)=3+4x-2x^{2}? \\ \end{aligned}
\begin{aligned} &\text{Given that -1 is a zero of the polynomial } \quad x^{3} + 2x^{2} - 11x - 12, \\ &\text{which of the following are all the zeros of the polynomial?} \end{aligned}
\begin{aligned} &\text{If 1 and -2 are zeros of the polynomial } \quad x^{3} - 4x^{2} - 7x + 10, \\ &\text{what is the third zero of the polynomial?} \end{aligned}
\begin{aligned} &\text{Given that 3 and -3 are zeros of the polynomial } \quad x^{4} + x^{3} - 11x^{2} - 9x + 18, \\ &\text{which of the following are all the zeros of the polynomial?} \end{aligned}
\begin{aligned} &\text{If 2 and -2 are zeros of the polynomial } \quad x^{4} + x^{3} - 34x^{2} - 4x + 120, \\ &\text{which of the following are all the zeros of the polynomial?} \end{aligned}
\begin{aligned} &\text{Find all the zeros of the polynomial } \quad x^{4} + x^{3} - 23x^{2} - 3x + 60, \\ &\text{given that two of its zeros are } \sqrt{3} \text{ and } -\sqrt{3}. \end{aligned}
\begin{aligned} &\text{Which of the following are the zeros of the polynomial } \quad 3x^{4} - 5x^{3} - 6x^{2} + 8x - 2, \\ &\text{given that two of its zeros are } \sqrt{3} \quad \text{and} \quad -\sqrt{3}? \end{aligned}
\begin{aligned} &\text{Determine the remaining zeros of the polynomial } \quad x^{4} + 3x^{3} - 3x^{2} - 18x - 10, \\ &\text{if two of its zeros are } \sqrt{5} \quad \text{and} \quad -\sqrt{5}? \end{aligned}
\begin{aligned} &\text{Identify all zeros of the polynomial } \quad 3x^{4} - 10x^{3} + 8x^{2} + 12x - 5, \\ &\text{given that two of its zeros are } (4+\sqrt{2}) \quad \text{and} \quad (4-\sqrt{2})? \end{aligned}
\begin{aligned} &\text{If one zero of the polynomial } \quad x^{2} - 5x + 2 \quad \text{is} \quad (3+\sqrt{3}), \\ &\text{what is the other zero?} \end{aligned}
\begin{aligned} &\text{What are the zeros of the polynomial } \quad x^{2} + x - q(q+1)? \end{aligned}
\begin{aligned} &\text{What are the zeros of the polynomial } \quad x^{2} - 5x - n(n + 5) \quad \text{?} \end{aligned}
\begin{aligned} &\text{Given that the sum and product of the zeros of a polynomial are } \quad 8 \quad \text{and} \quad 5, \quad \text{respectively, what is the polynomial?} \end{aligned}
\begin{aligned} &\text{If one zero of the quadratic polynomial } \quad m x^{2} + 4x + m \quad \text{is } \quad 3, \quad \text{what is the value of } \quad m \quad \text{?} \end{aligned}
\begin{aligned} &\text{If 4 is a zero of the polynomial } \quad 3x^{2} + x + p, \quad \text{what is the value of } \quad p \quad \text{?} \end{aligned}
\begin{aligned} &\text{If -5 is a zero of the polynomial } \quad x^{2} - x - (3k + 3), \quad \text{what is the value of } \quad k \quad \text{?} \end{aligned}
\begin{aligned} &\text{If 1 is a root of the polynomial } \quad b x^{2}-3(b-1) x-1, \\ &\text{what is the value of } \quad b \text{?} \end{aligned}
\begin{aligned} &\text{If -2 is a root of the polynomial } \quad 3 x^{2}+5 x+2 m, \\ &\text{what is the value of } \quad m \text{?} \end{aligned}
\begin{aligned} &\text{What are the zeros of the polynomial } \quad x^{2}-x-8 \text{?} \end{aligned}
\begin{aligned} &\text{If the sum of the zeros of the quadratic polynomial } \quad m x^{2}-3 x+5 \\ &\text{is 1, what is the value of } \quad m \text{?} \end{aligned}
\begin{aligned} &\text{If the product of the zeros of the quadratic polynomial } \quad x^{2}-5 x+n \\ &\text{is 4, what is the value of } \quad n \text{?} \end{aligned}
\begin{aligned} &\text{Determine the value of } a \text{ if } (x+a) \text{ is a factor of the polynomial } \ &2x^{2} + 3ax + 6x + 12. \end{aligned}
\begin{aligned} &\text{Given that } (a-b), a, \text{ and } (a+b) \text{ are zeros of the polynomial } \ &3x^{3} - 7x^{2} + 4x - 9, \text{ find the value of } a. \end{aligned}
\begin{aligned} &\text{Find the values of } a \text{ and } b \text{ if } x^{3} + 2x^{2} - ax + b \ &\text{is divisible by } (x^{2} - x). \end{aligned}
\begin{aligned} &\text{If } \alpha \text{ and } \beta \text{ are the zeros of the polynomial } \ &3x^{2} + 8x + 4, \text{ calculate the value of } \alpha + \beta + \alpha \beta. \end{aligned}
\begin{aligned} &\text{What is the division algorithm for polynomials?} \end{aligned}
\begin{aligned} &\text{Which quadratic polynomial has the sum of its zeros as } \quad \frac{3}{2} \quad \text{and the product as } \quad -4 \text{?} \end{aligned}
\begin{aligned} &\text{What are the zeros of the quadratic polynomial } \quad f(x)=5x^{2}-2 \text{?} \end{aligned}
\begin{aligned} &\text{Determine the zeros of the quadratic polynomial } \quad f(x)=3\sqrt{2}x^{2}+4x-3\sqrt{2} \text{?} \end{aligned}
\begin{aligned} &\text{If } \alpha \text{ and } \beta \text{ are the zeros of the polynomial } \quad f(x)=x^{2}-4x+k \text{ such that } \quad \alpha-\beta=2, \text{ what is the value of } k \text{?} \end{aligned}
\begin{aligned} &\text{If } \alpha \text{ and } \beta \text{ are the zeros of the polynomial } \quad f(x)=7x^{2}+x-3, \text{ find the value of } \quad \left(\frac{\alpha}{\beta}+\frac{\beta}{\alpha}\right) \text{?} \end{aligned}
\begin{aligned} &\text{Given that } \alpha \text{ and } \beta \text{ are the zeros of the polynomial } f(x)=3x^{2}-5x+2, \\ &\text{what is the value of } \left(\frac{1}{\alpha}+\frac{1}{\beta}\right)? \end{aligned}
\begin{aligned} &\text{If } \alpha \text{ and } \beta \text{ are the zeros of the polynomial } f(x)=x^{2}-2x+3, \\ &\text{what is the value of } \left(\frac{1}{\alpha}-\frac{1}{\beta}\right)? \end{aligned}
\begin{aligned} &\text{If the zeros of the polynomial } f(x)=x^{3}-4x^{2}+2x+3 \text{ are } (c-d), c, \text{ and } (c+d), \\ &\text{what are the values of } c \text{ and } d? \end{aligned}
\begin{aligned} &\text{Which of the following expressions represents a polynomial?} \end{aligned}
\begin{aligned} &\text{Which of the following expressions does not represent a polynomial?} \end{aligned}
\begin{aligned} &\text{What are the roots of the polynomial } \quad x^{2} - 3x - 4 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Determine the roots of the polynomial } \quad x^{2} - \sqrt{3}x - 10 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Identify the zeros of the polynomial } \quad 3x^{2} + 4\sqrt{2}x - 5 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Find the zeros of the polynomial } \quad x^{2} + \frac{1}{4}x - 3 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Calculate the zeros of the polynomial } \quad 5x^{2} - \frac{9x}{4} - \frac{1}{2} \quad \text{?} \end{aligned}
\begin{aligned} &\text{Which quadratic polynomial has a sum of zeros as 5 and a product of zeros as } \quad -12 \quad \text{?} \end{aligned}
\begin{aligned} &\text{What is the quadratic polynomial whose zeros are 6 and } \quad -4 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Identify the quadratic polynomial with zeros } \quad \frac{4}{7} \quad \text{and} \quad \frac{-2}{3} \quad \text{.} \end{aligned}
\begin{aligned} &\text{What are the zeros of the quadratic polynomial } \quad x^{2}+90x+130 \quad \text{?} \end{aligned}
\begin{aligned} &\text{If } \quad \alpha \quad \text{and} \quad \beta \quad \text{are the zeros of} \quad x^{2}+6x+9 \quad \text{, what is the value of} \quad (\alpha+\beta) \quad \text{?} \end{aligned}
\begin{aligned} &\text{What is the product of the zeros } \quad \alpha \quad \text{and} \quad \beta \quad \text{of the polynomial} \quad 3x^{2} + 7x - 10 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Determine the value of} \quad k \quad \text{if one zero of the polynomial} \quad kx^{2} + 4x + k \quad \text{is 3.} \end{aligned}
\begin{aligned} &\text{Find the value of} \quad k \quad \text{if one zero of the polynomial} \quad (k-2)x^{2} + kx + 1 \quad \text{is -5.} \end{aligned}
\begin{aligned} &\text{Given that -3 and 4 are the zeros of the polynomial} \quad x^{2} + (b+2)x + c, \quad \text{what is the relationship between} \quad b \quad \text{and} \quad c \quad \text{?} \end{aligned}
\begin{aligned} &\text{If one zero of the polynomial} \quad 4x^{2} + 9x + k \quad \text{is the reciprocal of the other, what is the value of} \quad k \quad \text{?} \end{aligned}
\begin{aligned} &\text{Determine the value of } \quad k \quad \text{if the sum of the zeros of the quadratic polynomial} \\ &k x^{2}+3 x+4 k \quad \text{equals the product of its zeros.} \end{aligned}
\begin{aligned} &\text{Given that } \quad \alpha, \beta \quad \text{are the zeros of the polynomial} \quad x^{2}+5 x+3, \\ &\text{find the value of } \quad \left(\frac{1}{\alpha}+\frac{1}{\beta}\right). \end{aligned}
\begin{aligned} &\text{If } \quad \alpha, \beta, \gamma \quad \text{are the zeros of the polynomial} \quad x^{3}-5 x^{2}-2 x+25, \\ &\text{what is the value of } \quad (\alpha \beta+\beta \gamma+\gamma \alpha)? \end{aligned}
\begin{aligned} &\text{For the polynomial } \quad 3 x^{3}+2 x^{2}-12 x+7, \\ &\text{if } \quad \alpha, \beta, \gamma \quad \text{are its zeros, find the value of } \quad \alpha \beta \gamma. \end{aligned}
\begin{aligned} &\text{If } \quad \alpha, \beta, \gamma \quad \text{are the zeros of the polynomial } \quad p(x) \quad \text{such that} \\ &(\alpha+\beta+\gamma)=4, \quad (\alpha \beta+\beta \gamma+\gamma \alpha)=-12, \\ &\text{and } \quad \alpha \beta \gamma=-30, \quad \text{then find } \quad p(x). \end{aligned}
\begin{aligned} &\text{If two of the zeros of the cubic polynomial} \quad 2x^{3}+3x^{2}+5x+7 \quad \text{are 0, what is the third zero?} \end{aligned}
\begin{aligned} &\text{If one of the zeros of the cubic polynomial} \quad 3x^{3}+4x^{2}+6x+8 \quad \text{is 0, what is the product of the other two zeros?} \end{aligned}
\begin{aligned} &\text{If one of the zeros of the cubic polynomial} \quad x^{3}+2x^{2}+3x+4 \quad \text{is -1, what is the product of the other two zeros?} \end{aligned}
\begin{aligned} &\text{If} \quad \alpha, \beta \quad \text{are the zeros of the polynomial} \quad 3x^{2}+4x+k \quad \text{such that} \quad \alpha^{2}+\beta^{2}+\alpha\beta=\frac{25}{4}, \quad \text{what is the value of} \quad k? \end{aligned}
\begin{aligned} &\text{When dividing a polynomial} \quad p(x) \quad \text{by a nonzero polynomial} \quad q(x), \quad \text{let} \quad g(x) \quad \text{be the quotient and} \quad r(x) \quad \text{be the remainder. What is the expression for} \quad p(x)? \end{aligned}
\begin{aligned} &\text{Which of the following statements is correct?} \end{aligned}
\begin{aligned} &\text{Identify the zeros of the polynomial } \quad p(x) = x^2 - 5x - 6. \end{aligned}
\begin{aligned} &\text{For the polynomial } \quad x^3 - 7x^2 - 2x + 35, \quad \text{if } \alpha, \beta, \gamma \text{ are its zeros, what is the value of } (\alpha \beta + \beta \gamma + \gamma \alpha)? \end{aligned}
\begin{aligned} &\text{Given that } \alpha, \beta \text{ are the zeros of } \quad kx^2 - 3x + 4k, \quad \text{and } \alpha + \beta = \alpha \beta, \quad \text{find the value of } k. \end{aligned}
\begin{aligned} &\text{If the difference between the zeros of } \quad 5x^2 - 10kx + 12 \quad \text{is 5 and } k > 0, \quad \text{what is the value of } k? \end{aligned}
\begin{aligned} &\text{Which of the following are the zeros of the polynomial } \quad x^{2}+3x-200 \quad \text{?} \end{aligned}
\begin{aligned} &\text{If one zero of the polynomial } \quad (b^{2}+8)x^{2}+12x+5b \quad \text{is the reciprocal of the other, what is the value of } \quad b \quad \text{?} \end{aligned}
\begin{aligned} &\text{Which quadratic polynomial has zeros at 3 and -6?} \end{aligned}
\begin{aligned} &\text{If the zeros of the polynomial } \quad x^{3}-4x^{2}+2x+2 \quad \text{are } \quad (c-d), c \quad \text{and } \quad (c+d), \quad \text{what are the values of } \quad c \quad \text{and } \quad d \quad \text{?} \end{aligned}
\begin{aligned} &\text{Is 3 a zero of the polynomial } \quad x^{3}+5x^{2}-4x-20 \quad \text{?} \end{aligned}
\begin{aligned} &\text{Which quadratic polynomial has zeros with a sum of } -7 \text{ and a product of } 10 \text{?} \end{aligned}
\begin{aligned} &\text{Which cubic polynomial has zeros at } 4, 6, \text{ and } -3 \text{?} \end{aligned}
\begin{aligned} &\text{Using the remainder theorem, what is the remainder when } p(x)=x^{3}+4x^{2}-6x+5 \text{ is divided by } (x-3)? \end{aligned}
\begin{aligned} &\text{Is } (x+3) \text{ a factor of } f(x)=x^{3}+5x^{2}+2x-7 \text{?} \end{aligned}
\begin{aligned} &\text{If } \alpha, \beta, \gamma \text{ are the zeros of the polynomial } p(x)=5x^{3}+2x^{2}-4x+2, \text{ what is the value of } \left(\frac{1}{\alpha}+\frac{1}{\beta}+\frac{1}{\gamma}\right)? \end{aligned}
\begin{aligned} &\text{Given that } \alpha \text{ and } \beta \text{ are the roots of the polynomial } f(x)=x^{2}-7x+k, \\ &\text{and } \alpha-\beta=2, \text{ what is the value of } k? \end{aligned}

# Solution and Distractors(Based on misconceptions)

In [17]:
llm = ChatOpenAI(model="gpt-4o", temperature=0.2, api_key = OPENAI_API_KEY ,  request_timeout=30.0)

In [18]:
questions_df = pd.DataFrame(clean_rephrased_questions_json[conf_data["chapter_name"]])
questions_df

,topic,topic_id,question
0,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,\begin{aligned} &\text{Determine the roots of ...
1,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,\begin{aligned} &\text{Identify the zeros of t...
2,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,\begin{aligned} &\text{Calculate the zeros of ...
3,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,\begin{aligned} &\text{Find the roots of the q...
4,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,\begin{aligned} &\text{Determine the zeros of ...
...,...,...,...
116,Geometrical Interpretation of the Zeros of Pol...,10_mathematics_polynomials_2,\begin{aligned} &\text{Which of the following ...
117,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,\begin{aligned} &\text{If 3 is one of the zero...
118,Geometrical Interpretation of the Zeros of Pol...,10_mathematics_polynomials_2,\begin{aligned} &\text{Given that } \sqrt{3} \...
119,Geometrical Interpretation of the Zeros of Pol...,10_mathematics_polynomials_2,\begin{aligned} &\text{What is the quotient wh...
120,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,\begin{aligned} &\text{Using the remainder the...

In [19]:
import json
def parse_Response(response):
    if isinstance(response, str):
        # print(response)
        start_index = response.find("{")
        end_index = response.rfind("}")
        if start_index != -1 and end_index != -1:
            valid_json_content = response[start_index : end_index + 1]
            try:
                JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
                # append_list_to_file(JSON_response)
                return JSON_response
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON response: {e.__class__.__name__} - {e}\n\n Still trying to work on particular exceptions ...")
                if str(e).startswith("Extra data"):
                    json_parts = valid_json_content.split('}\n{')
                    if json_parts:
                        first_json = json_parts[0] + '}'
                        return parse_Response(first_json)  
                elif str(e).startswith("Invalid \escape"):
                    print("Before removing \\ issue: ", valid_json_content)
                    str1 = valid_json_content.replace("\\\\\\\\\\", "fvback")
                    str1 = str1.replace("\\\\\\\\", "frback")
                    str1 = str1.replace("\\\\\\", "trlback")
                    str1 = str1.replace("\\\\", "dblback")
                    str1 = str1.replace("\\", "\\\\")
                    str1 = str1.replace("fvback","\\\\\\\\\\")
                    str1 = str1.replace("frback", "\\\\\\\\")
                    str1 = str1.replace("trlback","\\\\\\")
                    strfinal = str1.replace("dblback","\\\\")
                    print("After removing \\ issue: ", strfinal)
                    JSON_response = json.loads(strfinal.replace("\n", ""))
                    return JSON_response
                else:
                    print("Actual Content: ", valid_json_content)
        else:
            print("No valid JSON content found in the response.")
        # time.sleep(50)
    elif isinstance(response, dict):
        return response
    else:
        print("No response message found", type(response))

<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
<>:10: SyntaxWarning: invalid escape sequence '\('
<>:10: SyntaxWarning: invalid escape sequence '\)'
<>:20: SyntaxWarning: invalid escape sequence '\e'
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_12884\3339088456.py:10: SyntaxWarning: invalid escape sequence '\('
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_12884\3339088456.py:10: SyntaxWarning: invalid escape sequence '\)'
  JSON_response = json.loads(valid_json_content.replace("\n", "").replace("\(", "").replace("\)", ""))
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_12884\3339088456.py:20: SyntaxWarning: invalid escape sequence '\e'
  elif str(e).startswith("Invalid \escape"):

In [20]:
## Generating solutions
prompt_template = PromptTemplate(
    input_variables=["system_prompt", "question", "topic", "topic_id", "lulist"],
    template="{system_prompt}\n\n\nGenerate a hint, and solution for the given question. Also rephrase the given question according to the specified steps.\nHere are the required context:\nQuestion: {question}\nLearning unit data which defines scope from which solution should be generated: {lulist}\nTopic: {topic}\nTopic ID: {topic_id}\n\nReturn the output in the specified JSON format."
)

chain = LLMChain(llm=llm, prompt=prompt_template)
# chain = prompt_template | llm
# Function to process each question and generate hint, solution, and final answer
def generate_explanation(subject, question, topic, topic_id):
    try:
        match subject:
            case "mathematics":
                system = MATHEMATICS_SOLUTION_SYSTEM_PROMPT
            case "biology":
                system = BIOLOGY_SOLUTION_SYSTEM_PROMPT
            case "physics":
                system = PHYSICS_SOLUTION_SYSTEM_PROMPT
            case "chemistry":
                system = CHEMISTRY_SOLUTION_SYSTEM_PROMPT

        response = chain.run(
            system_prompt=system,
            lulist=total_LUs,
            question=question,
            topic=topic,
            topic_id=topic_id
        )
        return response
    except Exception as e:
        print(f"Error processing question: {question}\nError: {str(e)}")
        return None
# parser = PydanticOutputParser(pydantic_object=sol_data)
# global explanations
explanations = []
def loopForSolution(subject, questions_df):
    counter = 0
    retries_counter = 0
    maxCounter = len(questions_df)
    while counter < maxCounter:
        row = questions_df.iloc[counter]
        question = row['question']
        topic = row['topic']
        topic_id = row['topic_id']
        print(f"Processing question {counter + 1} out of {len(questions_df)}")
        explanation = generate_explanation(subject, question, topic, topic_id)
        parsed_explanation = parse_Response(explanation)
        if parsed_explanation:
            parsed_explanation["question"] = question
            parsed_explanation["topic"] = topic
            parsed_explanation["topic_id"] = topic_id
            explanations.append(parsed_explanation)
            counter += 1
            retries_counter = 0
        else:
            print("Issue in openai response", explanation, "\n\n Inputs: \n\n", question, "\n\n Topic: ", topic)
            print(f"Failed to parse explanation or generate solution for question {counter + 1}, retrying...")
            retries_counter += 1
        if retries_counter == 3:
            counter += 1

loopForSolution(subject, questions_df)

C:\Users\aniket singh\AppData\Local\Temp\ipykernel_12884\1295566236.py:7: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  chain = LLMChain(llm=llm, prompt=prompt_template)
C:\Users\aniket singh\AppData\Local\Temp\ipykernel_12884\1295566236.py:22: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  response = chain.run(

Processing question 1 out of 121
Processing question 2 out of 121
Processing question 3 out of 121
Processing question 4 out of 121
Processing question 5 out of 121
Processing question 6 out of 121
Processing question 7 out of 121
Processing question 8 out of 121
Processing question 9 out of 121
Processing question 10 out of 121
Processing question 11 out of 121
Processing question 12 out of 121
Processing question 13 out of 121
Processing question 14 out of 121
Processing question 15 out of 121
Processing question 16 out of 121
Processing question 17 out of 121
Processing question 18 out of 121
Processing question 19 out of 121
Processing question 20 out of 121
Processing question 21 out of 121
Processing question 22 out of 121
Processing question 23 out of 121
Processing question 24 out of 121
Processing question 25 out of 121
Processing question 26 out of 121
Processing question 27 out of 121
Processing question 28 out of 121
Processing question 29 out of 121
Processing question 30 out of 121
Processing question 31 out of 121
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 316 (char 315)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Use the factor theorem to find the zeros and verify using the relationship between zeros and coefficients} \\end{aligned}",
    "solution": "\\begin{aligned} &p(x) = 3x^3 - 10x^2 - 27x + 10 \\\\ &\\text{Assume } x = 2 \\\\ &p(2) = 3(2)^3 - 10(2)^2 - 27(2) + 10 \\\\ &\\implies \quad 24 - 40 - 54 + 10 = 0 \\\\ &\\therefore \quad x = 2 \\text{ is a zero of } p(x) \\\\ &\\text{Divide } p(x) \\text{ by } (x - 2) \\text{ to find other zeros} \\\\ &3x^3 - 10x^2 - 27x + 10 = (x - 2)(3x^2 - 4x - 5) \\\\ &\\text{Solve } 3x^2 - 4x - 5 = 0 \\text{ using quadratic formula} \\\\ &x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\quad \\text{where } a = 3, b = -4, c = -5 \\\\ &x = \\frac{4 \\pm \\sqrt{16 + 60}}{6} \\\\ &x = \\frac{4 \\pm \\sqrt{76}}{6} \\\\ &x = \\frac{4 \\pm 2\\sqrt{19}}{6} \\\\ &x = \\frac{2 \\pm \\sqrt{19}}{3} \\\\ &\\therefore \\text{ Zeros are } x = 2, \\frac{2 + \\sqrt{19}}{3}, \\frac{2 - \\sqrt{19}}{3} \\\\ &\\text{Verify: Sum of zeros } = \\frac{10}{3}, \\text{ Product of zeros } = -\\frac{10}{3} \\text{ matches coefficients} \\\\ \\end{aligned}"
}
After removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Use the factor theorem to find the zeros and verify using the relationship between zeros and coefficients} \\end{aligned}",
    "solution": "\\begin{aligned} &p(x) = 3x^3 - 10x^2 - 27x + 10 \\\\ &\\text{Assume } x = 2 \\\\ &p(2) = 3(2)^3 - 10(2)^2 - 27(2) + 10 \\\\ &\\implies \\quad 24 - 40 - 54 + 10 = 0 \\\\ &\\therefore \\quad x = 2 \\text{ is a zero of } p(x) \\\\ &\\text{Divide } p(x) \\text{ by } (x - 2) \\text{ to find other zeros} \\\\ &3x^3 - 10x^2 - 27x + 10 = (x - 2)(3x^2 - 4x - 5) \\\\ &\\text{Solve } 3x^2 - 4x - 5 = 0 \\text{ using quadratic formula} \\\\ &x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\quad \\text{where } a = 3, b = -4, c = -5 \\\\ &x = \\frac{4 \\pm \\sqrt{16 + 60}}{6} \\\\ &x = \\frac{4 \\pm \\sqrt{76}}{6} \\\\ &x = \\frac{4 \\pm 2\\sqrt{19}}{6} \\\\ &x = \\frac{2 \\pm \\sqrt{19}}{3} \\\\ &\\therefore \\text{ Zeros are } x = 2, \\frac{2 + \\sqrt{19}}{3}, \\frac{2 - \\sqrt{19}}{3} \\\\ &\\text{Verify: Sum of zeros } = \\frac{10}{3}, \\text{ Product of zeros } = -\\frac{10}{3} \\text{ matches coefficients} \\\\ \\end{aligned}"
}
Processing question 32 out of 121
Processing question 33 out of 121
Processing question 34 out of 121
Processing question 35 out of 121
Processing question 36 out of 121
Processing question 37 out of 121
Processing question 38 out of 121
Processing question 39 out of 121
Processing question 40 out of 121
Processing question 41 out of 121
Processing question 42 out of 121
Processing question 43 out of 121
Processing question 44 out of 121
Processing question 45 out of 121
Processing question 46 out of 121
Processing question 47 out of 121
Processing question 48 out of 121
Processing question 49 out of 121
Processing question 50 out of 121
Processing question 51 out of 121
Processing question 52 out of 121
Processing question 53 out of 121
Processing question 54 out of 121
Processing question 55 out of 121
Processing question 56 out of 121
Processing question 57 out of 121
Processing question 58 out of 121
Processing question 59 out of 121
Processing question 60 out of 121
Processing question 61 out of 121
Processing question 62 out of 121
Processing question 63 out of 121
Processing question 64 out of 121
Processing question 65 out of 121
Processing question 66 out of 121
Processing question 67 out of 121
Processing question 68 out of 121
Processing question 69 out of 121
Processing question 70 out of 121
Processing question 71 out of 121
Processing question 72 out of 121
Processing question 73 out of 121
Processing question 74 out of 121
Processing question 75 out of 121
Processing question 76 out of 121
Processing question 77 out of 121
Processing question 78 out of 121
Processing question 79 out of 121
Processing question 80 out of 121
Processing question 81 out of 121
Processing question 82 out of 121
Processing question 83 out of 121
Processing question 84 out of 121
Processing question 85 out of 121
Processing question 86 out of 121
Processing question 87 out of 121
Processing question 88 out of 121
Processing question 89 out of 121
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 240 (char 239)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Use the relationships: sum of zeros } (-3 + 4) = -(b+2) \\text{ and product of zeros } (-3)(4) = c \\end{aligned}",
    "solution": "\\begin{aligned} &\\text{Sum of zeros: } -3 + 4 = 1 \\\\ &\\implies \quad 1 = -(b+2) \\\\ &\\therefore \quad b = -3 \\\\ &\\text{Product of zeros: } (-3)(4) = -12 \\\\ &\\therefore \quad c = -12 \\\\ &\\text{Relationship: } b = -3, \, c = -12 \\\\ &\\therefore \quad b + 9 = c \\\\ \\end{aligned}"
}
After removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Use the relationships: sum of zeros } (-3 + 4) = -(b+2) \\text{ and product of zeros } (-3)(4) = c \\end{aligned}",
    "solution": "\\begin{aligned} &\\text{Sum of zeros: } -3 + 4 = 1 \\\\ &\\implies \\quad 1 = -(b+2) \\\\ &\\therefore \\quad b = -3 \\\\ &\\text{Product of zeros: } (-3)(4) = -12 \\\\ &\\therefore \\quad c = -12 \\\\ &\\text{Relationship: } b = -3, \\, c = -12 \\\\ &\\therefore \\quad b + 9 = c \\\\ \\end{aligned}"
}
Processing question 90 out of 121
Processing question 91 out of 121
Processing question 92 out of 121
Processing question 93 out of 121
Processing question 94 out of 121
Processing question 95 out of 121
Processing question 96 out of 121
Processing question 97 out of 121
Processing question 98 out of 121
Processing question 99 out of 121
Processing question 100 out of 121
Processing question 101 out of 121
Processing question 102 out of 121
Processing question 103 out of 121
Processing question 104 out of 121
Processing question 105 out of 121
Processing question 106 out of 121
Processing question 107 out of 121
Processing question 108 out of 121
Processing question 109 out of 121
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 379 (char 378)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Use the relationship between zeros and coefficients of a cubic polynomial} \\\\ &\\text{Sum of zeros: } (c-d) + c + (c+d) = 3c \\\\ &\\text{Product of zeros: } (c-d)c(c+d) = c(c^2-d^2) \\end{aligned}",
    "solution": "\\begin{aligned} &\\text{Given polynomial: } x^3 - 4x^2 + 2x + 2 \\\\ &\\text{Sum of zeros: } (c-d) + c + (c+d) = 3c = 4 \quad \\text{[Coefficient of } x^2 \\text{ term]} \\\\ &\\therefore c = \\frac{4}{3} \\\\ &\\text{Product of zeros: } (c-d)c(c+d) = c(c^2-d^2) = -2 \quad \\text{[Constant term]} \\\\ &\\implies \\frac{4}{3} \\left( \\left(\\frac{4}{3}\\right)^2 - d^2 \\right) = -2 \\\\ &\\implies \\frac{4}{3} \\left( \\frac{16}{9} - d^2 \\right) = -2 \\\\ &\\implies \\frac{64}{27} - \\frac{4}{3}d^2 = -2 \\\\ &\\implies \\frac{4}{3}d^2 = \\frac{64}{27} + 2 \\\\ &\\implies \\frac{4}{3}d^2 = \\frac{118}{27} \\\\ &\\implies d^2 = \\frac{118}{36} \\\\ &\\implies d = \\sqrt{\\frac{59}{18}} \\\\ &\\therefore c = \\frac{4}{3}, \\quad d = \\sqrt{\\frac{59}{18}} \\end{aligned}"
}
After removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Use the relationship between zeros and coefficients of a cubic polynomial} \\\\ &\\text{Sum of zeros: } (c-d) + c + (c+d) = 3c \\\\ &\\text{Product of zeros: } (c-d)c(c+d) = c(c^2-d^2) \\end{aligned}",
    "solution": "\\begin{aligned} &\\text{Given polynomial: } x^3 - 4x^2 + 2x + 2 \\\\ &\\text{Sum of zeros: } (c-d) + c + (c+d) = 3c = 4 \\quad \\text{[Coefficient of } x^2 \\text{ term]} \\\\ &\\therefore c = \\frac{4}{3} \\\\ &\\text{Product of zeros: } (c-d)c(c+d) = c(c^2-d^2) = -2 \\quad \\text{[Constant term]} \\\\ &\\implies \\frac{4}{3} \\left( \\left(\\frac{4}{3}\\right)^2 - d^2 \\right) = -2 \\\\ &\\implies \\frac{4}{3} \\left( \\frac{16}{9} - d^2 \\right) = -2 \\\\ &\\implies \\frac{64}{27} - \\frac{4}{3}d^2 = -2 \\\\ &\\implies \\frac{4}{3}d^2 = \\frac{64}{27} + 2 \\\\ &\\implies \\frac{4}{3}d^2 = \\frac{118}{27} \\\\ &\\implies d^2 = \\frac{118}{36} \\\\ &\\implies d = \\sqrt{\\frac{59}{18}} \\\\ &\\therefore c = \\frac{4}{3}, \\quad d = \\sqrt{\\frac{59}{18}} \\end{aligned}"
}
Processing question 110 out of 121
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 272 (char 271)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Substitute } x = 3 \\text{ into the polynomial and check if the result is zero} \\end{aligned}",
    "solution": "\\begin{aligned} &\\text{Given polynomial: } x^{3} + 5x^{2} - 4x - 20 \\\\ &\\text{Substitute } x = 3: \\\\ &\\implies \quad (3)^{3} + 5(3)^{2} - 4(3) - 20 \\\\ &\\implies \quad 27 + 45 - 12 - 20 \\\\ &\\implies \quad 40 \\\\ &\\therefore \quad \\text{3 is not a zero of the polynomial} \\\\ \\end{aligned}"
}
After removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Substitute } x = 3 \\text{ into the polynomial and check if the result is zero} \\end{aligned}",
    "solution": "\\begin{aligned} &\\text{Given polynomial: } x^{3} + 5x^{2} - 4x - 20 \\\\ &\\text{Substitute } x = 3: \\\\ &\\implies \\quad (3)^{3} + 5(3)^{2} - 4(3) - 20 \\\\ &\\implies \\quad 27 + 45 - 12 - 20 \\\\ &\\implies \\quad 40 \\\\ &\\therefore \\quad \\text{3 is not a zero of the polynomial} \\\\ \\end{aligned}"
}
Processing question 111 out of 121
Processing question 112 out of 121
Processing question 113 out of 121
Processing question 114 out of 121
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 315 (char 314)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Use the Factor Theorem to determine if } (x+3) \\text{ is a factor of } f(x) \\end{aligned}",
    "solution": "\\begin{aligned} &f(x) = x^{3} + 5x^{2} + 2x - 7 \\\\ &\\text{Substitute } x = -3 \\text{ into } f(x) \\\\ &f(-3) = (-3)^{3} + 5(-3)^{2} + 2(-3) - 7 \\\\ &\\implies \quad -27 + 45 - 6 - 7 \\\\ &\\implies \quad 5 \\\\ &\\therefore \\quad (x+3) \\text{ is not a factor of } f(x) \\end{aligned}"
}
After removing \ issue:  {
    "hint": "\\begin{aligned} &\\text{Use the Factor Theorem to determine if } (x+3) \\text{ is a factor of } f(x) \\end{aligned}",
    "solution": "\\begin{aligned} &f(x) = x^{3} + 5x^{2} + 2x - 7 \\\\ &\\text{Substitute } x = -3 \\text{ into } f(x) \\\\ &f(-3) = (-3)^{3} + 5(-3)^{2} + 2(-3) - 7 \\\\ &\\implies \\quad -27 + 45 - 6 - 7 \\\\ &\\implies \\quad 5 \\\\ &\\therefore \\quad (x+3) \\text{ is not a factor of } f(x) \\end{aligned}"
}
Processing question 115 out of 121
Processing question 116 out of 121
Processing question 117 out of 121
Processing question 118 out of 121
Processing question 119 out of 121
Processing question 120 out of 121
Processing question 121 out of 121

In [21]:
explanations

[{'hint': '\\begin{aligned} &\\text{Use the quadratic formula to find the roots and verify } \\alpha + \\beta = -b/a, \\alpha \\beta = c/a \\end{aligned}',
  'solution': '\\begin{aligned} &x^2 + 5x + 6 = 0 \\\\ &\\implies \\quad x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies \\quad x = \\frac{-5 \\pm \\sqrt{5^2 - 4 \\cdot 1 \\cdot 6}}{2 \\cdot 1} \\\\ &\\implies \\quad x = \\frac{-5 \\pm \\sqrt{25 - 24}}{2} \\\\ &\\implies \\quad x = \\frac{-5 \\pm 1}{2} \\\\ &\\implies \\quad x = -3, -2 \\\\ &\\text{Roots are } \\alpha = -3, \\beta = -2 \\\\ &\\text{Verify: } \\alpha + \\beta = -3 + (-2) = -5 = -b/a \\\\ &\\alpha \\beta = (-3)(-2) = 6 = c/a \\\\ &\\therefore \\text{Relationship confirmed} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Determine the roots of the quadratic polynomial} \\quad x^{2}+5x+6 \\ \\quad &\\text{and confirm the relationship between the roots and the coefficients.} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and verify using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given polynomial: } x^2 - 3x - 10 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 1, \\quad b = -3, \\quad c = -10 \\\\ &\\implies x = \\frac{-(-3) \\pm \\sqrt{(-3)^2 - 4 \\cdot 1 \\cdot (-10)}}{2 \\cdot 1} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{9 + 40}}{2} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{49}}{2} \\\\ &\\implies x = \\frac{3 \\pm 7}{2} \\\\ &\\implies x = 5 \\quad \\text{or} \\quad x = -2 \\\\ &\\text{Zeros are } 5 \\text{ and } -2 \\\\ &\\text{Verification:} \\\\ &\\alpha + \\beta = 5 + (-2) = 3 = -\\frac{b}{a} = -\\frac{-3}{1} \\\\ &\\alpha \\beta = 5 \\times (-2) = -10 = \\frac{c}{a} = \\frac{-10}{1} \\\\ &\\therefore \\text{Relationship verified} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Identify the zeros of the quadratic polynomial} \\quad x^{2}-3x-10 \\ \\quad &\\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula to find zeros and verify using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &x^2 + 4x - 12 = 0 \\\\ &\\implies \\quad x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{4^2 - 4 \\cdot 1 \\cdot (-12)}}{2 \\cdot 1} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{16 + 48}}{2} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{64}}{2} \\\\ &\\implies \\quad x = \\frac{-4 \\pm 8}{2} \\\\ &\\implies \\quad x = 2 \\quad \\text{or} \\quad x = -6 \\\\ &\\text{Verification:} \\\\ &\\alpha + \\beta = 2 + (-6) = -4 = -\\frac{b}{a} \\\\ &\\alpha \\beta = 2 \\times (-6) = -12 = \\frac{c}{a} \\\\ &\\therefore \\quad \\text{Zeros are verified} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Calculate the zeros of the quadratic polynomial} \\quad x^{2}+4x-12 \\ \\quad &\\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula to find the roots and verify } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given polynomial: } 3x^2 - 3x - 2 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 3, \\quad b = -3, \\quad c = -2 \\\\ &\\implies x = \\frac{-(-3) \\pm \\sqrt{(-3)^2 - 4 \\cdot 3 \\cdot (-2)}}{2 \\cdot 3} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{9 + 24}}{6} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{33}}{6} \\\\ &\\therefore \\text{Roots are } \\frac{3 + \\sqrt{33}}{6}, \\frac{3 - \\sqrt{33}}{6} \\\\ &\\text{Sum of roots } (\\alpha + \\beta) = \\frac{3 + \\sqrt{33}}{6} + \\frac{3 - \\sqrt{33}}{6} = \\frac{6}{6} = 1 \\\\ &\\text{Product of roots } (\\alpha \\beta) = \\left(\\frac{3 + \\sqrt{33}}{6}\\right) \\cdot \\left(\\frac{3 - \\sqrt{33}}{6}\\right) = \\frac{9 - 33}{36} = -\\frac{2}{3} \\\\ &\\text{Verification: } \\alpha + \\beta = -\\frac{b}{a} = 1, \\quad \\alpha \\beta = \\frac{c}{a} = -\\frac{2}{3} \\\\ &\\text{Relationship confirmed.} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Find the roots of the quadratic polynomial} \\quad 3x^{2}-3x-2 \\ \\quad &\\text{and confirm the relationship between the roots and the coefficients.} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and verify using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given polynomial: } 6x^2 - 9x - 5 \\\\ &\\text{Rearrange: } 6x^2 - 9x - 5 = 0 \\\\ &\\text{Coefficients: } a = 6, b = -9, c = -5 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{-(-9) \\pm \\sqrt{(-9)^2 - 4 \\cdot 6 \\cdot (-5)}}{2 \\cdot 6} \\\\ &\\implies x = \\frac{9 \\pm \\sqrt{81 + 120}}{12} \\\\ &\\implies x = \\frac{9 \\pm \\sqrt{201}}{12} \\\\ &\\therefore \\text{Zeros are } \\frac{9 + \\sqrt{201}}{12}, \\frac{9 - \\sqrt{201}}{12} \\\\ &\\text{Sum of zeros: } \\alpha + \\beta = \\frac{9 + \\sqrt{201}}{12} + \\frac{9 - \\sqrt{201}}{12} = \\frac{18}{12} = \\frac{3}{2} \\\\ &\\text{Product of zeros: } \\alpha \\beta = \\left(\\frac{9 + \\sqrt{201}}{12}\\right) \\left(\\frac{9 - \\sqrt{201}}{12}\\right) = \\frac{81 - 201}{144} = \\frac{-120}{144} = -\\frac{5}{6} \\\\ &\\text{Verification: } \\alpha + \\beta = -\\frac{b}{a} = \\frac{9}{6} = \\frac{3}{2}, \\alpha \\beta = \\frac{c}{a} = -\\frac{5}{6} \\\\ &\\text{Zeros and coefficients relationship verified.} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Determine the zeros of the quadratic polynomial} \\quad 6x^{2}-5-9x \\ \\quad &\\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\text{ to find the zeros} \\\\ &\\text{and relate them to the coefficients using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given quadratic polynomial: } 3\\sqrt{2}x^2 - 7x + \\sqrt{2} \\\\ &a = 3\\sqrt{2}, \\quad b = -7, \\quad c = \\sqrt{2} \\\\ &\\text{Zeros are given by } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{7 \\pm \\sqrt{(-7)^2 - 4 \\cdot 3\\sqrt{2} \\cdot \\sqrt{2}}}{2 \\cdot 3\\sqrt{2}} \\\\ &\\implies x = \\frac{7 \\pm \\sqrt{49 - 24}}{6\\sqrt{2}} \\\\ &\\implies x = \\frac{7 \\pm \\sqrt{25}}{6\\sqrt{2}} \\\\ &\\implies x = \\frac{7 \\pm 5}{6\\sqrt{2}} \\\\ &\\therefore x = \\frac{12}{6\\sqrt{2}}, \\frac{2}{6\\sqrt{2}} \\\\ &\\implies x = \\sqrt{2}, \\frac{1}{3\\sqrt{2}} \\\\ &\\text{Sum of zeros } (\\alpha + \\beta) = \\sqrt{2} + \\frac{1}{3\\sqrt{2}} = -\\frac{b}{a} = \\frac{7}{3\\sqrt{2}} \\\\ &\\text{Product of zeros } (\\alpha \\beta) = \\sqrt{2} \\cdot \\frac{1}{3\\sqrt{2}} = \\frac{c}{a} = \\frac{1}{3\\sqrt{2}} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{What are the zeros of the quadratic polynomial} \\quad 3\\sqrt{2}x^{2}-7x+\\sqrt{2} \\quad \\text{and how do they relate to the coefficients?} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and relate them to the coefficients using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha\\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given polynomial: } 3x^2 - 10x + 12 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 3, \\quad b = -10, \\quad c = 12 \\\\ &\\implies x = \\frac{-(-10) \\pm \\sqrt{(-10)^2 - 4 \\cdot 3 \\cdot 12}}{2 \\cdot 3} \\\\ &\\implies x = \\frac{10 \\pm \\sqrt{100 - 144}}{6} \\\\ &\\implies x = \\frac{10 \\pm \\sqrt{-44}}{6} \\\\ &\\text{No real zeros since the discriminant is negative} \\\\ &\\text{Relationship: } \\alpha + \\beta = -\\frac{-10}{3} = \\frac{10}{3}, \\quad \\alpha\\beta = \\frac{12}{3} = 4 \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Determine the zeros of the quadratic polynomial} \\quad 3x^{2}-10x+12 \\quad \\text{and explain the relationship with the coefficients.} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and verify using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given polynomial: } 5x^2 - 5x + 2 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 5, \\quad b = -5, \\quad c = 2 \\\\ &\\implies x = \\frac{-(-5) \\pm \\sqrt{(-5)^2 - 4 \\cdot 5 \\cdot 2}}{2 \\cdot 5} \\\\ &\\implies x = \\frac{5 \\pm \\sqrt{25 - 40}}{10} \\\\ &\\implies x = \\frac{5 \\pm \\sqrt{-15}}{10} \\\\ &\\text{Zeros are complex: } \\frac{5 \\pm i\\sqrt{15}}{10} \\\\ &\\text{Sum of zeros } (\\alpha + \\beta) = \\frac{5}{10} = \\frac{1}{2} \\\\ &\\text{Product of zeros } (\\alpha \\beta) = \\frac{5}{10} = \\frac{1}{2} \\\\ &\\therefore \\text{Sum and product verify } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Identify the zeros of the quadratic polynomial} \\quad 5x^{2}-5x+2 \\quad \\text{and verify the relationship with the coefficients.} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the formula for finding zeros of a quadratic polynomial and relate them to coefficients} \\end{aligned}',
  'solution': '\\begin{aligned} &x^2 - 7 = 0 \\\\ &\\implies x^2 = 7 \\\\ &\\implies x = \\pm \\sqrt{7} \\\\ &\\therefore \\text{Zeros are } \\sqrt{7} \\text{ and } -\\sqrt{7} \\\\ &\\text{For } ax^2 + bx + c, \\text{ sum of zeros } = -\\frac{b}{a}, \\text{ product of zeros } = \\frac{c}{a} \\\\ &\\text{Here, } a = 1, b = 0, c = -7 \\\\ &\\text{Sum of zeros } = -\\frac{0}{1} = 0 \\\\ &\\text{Product of zeros } = \\frac{-7}{1} = -7 \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{What are the zeros of the quadratic polynomial} \\quad x^{2}-7 \\quad \\text{and how do they relate to the coefficients?} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and relate them to the coefficients.} \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given polynomial: } 9x^2 - 5 \\\\ &\\text{Coefficients: } a = 9, \\ b = 0, \\ c = -5 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{-0 \\pm \\sqrt{0^2 - 4 \\cdot 9 \\cdot (-5)}}{2 \\cdot 9} \\\\ &\\implies x = \\frac{\\pm \\sqrt{180}}{18} \\\\ &\\implies x = \\frac{\\pm 6\\sqrt{5}}{18} \\\\ &\\implies x = \\pm \\frac{\\sqrt{5}}{3} \\\\ &\\text{Zeros are } \\frac{\\sqrt{5}}{3}, \\ -\\frac{\\sqrt{5}}{3} \\\\ &\\text{Sum of zeros: } \\frac{\\sqrt{5}}{3} + \\left(-\\frac{\\sqrt{5}}{3}\\right) = 0 = -\\frac{b}{a} \\\\ &\\text{Product of zeros: } \\left(\\frac{\\sqrt{5}}{3}\\right) \\left(-\\frac{\\sqrt{5}}{3}\\right) = -\\frac{5}{9} = \\frac{c}{a} \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Determine the zeros of the quadratic polynomial} \\quad 9x^{2}-5 \\quad \\text{and explain the relationship with the coefficients.} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula and relate zeros to coefficients using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given polynomial: } 4y^2 + 8y \\\\ &\\implies \\quad 4y^2 + 8y + 0 \\\\ &\\text{Coefficients: } a = 4, \\ b = 8, \\ c = 0 \\\\ &\\text{Quadratic formula: } y = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies \\quad y = \\frac{-8 \\pm \\sqrt{8^2 - 4 \\cdot 4 \\cdot 0}}{2 \\cdot 4} \\\\ &\\implies \\quad y = \\frac{-8 \\pm \\sqrt{64}}{8} \\\\ &\\implies \\quad y = \\frac{-8 \\pm 8}{8} \\\\ &\\implies \\quad y = 0 \\quad \\text{or} \\quad y = -2 \\\\ &\\text{Sum of zeros: } \\alpha + \\beta = 0 + (-2) = -2 \\\\ &\\text{Product of zeros: } \\alpha \\beta = 0 \\cdot (-2) = 0 \\\\ &\\therefore \\quad \\text{Zeros are } 0 \\text{ and } -2 \\end{aligned}',
  'question': '\\begin{aligned} &\\text{What are the zeros of the quadratic polynomial} \\quad 4y^{2}+8y \\quad \\text{and how do they relate to the coefficients?} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and apply the relationship } \\\\ &\\text{between zeros and coefficients: } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given polynomial: } 2x^2 - 3x - 5 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{-(-3) \\pm \\sqrt{(-3)^2 - 4 \\cdot 2 \\cdot (-5)}}{2 \\cdot 2} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{9 + 40}}{4} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{49}}{4} \\\\ &\\implies x = \\frac{3 \\pm 7}{4} \\\\ &\\therefore x = \\frac{10}{4} \\text{ or } x = \\frac{-4}{4} \\\\ &\\therefore x = 2.5 \\text{ or } x = -1 \\\\ &\\text{Sum of zeros: } \\alpha + \\beta = 2.5 + (-1) = 1.5 \\\\ &\\text{Product of zeros: } \\alpha \\beta = 2.5 \\times (-1) = -2.5 \\\\ &\\text{Relationship: } \\alpha + \\beta = -\\frac{-3}{2} = 1.5, \\alpha \\beta = \\frac{-5}{2} = -2.5 \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Determine the zeros of the quadratic polynomial} \\quad 2x^{2}-3x-5 \\quad \\text{and explain the relationship between the zeros and the coefficients.} \\end{aligned}',
  'topic': 'Relationship between zeros and coefficients of a polynomial',
  'topic_id': '10_mathematics_polynomials_3'},
 {'hint': '\\begin{aligned} &\\text{Use the formula for a quadratic polynomial } ax^2 + bx + c \\text{ with zeros } \\alpha \\text{ and } \\beta \\text{ as } x^2 - (\\alpha + \\beta)x + \\alpha\\beta \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Zeros are } 3 \\text{ and } -5 \\\\ &\\implies \\quad \\text{Sum of zeros } (\\alpha + \\beta) = 3 + (-5) = -2 \\\\ &\\implies \\quad \\text{Product of zeros } (\\alpha\\beta) = 3 \\times (-5) = -15 \\\\ &\\implies \\quad \\text{Quadratic polynomial is } x^2 - (\\alpha + \\beta)x + \\alpha\\beta \\\\ &\\implies \\quad x^2 + 2x - 15 \\\\ &\\text{Verification:} \\\\ &\\text{Coefficient of } x^2 = 1, \\text{ coefficient of } x = 2, \\text{ constant term } = -15 \\\\ &\\text{Sum of zeros } = -\\frac{\\text{coefficient of } x}{\\text{coefficient of } x^2} = -\\frac{2}{1} = -2 \\\\ &\\text{Product of zeros } = \\frac{\\text{constant term}}{\\text{coefficient of } x^2} = \\frac{-15}{1} = -15 \\\\ &\\therefore \\quad \\text{Relationship verified} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{What is the quadratic polynomial with zeros 3 and -5? Verify the relationship between the coefficients and the zeros.} \\end{aligned}',
  'topic': 'Formation of polynomial from given sum and product of zeroes',
  'topic_id': '10_mathematics_polynomials_4'},
 {'hint': '\\begin{aligned} &\\text{Use the relationship between zeros and coefficients: } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given zeros: } \\alpha = \\frac{1}{2}, \\beta = \\frac{-3}{5} \\\\ &\\implies \\alpha + \\beta = \\frac{1}{2} + \\frac{-3}{5} = \\frac{5 - 6}{10} = \\frac{-1}{10} \\\\ &\\implies \\alpha \\beta = \\frac{1}{2} \\times \\frac{-3}{5} = \\frac{-3}{10} \\\\ &\\text{Quadratic polynomial: } x^2 - (\\alpha + \\beta)x + \\alpha \\beta \\\\ &\\implies x^2 + \\frac{1}{10}x - \\frac{3}{10} \\\\ &\\therefore \\text{Quadratic polynomial: } 10x^2 + x - 3 \\\\ &\\text{Verification: } \\text{Sum of zeros: } \\frac{-b}{a} = \\frac{-1}{10} \\\\ &\\text{Product of zeros: } \\frac{c}{a} = \\frac{-3}{10} \\\\ &\\text{Both match the given zeros.} \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Identify the quadratic polynomial whose zeros are} \\quad \\frac{1}{2} \\quad \\text{and} \\quad \\frac{-3}{5}. \\quad \\text{Verify the relationship between the coefficients and the zeros.} \\end{aligned}',
  'topic': 'Formation of polynomial from given sum and product of zeroes',
  'topic_id': '10_mathematics_polynomials_4'},
 {'hint': '\\begin{aligned} &\\text{Use the formula for a quadratic polynomial: } x^2 - (\\text{sum of zeros})x + (\\text{product of zeros}) \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given: Sum of zeros } = 7, \\text{ Product of zeros } = 10 \\\\ &\\implies \\text{Quadratic polynomial: } x^2 - 7x + 10 \\\\ &\\text{To find zeros, solve: } x^2 - 7x + 10 = 0 \\\\ &\\implies (x - 5)(x - 2) = 0 \\\\ &\\therefore x = 5, 2 \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Find the quadratic polynomial where the sum of the zeros is 7 and their product is 10. What are the zeros of this polynomial?} \\end{aligned}',
  'topic': 'Formation of polynomial from given sum and product of zeroes',
  'topic_id': '10_mathematics_polynomials_4'},
 {'hint': '\\begin{aligned} &\\text{Use the relationship between zeros and coefficients of a quadratic polynomial:} \\\\ &\\text{If } \\alpha + \\beta = 0 \\text{ and } \\alpha \\beta = -2, \\text{ then the polynomial is } x^2 - (\\alpha + \\beta)x + \\alpha \\beta \\end{aligned}',
  'solution': '\\begin{aligned} &\\alpha + \\beta = 0, \\quad \\alpha \\beta = -2 \\\\ &\\implies \\quad x^2 - (\\alpha + \\beta)x + \\alpha \\beta \\\\ &\\implies \\quad x^2 - 0x - 2 \\\\ &\\therefore \\quad x^2 - 2 \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Which quadratic polynomial has zeros such that their sum is 0 and their product is } \\quad -2 \\quad \\text{?} \\end{aligned}',
  'topic': 'Formation of polynomial from given sum and product of zeroes',
  'topic_id': '10_mathematics_polynomials_4'},
 {'hint': '\\begin{aligned} &\\text{Use the formula for a quadratic polynomial: } x^2 - (\\text{sum of zeros})x + (\\text{product of zeros}) \\end{aligned}',
  'solution': '\\begin{aligned} &\\text{Given sum of zeros } = \\frac{3}{2}, \\text{ product of zeros } = 2 \\\\ &\\implies \\quad x^2 - \\left(\\frac{3}{2}\\right)x + 2 \\\\ &\\therefore \\quad 2x^2 - 3x + 4 \\\\ \\end{aligned}',
  'question': '\\begin{aligned} &\\text{Which quadratic polynomial has zeros with a sum of } \\quad \\frac{3}{2} \\quad \\text{and a product of } \\quad 2 \\quad \\text{?} \\end{aligned}',
  'topic': 'Formation of polynomial from given sum and product of zeroes',
  'topic_id': '10_mathematics_polynomials_4'},

### Generating Distractors

In [22]:
data = pd.DataFrame(explanations)

In [23]:
data['misconception_options'] = ''
data

,hint,solution,question,topic,topic_id,misconception_options
0,\begin{aligned} &\text{Use the quadratic formu...,\begin{aligned} &x^2 + 5x + 6 = 0 \\ &\implies...,\begin{aligned} &\text{Determine the roots of ...,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,
1,\begin{aligned} &\text{Use the quadratic formu...,\begin{aligned} &\text{Given polynomial: } x^2...,\begin{aligned} &\text{Identify the zeros of t...,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,
2,\begin{aligned} &\text{Use the quadratic formu...,\begin{aligned} &x^2 + 4x - 12 = 0 \\ &\implie...,\begin{aligned} &\text{Calculate the zeros of ...,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,
3,\begin{aligned} &\text{Use the quadratic formu...,\begin{aligned} &\text{Given polynomial: } 3x^...,\begin{aligned} &\text{Find the roots of the q...,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,
4,\begin{aligned} &\text{Use the quadratic formu...,\begin{aligned} &\text{Given polynomial: } 6x^...,\begin{aligned} &\text{Determine the zeros of ...,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,
...,...,...,...,...,...,...
116,\begin{aligned} &\text{Analyze the discriminan...,\begin{aligned} &f(x) = x^4 + 5x^2 + 7 \\ &\te...,\begin{aligned} &\text{Which of the following ...,Geometrical Interpretation of the Zeros of Pol...,10_mathematics_polynomials_2,
117,\begin{aligned} &\text{Use the factor theorem ...,\begin{aligned} &p(x) = x^3 - 7x^2 + 13x - 6 \...,\begin{aligned} &\text{If 3 is one of the zero...,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,
118,\begin{aligned} &\text{Use the fact that the s...,\begin{aligned} &\text{Given zeros: } \sqrt{3}...,\begin{aligned} &\text{Given that } \sqrt{3} \...,Geometrical Interpretation of the Zeros of Pol...,10_mathematics_polynomials_2,
119,\begin{aligned} &\text{Use polynomial long div...,\begin{aligned} &\text{Divide } 4x^4 + 6x^3 - ...,\begin{aligned} &\text{What is the quotient wh...,Geometrical Interpretation of the Zeros of Pol...,10_mathematics_polynomials_2,
120,\begin{aligned} &\text{Use the Remainder Theor...,\begin{aligned} &f(x) = x^3 + 2x^2 + kx + 3 \\...,\begin{aligned} &\text{Using the remainder the...,Relationship between zeros and coefficients of...,10_mathematics_polynomials_3,

In [24]:
for i in range(len(data)):
    print(data['solution'][i].split("\n"))

['\\begin{aligned} &x^2 + 5x + 6 = 0 \\\\ &\\implies \\quad x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies \\quad x = \\frac{-5 \\pm \\sqrt{5^2 - 4 \\cdot 1 \\cdot 6}}{2 \\cdot 1} \\\\ &\\implies \\quad x = \\frac{-5 \\pm \\sqrt{25 - 24}}{2} \\\\ &\\implies \\quad x = \\frac{-5 \\pm 1}{2} \\\\ &\\implies \\quad x = -3, -2 \\\\ &\\text{Roots are } \\alpha = -3, \\beta = -2 \\\\ &\\text{Verify: } \\alpha + \\beta = -3 + (-2) = -5 = -b/a \\\\ &\\alpha \\beta = (-3)(-2) = 6 = c/a \\\\ &\\therefore \\text{Relationship confirmed} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } x^2 - 3x - 10 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 1, \\quad b = -3, \\quad c = -10 \\\\ &\\implies x = \\frac{-(-3) \\pm \\sqrt{(-3)^2 - 4 \\cdot 1 \\cdot (-10)}}{2 \\cdot 1} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{9 + 40}}{2} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{49}}{2} \\\\ &\\implies x = \\frac{3 \\pm 7}{2} \\\\ &\\implies x = 5 \\quad \\text{or} \\quad x = -2 \\\\ &\\text{Zeros are } 5 \\text{ and } -2 \\\\ &\\text{Verification:} \\\\ &\\alpha + \\beta = 5 + (-2) = 3 = -\\frac{b}{a} = -\\frac{-3}{1} \\\\ &\\alpha \\beta = 5 \\times (-2) = -10 = \\frac{c}{a} = \\frac{-10}{1} \\\\ &\\therefore \\text{Relationship verified} \\\\ \\end{aligned}']
['\\begin{aligned} &x^2 + 4x - 12 = 0 \\\\ &\\implies \\quad x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{4^2 - 4 \\cdot 1 \\cdot (-12)}}{2 \\cdot 1} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{16 + 48}}{2} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{64}}{2} \\\\ &\\implies \\quad x = \\frac{-4 \\pm 8}{2} \\\\ &\\implies \\quad x = 2 \\quad \\text{or} \\quad x = -6 \\\\ &\\text{Verification:} \\\\ &\\alpha + \\beta = 2 + (-6) = -4 = -\\frac{b}{a} \\\\ &\\alpha \\beta = 2 \\times (-6) = -12 = \\frac{c}{a} \\\\ &\\therefore \\quad \\text{Zeros are verified} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } 3x^2 - 3x - 2 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 3, \\quad b = -3, \\quad c = -2 \\\\ &\\implies x = \\frac{-(-3) \\pm \\sqrt{(-3)^2 - 4 \\cdot 3 \\cdot (-2)}}{2 \\cdot 3} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{9 + 24}}{6} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{33}}{6} \\\\ &\\therefore \\text{Roots are } \\frac{3 + \\sqrt{33}}{6}, \\frac{3 - \\sqrt{33}}{6} \\\\ &\\text{Sum of roots } (\\alpha + \\beta) = \\frac{3 + \\sqrt{33}}{6} + \\frac{3 - \\sqrt{33}}{6} = \\frac{6}{6} = 1 \\\\ &\\text{Product of roots } (\\alpha \\beta) = \\left(\\frac{3 + \\sqrt{33}}{6}\\right) \\cdot \\left(\\frac{3 - \\sqrt{33}}{6}\\right) = \\frac{9 - 33}{36} = -\\frac{2}{3} \\\\ &\\text{Verification: } \\alpha + \\beta = -\\frac{b}{a} = 1, \\quad \\alpha \\beta = \\frac{c}{a} = -\\frac{2}{3} \\\\ &\\text{Relationship confirmed.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } 6x^2 - 9x - 5 \\\\ &\\text{Rearrange: } 6x^2 - 9x - 5 = 0 \\\\ &\\text{Coefficients: } a = 6, b = -9, c = -5 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{-(-9) \\pm \\sqrt{(-9)^2 - 4 \\cdot 6 \\cdot (-5)}}{2 \\cdot 6} \\\\ &\\implies x = \\frac{9 \\pm \\sqrt{81 + 120}}{12} \\\\ &\\implies x = \\frac{9 \\pm \\sqrt{201}}{12} \\\\ &\\therefore \\text{Zeros are } \\frac{9 + \\sqrt{201}}{12}, \\frac{9 - \\sqrt{201}}{12} \\\\ &\\text{Sum of zeros: } \\alpha + \\beta = \\frac{9 + \\sqrt{201}}{12} + \\frac{9 - \\sqrt{201}}{12} = \\frac{18}{12} = \\frac{3}{2} \\\\ &\\text{Product of zeros: } \\alpha \\beta = \\left(\\frac{9 + \\sqrt{201}}{12}\\right) \\left(\\frac{9 - \\sqrt{201}}{12}\\right) = \\frac{81 - 201}{144} = \\frac{-120}{144} = -\\frac{5}{6} \\\\ &\\text{Verification: } \\alpha + \\beta = -\\frac{b}{a} = \\frac{9}{6} = \\frac{3}{2}, \\alpha \\beta = \\frac{c}{a} = -\\frac{5}{6} \\\\ &\\text{Zeros and coefficients relationship verified.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given quadratic polynomial: } 3\\sqrt{2}x^2 - 7x + \\sqrt{2} \\\\ &a = 3\\sqrt{2}, \\quad b = -7, \\quad c = \\sqrt{2} \\\\ &\\text{Zeros are given by } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{7 \\pm \\sqrt{(-7)^2 - 4 \\cdot 3\\sqrt{2} \\cdot \\sqrt{2}}}{2 \\cdot 3\\sqrt{2}} \\\\ &\\implies x = \\frac{7 \\pm \\sqrt{49 - 24}}{6\\sqrt{2}} \\\\ &\\implies x = \\frac{7 \\pm \\sqrt{25}}{6\\sqrt{2}} \\\\ &\\implies x = \\frac{7 \\pm 5}{6\\sqrt{2}} \\\\ &\\therefore x = \\frac{12}{6\\sqrt{2}}, \\frac{2}{6\\sqrt{2}} \\\\ &\\implies x = \\sqrt{2}, \\frac{1}{3\\sqrt{2}} \\\\ &\\text{Sum of zeros } (\\alpha + \\beta) = \\sqrt{2} + \\frac{1}{3\\sqrt{2}} = -\\frac{b}{a} = \\frac{7}{3\\sqrt{2}} \\\\ &\\text{Product of zeros } (\\alpha \\beta) = \\sqrt{2} \\cdot \\frac{1}{3\\sqrt{2}} = \\frac{c}{a} = \\frac{1}{3\\sqrt{2}} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } 3x^2 - 10x + 12 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 3, \\quad b = -10, \\quad c = 12 \\\\ &\\implies x = \\frac{-(-10) \\pm \\sqrt{(-10)^2 - 4 \\cdot 3 \\cdot 12}}{2 \\cdot 3} \\\\ &\\implies x = \\frac{10 \\pm \\sqrt{100 - 144}}{6} \\\\ &\\implies x = \\frac{10 \\pm \\sqrt{-44}}{6} \\\\ &\\text{No real zeros since the discriminant is negative} \\\\ &\\text{Relationship: } \\alpha + \\beta = -\\frac{-10}{3} = \\frac{10}{3}, \\quad \\alpha\\beta = \\frac{12}{3} = 4 \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } 5x^2 - 5x + 2 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 5, \\quad b = -5, \\quad c = 2 \\\\ &\\implies x = \\frac{-(-5) \\pm \\sqrt{(-5)^2 - 4 \\cdot 5 \\cdot 2}}{2 \\cdot 5} \\\\ &\\implies x = \\frac{5 \\pm \\sqrt{25 - 40}}{10} \\\\ &\\implies x = \\frac{5 \\pm \\sqrt{-15}}{10} \\\\ &\\text{Zeros are complex: } \\frac{5 \\pm i\\sqrt{15}}{10} \\\\ &\\text{Sum of zeros } (\\alpha + \\beta) = \\frac{5}{10} = \\frac{1}{2} \\\\ &\\text{Product of zeros } (\\alpha \\beta) = \\frac{5}{10} = \\frac{1}{2} \\\\ &\\therefore \\text{Sum and product verify } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}']
['\\begin{aligned} &x^2 - 7 = 0 \\\\ &\\implies x^2 = 7 \\\\ &\\implies x = \\pm \\sqrt{7} \\\\ &\\therefore \\text{Zeros are } \\sqrt{7} \\text{ and } -\\sqrt{7} \\\\ &\\text{For } ax^2 + bx + c, \\text{ sum of zeros } = -\\frac{b}{a}, \\text{ product of zeros } = \\frac{c}{a} \\\\ &\\text{Here, } a = 1, b = 0, c = -7 \\\\ &\\text{Sum of zeros } = -\\frac{0}{1} = 0 \\\\ &\\text{Product of zeros } = \\frac{-7}{1} = -7 \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } 9x^2 - 5 \\\\ &\\text{Coefficients: } a = 9, \\ b = 0, \\ c = -5 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{-0 \\pm \\sqrt{0^2 - 4 \\cdot 9 \\cdot (-5)}}{2 \\cdot 9} \\\\ &\\implies x = \\frac{\\pm \\sqrt{180}}{18} \\\\ &\\implies x = \\frac{\\pm 6\\sqrt{5}}{18} \\\\ &\\implies x = \\pm \\frac{\\sqrt{5}}{3} \\\\ &\\text{Zeros are } \\frac{\\sqrt{5}}{3}, \\ -\\frac{\\sqrt{5}}{3} \\\\ &\\text{Sum of zeros: } \\frac{\\sqrt{5}}{3} + \\left(-\\frac{\\sqrt{5}}{3}\\right) = 0 = -\\frac{b}{a} \\\\ &\\text{Product of zeros: } \\left(\\frac{\\sqrt{5}}{3}\\right) \\left(-\\frac{\\sqrt{5}}{3}\\right) = -\\frac{5}{9} = \\frac{c}{a} \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } 4y^2 + 8y \\\\ &\\implies \\quad 4y^2 + 8y + 0 \\\\ &\\text{Coefficients: } a = 4, \\ b = 8, \\ c = 0 \\\\ &\\text{Quadratic formula: } y = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies \\quad y = \\frac{-8 \\pm \\sqrt{8^2 - 4 \\cdot 4 \\cdot 0}}{2 \\cdot 4} \\\\ &\\implies \\quad y = \\frac{-8 \\pm \\sqrt{64}}{8} \\\\ &\\implies \\quad y = \\frac{-8 \\pm 8}{8} \\\\ &\\implies \\quad y = 0 \\quad \\text{or} \\quad y = -2 \\\\ &\\text{Sum of zeros: } \\alpha + \\beta = 0 + (-2) = -2 \\\\ &\\text{Product of zeros: } \\alpha \\beta = 0 \\cdot (-2) = 0 \\\\ &\\therefore \\quad \\text{Zeros are } 0 \\text{ and } -2 \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } 2x^2 - 3x - 5 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{-(-3) \\pm \\sqrt{(-3)^2 - 4 \\cdot 2 \\cdot (-5)}}{2 \\cdot 2} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{9 + 40}}{4} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{49}}{4} \\\\ &\\implies x = \\frac{3 \\pm 7}{4} \\\\ &\\therefore x = \\frac{10}{4} \\text{ or } x = \\frac{-4}{4} \\\\ &\\therefore x = 2.5 \\text{ or } x = -1 \\\\ &\\text{Sum of zeros: } \\alpha + \\beta = 2.5 + (-1) = 1.5 \\\\ &\\text{Product of zeros: } \\alpha \\beta = 2.5 \\times (-1) = -2.5 \\\\ &\\text{Relationship: } \\alpha + \\beta = -\\frac{-3}{2} = 1.5, \\alpha \\beta = \\frac{-5}{2} = -2.5 \\end{aligned}']
['\\begin{aligned} &\\text{Zeros are } 3 \\text{ and } -5 \\\\ &\\implies \\quad \\text{Sum of zeros } (\\alpha + \\beta) = 3 + (-5) = -2 \\\\ &\\implies \\quad \\text{Product of zeros } (\\alpha\\beta) = 3 \\times (-5) = -15 \\\\ &\\implies \\quad \\text{Quadratic polynomial is } x^2 - (\\alpha + \\beta)x + \\alpha\\beta \\\\ &\\implies \\quad x^2 + 2x - 15 \\\\ &\\text{Verification:} \\\\ &\\text{Coefficient of } x^2 = 1, \\text{ coefficient of } x = 2, \\text{ constant term } = -15 \\\\ &\\text{Sum of zeros } = -\\frac{\\text{coefficient of } x}{\\text{coefficient of } x^2} = -\\frac{2}{1} = -2 \\\\ &\\text{Product of zeros } = \\frac{\\text{constant term}}{\\text{coefficient of } x^2} = \\frac{-15}{1} = -15 \\\\ &\\therefore \\quad \\text{Relationship verified} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given zeros: } \\alpha = \\frac{1}{2}, \\beta = \\frac{-3}{5} \\\\ &\\implies \\alpha + \\beta = \\frac{1}{2} + \\frac{-3}{5} = \\frac{5 - 6}{10} = \\frac{-1}{10} \\\\ &\\implies \\alpha \\beta = \\frac{1}{2} \\times \\frac{-3}{5} = \\frac{-3}{10} \\\\ &\\text{Quadratic polynomial: } x^2 - (\\alpha + \\beta)x + \\alpha \\beta \\\\ &\\implies x^2 + \\frac{1}{10}x - \\frac{3}{10} \\\\ &\\therefore \\text{Quadratic polynomial: } 10x^2 + x - 3 \\\\ &\\text{Verification: } \\text{Sum of zeros: } \\frac{-b}{a} = \\frac{-1}{10} \\\\ &\\text{Product of zeros: } \\frac{c}{a} = \\frac{-3}{10} \\\\ &\\text{Both match the given zeros.} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given: Sum of zeros } = 7, \\text{ Product of zeros } = 10 \\\\ &\\implies \\text{Quadratic polynomial: } x^2 - 7x + 10 \\\\ &\\text{To find zeros, solve: } x^2 - 7x + 10 = 0 \\\\ &\\implies (x - 5)(x - 2) = 0 \\\\ &\\therefore x = 5, 2 \\\\ \\end{aligned}']
['\\begin{aligned} &\\alpha + \\beta = 0, \\quad \\alpha \\beta = -2 \\\\ &\\implies \\quad x^2 - (\\alpha + \\beta)x + \\alpha \\beta \\\\ &\\implies \\quad x^2 - 0x - 2 \\\\ &\\therefore \\quad x^2 - 2 \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given sum of zeros } = \\frac{3}{2}, \\text{ product of zeros } = 2 \\\\ &\\implies \\quad x^2 - \\left(\\frac{3}{2}\\right)x + 2 \\\\ &\\therefore \\quad 2x^2 - 3x + 4 \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given sum of roots } = \\sqrt{3} \\quad \\text{and product of roots } = \\frac{1}{4} \\\\ &\\implies \\quad x^2 - (\\sqrt{3})x + \\frac{1}{4} \\\\ &\\therefore \\quad x^2 - \\sqrt{3}x + \\frac{1}{4} \\end{aligned}']
['\\begin{aligned} &\\text{Given roots: } x = \\frac{3}{4}, x = -4 \\\\ &\\text{Sum of roots: } \\frac{3}{4} + (-4) = -\\frac{13}{4} \\\\ &\\text{Product of roots: } \\frac{3}{4} \\times (-4) = -3 \\\\ &\\text{Using the relationship:} \\\\ &\\text{Sum of roots } = -\\frac{8}{a} \\implies -\\frac{13}{4} = -\\frac{8}{a} \\implies a = \\frac{32}{13} \\\\ &\\text{Product of roots } = \\frac{b}{a} \\implies -3 = \\frac{b}{\\frac{32}{13}} \\implies b = -\\frac{96}{13} \\\\ &\\therefore \\quad a = \\frac{32}{13}, \\quad b = -\\frac{96}{13} \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } 3x^{2} + 3bx + 6x + 12 \\\\ &\\implies 3x^{2} + (3b + 6)x + 12 \\\\ &\\text{If } (x+b) \\text{ is a factor, then } x = -b \\text{ is a root} \\\\ &\\implies 3(-b)^{2} + (3b + 6)(-b) + 12 = 0 \\\\ &\\implies 3b^{2} - 3b^{2} - 6b + 12 = 0 \\\\ &\\implies -6b + 12 = 0 \\\\ &\\therefore b = 2 \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given zero: } \\alpha = \\frac{3}{4} \\\\ &\\text{Polynomial: } 4x^{3}+12x^{2}+9x-20 \\\\ &\\text{Coefficients: } a = 4, b = 12, c = 9, d = -20 \\\\ &\\text{Sum of zeros: } \\alpha + \\beta + \\gamma = -\\frac{b}{a} = -\\frac{12}{4} = -3 \\\\ &\\implies \\frac{3}{4} + \\beta + \\gamma = -3 \\\\ &\\implies \\beta + \\gamma = -3 - \\frac{3}{4} = -\\frac{15}{4} \\\\ &\\text{Product of zeros: } \\alpha\\beta\\gamma = -\\frac{d}{a} = \\frac{20}{4} = 5 \\\\ &\\implies \\frac{3}{4} \\cdot \\beta \\cdot \\gamma = 5 \\\\ &\\implies \\beta \\cdot \\gamma = \\frac{20}{3} \\\\ &\\text{Quadratic equation: } x^2 + \\left(\\frac{15}{4}\\right)x + \\frac{20}{3} = 0 \\\\ &\\text{Solve using quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 1, b = \\frac{15}{4}, c = \\frac{20}{3} \\\\ &\\implies x = \\frac{-\\frac{15}{4} \\pm \\sqrt{\\left(\\frac{15}{4}\\right)^2 - 4 \\cdot 1 \\cdot \\frac{20}{3}}}{2 \\cdot 1} \\\\ &\\implies x = \\frac{-\\frac{15}{4} \\pm \\sqrt{\\frac{225}{16} - \\frac{80}{3}}}{2} \\\\ &\\implies x = \\frac{-\\frac{15}{4} \\pm \\sqrt{\\frac{225}{16} - \\frac{320}{16}}}{2} \\\\ &\\implies x = \\frac{-\\frac{15}{4} \\pm \\sqrt{-\\frac{95}{16}}}{2} \\\\ &\\text{No real roots, hence zeros are complex} \\\\ &\\therefore \\text{Other zeros are complex conjugates} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Divide: } 6x^3 - 15x^2 + 25x - 18 \\text{ by } x^2 - 3x + 4 \\\\\\ &\\implies \\quad \\text{First term: } \\frac{6x^3}{x^2} = 6x \\\\\\ &\\implies \\quad 6x(x^2 - 3x + 4) = 6x^3 - 18x^2 + 24x \\\\\\ &\\implies \\quad (6x^3 - 15x^2 + 25x - 18) - (6x^3 - 18x^2 + 24x) = 3x^2 + x - 18 \\\\\\ &\\implies \\quad \\text{Next term: } \\frac{3x^2}{x^2} = 3 \\\\\\ &\\implies \\quad 3(x^2 - 3x + 4) = 3x^2 - 9x + 12 \\\\\\ &\\implies \\quad (3x^2 + x - 18) - (3x^2 - 9x + 12) = 10x - 30 \\\\\\ &\\therefore \\quad \\text{Quotient: } 6x + 3, \\text{ Remainder: } 10x - 30 \\\\\\ &\\text{Verification: } \\text{Dividend} = \\text{Divisor} \\times \\text{Quotient} + \\text{Remainder} \\\\\\ &\\implies \\quad (x^2 - 3x + 4)(6x + 3) + (10x - 30) \\\\\\ &\\implies \\quad (6x^3 - 18x^2 + 24x + 3x^2 - 9x + 12) + 10x - 30 \\\\\\ &\\implies \\quad 6x^3 - 15x^2 + 25x - 18 \\\\\\ &\\therefore \\quad \\text{Verified} \\end{aligned}']
['\\begin{aligned} &\\text{Let } p(x) = 4x^{3}+12x^{2}-16x+11 \\text{ and } d(x) = 4x-3 \\\\ &\\text{Root of } d(x) = 0 \\implies 4x - 3 = 0 \\implies x = \\frac{3}{4} \\\\ &\\text{Using Remainder Theorem, find } p\\left(\\frac{3}{4}\\right) \\\\ &p\\left(\\frac{3}{4}\\right) = 4\\left(\\frac{3}{4}\\right)^{3} + 12\\left(\\frac{3}{4}\\right)^{2} - 16\\left(\\frac{3}{4}\\right) + 11 \\\\ &\\implies \\frac{108}{64} + \\frac{324}{16} - \\frac{48}{4} + 11 \\\\ &\\implies \\frac{27}{16} + \\frac{81}{4} - 12 + 11 \\\\ &\\implies \\frac{27}{16} + \\frac{324}{16} - \\frac{192}{16} + \\frac{176}{16} \\\\ &\\implies \\frac{335}{16} \\\\ &\\therefore \\text{The real number to be subtracted is } \\frac{335}{16} \\end{aligned}']
['\\begin{aligned} &\\text{Divide } (x^4 + 3x^3 + 9x^2 + 14x + 20) \\text{ by } (x^2 + 6) \\\\ &\\implies \\quad x^4 + 3x^3 + 9x^2 + 14x + 20 = (x^2 + 6)(x^2 + 3x + 3) + (px + q) \\\\ &\\text{Calculate } (x^2 + 6)(x^2 + 3x + 3) \\\\ &\\implies \\quad x^4 + 3x^3 + 3x^2 + 6x^2 + 18x + 18 \\\\ &\\implies \\quad x^4 + 3x^3 + 9x^2 + 18x + 18 \\\\ &\\text{Subtract from original polynomial:} \\\\ &\\implies \\quad (x^4 + 3x^3 + 9x^2 + 14x + 20) - (x^4 + 3x^3 + 9x^2 + 18x + 18) \\\\ &\\implies \\quad -4x + 2 \\\\ &\\therefore \\quad p = -4, \\quad q = 2 \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given: } f(x) = x^{3} - 4x^{2} + 2x + 3, \\ q(x) = x - 3, \\ r(x) = -3x + 5 \\\\ &\\text{Using the polynomial division algorithm: } f(x) = g(x) \\cdot q(x) + r(x) \\\\ &\\implies x^{3} - 4x^{2} + 2x + 3 = g(x) \\cdot (x - 3) + (-3x + 5) \\\\ &\\text{Rearrange to find } g(x): \\\\ &\\implies g(x) \\cdot (x - 3) = x^{3} - 4x^{2} + 2x + 3 + 3x - 5 \\\\ &\\implies g(x) \\cdot (x - 3) = x^{3} - 4x^{2} + 5x - 2 \\\\ &\\text{Assume } g(x) = ax^{2} + bx + c \\\\ &\\text{Equating coefficients: } \\\\ &\\implies ax^{3} - 3ax^{2} + bx^{2} - 3bx + cx - 3c = x^{3} - 4x^{2} + 5x - 2 \\\\ &\\implies a = 1, \\\\ &-3a + b = -4, \\\\ &-3b + c = 5, \\\\ &-3c = -2 \\\\ &\\therefore a = 1, \\\\ &b = -1, \\\\ &c = \\frac{2}{3} \\\\ &\\therefore g(x) = x^{2} - x + \\frac{2}{3} \\\\ \\end{aligned}']
['\\begin{aligned} &\\text{Given polynomial: } 5x - x^3 - 4 \\\\ &\\text{Rearrange: } -x^3 + 5x - 4 \\\\ &\\text{Divide } -x^3 + 5x - 4 \\text{ by } (x - 1) \\\\ &\\implies \\quad (-x^3 + 5x - 4) \\div (x - 1) \\\\ &\\implies \\quad -x^2 \\text{ (first term of quotient)} \\\\ &\\implies \\quad (-x^3 + x^2) \\text{ (subtract)} \\\\ &\\implies \\quad (0x^3 + 5x - 4) - (-x^3 + x^2) \\\\ &\\implies \\quad x^2 + 5x - 4 \\\\ &\\implies \\quad \\text{Continue division: } x^2 \\div (x - 1) \\\\ &\\implies \\quad x \\text{ (next term of quotient)} \\\\ &\\implies \\quad (x^2 - x) \\text{ (subtract)} \\\\ &\\implies \\quad (x^2 + 5x - 4) - (x^2 - x) \\\\ &\\implies \\quad 6x - 4 \\\\ &\\implies \\quad \\text{Continue division: } 6x \\div (x - 1) \\\\ &\\implies \\quad 6 \\text{ (next term of quotient)} \\\\ &\\implies \\quad (6x - 6) \\text{ (subtract)} \\\\ &\\implies \\quad (6x - 4) - (6x - 6) \\\\ &\\implies \\quad 2 \\\\ &\\therefore \\quad \\text{Quotient: } -x^2 + x + 6 \\text{ and remainder: } 2 \\\\ &\\text{Since remainder is not zero, } x = 1 \\text{ is not a zero. Re-evaluate division.} \\\\ &\\text{Correct division: } -x^3 + 5x - 4 \\div (x - 1) \\\\ &\\implies \\quad -x^2 \\text{ (first term of quotient)} \\\\ &\\implies \\quad (-x^3 + x^2) \\text{ (subtract)} \\\\ &\\implies \\quad (0x^3 + 5x - 4) - (-x^3 + x^2) \\\\ &\\implies \\quad x^2 + 5x - 4 \\\\ &\\implies \\quad \\text{Continue division: } x^2 \\div (x - 1) \\\\ &\\implies \\quad x \\text{ (next term of quotient)} \\\\ &\\implies \\quad (x^2 - x) \\text{ (subtract)} \\\\ &\\implies \\quad (x^2 + 5x - 4) - (x^2 - x) \\\\ &\\implies \\quad 6x - 4 \\\\ &\\implies \\quad \\text{Continue division: } 6x \\div (x - 1) \\\\ &\\implies \\quad 6 \\text{ (next term of quotient)} \\\\ &\\implies \\quad (6x - 6) \\text{ (subtract)} \\\\ &\\implies \\quad (6x - 4) - (6x - 6) \\\\ &\\implies \\quad 2 \\\\ &\\therefore \\quad \\text{Quotient: } -x^2 + x + 6 \\text{ and remainder: } 2 \\\\ &\\text{Re-evaluate: } x = 1 \\text{ is not a zero. Correct polynomial: } x^3 - 5x + 4 \\\\ &\\text{Perform division again: } x^3 - 5x + 4 \\div (x - 1) \\\\ &\\implies \\quad x^2 \\text{ (first term of quotient)} \\\\ &\\implies \\quad (x^3 - x^2) \\text{ (subtract)} \\\\ &\\implies \\quad (x^3 - 5x + 4) - (x^3 - x^2) \\\\ &\\implies \\quad -x^2 - 5x + 4 \\\\ &\\implies \\quad \\text{Continue division: } -x^2 \\div (x - 1) \\\\ &\\implies \\quad -x \\text{ (next term of quotient)} \\\\ &\\implies \\quad (-x^2 + x) \\text{ (subtract)} \\\\ &\\implies \\quad (-x^2 - 5x + 4) - (-x^2 + x) \\\\ &\\implies \\quad -6x + 4 \\\\ &\\implies \\quad \\text{Continue division: } -6x \\div (x - 1) \\\\ &\\implies \\quad -6 \\text{ (next term of quotient)} \\\\ &\\implies \\quad (-6x + 6) \\text{ (subtract)} \\\\ &\\implies \\quad (-6x + 4) - (-6x + 6) \\\\ &\\implies \\quad -2 \\\\ &\\therefore \\quad \\text{Quotient: } x^2 - x - 6 \\text{ and remainder: } 0 \\\\ &\\text{Factor } x^2 - x - 6 = (x - 3)(x + 2) \\\\ &\\therefore \\quad \\text{Other zeros are } 3 \\text{ and } -2 \\end{aligned}']

In [25]:
# Define the prompt template for generating misconceptions
prompt_template = PromptTemplate(
    input_variables=["system_prompt","topic", "topic_id", "question", "hint", "solution"],
    template="{system_prompt}\n\nGenerate one correct option and appropriate incorrect options in latex using given solution, hint, and misconceptions for the given question.\n\nTopic ID: {topic_id}\nTopic: {topic}\nQuestion: {question}\nHint: {hint}\nSolution: {solution}\n\nReturn the output in the specified JSON format."
)

# Extract relevant information from the 'explanation' column

def extract_explanation_details(explanation):
    try:
        explanation_data = json.loads(explanation)
        hint = explanation_data.get('hint', 'No hint available')
        solution = explanation_data.get('solution', 'No solution available')
        return hint, solution
    except json.JSONDecodeError:
        return 'No hint available', 'No solution available'

# Function to generate misconceptions-based incorrect options

def generate_incorrect_options(row):

    chain = LLMChain(llm=llm, prompt=prompt_template)
    try:
        response = chain.run(
            system_prompt=DISTRACTOR_SYSTEM_PROMPT,
            topic=row['topic'],
            topic_id=row['topic_id'],
            question=row['question'],
            hint=row['hint'],
            solution=row['solution']
        )
        # if response.strip().startswith("```json"):
        #     response = response.strip().strip("```json").strip("```").strip()
        return response
    except Exception as e:
        print(f"Unexpected error: {str(e)}")
        return None

# Apply the function to generate misconceptions-based incorrect options for each question
misconception_options = []
def loopForDistractor(data):
    distractor_counter = 0
    retries_counter = 0
    maxCounter = len(data)
    while distractor_counter<maxCounter:
        row = data.loc[distractor_counter]
        print(f"Processing question {distractor_counter + 1} out of {len(data)}")
        misconception_option = generate_incorrect_options(row)
        parsed_response = parse_Response(misconception_option)

        if parsed_response:
            # misconception_options.append(parsed_response)
            # row['misconception_options'] = parsed_response
            # print(distractor_counter)
            # print(data.loc[distractor_counter , 'misconception_options'])
            # print(parsed_response)

            data.loc[distractor_counter , 'misconception_options'] =[parsed_response]
            distractor_counter += 1
            retries_counter = 0
        else:
            print(f"Failed to parse response or generate distractors for question {distractor_counter + 1}, retrying...")
            retries_counter += 1
        if retries_counter == 3:
            # misconception_option.append("")
            data.loc[distractor_counter , 'misconception_options'] = ""
            distractor_counter += 1

loopForDistractor(data)
# data['misconception_options'] = misconception_options

Processing question 1 out of 121
Processing question 2 out of 121
Processing question 3 out of 121
Processing question 4 out of 121
Processing question 5 out of 121
Processing question 6 out of 121
Processing question 7 out of 121
Processing question 8 out of 121
Processing question 9 out of 121
Processing question 10 out of 121
Processing question 11 out of 121
Processing question 12 out of 121
Processing question 13 out of 121
Processing question 14 out of 121
Processing question 15 out of 121
Processing question 16 out of 121
Unexpected error: Request timed out.
No response message found <class 'NoneType'>
Failed to parse response or generate distractors for question 16, retrying...
Processing question 16 out of 121
Processing question 17 out of 121
Processing question 18 out of 121
Processing question 19 out of 121
Processing question 20 out of 121
Processing question 21 out of 121
Processing question 22 out of 121
Processing question 23 out of 121
Processing question 24 out of 121
Processing question 25 out of 121
Processing question 26 out of 121
Processing question 27 out of 121
Processing question 28 out of 121
Processing question 29 out of 121
Processing question 30 out of 121
Processing question 31 out of 121
Processing question 32 out of 121
Processing question 33 out of 121
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 67 (char 66)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
  "correct_option": "\\begin{aligned} &3x^3 + 4x^2 - 28x + 16 \\ \end{aligned}",
  "option1": {
    "option": "\\begin{aligned} &3x^3 - 4x^2 + 28x - 16 \\ \end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Confused the signs of the coefficients, leading to incorrect polynomial formation} \\end{aligned}"
  },
  "option2": {
    "option": "\\begin{aligned} &3x^3 + 4x^2 + 28x - 16 \\ \end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Forgot to apply the correct sign for the linear term coefficient} \\end{aligned}"
  },
  "option3": {
    "option": "\\begin{aligned} &3x^3 - 4x^2 - 28x + 16 \\ \end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Ignored the correct sign for the quadratic term coefficient} \\end{aligned}"
  }
}
After removing \ issue:  {
  "correct_option": "\\begin{aligned} &3x^3 + 4x^2 - 28x + 16 \\ \\end{aligned}",
  "option1": {
    "option": "\\begin{aligned} &3x^3 - 4x^2 + 28x - 16 \\ \\end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Confused the signs of the coefficients, leading to incorrect polynomial formation} \\end{aligned}"
  },
  "option2": {
    "option": "\\begin{aligned} &3x^3 + 4x^2 + 28x - 16 \\ \\end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Forgot to apply the correct sign for the linear term coefficient} \\end{aligned}"
  },
  "option3": {
    "option": "\\begin{aligned} &3x^3 - 4x^2 - 28x + 16 \\ \\end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Ignored the correct sign for the quadratic term coefficient} \\end{aligned}"
  }
}
Processing question 34 out of 121
Processing question 35 out of 121
Processing question 36 out of 121
Processing question 37 out of 121
Processing question 38 out of 121
Processing question 39 out of 121
Processing question 40 out of 121
Processing question 41 out of 121
Processing question 42 out of 121
Processing question 43 out of 121
Processing question 44 out of 121
Processing question 45 out of 121
Processing question 46 out of 121
Processing question 47 out of 121
Processing question 48 out of 121
Processing question 49 out of 121
Processing question 50 out of 121
Processing question 51 out of 121
Processing question 52 out of 121
Unexpected error: Request timed out.
No response message found <class 'NoneType'>
Failed to parse response or generate distractors for question 52, retrying...
Processing question 52 out of 121
Unexpected error: Request timed out.
No response message found <class 'NoneType'>
Failed to parse response or generate distractors for question 52, retrying...
Processing question 52 out of 121
Processing question 53 out of 121
Processing question 54 out of 121
Processing question 55 out of 121
Processing question 56 out of 121
Processing question 57 out of 121
Processing question 58 out of 121
Processing question 59 out of 121
Processing question 60 out of 121
Processing question 61 out of 121
Processing question 62 out of 121
Processing question 63 out of 121
Processing question 64 out of 121
Processing question 65 out of 121
Processing question 66 out of 121
Processing question 67 out of 121
Processing question 68 out of 121
Processing question 69 out of 121
Processing question 70 out of 121
Processing question 71 out of 121
Processing question 72 out of 121
Processing question 73 out of 121
Processing question 74 out of 121
Processing question 75 out of 121
Processing question 76 out of 121
Processing question 77 out of 121
Processing question 78 out of 121
Processing question 79 out of 121
Processing question 80 out of 121
Processing question 81 out of 121
Processing question 82 out of 121
Unexpected error: Request timed out.
No response message found <class 'NoneType'>
Failed to parse response or generate distractors for question 82, retrying...
Processing question 82 out of 121
Unexpected error: Request timed out.
No response message found <class 'NoneType'>
Failed to parse response or generate distractors for question 82, retrying...
Processing question 82 out of 121
Processing question 83 out of 121
Processing question 84 out of 121
Processing question 85 out of 121
Processing question 86 out of 121
Processing question 87 out of 121
Processing question 88 out of 121
Processing question 89 out of 121
Processing question 90 out of 121
Unexpected error: Request timed out.
No response message found <class 'NoneType'>
Failed to parse response or generate distractors for question 90, retrying...
Processing question 90 out of 121
Processing question 91 out of 121
Processing question 92 out of 121
Processing question 93 out of 121
Processing question 94 out of 121
Processing question 95 out of 121
Processing question 96 out of 121
Processing question 97 out of 121
Processing question 98 out of 121
Processing question 99 out of 121
Processing question 100 out of 121
Processing question 101 out of 121
Processing question 102 out of 121
Processing question 103 out of 121
Processing question 104 out of 121
Processing question 105 out of 121
Processing question 106 out of 121
Processing question 107 out of 121
Processing question 108 out of 121
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 58 (char 57)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
  "correct_option": "\\begin{aligned} &x^2 + 3x - 18 \\ \end{aligned}",
  "option1": {
    "option": "\\begin{aligned} &x^2 - 3x - 18 \\ \end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Confused the sign of the sum of zeros, using } -3 \\text{ instead of } +3. \\end{aligned}"
  },
  "option2": {
    "option": "\\begin{aligned} &x^2 + 3x + 18 \\ \end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Forgot to apply the correct sign for the product of zeros, using } +18 \\text{ instead of } -18. \\end{aligned}"
  },
  "option3": {
    "option": "\\begin{aligned} &x^2 - 3x + 18 \\ \end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Ignored both the correct signs for the sum and product of zeros, leading to incorrect terms.} \\end{aligned}"
  }
}
After removing \ issue:  {
  "correct_option": "\\begin{aligned} &x^2 + 3x - 18 \\ \\end{aligned}",
  "option1": {
    "option": "\\begin{aligned} &x^2 - 3x - 18 \\ \\end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Confused the sign of the sum of zeros, using } -3 \\text{ instead of } +3. \\end{aligned}"
  },
  "option2": {
    "option": "\\begin{aligned} &x^2 + 3x + 18 \\ \\end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Forgot to apply the correct sign for the product of zeros, using } +18 \\text{ instead of } -18. \\end{aligned}"
  },
  "option3": {
    "option": "\\begin{aligned} &x^2 - 3x + 18 \\ \\end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Ignored both the correct signs for the sum and product of zeros, leading to incorrect terms.} \\end{aligned}"
  }
}
Processing question 109 out of 121
Processing question 110 out of 121
Processing question 111 out of 121
Unexpected error: Request timed out.
No response message found <class 'NoneType'>
Failed to parse response or generate distractors for question 111, retrying...
Processing question 111 out of 121
Processing question 112 out of 121
Processing question 113 out of 121
Processing question 114 out of 121
Processing question 115 out of 121
Processing question 116 out of 121
Processing question 117 out of 121
Processing question 118 out of 121
Processing question 119 out of 121
Processing question 120 out of 121
Processing question 121 out of 121
Error decoding JSON response: JSONDecodeError - Invalid \escape: line 1 column 51 (char 50)

 Still trying to work on particular exceptions ...
Before removing \ issue:  {
  "correct_option": "\\begin{aligned} &k = -9 \\ \end{aligned}",
  "option1": {
    "option": "\\begin{aligned} &k = -3 \\ \end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Confused the subtraction step, calculating } 21 - 48 \\text{ as } -27 \\text{ incorrectly.} \\end{aligned}"
  },
  "option2": {
    "option": "\\begin{aligned} &k = 9 \\ \end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Ignored the sign change when solving } 3k = -27, \\text{ leading to a positive } k. \\end{aligned}"
  },
  "option3": {
    "option": "\\begin{aligned} &k = -6 \\ \end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Forgot to divide } -27 \\text{ by } 3 \\text{ correctly, resulting in } k = -6. \\end{aligned}"
  }
}
After removing \ issue:  {
  "correct_option": "\\begin{aligned} &k = -9 \\ \\end{aligned}",
  "option1": {
    "option": "\\begin{aligned} &k = -3 \\ \\end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Confused the subtraction step, calculating } 21 - 48 \\text{ as } -27 \\text{ incorrectly.} \\end{aligned}"
  },
  "option2": {
    "option": "\\begin{aligned} &k = 9 \\ \\end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Ignored the sign change when solving } 3k = -27, \\text{ leading to a positive } k. \\end{aligned}"
  },
  "option3": {
    "option": "\\begin{aligned} &k = -6 \\ \\end{aligned}",
    "rationale": "\\begin{aligned} &\\text{Forgot to divide } -27 \\text{ by } 3 \\text{ correctly, resulting in } k = -6. \\end{aligned}"
  }
}

In [26]:
for i in range(len(data)):
    print(data['misconception_options'][i])

[{'correct_option': '\\begin{aligned} &\\alpha = -3, \\beta = -2 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\alpha = -2, \\beta = -3 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the order of the roots, which does not affect the relationship.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\alpha = 3, \\beta = 2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the negative sign from the quadratic formula correctly.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\alpha = -1, \\beta = -6 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct calculation of the discriminant.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &5 \\quad \\text{and} \\quad -2 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &3 \\quad \\text{and} \\quad -5 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the signs in the quadratic formula, leading to incorrect zeros.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &2 \\quad \\text{and} \\quad -5 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly apply the quadratic formula, resulting in one incorrect zero.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &5 \\quad \\text{and} \\quad 2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the sign of the second zero, leading to an incorrect positive value.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\quad x = 2 \\quad \\text{or} \\quad x = -6 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\quad x = 3 \\quad \\text{or} \\quad x = -5 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the signs in the quadratic formula calculation, leading to incorrect zeros.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\quad x = 4 \\quad \\text{or} \\quad x = -4 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct computation of the discriminant, resulting in wrong zeros.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\quad x = 1 \\quad \\text{or} \\quad x = -7 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the quadratic formula correctly, leading to miscalculated zeros.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{3 \\pm \\sqrt{33}}{6} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{-3 \\pm \\sqrt{33}}{6} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the sign of } b \\text{ in the quadratic formula, leading to an incorrect sign in the numerator.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{3 \\pm \\sqrt{21}}{6} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly compute the discriminant } (b^2 - 4ac), \\text{ resulting in an incorrect value under the square root.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{3 \\pm \\sqrt{33}}{3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct denominator } (2a) \\text{ in the quadratic formula, using } 3 \\text{ instead of } 6. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{9 \\pm \\sqrt{201}}{12} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{9 \\pm \\sqrt{81}}{12} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the discriminant calculation by using } 81 \\text{ instead of } 201. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{9 \\pm \\sqrt{201}}{6} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to divide by } 2a \\text{ correctly, using } 6 \\text{ instead of } 12. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{-9 \\pm \\sqrt{201}}{12} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the sign change in the quadratic formula, using } -9 \\text{ instead of } 9. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\sqrt{2}, \\frac{1}{3\\sqrt{2}} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{7}{6\\sqrt{2}}, \\frac{5}{6\\sqrt{2}} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the calculation of } \\sqrt{b^2 - 4ac} \\text{ leading to incorrect zeros} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{12}{6\\sqrt{2}}, \\frac{2}{6\\sqrt{2}} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to simplify the fractions to their simplest form} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{7}{3\\sqrt{2}}, \\frac{1}{3\\sqrt{2}} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct simplification of the sum of zeros formula} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{No real zeros} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{Zeros are } \\frac{10}{3} \\text{ and } 4 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the relationship with actual zeros, which do not exist due to a negative discriminant.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{Zeros are } 3 \\text{ and } -4 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the negative discriminant, leading to incorrect real zeros.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{Zeros are } 2 \\text{ and } 6 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot the discriminant is negative, mistakenly calculated real zeros.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{5 \\pm i\\sqrt{15}}{10} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{5 \\pm \\sqrt{15}}{10} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the imaginary part, forgetting the } i \\text{ in the complex zeros.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{5 \\pm i\\sqrt{5}}{10} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood the discriminant calculation, using } \\sqrt{5} \\text{ instead of } \\sqrt{15}. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{5 \\pm i\\sqrt{10}}{10} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct discriminant value, mistakenly using } \\sqrt{10}. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\sqrt{7} \\text{ and } -\\sqrt{7} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &7 \\text{ and } -7 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the expression } x^2 = 7 \\text{ with } x = 7 \\text{ and } x = -7 \\text{ instead of taking the square root} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\pm 3.5 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the square root correctly, leading to an incorrect simplification} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &0 \\text{ and } -7 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the need to solve } x^2 = 7 \\text{ correctly, assuming one zero is } 0 \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\pm \\frac{\\sqrt{5}}{3} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\pm \\frac{\\sqrt{5}}{9} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the denominator by using the wrong coefficient value in the quadratic formula.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\pm \\frac{5\\sqrt{5}}{3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to simplify the square root correctly, leading to an incorrect numerator.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\pm \\frac{\\sqrt{5}}{6} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct simplification of the fraction, resulting in a wrong denominator.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{Zeros are } 0 \\text{ and } -2 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{Zeros are } 2 \\text{ and } -2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the signs of the zeros, forgetting the correct application of the quadratic formula.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{Zeros are } 0 \\text{ and } 2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the negative sign in the quadratic formula calculation.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{Zeros are } -1 \\text{ and } -2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Misunderstood the calculation of the square root term in the quadratic formula.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\alpha = 2.5, \\beta = -1 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\alpha = 1.5, \\beta = -2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the calculation of zeros by incorrectly solving the quadratic formula.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\alpha = 2, \\beta = -1.5 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct substitution into the quadratic formula, leading to wrong zeros.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\alpha = 3, \\beta = -0.5 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot the correct calculation of the discriminant, resulting in incorrect zeros.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x^2 + 2x - 15 \\ \\ \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x^2 - 2x - 15 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the sign of the sum of zeros, using } -2 \\text{ instead of } +2 \\text{ in the polynomial.} \\ \\ \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x^2 + 2x + 15 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the sign of the product of zeros, using } +15 \\text{ instead of } -15 \\text{ in the polynomial.} \\ \\ \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x^2 - 2x + 15 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot both the correct signs for sum and product of zeros, using } -2 \\text{ and } +15. \\ \\ \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &10x^2 + x - 3 \\ \\ \\end{aligned}', 'option1': {'option': '\\begin{aligned} &10x^2 - x - 3 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the sign of the linear coefficient, leading to an incorrect sum of zeros.} \\ \\ \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &10x^2 + x + 3 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the sign of the constant term, resulting in an incorrect product of zeros.} \\ \\ \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x^2 + \\frac{1}{10}x + \\frac{3}{10} \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to multiply through by 10, leading to incorrect polynomial coefficients.} \\ \\ \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x = 5,\\quad 2 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x = 3,\\quad 4 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the factorization, leading to incorrect roots.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x = 6,\\quad 1 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly apply the sum and product of zeros.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x = 7,\\quad 0 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct polynomial formation, leading to wrong zeros.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x^2 - 2 \\ \\ \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x^2 + 2 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the sign of the product, using } +2 \\text{ instead of } -2. \\ \\ \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x^2 - x - 2 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot that the sum of zeros is zero, incorrectly including } x \\text{ term.} \\ \\ \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x^2 + x - 2 \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the sum of zeros being zero, mistakenly adding } x \\text{ term.} \\ \\ \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &2x^2 - 3x + 4 \\ \\ \\ \\ \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x^2 - \\frac{3}{2}x + 2 \\ \\ \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the multiplication factor needed to clear the fraction in the polynomial.} \\ \\ \\ \\ \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &2x^2 - 3x + 2 \\ \\ \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to adjust the constant term after multiplying through by 2.} \\ \\ \\ \\ \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &2x^2 - \\frac{3}{2}x + 4 \\ \\ \\ \\ \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the need to multiply the linear term by 2 to clear the fraction.} \\ \\ \\ \\ \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &x^2 - \\sqrt{3}x + \\frac{1}{4} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &x^2 + \\sqrt{3}x + \\frac{1}{4} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the sign of the sum of roots, using } + \\sqrt{3} \\text{ instead of } - \\sqrt{3} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &x^2 - \\sqrt{3}x - \\frac{1}{4} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot that the product of roots should be positive, using } - \\frac{1}{4} \\text{ instead of } + \\frac{1}{4} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &x^2 + \\sqrt{3}x - \\frac{1}{4} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored both the correct signs for sum and product of roots, using } + \\sqrt{3} \\text{ and } - \\frac{1}{4} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &a = \\frac{32}{13}, \\quad b = -\\frac{96}{13} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &a = \\frac{13}{32}, \\quad b = -\\frac{96}{13} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the reciprocal of } a \\text{ with the correct value, leading to an incorrect } a \\text{ value.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &a = \\frac{32}{13}, \\quad b = \\frac{96}{13} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the negative sign in the product of roots, resulting in a positive } b \\text{ value.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &a = \\frac{32}{13}, \\quad b = -\\frac{13}{96} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the reciprocal of } b \\text{ with the correct value, leading to an incorrect } b \\text{ value.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &b \\quad = \\quad 2 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &b \\quad = \\quad -2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the sign of } b \\text{ when solving the equation, leading to an incorrect value of } b. \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &b \\quad = \\quad 0 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the linear term coefficient, assuming it cancels out, resulting in } b \\quad = \\quad 0. \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &b \\quad = \\quad 4 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Miscalculated the equation by incorrectly simplifying the terms, leading to } b \\quad = \\quad 4. \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{Complex conjugates} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{Real and distinct} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the nature of roots by assuming the discriminant was positive, indicating real and distinct roots.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{Real and equal} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot that a zero discriminant indicates real and equal roots, not applicable here.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{Imaginary and distinct} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the fact that complex roots occur in conjugate pairs, not as distinct imaginary numbers.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\text{Quotient: } 6x + 3, \\text{ Remainder: } 10x - 30 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\text{Quotient: } 6x + 2, \\text{ Remainder: } 10x - 30 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the constant term in the quotient, resulting in an incorrect quotient.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\text{Quotient: } 6x + 3, \\text{ Remainder: } 10x - 20 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly calculate the constant term in the remainder.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\text{Quotient: } 6x + 4, \\text{ Remainder: } 10x - 30 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct subtraction of terms, leading to an incorrect quotient.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\frac{335}{16} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\frac{325}{16} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the calculation of } p\\left(\\frac{3}{4}\\right) \\text{ leading to a slightly incorrect result} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\frac{335}{15} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to correctly simplify the fractions, resulting in a denominator error} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\frac{345}{16} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct order of operations, leading to an incorrect numerator} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &\\quad p = -4, \\quad q = 2 \\end{aligned}', 'option1': {'option': '\\begin{aligned} &\\quad p = -4, \\quad q = -2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the sign of } q \\text{ when subtracting the constants in the remainder.} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &\\quad p = 4, \\quad q = 2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the correct sign to } p \\text{ after subtraction.} \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &\\quad p = -2, \\quad q = 4 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct coefficients by miscalculating the remainder terms.} \\end{aligned}'}}]
[{'correct_option': '\\begin{aligned} &g(x) = x^{2} - x + \\frac{2}{3} \\end{aligned}', 'option1': {'option': '\\begin{aligned} &g(x) = x^{2} - x + 2 \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Confused the constant term by ignoring the fraction in } c = \\frac{2}{3} \\end{aligned}'}, 'option2': {'option': '\\begin{aligned} &g(x) = x^{2} + x + \\frac{2}{3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Forgot to apply the correct sign for the } b \\text{ term, using } +x \\text{ instead of } -x \\end{aligned}'}, 'option3': {'option': '\\begin{aligned} &g(x) = x^{2} - 2x + \\frac{2}{3} \\end{aligned}', 'rationale': '\\begin{aligned} &\\text{Ignored the correct coefficient for the } x \\text{ term, using } -2x \\text{ instead of } -x \\end{aligned}'}}]

### Output Formatting & Pushing into the DB

In [27]:
# Function to process each row and extract required fields
def process_row(row, index):
    try:
        misconception_data = row["misconception_options"]
        # Extract topic, question, and solution details
        topic_id = row["topic_id"]
        topic_name = row["topic"]
        question = row["question"]
        hint = row["hint"]
        explanation = row["solution"]
        # correct_answer = row["final_answer"]
        chapter = conf_data['chapter_name']

        # Extract option and rationale details
        options = {}
        for i in range(1, 4):  # Assuming there are 4 options for each question
            options["correct_answer"] = misconception_data[0]["correct_option"]
            option_key = f'option{i}'
            option_info = misconception_data[0][option_key]
            options[f'option{i}'] = option_info.get('option', '')
            options[f'dr{i}'] = option_info.get('rationale', '')
        
        # Construct the final JSON structure
        start = "\\begin{aligned}"
        end = "\\end{aligned}"
        
        combined_data = {
            'topic_id': topic_id,
            'topic_name': topic_name,
            'grade' : conf_data['grade'],
            'board' : "CBSE",
            
            'subject' : subject,
            'chapter_name' : chapter,
            'publication' : conf_data['publication'],
            'question': [{"content": question}],
            # if (str(question).startswith("\\begin{aligned}") and str(question).endswith("\\end{aligned}")) else [{"content": start + question + end}],

            'hint': [{"content": hint}],
            # if (str(hint).startswith("\\begin{aligned}") and str(hint).endswith("\\end{aligned}")) else [{"content": start + hint + end}],

            'solution': [{"content": explanation}],
            # if (str(explanation).startswith("\\begin{aligned}") and str(explanation).endswith("\\end{aligned}")) else [{"content": start + explanation + end}],

            'final_answer': [{"content": options.get('correct_answer', '')}],
            # if (str(options.get('correct_answer', '')).startswith("\\begin{aligned}") and str(options.get('correct_answer', '')).endswith("\\end{aligned}")) else [{"content": start + options.get('correct_answer', '') + end}],

            'option1': [{"content": options.get('option1', '')}],
            # if (str(options.get('option1')).startswith("\\begin{aligned}") and str(options.get('option1')).endswith("\\end{aligned}")) else [{"content": start + str(options.get('option1', '')) + end} ],
            'dr1': [{"content": options.get('dr1', '')}],
            'option2': [{"content": options.get('option2', '')}],
            # if (str(options.get('option2')).startswith("\\begin{aligned}") and str(options.get('option2')).endswith("\\end{aligned}")) else [{"content": start + str(options.get('option2', '')) + end}],
            'dr2': [{"content": options.get('dr2', '')}],
            'option3': [{"content": options.get('option3', '')}],
            # if (str(options.get('option3')).startswith("\\begin{aligned}") and str(options.get('option3')).endswith("\\end{aligned}")) else [{"content": start + str(options.get('option3', '')) + end}],
            'dr3': [{"content": options.get('dr3', '')}]


        }

        return combined_data
    except Exception as e:
        print(f"Exception Occurred: {type(e).__name__} – {e} \n {traceback.format_exc()}")


# Process all rows in the dataframe
final_output = [process_row(row, idx) for idx, row in data.iterrows()]
final_output[2]

{'topic_id': '10_mathematics_polynomials_3',
 'topic_name': 'Relationship between zeros and coefficients of a polynomial',
 'grade': '10',
 'board': 'CBSE',
 'subject': 'mathematics',
 'chapter_name': 'Polynomials',
 'publication': 'rsagarwal',
 'question': [{'content': '\\begin{aligned} &\\text{Calculate the zeros of the quadratic polynomial} \\quad x^{2}+4x-12 \\ \\quad &\\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'}],
 'hint': [{'content': '\\begin{aligned} &\\text{Use the quadratic formula to find zeros and verify using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}'}],
 'solution': [{'content': '\\begin{aligned} &x^2 + 4x - 12 = 0 \\\\ &\\implies \\quad x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{4^2 - 4 \\cdot 1 \\cdot (-12)}}{2 \\cdot 1} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{16 + 48}}{2} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{64}}{2} \\\\ &\\implies \\quad x = \\frac{-4 \\pm 8}{2} \\\\ &\\implies \\quad x = 2 \\quad \\text{or} \\quad x = -6 \\\\ &\\text{Verification:} \\\\ &\\alpha + \\beta = 2 + (-6) = -4 = -\\frac{b}{a} \\\\ &\\alpha \\beta = 2 \\times (-6) = -12 = \\frac{c}{a} \\\\ &\\therefore \\quad \\text{Zeros are verified} \\\\ \\end{aligned}'}],
 'final_answer': [{'content': '\\begin{aligned} &\\quad x = 2 \\quad \\text{or} \\quad x = -6 \\end{aligned}'}],
 'option1': [{'content': '\\begin{aligned} &\\quad x = 3 \\quad \\text{or} \\quad x = -5 \\end{aligned}'}],
 'dr1': [{'content': '\\begin{aligned} &\\text{Confused the signs in the quadratic formula calculation, leading to incorrect zeros.} \\end{aligned}'}],
 'option2': [{'content': '\\begin{aligned} &\\quad x = 4 \\quad \\text{or} \\quad x = -4 \\end{aligned}'}],
 'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct computation of the discriminant, resulting in wrong zeros.} \\end{aligned}'}],
 'option3': [{'content': '\\begin{aligned} &\\quad x = 1 \\quad \\text{or} \\quad x = -7 \\end{aligned}'}],
 'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the quadratic formula correctly, leading to miscalculated zeros.} \\end{aligned}'}]}

In [28]:
final_output

[{'topic_id': '10_mathematics_polynomials_3',
  'topic_name': 'Relationship between zeros and coefficients of a polynomial',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Polynomials',
  'publication': 'rsagarwal',
  'question': [{'content': '\\begin{aligned} &\\text{Determine the roots of the quadratic polynomial} \\quad x^{2}+5x+6 \\ \\quad &\\text{and confirm the relationship between the roots and the coefficients.} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the quadratic formula to find the roots and verify } \\alpha + \\beta = -b/a, \\alpha \\beta = c/a \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &x^2 + 5x + 6 = 0 \\\\ &\\implies \\quad x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies \\quad x = \\frac{-5 \\pm \\sqrt{5^2 - 4 \\cdot 1 \\cdot 6}}{2 \\cdot 1} \\\\ &\\implies \\quad x = \\frac{-5 \\pm \\sqrt{25 - 24}}{2} \\\\ &\\implies \\quad x = \\frac{-5 \\pm 1}{2} \\\\ &\\implies \\quad x = -3, -2 \\\\ &\\text{Roots are } \\alpha = -3, \\beta = -2 \\\\ &\\text{Verify: } \\alpha + \\beta = -3 + (-2) = -5 = -b/a \\\\ &\\alpha \\beta = (-3)(-2) = 6 = c/a \\\\ &\\therefore \\text{Relationship confirmed} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\alpha = -3, \\beta = -2 \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\alpha = -2, \\beta = -3 \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the order of the roots, which does not affect the relationship.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\alpha = 3, \\beta = 2 \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to apply the negative sign from the quadratic formula correctly.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\alpha = -1, \\beta = -6 \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the correct calculation of the discriminant.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_polynomials_3',
  'topic_name': 'Relationship between zeros and coefficients of a polynomial',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Polynomials',
  'publication': 'rsagarwal',
  'question': [{'content': '\\begin{aligned} &\\text{Identify the zeros of the quadratic polynomial} \\quad x^{2}-3x-10 \\ \\quad &\\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and verify using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given polynomial: } x^2 - 3x - 10 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 1, \\quad b = -3, \\quad c = -10 \\\\ &\\implies x = \\frac{-(-3) \\pm \\sqrt{(-3)^2 - 4 \\cdot 1 \\cdot (-10)}}{2 \\cdot 1} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{9 + 40}}{2} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{49}}{2} \\\\ &\\implies x = \\frac{3 \\pm 7}{2} \\\\ &\\implies x = 5 \\quad \\text{or} \\quad x = -2 \\\\ &\\text{Zeros are } 5 \\text{ and } -2 \\\\ &\\text{Verification:} \\\\ &\\alpha + \\beta = 5 + (-2) = 3 = -\\frac{b}{a} = -\\frac{-3}{1} \\\\ &\\alpha \\beta = 5 \\times (-2) = -10 = \\frac{c}{a} = \\frac{-10}{1} \\\\ &\\therefore \\text{Relationship verified} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &5 \\quad \\text{and} \\quad -2 \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &3 \\quad \\text{and} \\quad -5 \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the signs in the quadratic formula, leading to incorrect zeros.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &2 \\quad \\text{and} \\quad -5 \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to correctly apply the quadratic formula, resulting in one incorrect zero.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &5 \\quad \\text{and} \\quad 2 \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the sign of the second zero, leading to an incorrect positive value.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_polynomials_3',
  'topic_name': 'Relationship between zeros and coefficients of a polynomial',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Polynomials',
  'publication': 'rsagarwal',
  'question': [{'content': '\\begin{aligned} &\\text{Calculate the zeros of the quadratic polynomial} \\quad x^{2}+4x-12 \\ \\quad &\\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the quadratic formula to find zeros and verify using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &x^2 + 4x - 12 = 0 \\\\ &\\implies \\quad x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{4^2 - 4 \\cdot 1 \\cdot (-12)}}{2 \\cdot 1} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{16 + 48}}{2} \\\\ &\\implies \\quad x = \\frac{-4 \\pm \\sqrt{64}}{2} \\\\ &\\implies \\quad x = \\frac{-4 \\pm 8}{2} \\\\ &\\implies \\quad x = 2 \\quad \\text{or} \\quad x = -6 \\\\ &\\text{Verification:} \\\\ &\\alpha + \\beta = 2 + (-6) = -4 = -\\frac{b}{a} \\\\ &\\alpha \\beta = 2 \\times (-6) = -12 = \\frac{c}{a} \\\\ &\\therefore \\quad \\text{Zeros are verified} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\quad x = 2 \\quad \\text{or} \\quad x = -6 \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\quad x = 3 \\quad \\text{or} \\quad x = -5 \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the signs in the quadratic formula calculation, leading to incorrect zeros.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\quad x = 4 \\quad \\text{or} \\quad x = -4 \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the correct computation of the discriminant, resulting in wrong zeros.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\quad x = 1 \\quad \\text{or} \\quad x = -7 \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot to apply the quadratic formula correctly, leading to miscalculated zeros.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_polynomials_3',
  'topic_name': 'Relationship between zeros and coefficients of a polynomial',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Polynomials',
  'publication': 'rsagarwal',
  'question': [{'content': '\\begin{aligned} &\\text{Find the roots of the quadratic polynomial} \\quad 3x^{2}-3x-2 \\ \\quad &\\text{and confirm the relationship between the roots and the coefficients.} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the quadratic formula to find the roots and verify } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given polynomial: } 3x^2 - 3x - 2 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 3, \\quad b = -3, \\quad c = -2 \\\\ &\\implies x = \\frac{-(-3) \\pm \\sqrt{(-3)^2 - 4 \\cdot 3 \\cdot (-2)}}{2 \\cdot 3} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{9 + 24}}{6} \\\\ &\\implies x = \\frac{3 \\pm \\sqrt{33}}{6} \\\\ &\\therefore \\text{Roots are } \\frac{3 + \\sqrt{33}}{6}, \\frac{3 - \\sqrt{33}}{6} \\\\ &\\text{Sum of roots } (\\alpha + \\beta) = \\frac{3 + \\sqrt{33}}{6} + \\frac{3 - \\sqrt{33}}{6} = \\frac{6}{6} = 1 \\\\ &\\text{Product of roots } (\\alpha \\beta) = \\left(\\frac{3 + \\sqrt{33}}{6}\\right) \\cdot \\left(\\frac{3 - \\sqrt{33}}{6}\\right) = \\frac{9 - 33}{36} = -\\frac{2}{3} \\\\ &\\text{Verification: } \\alpha + \\beta = -\\frac{b}{a} = 1, \\quad \\alpha \\beta = \\frac{c}{a} = -\\frac{2}{3} \\\\ &\\text{Relationship confirmed.} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\frac{3 \\pm \\sqrt{33}}{6} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\frac{-3 \\pm \\sqrt{33}}{6} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the sign of } b \\text{ in the quadratic formula, leading to an incorrect sign in the numerator.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\frac{3 \\pm \\sqrt{21}}{6} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to correctly compute the discriminant } (b^2 - 4ac), \\text{ resulting in an incorrect value under the square root.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\frac{3 \\pm \\sqrt{33}}{3} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the correct denominator } (2a) \\text{ in the quadratic formula, using } 3 \\text{ instead of } 6. \\end{aligned}'}]},
 {'topic_id': '10_mathematics_polynomials_3',
  'topic_name': 'Relationship between zeros and coefficients of a polynomial',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Polynomials',
  'publication': 'rsagarwal',
  'question': [{'content': '\\begin{aligned} &\\text{Determine the zeros of the quadratic polynomial} \\quad 6x^{2}-5-9x \\ \\quad &\\text{and verify the relationship between the zeros and the coefficients.} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and verify using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given polynomial: } 6x^2 - 9x - 5 \\\\ &\\text{Rearrange: } 6x^2 - 9x - 5 = 0 \\\\ &\\text{Coefficients: } a = 6, b = -9, c = -5 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{-(-9) \\pm \\sqrt{(-9)^2 - 4 \\cdot 6 \\cdot (-5)}}{2 \\cdot 6} \\\\ &\\implies x = \\frac{9 \\pm \\sqrt{81 + 120}}{12} \\\\ &\\implies x = \\frac{9 \\pm \\sqrt{201}}{12} \\\\ &\\therefore \\text{Zeros are } \\frac{9 + \\sqrt{201}}{12}, \\frac{9 - \\sqrt{201}}{12} \\\\ &\\text{Sum of zeros: } \\alpha + \\beta = \\frac{9 + \\sqrt{201}}{12} + \\frac{9 - \\sqrt{201}}{12} = \\frac{18}{12} = \\frac{3}{2} \\\\ &\\text{Product of zeros: } \\alpha \\beta = \\left(\\frac{9 + \\sqrt{201}}{12}\\right) \\left(\\frac{9 - \\sqrt{201}}{12}\\right) = \\frac{81 - 201}{144} = \\frac{-120}{144} = -\\frac{5}{6} \\\\ &\\text{Verification: } \\alpha + \\beta = -\\frac{b}{a} = \\frac{9}{6} = \\frac{3}{2}, \\alpha \\beta = \\frac{c}{a} = -\\frac{5}{6} \\\\ &\\text{Zeros and coefficients relationship verified.} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\frac{9 \\pm \\sqrt{201}}{12} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\frac{9 \\pm \\sqrt{81}}{12} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the discriminant calculation by using } 81 \\text{ instead of } 201. \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\frac{9 \\pm \\sqrt{201}}{6} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to divide by } 2a \\text{ correctly, using } 6 \\text{ instead of } 12. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\frac{-9 \\pm \\sqrt{201}}{12} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the sign change in the quadratic formula, using } -9 \\text{ instead of } 9. \\end{aligned}'}]},
 {'topic_id': '10_mathematics_polynomials_3',
  'topic_name': 'Relationship between zeros and coefficients of a polynomial',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Polynomials',
  'publication': 'rsagarwal',
  'question': [{'content': '\\begin{aligned} &\\text{What are the zeros of the quadratic polynomial} \\quad 3\\sqrt{2}x^{2}-7x+\\sqrt{2} \\quad \\text{and how do they relate to the coefficients?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the quadratic formula } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\text{ to find the zeros} \\\\ &\\text{and relate them to the coefficients using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given quadratic polynomial: } 3\\sqrt{2}x^2 - 7x + \\sqrt{2} \\\\ &a = 3\\sqrt{2}, \\quad b = -7, \\quad c = \\sqrt{2} \\\\ &\\text{Zeros are given by } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &\\implies x = \\frac{7 \\pm \\sqrt{(-7)^2 - 4 \\cdot 3\\sqrt{2} \\cdot \\sqrt{2}}}{2 \\cdot 3\\sqrt{2}} \\\\ &\\implies x = \\frac{7 \\pm \\sqrt{49 - 24}}{6\\sqrt{2}} \\\\ &\\implies x = \\frac{7 \\pm \\sqrt{25}}{6\\sqrt{2}} \\\\ &\\implies x = \\frac{7 \\pm 5}{6\\sqrt{2}} \\\\ &\\therefore x = \\frac{12}{6\\sqrt{2}}, \\frac{2}{6\\sqrt{2}} \\\\ &\\implies x = \\sqrt{2}, \\frac{1}{3\\sqrt{2}} \\\\ &\\text{Sum of zeros } (\\alpha + \\beta) = \\sqrt{2} + \\frac{1}{3\\sqrt{2}} = -\\frac{b}{a} = \\frac{7}{3\\sqrt{2}} \\\\ &\\text{Product of zeros } (\\alpha \\beta) = \\sqrt{2} \\cdot \\frac{1}{3\\sqrt{2}} = \\frac{c}{a} = \\frac{1}{3\\sqrt{2}} \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\sqrt{2}, \\frac{1}{3\\sqrt{2}} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\frac{7}{6\\sqrt{2}}, \\frac{5}{6\\sqrt{2}} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the calculation of } \\sqrt{b^2 - 4ac} \\text{ leading to incorrect zeros} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\frac{12}{6\\sqrt{2}}, \\frac{2}{6\\sqrt{2}} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Forgot to simplify the fractions to their simplest form} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\frac{7}{3\\sqrt{2}}, \\frac{1}{3\\sqrt{2}} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the correct simplification of the sum of zeros formula} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_polynomials_3',
  'topic_name': 'Relationship between zeros and coefficients of a polynomial',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Polynomials',
  'publication': 'rsagarwal',
  'question': [{'content': '\\begin{aligned} &\\text{Determine the zeros of the quadratic polynomial} \\quad 3x^{2}-10x+12 \\quad \\text{and explain the relationship with the coefficients.} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and relate them to the coefficients using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha\\beta = \\frac{c}{a} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given polynomial: } 3x^2 - 10x + 12 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 3, \\quad b = -10, \\quad c = 12 \\\\ &\\implies x = \\frac{-(-10) \\pm \\sqrt{(-10)^2 - 4 \\cdot 3 \\cdot 12}}{2 \\cdot 3} \\\\ &\\implies x = \\frac{10 \\pm \\sqrt{100 - 144}}{6} \\\\ &\\implies x = \\frac{10 \\pm \\sqrt{-44}}{6} \\\\ &\\text{No real zeros since the discriminant is negative} \\\\ &\\text{Relationship: } \\alpha + \\beta = -\\frac{-10}{3} = \\frac{10}{3}, \\quad \\alpha\\beta = \\frac{12}{3} = 4 \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\text{No real zeros} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\text{Zeros are } \\frac{10}{3} \\text{ and } 4 \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the relationship with actual zeros, which do not exist due to a negative discriminant.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\text{Zeros are } 3 \\text{ and } -4 \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Ignored the negative discriminant, leading to incorrect real zeros.} \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\text{Zeros are } 2 \\text{ and } 6 \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Forgot the discriminant is negative, mistakenly calculated real zeros.} \\end{aligned}'}]},
 {'topic_id': '10_mathematics_polynomials_3',
  'topic_name': 'Relationship between zeros and coefficients of a polynomial',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Polynomials',
  'publication': 'rsagarwal',
  'question': [{'content': '\\begin{aligned} &\\text{Identify the zeros of the quadratic polynomial} \\quad 5x^{2}-5x+2 \\quad \\text{and verify the relationship with the coefficients.} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the quadratic formula to find the zeros and verify using } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &\\text{Given polynomial: } 5x^2 - 5x + 2 \\\\ &\\text{Quadratic formula: } x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ &a = 5, \\quad b = -5, \\quad c = 2 \\\\ &\\implies x = \\frac{-(-5) \\pm \\sqrt{(-5)^2 - 4 \\cdot 5 \\cdot 2}}{2 \\cdot 5} \\\\ &\\implies x = \\frac{5 \\pm \\sqrt{25 - 40}}{10} \\\\ &\\implies x = \\frac{5 \\pm \\sqrt{-15}}{10} \\\\ &\\text{Zeros are complex: } \\frac{5 \\pm i\\sqrt{15}}{10} \\\\ &\\text{Sum of zeros } (\\alpha + \\beta) = \\frac{5}{10} = \\frac{1}{2} \\\\ &\\text{Product of zeros } (\\alpha \\beta) = \\frac{5}{10} = \\frac{1}{2} \\\\ &\\therefore \\text{Sum and product verify } \\alpha + \\beta = -\\frac{b}{a}, \\alpha \\beta = \\frac{c}{a} \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\frac{5 \\pm i\\sqrt{15}}{10} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &\\frac{5 \\pm \\sqrt{15}}{10} \\end{aligned}'}],
  'dr1': [{'content': '\\begin{aligned} &\\text{Confused the imaginary part, forgetting the } i \\text{ in the complex zeros.} \\end{aligned}'}],
  'option2': [{'content': '\\begin{aligned} &\\frac{5 \\pm i\\sqrt{5}}{10} \\end{aligned}'}],
  'dr2': [{'content': '\\begin{aligned} &\\text{Misunderstood the discriminant calculation, using } \\sqrt{5} \\text{ instead of } \\sqrt{15}. \\end{aligned}'}],
  'option3': [{'content': '\\begin{aligned} &\\frac{5 \\pm i\\sqrt{10}}{10} \\end{aligned}'}],
  'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the correct discriminant value, mistakenly using } \\sqrt{10}. \\end{aligned}'}]},
 {'topic_id': '10_mathematics_polynomials_3',
  'topic_name': 'Relationship between zeros and coefficients of a polynomial',
  'grade': '10',
  'board': 'CBSE',
  'subject': 'mathematics',
  'chapter_name': 'Polynomials',
  'publication': 'rsagarwal',
  'question': [{'content': '\\begin{aligned} &\\text{What are the zeros of the quadratic polynomial} \\quad x^{2}-7 \\quad \\text{and how do they relate to the coefficients?} \\end{aligned}'}],
  'hint': [{'content': '\\begin{aligned} &\\text{Use the formula for finding zeros of a quadratic polynomial and relate them to coefficients} \\end{aligned}'}],
  'solution': [{'content': '\\begin{aligned} &x^2 - 7 = 0 \\\\ &\\implies x^2 = 7 \\\\ &\\implies x = \\pm \\sqrt{7} \\\\ &\\therefore \\text{Zeros are } \\sqrt{7} \\text{ and } -\\sqrt{7} \\\\ &\\text{For } ax^2 + bx + c, \\text{ sum of zeros } = -\\frac{b}{a}, \\text{ product of zeros } = \\frac{c}{a} \\\\ &\\text{Here, } a = 1, b = 0, c = -7 \\\\ &\\text{Sum of zeros } = -\\frac{0}{1} = 0 \\\\ &\\text{Product of zeros } = \\frac{-7}{1} = -7 \\\\ \\end{aligned}'}],
  'final_answer': [{'content': '\\begin{aligned} &\\sqrt{7} \\text{ and } -\\sqrt{7} \\end{aligned}'}],
  'option1': [{'content': '\\begin{aligned} &7 \\text{ and } -7 \\end{aligned}'}],

In [ ]:
sadsafsd

#### Latex Formatting to store in DB

In [29]:
from config import MONGO_URL , DB_NAME

In [30]:
dbCollection = "LatexTest"
client = AsyncIOMotorClient(MONGO_URL)

In [31]:
async def pushToDB(dbContent, subject):
    try:
        db = client[DB_NAME]
        que_collection = db[dbCollection]

        dbContent["status"] = "not_reviewed"
        dbContent["comment"] = ""
        dbContent["testFlag"] = "true"
        dbContent["subject"] = subject
        await que_collection.insert_one(dbContent)
        print("Data Uploaded to the database successfully.")
    except Exception as e:
        print("Exception Occurred: ", type(e).__name__, "–", e, "\n", traceback.format_exc())

In [32]:
for doc in final_output:
    await pushToDB(doc, subject)
client.close()

Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.
Data Uploaded to the database successfully.

In [ ]:
with open('defaultConf.json', 'r') as f:
    conf_data = json.load(f)

conf_data

{'publication': 'arihant',
 'grade': '10',
 'subject': 'mathematics',
 'term': '1',
 'chapter_name': 'Pair of Linear Equations in Two Variables'}

In [ ]:
dbCollection = "LatexTest"
client = AsyncIOMotorClient(MONGO_URL)

In [ ]:
async def getFromDB():
    try:
        db = client[DB_NAME]
        que_collection = db[dbCollection]
        res = await que_collection.find({"grade": conf_data['grade'], "subject": conf_data['subject'], "chapter_name": conf_data['chapter_name']}).to_list(length=10000)
        return res
    except Exception as e:
        print("Exception Occurred: ", type(e).__name__, "–", e, "\n", traceback.format_exc())

In [ ]:
questionsList = await getFromDB()
client.close()

In [ ]:
len(questionsList)

187

In [ ]:
questionsList[-1]

{'_id': ObjectId('67a310140b8be3d67104e8ab'),
 'topic_id': '10_mathematics_pair of linear equations in two variables_1',
 'topic_name': 'Introduction of linear pair of equations',
 'grade': '10',
 'board': 'CBSE',
 'subject': 'mathematics',
 'chapter_name': 'Pair of Linear Equations in Two Variables',
 'publication': 'mtg',
 'question': [{'content': '\\begin{aligned} &\\text{Which of the following statements is true about the lines } x=3 \\text{ and } y=4 \\text{?} \\\\ &\\text{(A) They are parallel to the } y\\text{-axis and } x\\text{-axis respectively.} \\\\ &\\text{(B) They will intersect at a point.} \\\\ &\\text{(C) They are the same line.} \\\\ &\\text{(D) They are perpendicular to each other.} \\end{aligned}'}],
 'hint': [{'content': '\\begin{aligned} &\\text{Identify the orientation of the lines } x=3 \\text{ and } y=4 \\text{ on the coordinate plane.} \\\\ &\\text{Determine their relationship based on their orientation.} \\end{aligned}'}],
 'solution': [{'content': '\\begin{aligned} &\\text{Line } x=3 \\text{ is a vertical line parallel to the } y\\text{-axis.} \\\\ &\\text{Line } y=4 \\text{ is a horizontal line parallel to the } x\\text{-axis.} \\\\ &\\therefore \\text{The lines are perpendicular to each other.} \\\\ &\\text{Correct answer: (D) They are perpendicular to each other.} \\end{aligned}'}],
 'final_answer': [{'content': '\\begin{aligned} &\\text{They are perpendicular to each other.} \\end{aligned}'}],
 'option1': [{'content': '\\begin{aligned} &\\text{They are parallel to the } y\\text{-axis and } x\\text{-axis respectively.} \\end{aligned}'}],
 'dr1': [{'content': '\\begin{aligned} &\\text{Confused the orientation of the lines, thinking both are parallel to axes.} \\end{aligned}'}],
 'option2': [{'content': '\\begin{aligned} &\\text{They will intersect at a point.} \\end{aligned}'}],
 'dr2': [{'content': '\\begin{aligned} &\\text{Forgot that a vertical and a horizontal line intersect at a point.} \\end{aligned}'}],
 'option3': [{'content': '\\begin{aligned} &\\text{They are the same line.} \\end{aligned}'}],
 'dr3': [{'content': '\\begin{aligned} &\\text{Ignored the fact that } x=3 \\text{ and } y=4 \\text{ are distinct lines.} \\end{aligned}'}],
 'status': 'not_reviewed',
 'comment': '',
 'testFlag': 'true',
 'qid': '10647-4'}

In [ ]:
from pydantic import BaseModel, Field

class Question(BaseModel):
    question: str = Field(..., description="Question text", examples=["\\begin{{aligned}} \\text{{Solve given equation}} \\quad x^2 - 4x + 7 = 0. \\end{{aligned}}"])
    qid: int = Field(..., description="Question ID same as provided in input", examples=[224, 8623, 10234])


class SingleCluster(BaseModel):
    cluster1: list[Question]

class Clusters(BaseModel):
    clusters: list[SingleCluster]

Clusters.model_json_schema()

{'$defs': {'Question': {'properties': {'question': {'description': 'Question text',
     'examples': ['\\begin{{aligned}} \\text{{Solve given equation}} \\quad x^2 - 4x + 7 = 0. \\end{{aligned}}'],
     'title': 'Question',
     'type': 'string'},
    'qid': {'description': 'Question ID same as provided in input',
     'examples': [224, 8623, 10234],
     'title': 'Qid',
     'type': 'integer'}},
   'required': ['question', 'qid'],
   'title': 'Question',
   'type': 'object'},
  'SingleCluster': {'properties': {'cluster1': {'items': {'$ref': '#/$defs/Question'},
     'title': 'Cluster1',
     'type': 'array'}},
   'required': ['cluster1'],
   'title': 'SingleCluster',
   'type': 'object'}},
 'properties': {'clusters': {'items': {'$ref': '#/$defs/SingleCluster'},
   'title': 'Clusters',
   'type': 'array'}},
 'required': ['clusters'],
 'title': 'Clusters',
 'type': 'object'}

In [ ]:
questionTopicDict = {}
for i in questionsList:
    if i['topic_id'] in questionTopicDict:
        questionTopicDict[i['topic_id']].append({"question": i['question'], "qid": i['qid']})
    else:
        questionTopicDict[i['topic_id']] = [{"question": i['question'], "qid": i['qid']}]
questionTopicDict

{'10_mathematics_pair of linear equations in two variables_1': [{'question': [{'content': '\\begin{aligned} &\\text{Which of the following represents a linear equation in two variables?} \\end{aligned}'}],
   'qid': '10317-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which equation describes the relationship between the number of bags } x, \\\\ &\\text{and the number of baskets, } y \\text{?} \\end{aligned}'}],
   'qid': '10319-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of these pairs of equations is equivalent to the given pair of equations?} \\\\ \\end{aligned}'}],
   'qid': '10331-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{What are the possible values of } \\quad x \\quad \\text{and} \\quad y \\quad \\text{in the given equation?} \\end{aligned}'}],
   'qid': '10331-2'},
  {'question': [{'content': '\\begin{aligned} &\\text{What do the variables } \\quad x \\quad \\text{and} \\quad y \\quad \\text{symbolize in the context of the equation?} \\end{aligned}'}],
   'qid': '10319-2'},
  {'question': [{'content': '\\begin{aligned} &\\text{Substitute the variables } \\quad x \\quad \\text{and} \\quad y \\quad \\text{with words and explain the meaning of the equation.} \\end{aligned}'}],
   'qid': '10319-3'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which has a greater quantity: bags of raisins or bags of nuts? Justify your answer.} \\end{aligned}'}],
   'qid': '10319-4'},
  {'question': [{'content': '\\begin{aligned} &\\text{Can you find any values for } \\quad x \\quad \\text{and} \\quad y \\quad \\text{that satisfy the initial equation?} \\end{aligned}'}],
   'qid': '10331-3'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which values of } x \\quad \\text{and} \\quad y \\quad \\text{can be used to verify the second equation?} \\end{aligned}'}],
   'qid': '10331-4'},
  {'question': [{'content': '\\begin{aligned} &\\text{What is the reason for selecting these specific values for } x \\quad \\text{and} \\quad y \\quad \\text{?} \\end{aligned}'}],
   'qid': '10331-5'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which method can be used to verify the correctness of your solution?} \\end{aligned}'}],
   'qid': '10331-6'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which linear equation represents the condition if Akhila spends } \\\\ &\\text{₹ 20 on rides costing ₹ 3 each and hoopla games costing ₹ 4 each?} \\end{aligned}'}],
   'qid': '10317-2'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of the following represents the pair of linear equations } 3x - 4y - 10 = 0, 9y + 18 = 6x \\text{?} \\end{aligned}'}],
   'qid': '10319-5'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the difference between two numbers is 30 and one number is four times the other, what are the numbers?} \\end{aligned}'}],
   'qid': '10319-6'},
  {'question': [{'content': '\\begin{aligned} &\\text{What are the values of } x \\text{ and } y \\text{ for the linear equations } \\quad 41x + 53y = 135 \\\\ &\\text{and } \\quad 53x + 41y = 147 \\text{?} \\end{aligned}'}],
   'qid': '10331-7'},
  {'question': [{'content': '\\begin{aligned} &\\text{If } x = a \\text{ and } y = b \\text{ is the solution to the equations } \\quad x - y = 2 \\\\ &\\text{and } \\quad x + y = 4, \\text{ what are the values of } a \\text{ and } b \\text{?} \\end{aligned}'}],
   'qid': '10331-8'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the angles of a triangle are } x, y \\text{ and } 40^{\\circ} \\text{, and the difference between } \\\\ &\\text{angles } x \\text{ and } y \\text{ is } 30^{\\circ}, \\text{ what are the values of } x \\text{ and } y \\text{?} \\end{aligned}'}],
   'qid': '10331-9'},
  {'question': [{'content': "\\begin{aligned} &\\text{A train travels a certain distance at a constant speed. If the train's speed was increased by } \\quad 12 \\mathrm{~km} / \\mathrm{h}, \\text{ it would take 2 hours less than the scheduled time.} \\\\ &\\text{If the speed was decreased by } 12 \\mathrm{~km} / \\mathrm{h}, \\text{ it would take 3 hours more than the scheduled time.} \\\\ &\\text{What is the distance covered by the train?} \\end{aligned}"}],
   'qid': '10319-7'},
  {'question': [{'content': '\\begin{aligned} &\\text{Read the Assertion (A) and Reason (R) statements carefully and choose the correct option:} \\\\ &\\text{Assertion (A): The value of } q= \\pm 3, \\text{ if } x=4, y=2 \\text{ is the solution of the line } 2x+y-q^{2}-4=0. \\\\ &\\text{Reason (R): The solution of the line will satisfy the equation of the line.} \\end{aligned}'}],
   'qid': '10331-10'},
  {'question': [{'content': '\\begin{aligned} &\\text{What is the fare from Rajiv Chowk to Karol Bagh?} \\end{aligned}'}],
   'qid': '10405-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{What is the fare from Rajiv Chowk to Hauz Khas?} \\end{aligned}'}],
   'qid': '10405-2'},
  {'question': [{'content': "\\begin{aligned} &\\text{A test consists of 'True' or 'False' questions. One mark is awarded for every correct answer while} \\\\ &\\frac{1}{4} \\text{ mark is deducted for every wrong answer. A student knew answers to some of the questions.} \\\\ &\\text{Rest of the questions he attempted by guessing. He answered 150 questions and got 110 marks.} \\\\ &\\text{How many questions did he answer correctly?} \\end{aligned}"}],
   'qid': '10408-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{If all the questions he guessed were incorrect, how many questions did he answer correctly?} \\end{aligned}'}],
   'qid': '10408-2'},
  {'question': [{'content': '\\begin{aligned} &\\text{How many questions did the student guess if he answered 150 questions in total?} \\end{aligned}'}],
   'qid': '10408-3'},
  {'question': [{'content': '\\begin{aligned} &\\text{If all the questions he guessed were incorrect and he answered 90 correctly, how many marks did he obtain?} \\end{aligned}'}],
   'qid': '10408-4'},
  {'question': [{'content': '\\begin{aligned} &\\text{If all the questions he guessed were incorrect, how many questions did he answer correctly to score 100 marks?} \\end{aligned}'}],
   'qid': '10408-5'},
  {'question': [{'content': '\\begin{aligned} &\\text{If a student answered all questions incorrectly except for 90, how many marks did he receive?} \\end{aligned}'}],
   'qid': '10408-6'},
  {'question': [{'content': '\\begin{aligned} &\\text{If there are 15 guests at the dinner party, what amount does Mr. Jayant need to pay?} \\end{aligned}'}],
   'qid': '10319-8'},
  {'question': [{'content': '\\begin{aligned} &\\text{Amit is planning to buy a house, and the layout is given below. The design and the measurement are such that the areas of two bedrooms and the kitchen together is 120 sq m. Based on the above information, answer the following questions:} \\end{aligned}'}],
   'qid': '10319-9'},
  {'question': [{'content': '\\begin{aligned} &\\text{Create the pair of linear equations in two variables from this situation.} \\end{aligned}'}],
   'qid': '10319-10'},
  {'question': [{'content': '\\begin{aligned} &\\text{Calculate the length of the outer boundary of the layout.} \\end{aligned}'}],
   'qid': '10319-11'},
  {'question': [{'content': '\\begin{aligned} & \\text{Which of the following equations represents the situation if the number of children is } \\quad x \\quad \\text{and the number of adults is } \\quad y \\quad \\text{?} \\end{aligned}'}],
   'qid': '10317-3'},
  {'question': [{'content': '\\begin{aligned} & \\text{What is the total number of children who visited the amusement park on that day?} \\end{aligned}'}],
   'qid': '10319-12'},
  {'question': [{'content': '\\begin{aligned} & \\text{What is the total number of adults who visited the amusement park on that day?} \\end{aligned}'}],
   'qid': '10319-13'},
  {'question': [{'content': '\\begin{aligned} & \\text{Calculate the total amount collected if 300 children and 150 adults visit the amusement park.} \\end{aligned}'}],
   'qid': '10319-14'},
  {'question': [{'content': '\\begin{aligned} & \\text{Which algebraic expression represents the given information in terms of } \\quad x \\quad \\text{and } \\quad y \\quad \\text{?} \\end{aligned}'}],
   'qid': '10319-15'},
  {'question': [{'content': '\\begin{aligned} & \\text{What is the prize amount awarded for the game of hockey?} \\end{aligned}'}],
   'qid': '10319-16'},
  {'question': [{'content': '\\begin{aligned} & \\text{Which game has a higher prize amount and by what difference?} \\end{aligned}'}],
   'qid': '10319-17'},
  {'question': [{'content': '\\begin{aligned} & \\text{Calculate the total prize amount if there are two participants from each of two games.} \\end{aligned}'}],
   'qid': '10319-18'},
  {'question': [{'content': '\\begin{aligned} & \\text{How many lines are there in the blue wheel of the Indian National flag if one student says it is 8 times the number of colors in the flag,} \\\\ & \\text{and another says the sum of the number of colors and lines is 27? Convert these statements into a linear equation and find the number of lines.} \\end{aligned}'}],
   'qid': '10319-19'},
  {'question': [{'content': '\\begin{aligned} & \\text{Which of the following points lies on the line } \\quad 3x - 4y = 6 \\text{?} \\end{aligned}'}],
   'qid': '10647-1'},
  {'question': [{'content': '\\begin{aligned} & \\text{Which of the following represents the equation of the line } \\quad k_{5} \\text{?} \\end{aligned}'}],
   'qid': '10317-5'},
  {'question': [{'content': '\\begin{aligned} & \\text{If Heena took 2 minutes more than Kimaya to reach her destination, what is the time taken by Heena to reach the badminton court?} \\end{aligned}'}],
   'qid': '10319-20'},
  {'question': [{'content': '\\begin{aligned} & \\text{Which equation represents one of the lines from the given pair of linear equations?} \\end{aligned}'}],
   'qid': '10331-11'},
  {'question': [{'content': '\\begin{aligned} & \\text{What is the two-digit number if the sum of the number and the number obtained by reversing its digits is 66,} \\\\ & \\text{and the digits differ by 2? How many such numbers exist?} \\end{aligned}'}],
   'qid': '10319-21'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the larger angle is } x^{\\circ} \\text{ and the smaller angle is } y^{\\circ}, \\text{ what is the equation representing their sum if they are supplementary?} \\end{aligned}'}],
   'qid': '10319-22'},
  {'question': [{'content': "\\begin{aligned} &\\text{If Rashmi's current age is } x \\text{ years and Nazma's current age is } y \\text{ years, what equation can represent their ages?} \\end{aligned}"}],
   'qid': '10319-23'},
  {'question': [{'content': '\\begin{aligned} &\\text{If } x \\text{ Litres of } 50\\% \\text{ acid solution is mixed with } y \\text{ Litres of } 25\\% \\text{ acid solution, what equation represents the mixture?} \\end{aligned}'}],
   'qid': '10319-24'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the ages of two children are } x \\text{ years and } y \\text{ years respectively, what equation can represent their ages?} \\end{aligned}'}],
   'qid': '10319-25'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the speed of person 1 is } x \\mathrm{~km/h} \\text{ and the speed of person 2 is } y \\mathrm{~km/h} \\text{ with } x > y, \\text{ what equation represents their speeds?} \\end{aligned}'}],
   'qid': '10319-26'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of the following equations represents the given linear equation?} \\\\ &217x + 131y = 913 \\end{aligned}'}],
   'qid': '10317-4'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of the following represents the fraction } \\frac{x}{y}? \\end{aligned}'}],
   'qid': '10687-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the present age of a son is } x \\text{ years and that of the father is } y \\text{ years, which of the following is correct?} \\end{aligned}'}],
   'qid': '10319-27'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the ages of two children are } x \\text{ and } y \\text{ respectively, which of the following statements is true?} \\end{aligned}'}],
   'qid': '10319-28'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of the following represents the fraction } \\quad \\frac{a}{b} \\quad \\text{correctly?} \\end{aligned}'}],
   'qid': '10687-2'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the monthly fixed charges are } ₹ a \\text{ and the cost of food per day is } ₹ b, \\\\ &\\text{which of the following equations represents the total monthly cost?} \\end{aligned}'}],
   'qid': '10317-6'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the cost of a chair is } ₹ a \\text{ and the cost of a table is } ₹ b, \\\\ &\\text{which equation represents the total cost of } n \\text{ chairs and } m \\text{ tables?} \\end{aligned}'}],
   'qid': '10317-7'},
  {'question': [{'content': '\\begin{aligned} &\\text{Given the ticket charges for the park are } ₹ 160 \\text{ per child and } ₹ 260 \\text{ per adult,} \\\\ &\\text{which equation represents the total cost for } c \\text{ children and } a \\text{ adults?} \\end{aligned}'}],
   'qid': '10317-8'},
  {'question': [{'content': '\\begin{aligned} &\\text{What is the total cost for student A if the fixed charges and cost of food for 30 days is } \\quad ₹ 5000 \\text{?} \\end{aligned}'}],
   'qid': '10319-33'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the income of the first person is } 8x \\text{ and the income of the second person is } 6x, \\quad \\text{what are their expenditures if the first and second persons spend } 5y \\text{ and } 4y \\text{ respectively?} \\end{aligned}'}],
   'qid': '10319-29'},
  {'question': [{'content': '\\begin{aligned} &\\text{If a number has a tens digit } a \\text{ and a ones digit } b, \\quad \\text{what is the number represented as } 10a + b \\text{?} \\end{aligned}'}],
   'qid': '10319-30'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the number of colours in a flag is } x \\text{ and the number of lines in the blue colour wheel is } y, \\quad \\text{what is the equation relating them if } 9x = y \\text{?} \\end{aligned}'}],
   'qid': '10319-31'},
  {'question': [{'content': '\\begin{aligned} &\\text{What are the speeds of cars at points A and B if the speed at A is } u \\text{ km/h and at B is } v \\text{ km/h?} \\end{aligned}'}],
   'qid': '10319-32'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of the following points lies on the line } \\quad 3x + 4y = 12 \\text{?} \\end{aligned}'}],
   'qid': '10647-2'},
  {'question': [{'content': '\\begin{aligned} &\\text{What is the } y\\text{-intercept of the line } \\quad 5x + 2y = 10 \\text{?} \\end{aligned}'}],
   'qid': '10647-3'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of the following statements is true about the lines } x=3 \\text{ and } y=4 \\text{?} \\\\ &\\text{(A) They are parallel to the } y\\text{-axis and } x\\text{-axis respectively.} \\\\ &\\text{(B) They will intersect at a point.} \\\\ &\\text{(C) They are the same line.} \\\\ &\\text{(D) They are perpendicular to each other.} \\end{aligned}'}],
   'qid': '10647-4'}],
 '10_mathematics_pair of linear equations in two variables_2': [{'question': [{'content': '\\begin{aligned} &\\text{If } x^{3n}-1+y^{m-3}=0 \\text{ is a linear equation, which of these is also a linear equation?} \\end{aligned}'}],
   'qid': '10318-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of these linear equations has a unique solution?} \\end{aligned}'}],
   'qid': '10318-2'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of these statements is true about the given equations?} \\\\ \\end{aligned}'}],
   'qid': '10318-3'},
  {'question': [{'content': '\\begin{aligned} &\\text{On comparing the coefficients, a student claims these pairs of equations are consistent.} \\\\ &\\text{Is the student correct? Which of these explains why?} \\\\ \\end{aligned}'}],
   'qid': '10318-4'},
  {'question': [{'content': '\\begin{aligned} &\\text{If there are 7 bags of nuts, so } x=7, \\quad \\text{how many bags of raisins are there according to the first equation?} \\end{aligned}'}],
   'qid': '10339-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{According to the second equation, how many bags of raisins are there?} \\end{aligned}'}],
   'qid': '10339-2'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of the following systems of equations has infinitely many solutions?} \\\\ &3x - y = 3, \\\\ &9x - 3y = 9 \\\\ \\end{aligned}'}],
   'qid': '10318-5'},
  {'question': [{'content': '\\begin{aligned} &\\text{Without graphing, determine the nature of the pair of linear equations:} \\\\ &3x - 5y + 8 = 0, \\\\ &7x + 6y - 9 = 0 \\\\ \\end{aligned}'}],
   'qid': '10318-6'},
  {'question': [{'content': '\\begin{aligned} &\\text{If a pair of linear equations is consistent, what can be said about the lines?} \\\\ \\end{aligned}'}],
   'qid': '10318-7'},
  {'question': [{'content': '\\begin{aligned} &\\text{Read the Assertion (A) and Reason (R) statements carefully and choose the correct option:} \\\\ &\\text{Assertion (A): If } \\frac{a_{1}}{a_{2}} = \\frac{b_{1}}{b_{2}} \\neq \\frac{c_{1}}{c_{2}}, \\text{ then the pair of linear equations is consistent.} \\\\ &\\text{Reason (R): The lines represented by the equations are parallel.} \\\\ \\end{aligned}'}],
   'qid': '10352-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of the following pairs of equations are parallel, indicating no solution?} \\end{aligned}'}],
   'qid': '10318-8'},
  {'question': [{'content': '\\begin{aligned} &\\text{Identify the pair of equations that are inconsistent.} \\end{aligned}'}],
   'qid': '10318-9'},
  {'question': [{'content': '\\begin{aligned} &\\text{Which of the following describes the relationship between the equations } \\\\ &x + 2y + 5 = 0 \\\\ &\\text{and } -3x - 6y + 1 = 0? \\end{aligned}'}],
   'qid': '10318-10'},
  {'question': [{'content': '\\begin{aligned} &\\text{If one equation of a pair of dependent linear equations is } \\\\ &-5x + 7y - 2 = 0, \\\\ &\\text{which of the following could be the second equation?} \\end{aligned}'}],
   'qid': '10318-11'},
  {'question': [{'content': '\\begin{aligned} &\\text{What is the value of } k \\text{ for which the system of linear equations } \\\\ &x + 2y = 3, \\\\ &5x + ky + 7 = 0 \\text{ is inconsistent?} \\end{aligned}'}],
   'qid': '10361-1'},
  {'question': [{'content': '\\begin{aligned} &\\text{Determine the value of } k \\text{ for which the system of equations } \\\\ &kx - 5y = 2; \\\\ &6x + 2y = 7 \\text{ has no solution.} \\end{aligned}'}],
   'qid': '10361-2'},
  {'question': [{'content': '\\begin{aligned} &\\text{What is the value of } \\quad k \\quad \\text{for which the system of equations} \\\\ &3x + 4y = 5 \\quad \\text{and} \\quad (k+3)x + 8y = 3k + 5 \\quad \\text{has infinitely many solutions?} \\end{aligned}'}],
   'qid': '10361-3'},
  {'question': [{'content': '\\begin{aligned} &\\text{If the lines represented by } \\quad 4x + 3ky = 3 \\quad \\text{and} \\quad 3x + 7y = 2 \\quad \\text{are parallel, what is the value of } \\quad k \\quad \\text{?} \\end{aligned}'}],
   'qid': '10361-4'},
  {'question': [{'content': '\\begin{aligned} &\\text{Determine the value of } \\quad p \\quad \\text{such that the equations} \\\\ &-2x + py = 3 \\quad \\text{and} \\quad px - 2y = 3 \\quad \\text{represent parallel lines.} \\end{aligned}'}],
   'qid': '10361-5'},
  {'question': [{'content': '\\begin{aligned} &\\text{Find the value of } \\quad a \\quad \\text{for which the lines} \\\\ &x = 1, \\quad y = 2, \\quad \\text{and} \\quad a^{2}x + 3y - 25 = 0 \\quad \\text{are concurrent.} \\end{aligned}'}],
   'qid': '10361-6'},

In [ ]:
list(questionTopicDict.keys())

['10_mathematics_pair of linear equations in two variables_1',
 '10_mathematics_pair of linear equations in two variables_2',
 '10_mathematics_pair of linear equations in two variables_4',
 '10_mathematics_pair of linear equations in two variables_3']

In [ ]:
len(questionTopicDict['10_mathematics_pair of linear equations in two variables_1'])

66

In [ ]:
system_cluster_prompt = """
You are an academic expert who is responsible for clustering similar questions based on different parameters.

## FOLLOW THESE INSTRUCTIONS TO CLUSTER THE QUESTIONS:
    - Read and Understand Each Question: First, carefully analyze each question. Think about its key concept, context, or content.
    - Identify Common Patterns: Next, consider which questions share similar content/context, whether they are asking about the same learning unit, are related to the same topic, or have same structure.
    - Identify and Group Similar Questions: Based on the identified patterns, identify similar questions.
    - Reflect on Your Choices: After grouping, double-check to ensure that questions in the same group are closely related and that no questions have been misplaced.
    - No question should be lost or repeated in the output.
    - Always return all the given questions clustered into groups in the specified JSON format.

###OUTPUT INSTRUCTIONS###:
- Return same question and qid after grouping. Do not change any question or text, just cluster them according to the above criteria.

Return your output in the following json format:
'''
{
  "clusters": [
    {
      "cluster1": [
        {
          "qid": "qid of the question",
          "question": "whole content of the question"
        },
      ]
    },
  ]
}
'''
"""

user_cluster_prompt = """
Group all the questions into different clusters based on their similarity, content, and context behind the question. You will be provided a list of questions with their qid(i.e. question id).

## Input:
List of questions with their qid/s: {questions_input}

Please follow this thought process:
- Read through each question carefully.
- Identify the context, structure or concept within each question.
- Group the questions that share similar concept, context or structure.
- Reflect on your choices and make sure questions are grouped logically.
- Please reason through each step clearly as you perform the clustering.
"""

In [ ]:
from openai import OpenAI
def generateUsingOpenAI(system, user):
    client = OpenAI()
    #generating response from api call
    response = client.beta.chat.completions.parse(
        model = "o3-mini-2025-01-31",
        messages = [
            {"role":"system", "content": system},
            {"role" :"user", "content": user}
        ],
    )
    return response

In [ ]:
topic_ids = list(questionTopicDict.keys())
topic_ids

['10_mathematics_pair of linear equations in two variables_1',
 '10_mathematics_pair of linear equations in two variables_2',
 '10_mathematics_pair of linear equations in two variables_4',
 '10_mathematics_pair of linear equations in two variables_3']

In [ ]:
totalClustering = {}
topic_ids = list(questionTopicDict.keys())
for topic_id in topic_ids:
    print("Processing topic: ", topic_id)
    user = user_cluster_prompt.format(questions_input=questionTopicDict[topic_id])

    #generating response
    raw_response = generateUsingOpenAI(system_cluster_prompt, user)
    parsed_resp = parse_Response(raw_response.choices[0].message.content)
    if parsed_resp:
        totalClustering[topic_id] = parsed_resp['clusters']
        print("Generated response", raw_response, '\n\n')
    else:
        print("Error in response generation: ", raw_response, '\n\n')

Processing topic:  10_mathematics_pair of linear equations in two variables_1
Generated response ParsedChatCompletion[NoneType](id='chatcmpl-AyAphDIFkUmV0DCVnbMXiw6CWuLEL', choices=[ParsedChoice[NoneType](finish_reason='stop', index=0, logprobs=None, message=ParsedChatCompletionMessage[NoneType](content='{\n  "clusters": [\n    {\n      "cluster1": [\n        {\n          "qid": "10317-1",\n          "question": "\\\\begin{aligned} &\\\\text{Which of the following represents a linear equation in two variables?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10317-2",\n          "question": "\\\\begin{aligned} &\\\\text{Which linear equation represents the condition if Akhila spends } \\\\\\\\ &\\\\text{₹ 20 on rides costing ₹ 3 each and hoopla games costing ₹ 4 each?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10317-3",\n          "question": "\\\\begin{aligned} & \\\\text{Which of the following equations represents the pair of linear equations } 3x - 4y - 10 = 0, 9y + 18 = 6x \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10317-4",\n          "question": "\\\\begin{aligned} &\\\\text{Which of the following represents the given linear equation?} \\\\\\\\ &217x + 131y = 913 \\\\end{aligned}"\n        },\n        {\n          "qid": "10317-5",\n          "question": "\\\\begin{aligned} &\\\\text{Which of the following represents the equation of the line } \\\\quad k_{5} \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10317-6",\n          "question": "\\\\begin{aligned} &\\\\text{If the monthly fixed charges are } ₹ a \\\\text{ and the cost of food per day is } ₹ b, \\\\\\\\ &\\\\text{which of the following equations represents the total monthly cost?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10317-7",\n          "question": "\\\\begin{aligned} &\\\\text{If the cost of a chair is } ₹ a \\\\text{ and the cost of a table is } ₹ b, \\\\\\\\ &\\\\text{which equation represents the total cost of } n \\\\text{ chairs and } m \\\\text{ tables?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10317-8",\n          "question": "\\\\begin{aligned} &\\\\text{Given the ticket charges for the park are } ₹ 160 \\\\text{ per child and } ₹ 260 \\\\text{ per adult,} \\\\\\\\ &\\\\text{which equation represents the total cost for } c \\\\text{ children and } a \\\\text{ adults?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-5",\n          "question": "\\\\begin{aligned} &\\\\text{Which of the following represents the pair of linear equations } 3x - 4y - 10 = 0, 9y + 18 = 6x \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-15",\n          "question": "\\\\begin{aligned} & \\\\text{Which algebraic expression represents the given information in terms of } \\\\quad x \\\\quad \\\\text{and } \\\\quad y \\\\quad \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10687-1",\n          "question": "\\\\begin{aligned} &\\\\text{Which of the following represents the fraction } \\\\frac{x}{y}? \\\\end{aligned}"\n        },\n        {\n          "qid": "10687-2",\n          "question": "\\\\begin{aligned} &\\\\text{Which of the following represents the fraction } \\\\quad \\\\frac{a}{b} \\\\quad \\\\text{correctly?} \\\\end{aligned}"\n        }\n      ]\n    },\n    {\n      "cluster2": [\n        {\n          "qid": "10319-1",\n          "question": "\\\\begin{aligned} &\\\\text{Which equation describes the relationship between the number of bags } x, \\\\\\\\ &\\\\text{and the number of baskets, } y \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-2",\n          "question": "\\\\begin{aligned} &\\\\text{What do the variables } \\\\quad x \\\\quad \\\\text{and} \\\\quad y \\\\quad \\\\text{symbolize in the context of the equation?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-3",\n          "question": "\\\\begin{aligned} &\\\\text{Substitute the variables } \\\\quad x \\\\quad \\\\text{and} \\\\quad y \\\\quad \\\\text{with words and explain the meaning of the equation.} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-4",\n          "question": "\\\\begin{aligned} &\\\\text{Which has a greater quantity: bags of raisins or bags of nuts? Justify your answer.} \\\\end{aligned}"\n        }\n      ]\n    },\n    {\n      "cluster3": [\n        {\n          "qid": "10331-1",\n          "question": "\\\\begin{aligned} &\\\\text{Which of these pairs of equations is equivalent to the given pair of equations?} \\\\\\\\ \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-2",\n          "question": "\\\\begin{aligned} &\\\\text{What are the possible values of } \\\\quad x \\\\quad \\\\text{and} \\\\quad y \\\\quad \\\\text{in the given equation?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-3",\n          "question": "\\\\begin{aligned} &\\\\text{Can you find any values for } \\\\quad x \\\\quad \\\\text{and} \\\\quad y \\\\quad \\\\text{that satisfy the initial equation?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-4",\n          "question": "\\\\begin{aligned} &\\\\text{Which values of } x \\\\quad \\\\text{and} \\\\quad y \\\\quad \\\\text{can be used to verify the second equation?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-5",\n          "question": "\\\\begin{aligned} &\\\\text{What is the reason for selecting these specific values for } x \\\\quad \\\\text{and} \\\\quad y \\\\quad \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-6",\n          "question": "\\\\begin{aligned} &\\\\text{Which method can be used to verify the correctness of your solution?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-7",\n          "question": "\\\\begin{aligned} &\\\\text{What are the values of } x \\\\text{ and } y \\\\text{ for the linear equations } \\\\quad 41x + 53y = 135 \\\\\\\\ &\\\\text{and } \\\\quad 53x + 41y = 147 \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-8",\n          "question": "\\\\begin{aligned} &\\\\text{If } x = a \\\\text{ and } y = b \\\\text{ is the solution to the equations } \\\\quad x - y = 2 \\\\\\\\ &\\\\text{and } \\\\quad x + y = 4, \\\\text{ what are the values of } a \\\\text{ and } b \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-9",\n          "question": "\\\\begin{aligned} &\\\\text{If the angles of a triangle are } x, y \\\\text{ and } 40^{\\\\circ} \\\\text{, and the difference between } \\\\\\\\ &\\\\text{angles } x \\\\text{ and } y \\\\text{ is } 30^{\\\\circ}, \\\\text{ what are the values of } x \\\\text{ and } y \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-10",\n          "question": "\\\\begin{aligned} &\\\\text{Read the Assertion (A) and Reason (R) statements carefully and choose the correct option:} \\\\\\\\ &\\\\text{Assertion (A): The value of } q= \\\\pm 3, \\\\text{ if } x=4, y=2 \\\\text{ is the solution of the line } 2x+y-q^{2}-4=0. \\\\\\\\ &\\\\text{Reason (R): The solution of the line will satisfy the equation of the line.} \\\\end{aligned}"\n        },\n        {\n          "qid": "10331-11",\n          "question": "\\\\begin{aligned} &\\\\text{Which equation represents one of the lines from the given pair of linear equations?} \\\\end{aligned}"\n        }\n      ]\n    },\n    {\n      "cluster4": [\n        {\n          "qid": "10319-6",\n          "question": "\\\\begin{aligned} &\\\\text{If the difference between two numbers is 30 and one number is four times the other, what are the numbers?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-7",\n          "question": "\\\\begin{aligned} &\\\\text{A train travels a certain distance at a constant speed. If the train\'s speed was increased by } \\\\quad 12 \\\\mathrm{~km} / \\\\mathrm{h}, \\\\text{ it would take 2 hours less than the scheduled time.} \\\\\\\\ &\\\\text{If the speed was decreased by } 12 \\\\mathrm{~km} / \\\\mathrm{h}, \\\\text{ it would take 3 hours more than the scheduled time.} \\\\\\\\ &\\\\text{What is the distance covered by the train?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-8",\n          "question": "\\\\begin{aligned} &\\\\text{If there are 15 guests at the dinner party, what amount does Mr. Jayant need to pay?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-9",\n          "question": "\\\\begin{aligned} &\\\\text{Amit is planning to buy a house, and the layout is given below. The design and the measurement are such that the areas of two bedrooms and the kitchen together is 120 sq m. Based on the above information, answer the following questions:} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-10",\n          "question": "\\\\begin{aligned} &\\\\text{Create the pair of linear equations in two variables from this situation.} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-11",\n          "question": "\\\\begin{aligned} &\\\\text{Calculate the length of the outer boundary of the layout.} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-12",\n          "question": "\\\\begin{aligned} & \\\\text{What is the total number of children who visited the amusement park on that day?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-13",\n          "question": "\\\\begin{aligned} & \\\\text{What is the total number of adults who visited the amusement park on that day?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-14",\n          "question": "\\\\begin{aligned} & \\\\text{Calculate the total amount collected if 300 children and 150 adults visit the amusement park.} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-16",\n          "question": "\\\\begin{aligned} & \\\\text{What is the prize amount awarded for the game of hockey?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-17",\n          "question": "\\\\begin{aligned} & \\\\text{Which game has a higher prize amount and by what difference?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-18",\n          "question": "\\\\begin{aligned} & \\\\text{Calculate the total prize amount if there are two participants from each of two games.} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-19",\n          "question": "\\\\begin{aligned} & \\\\text{How many lines are there in the blue wheel of the Indian National flag if one student says it is 8 times the number of colors in the flag,} \\\\\\\\ & \\\\text{and another says the sum of the number of colors and lines is 27? Convert these statements into a linear equation and find the number of lines.} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-20",\n          "question": "\\\\begin{aligned} & \\\\text{If Heena took 2 minutes more than Kimaya to reach her destination, what is the time taken by Heena to reach the badminton court?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-21",\n          "question": "\\\\begin{aligned} & \\\\text{What is the two-digit number if the sum of the number and the number obtained by reversing its digits is 66,} \\\\\\\\ & \\\\text{and the digits differ by 2? How many such numbers exist?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-22",\n          "question": "\\\\begin{aligned} &\\\\text{If the larger angle is } x^{\\\\circ} \\\\text{ and the smaller angle is } y^{\\\\circ}, \\\\text{ what is the equation representing their sum if they are supplementary?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-23",\n          "question": "\\\\begin{aligned} &\\\\text{If Rashmi\'s current age is } x \\\\text{ years and Nazma\'s current age is } y \\\\text{ years, what equation can represent their ages?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-24",\n          "question": "\\\\begin{aligned} &\\\\text{If } x \\\\text{ Litres of } 50\\\\% \\\\text{ acid solution is mixed with } y \\\\text{ Litres of } 25\\\\% \\\\text{ acid solution, what equation represents the mixture?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-25",\n          "question": "\\\\begin{aligned} &\\\\text{If the ages of two children are } x \\\\text{ years and } y \\\\text{ years respectively, what equation can represent their ages?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-26",\n          "question": "\\\\begin{aligned} &\\\\text{If the speed of person 1 is } x \\\\mathrm{~km/h} \\\\text{ and the speed of person 2 is } y \\\\mathrm{~km/h} \\\\text{ with } x > y, \\\\text{ what equation represents their speeds?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-27",\n          "question": "\\\\begin{aligned} &\\\\text{If the present age of a son is } x \\\\text{ years and that of the father is } y \\\\text{ years, which of the following is correct?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-28",\n          "question": "\\\\begin{aligned} &\\\\text{If the ages of two children are } x \\\\text{ and } y \\\\text{ respectively, which of the following statements is true?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-29",\n          "question": "\\\\begin{aligned} &\\\\text{If the income of the first person is } 8x \\\\text{ and the income of the second person is } 6x, \\\\quad \\\\text{what are their expenditures if the first and second persons spend } 5y \\\\text{ and } 4y \\\\text{ respectively?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-30",\n          "question": "\\\\begin{aligned} &\\\\text{If a number has a tens digit } a \\\\text{ and a ones digit } b, \\\\quad \\\\text{what is the number represented as } 10a + b \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-31",\n          "question": "\\\\begin{aligned} &\\\\text{If the number of colours in a flag is } x \\\\text{ and the number of lines in the blue colour wheel is } y, \\\\quad \\\\text{what is the equation relating them if } 9x = y \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-32",\n          "question": "\\\\begin{aligned} &\\\\text{What are the speeds of cars at points A and B if the speed at A is } u \\\\text{ km/h and at B is } v \\\\text{ km/h?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10319-33",\n          "question": "\\\\begin{aligned} &\\\\text{What is the total cost for student A if the fixed charges and cost of food for 30 days is } \\\\quad ₹ 5000 \\\\text{?} \\\\end{aligned}"\n        }\n      ]\n    },\n    {\n      "cluster5": [\n        {\n          "qid": "10647-1",\n          "question": "\\\\begin{aligned} &\\\\text{Which of the following points lies on the line } \\\\quad 3x - 4y = 6 \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10647-2",\n          "question": "\\\\begin{aligned} &\\\\text{Which of the following points lies on the line } \\\\quad 3x + 4y = 12 \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10647-3",\n          "question": "\\\\begin{aligned} &\\\\text{What is the } y\\\\text{-intercept of the line } \\\\quad 5x + 2y = 10 \\\\text{?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10647-4",\n          "question": "\\\\begin{aligned} &\\\\text{Which of the following statements is true about the lines } x=3 \\\\text{ and } y=4 \\\\text{?} \\\\\\\\ &\\\\text{(A) They are parallel to the } y\\\\text{-axis and } x\\\\text{-axis respectively.} \\\\\\\\ &\\\\text{(B) They will intersect at a point.} \\\\\\\\ &\\\\text{(C) They are the same line.} \\\\\\\\ &\\\\text{(D) They are perpendicular to each other.} \\\\end{aligned}"\n        }\n      ]\n    },\n    {\n      "cluster6": [\n        {\n          "qid": "10405-1",\n          "question": "\\\\begin{aligned} &\\\\text{What is the fare from Rajiv Chowk to Karol Bagh?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10405-2",\n          "question": "\\\\begin{aligned} &\\\\text{What is the fare from Rajiv Chowk to Hauz Khas?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10408-1",\n          "question": "\\\\begin{aligned} &\\\\text{A test consists of \'True\' or \'False\' questions. One mark is awarded for every correct answer while} \\\\\\\\ &\\\\frac{1}{4} \\\\text{ mark is deducted for every wrong answer. A student knew answers to some of the questions.} \\\\\\\\ &\\\\text{Rest of the questions he attempted by guessing. He answered 150 questions and got 110 marks.} \\\\\\\\ &\\\\text{How many questions did he answer correctly?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10408-2",\n          "question": "\\\\begin{aligned} &\\\\text{If all the questions he guessed were incorrect, how many questions did he answer correctly?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10408-3",\n          "question": "\\\\begin{aligned} &\\\\text{How many questions did the student guess if he answered 150 questions in total?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10408-4",\n          "question": "\\\\begin{aligned} &\\\\text{If all the questions he guessed were incorrect and he answered 90 correctly, how many marks did he obtain?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10408-5",\n          "question": "\\\\begin{aligned} &\\\\text{If all the questions he guessed were incorrect, how many questions did he answer correctly to score 100 marks?} \\\\end{aligned}"\n        },\n        {\n          "qid": "10408-6",\n          "question": "\\\\begin{aligned} &\\\\text{If a student answered all questions incorrectly except for 90, how many marks did he receive?} \\\\end{aligned}"\n        }\n      ]\n    }\n  ]\n}', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=[], parsed=None))], created=1738904685, model='o3-mini-2025-01-31', object='chat.completion', service_tier='default', system_fingerprint='fp_8bcaa0ca21', usage=CompletionUsage(completion_tokens=12618, prompt_tokens=4848, total_tokens=17466, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=0, audio_tokens=0, reasoning_tokens=8000, rejected_prediction_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0)))


Processing topic:  10_mathematics_pair of linear equations in two variables_2

In [ ]:
totalClustering

{'10_mathematics_pair of linear equations in two variables_1': [{'cluster1': [{'qid': '10317-1',
     'question': '\\begin{aligned} &\\text{Which of the following represents a linear equation in two variables?} \\end{aligned}'},
    {'qid': '10317-2',
     'question': '\\begin{aligned} &\\text{Which linear equation represents the condition if Akhila spends } \\\\ &\\text{₹ 20 on rides costing ₹ 3 each and hoopla games costing ₹ 4 each?} \\end{aligned}'},
    {'qid': '10317-3',
     'question': '\\begin{aligned} & \\text{Which of the following equations represents the pair of linear equations } 3x - 4y - 10 = 0, 9y + 18 = 6x \\text{?} \\end{aligned}'},
    {'qid': '10317-4',
     'question': '\\begin{aligned} &\\text{Which of the following represents the given linear equation?} \\\\ &217x + 131y = 913 \\end{aligned}'},
    {'qid': '10317-5',
     'question': '\\begin{aligned} &\\text{Which of the following represents the equation of the line } \\quad k_{5} \\text{?} \\end{aligned}'},
    {'qid': '10317-6',
     'question': '\\begin{aligned} &\\text{If the monthly fixed charges are } ₹ a \\text{ and the cost of food per day is } ₹ b, \\\\ &\\text{which of the following equations represents the total monthly cost?} \\end{aligned}'},
    {'qid': '10317-7',
     'question': '\\begin{aligned} &\\text{If the cost of a chair is } ₹ a \\text{ and the cost of a table is } ₹ b, \\\\ &\\text{which equation represents the total cost of } n \\text{ chairs and } m \\text{ tables?} \\end{aligned}'},
    {'qid': '10317-8',
     'question': '\\begin{aligned} &\\text{Given the ticket charges for the park are } ₹ 160 \\text{ per child and } ₹ 260 \\text{ per adult,} \\\\ &\\text{which equation represents the total cost for } c \\text{ children and } a \\text{ adults?} \\end{aligned}'},
    {'qid': '10319-5',
     'question': '\\begin{aligned} &\\text{Which of the following represents the pair of linear equations } 3x - 4y - 10 = 0, 9y + 18 = 6x \\text{?} \\end{aligned}'},
    {'qid': '10319-15',
     'question': '\\begin{aligned} & \\text{Which algebraic expression represents the given information in terms of } \\quad x \\quad \\text{and } \\quad y \\quad \\text{?} \\end{aligned}'},
    {'qid': '10687-1',
     'question': '\\begin{aligned} &\\text{Which of the following represents the fraction } \\frac{x}{y}? \\end{aligned}'},
    {'qid': '10687-2',
     'question': '\\begin{aligned} &\\text{Which of the following represents the fraction } \\quad \\frac{a}{b} \\quad \\text{correctly?} \\end{aligned}'}]},
  {'cluster2': [{'qid': '10319-1',
     'question': '\\begin{aligned} &\\text{Which equation describes the relationship between the number of bags } x, \\\\ &\\text{and the number of baskets, } y \\text{?} \\end{aligned}'},
    {'qid': '10319-2',
     'question': '\\begin{aligned} &\\text{What do the variables } \\quad x \\quad \\text{and} \\quad y \\quad \\text{symbolize in the context of the equation?} \\end{aligned}'},
    {'qid': '10319-3',
     'question': '\\begin{aligned} &\\text{Substitute the variables } \\quad x \\quad \\text{and} \\quad y \\quad \\text{with words and explain the meaning of the equation.} \\end{aligned}'},
    {'qid': '10319-4',
     'question': '\\begin{aligned} &\\text{Which has a greater quantity: bags of raisins or bags of nuts? Justify your answer.} \\end{aligned}'}]},
  {'cluster3': [{'qid': '10331-1',
     'question': '\\begin{aligned} &\\text{Which of these pairs of equations is equivalent to the given pair of equations?} \\\\ \\end{aligned}'},
    {'qid': '10331-2',
     'question': '\\begin{aligned} &\\text{What are the possible values of } \\quad x \\quad \\text{and} \\quad y \\quad \\text{in the given equation?} \\end{aligned}'},
    {'qid': '10331-3',
     'question': '\\begin{aligned} &\\text{Can you find any values for } \\quad x \\quad \\text{and} \\quad y \\quad \\text{that satisfy the initial equation?} \\end{aligned}'},
    {'qid': '10331-4',
     'question': '\\begin{aligned} &\\text{Which values of } x \\quad \\text{and} \\quad y \\quad \\text{can be used to verify the second equation?} \\end{aligned}'},
    {'qid': '10331-5',
     'question': '\\begin{aligned} &\\text{What is the reason for selecting these specific values for } x \\quad \\text{and} \\quad y \\quad \\text{?} \\end{aligned}'},
    {'qid': '10331-6',
     'question': '\\begin{aligned} &\\text{Which method can be used to verify the correctness of your solution?} \\end{aligned}'},
    {'qid': '10331-7',
     'question': '\\begin{aligned} &\\text{What are the values of } x \\text{ and } y \\text{ for the linear equations } \\quad 41x + 53y = 135 \\\\ &\\text{and } \\quad 53x + 41y = 147 \\text{?} \\end{aligned}'},
    {'qid': '10331-8',
     'question': '\\begin{aligned} &\\text{If } x = a \\text{ and } y = b \\text{ is the solution to the equations } \\quad x - y = 2 \\\\ &\\text{and } \\quad x + y = 4, \\text{ what are the values of } a \\text{ and } b \\text{?} \\end{aligned}'},
    {'qid': '10331-9',
     'question': '\\begin{aligned} &\\text{If the angles of a triangle are } x, y \\text{ and } 40^{\\circ} \\text{, and the difference between } \\\\ &\\text{angles } x \\text{ and } y \\text{ is } 30^{\\circ}, \\text{ what are the values of } x \\text{ and } y \\text{?} \\end{aligned}'},
    {'qid': '10331-10',
     'question': '\\begin{aligned} &\\text{Read the Assertion (A) and Reason (R) statements carefully and choose the correct option:} \\\\ &\\text{Assertion (A): The value of } q= \\pm 3, \\text{ if } x=4, y=2 \\text{ is the solution of the line } 2x+y-q^{2}-4=0. \\\\ &\\text{Reason (R): The solution of the line will satisfy the equation of the line.} \\end{aligned}'},
    {'qid': '10331-11',
     'question': '\\begin{aligned} &\\text{Which equation represents one of the lines from the given pair of linear equations?} \\end{aligned}'}]},
  {'cluster4': [{'qid': '10319-6',
     'question': '\\begin{aligned} &\\text{If the difference between two numbers is 30 and one number is four times the other, what are the numbers?} \\end{aligned}'},
    {'qid': '10319-7',
     'question': "\\begin{aligned} &\\text{A train travels a certain distance at a constant speed. If the train's speed was increased by } \\quad 12 \\mathrm{~km} / \\mathrm{h}, \\text{ it would take 2 hours less than the scheduled time.} \\\\ &\\text{If the speed was decreased by } 12 \\mathrm{~km} / \\mathrm{h}, \\text{ it would take 3 hours more than the scheduled time.} \\\\ &\\text{What is the distance covered by the train?} \\end{aligned}"},
    {'qid': '10319-8',
     'question': '\\begin{aligned} &\\text{If there are 15 guests at the dinner party, what amount does Mr. Jayant need to pay?} \\end{aligned}'},
    {'qid': '10319-9',
     'question': '\\begin{aligned} &\\text{Amit is planning to buy a house, and the layout is given below. The design and the measurement are such that the areas of two bedrooms and the kitchen together is 120 sq m. Based on the above information, answer the following questions:} \\end{aligned}'},
    {'qid': '10319-10',
     'question': '\\begin{aligned} &\\text{Create the pair of linear equations in two variables from this situation.} \\end{aligned}'},
    {'qid': '10319-11',
     'question': '\\begin{aligned} &\\text{Calculate the length of the outer boundary of the layout.} \\end{aligned}'},
    {'qid': '10319-12',
     'question': '\\begin{aligned} & \\text{What is the total number of children who visited the amusement park on that day?} \\end{aligned}'},
    {'qid': '10319-13',
     'question': '\\begin{aligned} & \\text{What is the total number of adults who visited the amusement park on that day?} \\end{aligned}'},
    {'qid': '10319-14',
     'question': '\\begin{aligned} & \\text{Calculate the total amount collected if 300 children and 150 adults visit the amusement park.} \\end{aligned}'},
    {'qid': '10319-16',
     'question': '\\begin{aligned} & \\text{What is the prize amount awarded for the game of hockey?} \\end{aligned}'},
    {'qid': '10319-17',
     'question': '\\begin{aligned} & \\text{Which game has a higher prize amount and by what difference?} \\end{aligned}'},
    {'qid': '10319-18',
     'question': '\\begin{aligned} & \\text{Calculate the total prize amount if there are two participants from each of two games.} \\end{aligned}'},
    {'qid': '10319-19',
     'question': '\\begin{aligned} & \\text{How many lines are there in the blue wheel of the Indian National flag if one student says it is 8 times the number of colors in the flag,} \\\\ & \\text{and another says the sum of the number of colors and lines is 27? Convert these statements into a linear equation and find the number of lines.} \\end{aligned}'},
    {'qid': '10319-20',
     'question': '\\begin{aligned} & \\text{If Heena took 2 minutes more than Kimaya to reach her destination, what is the time taken by Heena to reach the badminton court?} \\end{aligned}'},
    {'qid': '10319-21',
     'question': '\\begin{aligned} & \\text{What is the two-digit number if the sum of the number and the number obtained by reversing its digits is 66,} \\\\ & \\text{and the digits differ by 2? How many such numbers exist?} \\end{aligned}'},
    {'qid': '10319-22',
     'question': '\\begin{aligned} &\\text{If the larger angle is } x^{\\circ} \\text{ and the smaller angle is } y^{\\circ}, \\text{ what is the equation representing their sum if they are supplementary?} \\end{aligned}'},
    {'qid': '10319-23',
     'question': "\\begin{aligned} &\\text{If Rashmi's current age is } x \\text{ years and Nazma's current age is } y \\text{ years, what equation can represent their ages?} \\end{aligned}"},
    {'qid': '10319-24',
     'question': '\\begin{aligned} &\\text{If } x \\text{ Litres of } 50\\% \\text{ acid solution is mixed with } y \\text{ Litres of } 25\\% \\text{ acid solution, what equation represents the mixture?} \\end{aligned}'},
    {'qid': '10319-25',
     'question': '\\begin{aligned} &\\text{If the ages of two children are } x \\text{ years and } y \\text{ years respectively, what equation can represent their ages?} \\end{aligned}'},
    {'qid': '10319-26',
     'question': '\\begin{aligned} &\\text{If the speed of person 1 is } x \\mathrm{~km/h} \\text{ and the speed of person 2 is } y \\mathrm{~km/h} \\text{ with } x > y, \\text{ what equation represents their speeds?} \\end{aligned}'},
    {'qid': '10319-27',
     'question': '\\begin{aligned} &\\text{If the present age of a son is } x \\text{ years and that of the father is } y \\text{ years, which of the following is correct?} \\end{aligned}'},
    {'qid': '10319-28',
     'question': '\\begin{aligned} &\\text{If the ages of two children are } x \\text{ and } y \\text{ respectively, which of the following statements is true?} \\end{aligned}'},
    {'qid': '10319-29',
     'question': '\\begin{aligned} &\\text{If the income of the first person is } 8x \\text{ and the income of the second person is } 6x, \\quad \\text{what are their expenditures if the first and second persons spend } 5y \\text{ and } 4y \\text{ respectively?} \\end{aligned}'},
    {'qid': '10319-30',
     'question': '\\begin{aligned} &\\text{If a number has a tens digit } a \\text{ and a ones digit } b, \\quad \\text{what is the number represented as } 10a + b \\text{?} \\end{aligned}'},
    {'qid': '10319-31',
     'question': '\\begin{aligned} &\\text{If the number of colours in a flag is } x \\text{ and the number of lines in the blue colour wheel is } y, \\quad \\text{what is the equation relating them if } 9x = y \\text{?} \\end{aligned}'},
    {'qid': '10319-32',
     'question': '\\begin{aligned} &\\text{What are the speeds of cars at points A and B if the speed at A is } u \\text{ km/h and at B is } v \\text{ km/h?} \\end{aligned}'},
    {'qid': '10319-33',
     'question': '\\begin{aligned} &\\text{What is the total cost for student A if the fixed charges and cost of food for 30 days is } \\quad ₹ 5000 \\text{?} \\end{aligned}'}]},
  {'cluster5': [{'qid': '10647-1',
     'question': '\\begin{aligned} &\\text{Which of the following points lies on the line } \\quad 3x - 4y = 6 \\text{?} \\end{aligned}'},
    {'qid': '10647-2',
     'question': '\\begin{aligned} &\\text{Which of the following points lies on the line } \\quad 3x + 4y = 12 \\text{?} \\end{aligned}'},
    {'qid': '10647-3',
     'question': '\\begin{aligned} &\\text{What is the } y\\text{-intercept of the line } \\quad 5x + 2y = 10 \\text{?} \\end{aligned}'},
    {'qid': '10647-4',
     'question': '\\begin{aligned} &\\text{Which of the following statements is true about the lines } x=3 \\text{ and } y=4 \\text{?} \\\\ &\\text{(A) They are parallel to the } y\\text{-axis and } x\\text{-axis respectively.} \\\\ &\\text{(B) They will intersect at a point.} \\\\ &\\text{(C) They are the same line.} \\\\ &\\text{(D) They are perpendicular to each other.} \\end{aligned}'}]},
  {'cluster6': [{'qid': '10405-1',
     'question': '\\begin{aligned} &\\text{What is the fare from Rajiv Chowk to Karol Bagh?} \\end{aligned}'},
    {'qid': '10405-2',
     'question': '\\begin{aligned} &\\text{What is the fare from Rajiv Chowk to Hauz Khas?} \\end{aligned}'},
    {'qid': '10408-1',
     'question': "\\begin{aligned} &\\text{A test consists of 'True' or 'False' questions. One mark is awarded for every correct answer while} \\\\ &\\frac{1}{4} \\text{ mark is deducted for every wrong answer. A student knew answers to some of the questions.} \\\\ &\\text{Rest of the questions he attempted by guessing. He answered 150 questions and got 110 marks.} \\\\ &\\text{How many questions did he answer correctly?} \\end{aligned}"},
    {'qid': '10408-2',
     'question': '\\begin{aligned} &\\text{If all the questions he guessed were incorrect, how many questions did he answer correctly?} \\end{aligned}'},
    {'qid': '10408-3',
     'question': '\\begin{aligned} &\\text{How many questions did the student guess if he answered 150 questions in total?} \\end{aligned}'},
    {'qid': '10408-4',
     'question': '\\begin{aligned} &\\text{If all the questions he guessed were incorrect and he answered 90 correctly, how many marks did he obtain?} \\end{aligned}'},
    {'qid': '10408-5',
     'question': '\\begin{aligned} &\\text{If all the questions he guessed were incorrect, how many questions did he answer correctly to score 100 marks?} \\end{aligned}'},
    {'qid': '10408-6',
     'question': '\\begin{aligned} &\\text{If a student answered all questions incorrectly except for 90, how many marks did he receive?} \\end{aligned}'}]}],
 '10_mathematics_pair of linear equations in two variables_2': [{'cluster1': [{'qid': '10318-1',
     'question': '\\begin{aligned} &\\text{If } x^{3n}-1+y^{m-3}=0 \\text{ is a linear equation, which of these is also a linear equation?} \\end{aligned}'},
    {'qid': '10318-2',
     'question': '\\begin{aligned} &\\text{Which of these linear equations has a unique solution?} \\end{aligned}'},
    {'qid': '10318-3',
     'question': '\\begin{aligned} &\\text{Which of these statements is true about the given equations?} \\\\ \\end{aligned}'},
    {'qid': '10318-4',
     'question': '\\begin{aligned} &\\text{On comparing the coefficients, a student claims these pairs of equations are consistent.} \\\\ &\\text{Is the student correct? Which of these explains why?} \\\\ \\end{aligned}'},
    {'qid': '10318-7',
     'question': '\\begin{aligned} &\\text{If a pair of linear equations is consistent, what can be said about the lines?} \\\\ \\end{aligned}'},
    {'qid': '10318-12',
     'question': '\\begin{aligned} &\\text{What characteristics does the system of linear equations for both situations have?} \\end{aligned}'},
    {'qid': '10318-13',
     'question': '\\begin{aligned} &\\text{What type of solution does the system of linear equations representing both situations have?} \\end{aligned}'},
    {'qid': '10318-15',
     'question': '\\begin{aligned} &\\text{What is the relationship between the lines } \\quad x = a \\quad \\text{and} \\quad y = b \\quad \\text{?} \\end{aligned}'},
    {'qid': '10318-18',
     'question': '\\begin{aligned} & \\text{If } \\quad \\frac{a_1}{a_2} = \\frac{b_1}{b_2} = \\frac{c_1}{c_2}, \\quad \\text{what can be said about the lines } \\\\ &a_1x + b_1y + c_1 = 0 \\quad \\text{and} \\quad a_2x + b_2y + c_2 = 0 \\text{?} \\end{aligned}'},
    {'qid': '10318-19',
     'question': '\\begin{aligned} &\\text{What condition must be satisfied for two lines to coincide, given } \\\\ &\\frac{a_1}{a_2}=\\frac{b_1}{b_2}=\\frac{c_1}{c_2}? \\end{aligned}'}]},
  {'cluster2': [{'qid': '10318-8',
     'question': '\\begin{aligned} &\\text{Which of the following pairs of equations are parallel, indicating no solution?} \\end{aligned}'},
    {'qid': '10318-9',
     'question': '\\begin{aligned} &\\text{Identify the pair of equations that are inconsistent.} \\end{aligned}'},
    {'qid': '10318-10',
     'question': '\\begin{aligned} &\\text{Which of the following describes the relationship between the equations } \\\\ &x + 2y + 5 = 0 \\\\ &\\text{and } -3x - 6y + 1 = 0? \\end{aligned}'},
    {'qid': '10318-11',
     'question': '\\begin{aligned} &\\text{If one equation of a pair of dependent linear equations is } \\\\ &-5x + 7y - 2 = 0, \\\\ &\\text{which of the following could be the second equation?} \\end{aligned}'},
    {'qid': '10318-16',
     'question': '\\begin{aligned} &\\text{Given one equation of a pair of dependent linear equations is } \\\\ &-5x + 7y = 2, \\quad \\text{what could be the second equation?} \\end{aligned}'},
    {'qid': '10318-17',
     'question': '\\begin{aligned} &\\text{For the given pair of linear equations that do not intersect, which statement is correct?} \\end{aligned}'}]},
  {'cluster3': [{'qid': '10361-1',
     'question': '\\begin{aligned} &\\text{What is the value of } k \\text{ for which the system of linear equations } \\\\ &x + 2y = 3, \\\\ &5x + ky + 7 = 0 \\text{ is inconsistent?} \\end{aligned}'},
    {'qid': '10361-2',
     'question': '\\begin{aligned} &\\text{Determine the value of } k \\text{ for which the system of equations } \\\\ &kx - 5y = 2; \\\\ &6x + 2y = 7 \\text{ has no solution.} \\end{aligned}'},
    {'qid': '10361-3',
     'question': '\\begin{aligned} &\\text{What is the value of } \\quad k \\quad \\text{for which the system of equations} \\\\ &3x + 4y = 5 \\quad \\text{and} \\quad (k+3)x + 8y = 3k + 5 \\quad \\text{has infinitely many solutions?} \\end{aligned}'},
    {'qid': '10361-4',
     'question': '\\begin{aligned} &\\text{If the lines represented by } \\quad 4x + 3ky = 3 \\quad \\text{and} \\quad 3x + 7y = 2 \\quad \\text{are parallel, what is the value of } \\quad k \\quad \\text{?} \\end{aligned}'},
    {'qid': '10361-5',
     'question': '\\begin{aligned} &\\text{Determine the value of } \\quad p \\quad \\text{such that the equations} \\\\ &-2x + py = 3 \\quad \\text{and} \\quad px - 2y = 3 \\quad \\text{represent parallel lines.} \\end{aligned}'},
    {'qid': '10361-6',
     'question': '\\begin{aligned} &\\text{Find the value of } \\quad a \\quad \\text{for which the lines} \\\\ &x = 1, \\quad y = 2, \\quad \\text{and} \\quad a^{2}x + 3y - 25 = 0 \\quad \\text{are concurrent.} \\end{aligned}'},
    {'qid': '10361-7',
     'question': '\\begin{aligned} &\\text{What is the value of } k \\text{ for which the pair of equations } kx = y + 2 \\text{ and } 6x = 2y + 3 \\text{ has infinitely many solutions?} \\end{aligned}'},
    {'qid': '10361-8',
     'question': '\\begin{aligned} & \\text{For the pair of equations } \\quad a_{1}x + b_{1}y + c_{1} = 0 \\quad \\text{and} \\quad a_{2}x + b_{2}y + c_{2} = 0, \\ & \\text{what condition must be satisfied for them to have a unique solution?} \\end{aligned}'},
    {'qid': '10361-9',
     'question': '\\begin{aligned} & \\text{Determine the value of } k \\text{ for which the system of equations } x + 2y = 5 \\text{ and } 3x + ky + 10 = 0 \\text{ has no solution.} \\end{aligned}'},
    {'qid': '10361-10',

In [ ]:
count = 0
for i in list(totalClustering.keys()):
    for j in range(len(totalClustering[i])):
        # print("\n\nSingle doc ======================>",totalClustering[i][j][list(totalClustering[i][j].keys())[0]])
        count += len(totalClustering[i][j][list(totalClustering[i][j].keys())[0]])
count

183

In [ ]:
dbCollection = "LatexTest"
client = AsyncIOMotorClient(MONGO_URL)
async def updateQIDs(firstqid, totalClustering):
    try:
        db = client[DB_NAME]
        que_collection = db[dbCollection]
        for topic_id in list(totalClustering.keys()):
            for j in range(len(totalClustering[topic_id])):
                print("Inside cluster: ", totalClustering[topic_id][j][list(totalClustering[topic_id][j].keys())[0]])
                firstqid = int(totalClustering[topic_id][j][list(totalClustering[topic_id][j].keys())[0]][0]["qid"])
                print(firstqid, type(firstqid))
                for k in range(len(totalClustering[topic_id][j][list(totalClustering[topic_id][j].keys())[0]])):
                    firstqid += 1
                    print("Later qid: ",totalClustering[topic_id][j][list(totalClustering[topic_id][j].keys())[0]][k]["qid"], "------", f'{firstqid}-{k+1}')
                    await que_collection.update_one({"topic_id": topic_id, "qid": totalClustering[topic_id][j][list(totalClustering[topic_id][j].keys())[0]][k]["qid"]}, {"$set": {"qid": f'{firstqid}-{k+1}'}})
                
        print("Clustering updated successfully.")
    except Exception as e:
        print("Exception Occurred: ", type(e).__name__, "–", e, "\n", traceback.format_exc())

In [ ]:
await updateQIDs(totalClustering)
client.close()

Inside cluster:  [{'qid': '10317-1', 'question': '\\begin{aligned} &\\text{Which of the following represents a linear equation in two variables?} \\end{aligned}'}, {'qid': '10317-2', 'question': '\\begin{aligned} &\\text{Which linear equation represents the condition if Akhila spends } \\\\ &\\text{₹ 20 on rides costing ₹ 3 each and hoopla games costing ₹ 4 each?} \\end{aligned}'}, {'qid': '10317-3', 'question': '\\begin{aligned} & \\text{Which of the following equations represents the pair of linear equations } 3x - 4y - 10 = 0, 9y + 18 = 6x \\text{?} \\end{aligned}'}, {'qid': '10317-4', 'question': '\\begin{aligned} &\\text{Which of the following represents the given linear equation?} \\\\ &217x + 131y = 913 \\end{aligned}'}, {'qid': '10317-5', 'question': '\\begin{aligned} &\\text{Which of the following represents the equation of the line } \\quad k_{5} \\text{?} \\end{aligned}'}, {'qid': '10317-6', 'question': '\\begin{aligned} &\\text{If the monthly fixed charges are } ₹ a \\text{ and the cost of food per day is } ₹ b, \\\\ &\\text{which of the following equations represents the total monthly cost?} \\end{aligned}'}, {'qid': '10317-7', 'question': '\\begin{aligned} &\\text{If the cost of a chair is } ₹ a \\text{ and the cost of a table is } ₹ b, \\\\ &\\text{which equation represents the total cost of } n \\text{ chairs and } m \\text{ tables?} \\end{aligned}'}, {'qid': '10317-8', 'question': '\\begin{aligned} &\\text{Given the ticket charges for the park are } ₹ 160 \\text{ per child and } ₹ 260 \\text{ per adult,} \\\\ &\\text{which equation represents the total cost for } c \\text{ children and } a \\text{ adults?} \\end{aligned}'}, {'qid': '10319-5', 'question': '\\begin{aligned} &\\text{Which of the following represents the pair of linear equations } 3x - 4y - 10 = 0, 9y + 18 = 6x \\text{?} \\end{aligned}'}, {'qid': '10319-15', 'question': '\\begin{aligned} & \\text{Which algebraic expression represents the given information in terms of } \\quad x \\quad \\text{and } \\quad y \\quad \\text{?} \\end{aligned}'}, {'qid': '10687-1', 'question': '\\begin{aligned} &\\text{Which of the following represents the fraction } \\frac{x}{y}? \\end{aligned}'}, {'qid': '10687-2', 'question': '\\begin{aligned} &\\text{Which of the following represents the fraction } \\quad \\frac{a}{b} \\quad \\text{correctly?} \\end{aligned}'}]
Later qid:  10317-1 ------ 10981-1
Later qid:  10317-2 ------ 10981-2
Later qid:  10317-3 ------ 10981-3
Later qid:  10317-4 ------ 10981-4
Later qid:  10317-5 ------ 10981-5
Later qid:  10317-6 ------ 10981-6
Later qid:  10317-7 ------ 10981-7
Later qid:  10317-8 ------ 10981-8
Later qid:  10319-5 ------ 10981-9
Later qid:  10319-15 ------ 10981-10
Later qid:  10687-1 ------ 10981-11
Later qid:  10687-2 ------ 10981-12
Inside cluster:  [{'qid': '10319-1', 'question': '\\begin{aligned} &\\text{Which equation describes the relationship between the number of bags } x, \\\\ &\\text{and the number of baskets, } y \\text{?} \\end{aligned}'}, {'qid': '10319-2', 'question': '\\begin{aligned} &\\text{What do the variables } \\quad x \\quad \\text{and} \\quad y \\quad \\text{symbolize in the context of the equation?} \\end{aligned}'}, {'qid': '10319-3', 'question': '\\begin{aligned} &\\text{Substitute the variables } \\quad x \\quad \\text{and} \\quad y \\quad \\text{with words and explain the meaning of the equation.} \\end{aligned}'}, {'qid': '10319-4', 'question': '\\begin{aligned} &\\text{Which has a greater quantity: bags of raisins or bags of nuts? Justify your answer.} \\end{aligned}'}]
Later qid:  10319-1 ------ 10982-1
Later qid:  10319-2 ------ 10982-2
Later qid:  10319-3 ------ 10982-3
Later qid:  10319-4 ------ 10982-4
Inside cluster:  [{'qid': '10331-1', 'question': '\\begin{aligned} &\\text{Which of these pairs of equations is equivalent to the given pair of equations?} \\\\ \\end{aligned}'}, {'qid': '10331-2', 'question': '\\begin{aligned} &\\text{What are the possible values of } \\quad x \\quad \\text{and} \\quad y \\quad \\text{in the given equation?} \\end{aligned}'}, {'qid': '10331-3', 'question': '\\begin{aligned} &\\text{Can you find any values for } \\quad x \\quad \\text{and} \\quad y \\quad \\text{that satisfy the initial equation?} \\end{aligned}'}, {'qid': '10331-4', 'question': '\\begin{aligned} &\\text{Which values of } x \\quad \\text{and} \\quad y \\quad \\text{can be used to verify the second equation?} \\end{aligned}'}, {'qid': '10331-5', 'question': '\\begin{aligned} &\\text{What is the reason for selecting these specific values for } x \\quad \\text{and} \\quad y \\quad \\text{?} \\end{aligned}'}, {'qid': '10331-6', 'question': '\\begin{aligned} &\\text{Which method can be used to verify the correctness of your solution?} \\end{aligned}'}, {'qid': '10331-7', 'question': '\\begin{aligned} &\\text{What are the values of } x \\text{ and } y \\text{ for the linear equations } \\quad 41x + 53y = 135 \\\\ &\\text{and } \\quad 53x + 41y = 147 \\text{?} \\end{aligned}'}, {'qid': '10331-8', 'question': '\\begin{aligned} &\\text{If } x = a \\text{ and } y = b \\text{ is the solution to the equations } \\quad x - y = 2 \\\\ &\\text{and } \\quad x + y = 4, \\text{ what are the values of } a \\text{ and } b \\text{?} \\end{aligned}'}, {'qid': '10331-9', 'question': '\\begin{aligned} &\\text{If the angles of a triangle are } x, y \\text{ and } 40^{\\circ} \\text{, and the difference between } \\\\ &\\text{angles } x \\text{ and } y \\text{ is } 30^{\\circ}, \\text{ what are the values of } x \\text{ and } y \\text{?} \\end{aligned}'}, {'qid': '10331-10', 'question': '\\begin{aligned} &\\text{Read the Assertion (A) and Reason (R) statements carefully and choose the correct option:} \\\\ &\\text{Assertion (A): The value of } q= \\pm 3, \\text{ if } x=4, y=2 \\text{ is the solution of the line } 2x+y-q^{2}-4=0. \\\\ &\\text{Reason (R): The solution of the line will satisfy the equation of the line.} \\end{aligned}'}, {'qid': '10331-11', 'question': '\\begin{aligned} &\\text{Which equation represents one of the lines from the given pair of linear equations?} \\end{aligned}'}]
Later qid:  10331-1 ------ 10983-1
Later qid:  10331-2 ------ 10983-2
Later qid:  10331-3 ------ 10983-3
Later qid:  10331-4 ------ 10983-4
Later qid:  10331-5 ------ 10983-5
Later qid:  10331-6 ------ 10983-6
Later qid:  10331-7 ------ 10983-7
Later qid:  10331-8 ------ 10983-8
Later qid:  10331-9 ------ 10983-9
Later qid:  10331-10 ------ 10983-10
Later qid:  10331-11 ------ 10983-11
Inside cluster:  [{'qid': '10319-6', 'question': '\\begin{aligned} &\\text{If the difference between two numbers is 30 and one number is four times the other, what are the numbers?} \\end{aligned}'}, {'qid': '10319-7', 'question': "\\begin{aligned} &\\text{A train travels a certain distance at a constant speed. If the train's speed was increased by } \\quad 12 \\mathrm{~km} / \\mathrm{h}, \\text{ it would take 2 hours less than the scheduled time.} \\\\ &\\text{If the speed was decreased by } 12 \\mathrm{~km} / \\mathrm{h}, \\text{ it would take 3 hours more than the scheduled time.} \\\\ &\\text{What is the distance covered by the train?} \\end{aligned}"}, {'qid': '10319-8', 'question': '\\begin{aligned} &\\text{If there are 15 guests at the dinner party, what amount does Mr. Jayant need to pay?} \\end{aligned}'}, {'qid': '10319-9', 'question': '\\begin{aligned} &\\text{Amit is planning to buy a house, and the layout is given below. The design and the measurement are such that the areas of two bedrooms and the kitchen together is 120 sq m. Based on the above information, answer the following questions:} \\end{aligned}'}, {'qid': '10319-10', 'question': '\\begin{aligned} &\\text{Create the pair of linear equations in two variables from this situation.} \\end{aligned}'}, {'qid': '10319-11', 'question': '\\begin{aligned} &\\text{Calculate the length of the outer boundary of the layout.} \\end{aligned}'}, {'qid': '10319-12', 'question': '\\begin{aligned} & \\text{What is the total number of children who visited the amusement park on that day?} \\end{aligned}'}, {'qid': '10319-13', 'question': '\\begin{aligned} & \\text{What is the total number of adults who visited the amusement park on that day?} \\end{aligned}'}, {'qid': '10319-14', 'question': '\\begin{aligned} & \\text{Calculate the total amount collected if 300 children and 150 adults visit the amusement park.} \\end{aligned}'}, {'qid': '10319-16', 'question': '\\begin{aligned} & \\text{What is the prize amount awarded for the game of hockey?} \\end{aligned}'}, {'qid': '10319-17', 'question': '\\begin{aligned} & \\text{Which game has a higher prize amount and by what difference?} \\end{aligned}'}, {'qid': '10319-18', 'question': '\\begin{aligned} & \\text{Calculate the total prize amount if there are two participants from each of two games.} \\end{aligned}'}, {'qid': '10319-19', 'question': '\\begin{aligned} & \\text{How many lines are there in the blue wheel of the Indian National flag if one student says it is 8 times the number of colors in the flag,} \\\\ & \\text{and another says the sum of the number of colors and lines is 27? Convert these statements into a linear equation and find the number of lines.} \\end{aligned}'}, {'qid': '10319-20', 'question': '\\begin{aligned} & \\text{If Heena took 2 minutes more than Kimaya to reach her destination, what is the time taken by Heena to reach the badminton court?} \\end{aligned}'}, {'qid': '10319-21', 'question': '\\begin{aligned} & \\text{What is the two-digit number if the sum of the number and the number obtained by reversing its digits is 66,} \\\\ & \\text{and the digits differ by 2? How many such numbers exist?} \\end{aligned}'}, {'qid': '10319-22', 'question': '\\begin{aligned} &\\text{If the larger angle is } x^{\\circ} \\text{ and the smaller angle is } y^{\\circ}, \\text{ what is the equation representing their sum if they are supplementary?} \\end{aligned}'}, {'qid': '10319-23', 'question': "\\begin{aligned} &\\text{If Rashmi's current age is } x \\text{ years and Nazma's current age is } y \\text{ years, what equation can represent their ages?} \\end{aligned}"}, {'qid': '10319-24', 'question': '\\begin{aligned} &\\text{If } x \\text{ Litres of } 50\\% \\text{ acid solution is mixed with } y \\text{ Litres of } 25\\% \\text{ acid solution, what equation represents the mixture?} \\end{aligned}'}, {'qid': '10319-25', 'question': '\\begin{aligned} &\\text{If the ages of two children are } x \\text{ years and } y \\text{ years respectively, what equation can represent their ages?} \\end{aligned}'}, {'qid': '10319-26', 'question': '\\begin{aligned} &\\text{If the speed of person 1 is } x \\mathrm{~km/h} \\text{ and the speed of person 2 is } y \\mathrm{~km/h} \\text{ with } x > y, \\text{ what equation represents their speeds?} \\end{aligned}'}, {'qid': '10319-27', 'question': '\\begin{aligned} &\\text{If the present age of a son is } x \\text{ years and that of the father is } y \\text{ years, which of the following is correct?} \\end{aligned}'}, {'qid': '10319-28', 'question': '\\begin{aligned} &\\text{If the ages of two children are } x \\text{ and } y \\text{ respectively, which of the following statements is true?} \\end{aligned}'}, {'qid': '10319-29', 'question': '\\begin{aligned} &\\text{If the income of the first person is } 8x \\text{ and the income of the second person is } 6x, \\quad \\text{what are their expenditures if the first and second persons spend } 5y \\text{ and } 4y \\text{ respectively?} \\end{aligned}'}, {'qid': '10319-30', 'question': '\\begin{aligned} &\\text{If a number has a tens digit } a \\text{ and a ones digit } b, \\quad \\text{what is the number represented as } 10a + b \\text{?} \\end{aligned}'}, {'qid': '10319-31', 'question': '\\begin{aligned} &\\text{If the number of colours in a flag is } x \\text{ and the number of lines in the blue colour wheel is } y, \\quad \\text{what is the equation relating them if } 9x = y \\text{?} \\end{aligned}'}, {'qid': '10319-32', 'question': '\\begin{aligned} &\\text{What are the speeds of cars at points A and B if the speed at A is } u \\text{ km/h and at B is } v \\text{ km/h?} \\end{aligned}'}, {'qid': '10319-33', 'question': '\\begin{aligned} &\\text{What is the total cost for student A if the fixed charges and cost of food for 30 days is } \\quad ₹ 5000 \\text{?} \\end{aligned}'}]
Later qid:  10319-6 ------ 10984-1
Later qid:  10319-7 ------ 10984-2
Later qid:  10319-8 ------ 10984-3
Later qid:  10319-9 ------ 10984-4
Later qid:  10319-10 ------ 10984-5
Later qid:  10319-11 ------ 10984-6
Later qid:  10319-12 ------ 10984-7
Later qid:  10319-13 ------ 10984-8
Later qid:  10319-14 ------ 10984-9
Later qid:  10319-16 ------ 10984-10
Later qid:  10319-17 ------ 10984-11
Later qid:  10319-18 ------ 10984-12
Later qid:  10319-19 ------ 10984-13
Later qid:  10319-20 ------ 10984-14
Later qid:  10319-21 ------ 10984-15
Later qid:  10319-22 ------ 10984-16
Later qid:  10319-23 ------ 10984-17
Later qid:  10319-24 ------ 10984-18
Later qid:  10319-25 ------ 10984-19
Later qid:  10319-26 ------ 10984-20
Later qid:  10319-27 ------ 10984-21
Later qid:  10319-28 ------ 10984-22
Later qid:  10319-29 ------ 10984-23
Later qid:  10319-30 ------ 10984-24
Later qid:  10319-31 ------ 10984-25
Later qid:  10319-32 ------ 10984-26
Later qid:  10319-33 ------ 10984-27
Inside cluster:  [{'qid': '10647-1', 'question': '\\begin{aligned} &\\text{Which of the following points lies on the line } \\quad 3x - 4y = 6 \\text{?} \\end{aligned}'}, {'qid': '10647-2', 'question': '\\begin{aligned} &\\text{Which of the following points lies on the line } \\quad 3x + 4y = 12 \\text{?} \\end{aligned}'}, {'qid': '10647-3', 'question': '\\begin{aligned} &\\text{What is the } y\\text{-intercept of the line } \\quad 5x + 2y = 10 \\text{?} \\end{aligned}'}, {'qid': '10647-4', 'question': '\\begin{aligned} &\\text{Which of the following statements is true about the lines } x=3 \\text{ and } y=4 \\text{?} \\\\ &\\text{(A) They are parallel to the } y\\text{-axis and } x\\text{-axis respectively.} \\\\ &\\text{(B) They will intersect at a point.} \\\\ &\\text{(C) They are the same line.} \\\\ &\\text{(D) They are perpendicular to each other.} \\end{aligned}'}]
Later qid:  10647-1 ------ 10985-1
Later qid:  10647-2 ------ 10985-2
Later qid:  10647-3 ------ 10985-3
Later qid:  10647-4 ------ 10985-4
Inside cluster:  [{'qid': '10405-1', 'question': '\\begin{aligned} &\\text{What is the fare from Rajiv Chowk to Karol Bagh?} \\end{aligned}'}, {'qid': '10405-2', 'question': '\\begin{aligned} &\\text{What is the fare from Rajiv Chowk to Hauz Khas?} \\end{aligned}'}, {'qid': '10408-1', 'question': "\\begin{aligned} &\\text{A test consists of 'True' or 'False' questions. One mark is awarded for every correct answer while} \\\\ &\\frac{1}{4} \\text{ mark is deducted for every wrong answer. A student knew answers to some of the questions.} \\\\ &\\text{Rest of the questions he attempted by guessing. He answered 150 questions and got 110 marks.} \\\\ &\\text{How many questions did he answer correctly?} \\end{aligned}"}, {'qid': '10408-2', 'question': '\\begin{aligned} &\\text{If all the questions he guessed were incorrect, how many questions did he answer correctly?} \\end{aligned}'}, {'qid': '10408-3', 'question': '\\begin{aligned} &\\text{How many questions did the student guess if he answered 150 questions in total?} \\end{aligned}'}, {'qid': '10408-4', 'question': '\\begin{aligned} &\\text{If all the questions he guessed were incorrect and he answered 90 correctly, how many marks did he obtain?} \\end{aligned}'}, {'qid': '10408-5', 'question': '\\begin{aligned} &\\text{If all the questions he guessed were incorrect, how many questions did he answer correctly to score 100 marks?} \\end{aligned}'}, {'qid': '10408-6', 'question': '\\begin{aligned} &\\text{If a student answered all questions incorrectly except for 90, how many marks did he receive?} \\end{aligned}'}]
Later qid:  10405-1 ------ 10986-1
Later qid:  10405-2 ------ 10986-2
Later qid:  10408-1 ------ 10986-3
Later qid:  10408-2 ------ 10986-4
Later qid:  10408-3 ------ 10986-5
Later qid:  10408-4 ------ 10986-6
Later qid:  10408-5 ------ 10986-7
Later qid:  10408-6 ------ 10986-8
Inside cluster:  [{'qid': '10318-1', 'question': '\\begin{aligned} &\\text{If } x^{3n}-1+y^{m-3}=0 \\text{ is a linear equation, which of these is also a linear equation?} \\end{aligned}'}, {'qid': '10318-2', 'question': '\\begin{aligned} &\\text{Which of these linear equations has a unique solution?} \\end{aligned}'}, {'qid': '10318-3', 'question': '\\begin{aligned} &\\text{Which of these statements is true about the given equations?} \\\\ \\end{aligned}'}, {'qid': '10318-4', 'question': '\\begin{aligned} &\\text{On comparing the coefficients, a student claims these pairs of equations are consistent.} \\\\ &\\text{Is the student correct? Which of these explains why?} \\\\ \\end{aligned}'}, {'qid': '10318-7', 'question': '\\begin{aligned} &\\text{If a pair of linear equations is consistent, what can be said about the lines?} \\\\ \\end{aligned}'}, {'qid': '10318-12', 'question': '\\begin{aligned} &\\text{What characteristics does the system of linear equations for both situations have?} \\end{aligned}'}, {'qid': '10318-13', 'question': '\\begin{aligned} &\\text{What type of solution does the system of linear equations representing both situations have?} \\end{aligned}'}, {'qid': '10318-15', 'question': '\\begin{aligned} &\\text{What is the relationship between the lines } \\quad x = a \\quad \\text{and} \\quad y = b \\quad \\text{?} \\end{aligned}'}, {'qid': '10318-18', 'question': '\\begin{aligned} & \\text{If } \\quad \\frac{a_1}{a_2} = \\frac{b_1}{b_2} = \\frac{c_1}{c_2}, \\quad \\text{what can be said about the lines } \\\\ &a_1x + b_1y + c_1 = 0 \\quad \\text{and} \\quad a_2x + b_2y + c_2 = 0 \\text{?} \\end{aligned}'}, {'qid': '10318-19', 'question': '\\begin{aligned} &\\text{What condition must be satisfied for two lines to coincide, given } \\\\ &\\frac{a_1}{a_2}=\\frac{b_1}{b_2}=\\frac{c_1}{c_2}? \\end{aligned}'}]
Later qid:  10318-1 ------ 10987-1
Later qid:  10318-2 ------ 10987-2
Later qid:  10318-3 ------ 10987-3
Later qid:  10318-4 ------ 10987-4
Later qid:  10318-7 ------ 10987-5
Later qid:  10318-12 ------ 10987-6
Later qid:  10318-13 ------ 10987-7
Later qid:  10318-15 ------ 10987-8
Later qid:  10318-18 ------ 10987-9
Later qid:  10318-19 ------ 10987-10
Inside cluster:  [{'qid': '10318-8', 'question': '\\begin{aligned} &\\text{Which of the following pairs of equations are parallel, indicating no solution?} \\end{aligned}'}, {'qid': '10318-9', 'question': '\\begin{aligned} &\\text{Identify the pair of equations that are inconsistent.} \\end{aligned}'}, {'qid': '10318-10', 'question': '\\begin{aligned} &\\text{Which of the following describes the relationship between the equations } \\\\ &x + 2y + 5 = 0 \\\\ &\\text{and } -3x - 6y + 1 = 0? \\end{aligned}'}, {'qid': '10318-11', 'question': '\\begin{aligned} &\\text{If one equation of a pair of dependent linear equations is } \\\\ &-5x + 7y - 2 = 0, \\\\ &\\text{which of the following could be the second equation?} \\end{aligned}'}, {'qid': '10318-16', 'question': '\\begin{aligned} &\\text{Given one equation of a pair of dependent linear equations is } \\\\ &-5x + 7y = 2, \\quad \\text{what could be the second equation?} \\end{aligned}'}, {'qid': '10318-17', 'question': '\\begin{aligned} &\\text{For the given pair of linear equations that do not intersect, which statement is correct?} \\end{aligned}'}]
Later qid:  10318-8 ------ 10988-1
Later qid:  10318-9 ------ 10988-2
Later qid:  10318-10 ------ 10988-3
Later qid:  10318-11 ------ 10988-4
Later qid:  10318-16 ------ 10988-5
Later qid:  10318-17 ------ 10988-6